export const FACTS = [
  "Madam C.J. Walker built a hair-care empire in the early 1900s and became one of America's first self-made women millionaires.",
  "Garrett Morgan patented an improved traffic signal in 1923 that added a warning position, the idea behind today's yellow light.",
  "Dr. Charles Drew developed large-scale blood plasma storage and ran the first major blood banks during World War II.",
  "Katherine Johnson calculated the trajectories for NASA's first American crewed orbital flight and the Apollo 11 Moon landing.",
  "Hip-hop was born on August 11, 1973 at a back-to-school party DJ Kool Herc threw at 1520 Sedgwick Avenue in the Bronx.",
  "Kente cloth comes from the Ashanti and Ewe peoples of Ghana, and every color and pattern carries its own meaning.",
  "The Harlem Renaissance of the 1920s and 30s gave the world Langston Hughes, Zora Neale Hurston and Duke Ellington.",
  "Juneteenth marks June 19, 1865, when enslaved people in Galveston, Texas learned they were free. It became a federal holiday in 2021.",
  "The djembe drum from West Africa is traditionally carved from a single piece of hardwood and topped with goatskin.",
  "Mae Jemison became the first Black woman in space when she flew aboard the Space Shuttle Endeavour in 1992.",
  "Lewis Latimer improved the carbon filament for light bulbs, making electric lighting longer lasting and cheaper.",
  "Marie Van Brittan Brown co-invented the first home security system with video surveillance in 1966.",
  "Lonnie Johnson, a former NASA engineer, invented the Super Soaker water gun.",
  "Jerry Lawson led the team that built the Fairchild Channel F, the first home console with swappable game cartridges.",
  "Mansa Musa, ruler of the Mali Empire in the 1300s, is often called one of the richest people who ever lived.",
  "Timbuktu was home to the Sankore center of learning, which held hundreds of thousands of manuscripts.",
  "The afro pick with a raised Black Power fist handle became a symbol of pride in the 1970s.",
  "Soul Train ran for 35 years starting in 1971, one of the longest-running first-run syndicated TV shows in American history.",
  "Motown Records, founded by Berry Gordy in Detroit in 1959, launched The Supremes, Stevie Wonder and The Jackson 5.",
  "Jazz was born in New Orleans in the early 1900s, blending blues, ragtime and West African rhythms.",
  "Shirley Chisholm was the first Black woman elected to Congress (1968) and the first to run for a major party's presidential nomination.",
  "Bessie Coleman became the first Black woman and first Native American woman to earn a pilot's license, in 1921.",
  "Wakanda may be fictional, but Afrofuturism has roots in the 1950s and 60s with artists like Sun Ra.",
  "Alice Ball developed the first effective treatment for leprosy in 1915, at just 23 years old.",
  "Frederick McKinley Jones invented portable refrigeration for trucks, changing how food is shipped worldwide.",
  "The Great Pyramid of Giza in Africa was the tallest human-made structure on Earth for nearly 4,000 years.",
  "Wangari Maathai founded the Green Belt Movement, which planted tens of millions of trees, and won the 2004 Nobel Peace Prize.",
  "Sneaker culture took off when Run-DMC released 'My Adidas' in 1986, leading to one of the first major hip-hop endorsement deals.",
  "Dr. Patricia Bath invented the Laserphaco Probe for cataract surgery and was the first Black female doctor to receive a medical patent.",
  "The boombox became a symbol of 1980s street culture, carrying breakdance battles and block parties across New York.",
  "Benjamin Banneker built one of the first clocks made in America, carved almost entirely from wood, in 1753.",
  "Gladys West's mathematical modeling of the Earth's shape helped make modern GPS possible.",
  "Phillis Wheatley published a book of poetry in 1773, the first by an African American woman.",
  "Jesse Owens won four gold medals at the 1936 Berlin Olympics.",
  "Ghana became the first sub-Saharan African country to gain independence from colonial rule, in 1957.",
  "The Black national anthem, 'Lift Every Voice and Sing', was written as a poem by James Weldon Johnson in 1900.",
];

export const randomFact = () => FACTS[Math.floor(Math.random() * FACTS.length)];
