[[redirects]]
  from = "/games/vocotap"
  to = "https://vocotap.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/games/vocotap/*"
  to = "https://vocotap.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/games/bronze-blitz"
  to = "https://bronzeblitz.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/games/bronze-blitz/*"
  to = "https://bronzeblitz.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/games/sonoku"
  to = "https://sonokoo.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/games/sonoku/*"
  to = "https://sonokoo.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/games/ebonics"
  to = "https://t-ebonics.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "/games/ebonics/*"
  to = "https://t-ebonics.netlify.app/:splat"
  status = 200
  force = true
