# In-app copy edits: no "saved on this device" talk (privacy.html lists local-only features instead)
COPY = [
 (r"This replaces the data on this device with the backup\u2019s profile", r"This replaces your current data with the backup\u2019s profile"),
 (r"'Erase all data','Reset Treesh on this device'", r"'Erase all data','Start Treesh fresh'"),
 (r'">On this device</p><button data-act="ls-picker"', r'">Your uploads</p><button data-act="ls-picker"'),
 (r'</i>Protected on this device</p>', r'</i>Protected</p>'),
 (r"This will turn off app and page locks on this device.", r"This will turn off app and page locks."),
 (r">Protects your data on this device.</p>", r">Protects your data.</p>"),
 (r'layout stickers & profile banner, saved on device storage"', r'layout stickers & profile banner"'),
 (r'+g.desc.toLowerCase()+" from this device. This can', r'+g.desc.toLowerCase()+". This can'),
 (r"Your saved &amp; synced lyrics live only on this device. Export a backup file, then import it", r"Export a backup file of your saved &amp; synced lyrics, then import it"),
 (r"Everything in Treesh is saved on this device. Signed in? Your profile also syncs to your account. ", r""),
 (r">Media on device</p>", r">Media storage</p>"),
 (r"${USER_SONGS.length!==1?'s':''} on this device</p>", r"${USER_SONGS.length!==1?'s':''}</p>"),
 (r'(USER_SONGS.length!==1?"s":"")+" on this device"', r'(USER_SONGS.length!==1?"s":"")'),
 (r'(recs.length!==1?"s":"")+" on this device"', r'(recs.length!==1?"s":"")'),
 (r"</span> free on device`", r"</span> free`"),
 (r"Custom uploaded font active \u00b7 saved on device storage.", r"Custom uploaded font active."),
 (r"Changes apply instantly and are saved on this device.", r"Changes apply instantly."),
 (r"Clears your profile, favorites, playlists and theme on this device.", r"Clears your profile, favorites, playlists and theme."),
 (r"Upload your tracks and cover art from this device and play them", r"Upload your tracks and cover art and play them"),
 (r"then save your beats on this device.", r"then save your beats."),
 (r"See what is saved on this device and clear any part of it", r"See what Treesh keeps and clear any part of it"),
 (r"Keep synced lyrics on this device or export them", r"Keep synced lyrics or export them"),
 (r'"Lyrics saved on this device"', r'"Lyrics saved"', 2),
 (r"Correct the wording for playback on this device.", r"Correct the wording for playback."),
 (r'"Lyrics updated on this device"', r'"Lyrics updated"'),
 (r'"Draft saved on this device"', r'"Draft saved"'),
 (r"""'" will be removed from this device.'""", r"""'" will be removed.'"""),
 (r"'Upload your own tracks, saved right on this device'", r"'Upload your own tracks'"),
 (r"No signup needed, everything stays on this device.", r"No signup needed."),
 (r"will be cleared on this device.", r"will be cleared.", 2),
 (r'"This permanently deletes the track from this device."', r'"This permanently deletes the track."'),
 (r"will be permanently deleted from this device. This can", r"will be permanently deleted. This can", 3),
 (r"settings and locks on this device will be permanently erased", r"settings and locks will be permanently erased"),
 (r'\u201D will be permanently deleted from this device."', r'\u201D will be permanently deleted."'),
 (r"This erases everything saved on this device: profile", r"This erases everything: profile"),
 (r"to any photo, then save it to your device.'", r"to any photo, then download it.'"),
 (r"The audio, cover and lyrics are removed from this device.", r"The audio, cover and lyrics are removed."),
 (r"Upload songs from your device. They stay saved right here, even offline.", r"Upload songs and play them alongside the catalog, even offline."),
 (r"toast('Signed out','Your profile stays on this device')", r"toast('Signed out','Sign in any time to sync again')"),
 (r"Can\u2019t reach Treesh accounts right now. Your profile is safe on this device. Try again", r"Can\u2019t reach Treesh accounts right now. Try again"),
 (r"Accounts aren\u2019t switched on yet. Your profile is saved on this device for now.", r"Accounts aren\u2019t switched on yet."),
 (r"settings on any device. Your custom music always stays on this device.", r"settings on any device."),
 (r"sync every 30 seconds. Custom music always stays on this device.</p>", r"sync every 30 seconds.</p>"),
 (r'<span class="obx-acct-or">No signup, everything stays on this device.</span>', r'<span class="obx-acct-or">No signup needed.</span>'),
 (r'<i data-lucide="hard-drive"></i><span>Saved on this device.</span>', r'<i data-lucide="user-round"></i><span>Using Treesh as a guest.</span>'),
 (r"then clears everything from this device too, including your custom music and settings.", r"then signs you out and resets Treesh, including your custom music and settings."),
 (r"'Clearing Treesh from this device\u2026'", r"'Resetting Treesh\u2026'"),
 (r"'Your profile stays on this device. Sign back in any time to sync it again.'", r"'Sign back in any time to sync again.'"),
 (r'<p class="umx-note"><i data-lucide="hard-drive"></i>Custom music stays on this device. It never uploads to your Treesh account.</p>', r''),
 (r"added','Saved on this device');", r"added','Ready in My Music');"),
 (r"about every 30 seconds. Custom music always stays on your device.'", r"about every 30 seconds.'"),
 (r'<p class="cf-fine">Custom music always stays on your device.</p>', r''),
 (r"'Account deleted','Treesh is fresh on this device'", r"'Account deleted','Treesh is starting fresh'"),
 (r"Accounts aren\u2019t available right now. Your profile is saved on this device.", r"Accounts aren\u2019t available right now."),
 (r"'Custom music lives on this device. Clearing browser data removes it.'", r"'Clearing your browser data removes uploaded music.'"),
 (r"toast('Not on this device','That song lives on their phone')", r"toast('Can\u2019t play that one','It\u2019s one of their own uploads')"),
 (r'<p class="sba-fine">Everything on this device stays here. You\u2019ve been signed out.</p>', r'<p class="sba-fine">You\u2019ve been signed out.</p>'),
 (r"'Photo saved on this device. It goes public when your mute ends.'", r"'Photo saved. It goes public when your mute ends.'"),
 (r'<p class="sp-hint">Uploaded from this device. It goes public when you\u2019re signed in.</p>', r'<p class="sp-hint">It goes public when you\u2019re signed in.</p>'),
]
def apply_copy(s):
    miss = []
    for row in COPY:
        old, new = row[0], row[1]; n = row[2] if len(row) > 2 else 1
        c = s.count(old)
        if c != n: miss.append(f'{c}/{n}: {old[:80]}')
        s = s.replace(old, new)
    return s, miss
