<script>
/* ============================================================
   MAGIC MARKUP + BUBBLE GLASS + PROFILE PAGE
   Loaded before the main script; everything runs lazily after boot.
   ============================================================ */
const MK_PAGES=['library','artists','studios','game'];
const MK_NAV=[['library','Library','library-big'],['artists','Icons','sparkles'],['studios','Studios','layout-grid'],['game','Game','gamepad-2'],['settings','Settings','settings']];
const MK_PAGE_LABEL={library:'Library',artists:'Icons',studios:'Studios',game:'Game',settings:'Settings'};
const MK_WIDGETS={ nowplaying:{label:'Now Playing',ic:'disc-3',from:'the Player'}, recent:{label:'Recently Played',ic:'history',from:'your history'}, icons:{label:'Icons Spotlight',ic:'sparkles',from:'Icons'}, quick:{label:'Quick Settings',ic:'sliders-horizontal',from:'Settings'}, gamestats:{label:'Game Stats',ic:'trophy',from:'Game'} };
const MK_LABELS={hero:'Welcome banner',whatsnew:"What's New",picks:"Treesh's Picks",weekly:'Weekly Top',playlists:'Playlists',mymusic:'My Music',all:'All Music','icons-head':'Page header','icons-grid':'Icons grid','studios-head':'Page header','studio-instrum':'Instrum Studio','studio-lyric':'LyricFlow','game-head':'Page header','game-main':'Games & Things'};
const MK_WIDTHS=[['full','Full'],['twothird','2/3'],['half','1/2'],['third','1/3']];
const MK_SURF=[['default','Default'],['glass','Glass'],['bubble','Bubble'],['solid','Solid'],['clear','Clear']];
const MK_TINTS=['#9328ff','#3b82f6','#22d3ee','#34d399','#f59e0b','#ff2d78','#ffffff'];
const _mkImgs={};
let _mkRAF=null, _mkScrollRAF=null, _mkSaveT=null, _mkScrollV=0;

function mkS(){ if(!state.mk){ const d=LS.get('treesh_mk',null); state.mk=Object.assign({v:1,home:'library',hidden:[],fab:true,pages:{}},(d&&typeof d==='object')?d:{}); if(!Array.isArray(state.mk.hidden)) state.mk.hidden=[]; if(!state.mk.pages||typeof state.mk.pages!=='object') state.mk.pages={}; } return state.mk; }
function mkSave(){ LS.set('treesh_mk', mkS()); }
function mkSaveSoon(){ clearTimeout(_mkSaveT); _mkSaveT=setTimeout(mkSave,250); }
function mkPage(p){ const m=mkS(); let P=m.pages[p]; if(!P||typeof P!=='object') P=m.pages[p]={}; if(!Array.isArray(P.order)) P.order=[]; if(!P.blocks||typeof P.blocks!=='object') P.blocks={}; ['widgets','canvases','stickers'].forEach(k=>{ if(!Array.isArray(P[k])) P[k]=[]; }); return P; }
function mkUID(p){ return p+Date.now().toString(36).slice(-4)+Math.random().toString(36).slice(2,6); }
function mkHome(){ const m=mkS(); const shown=mkNav(MK_NAV).map(n=>n[0]); return shown.includes(m.home)?m.home:(shown[0]||'library'); }
function mkNav(list){ const hid=mkS().hidden; return list.filter(n=>n[0]==='settings'||!hid.includes(n[0])); }
function mkCurPage(){ const el=document.querySelector('#view [data-mk-page]'); return el?el.dataset.mkPage:null; }
function mkBlockEl(id){ return document.querySelector('#view [data-mk-id="'+id+'"]'); }
function mkLabel(b){ return b.kind==='widget'?((MK_WIDGETS[b.type]||{}).label||'Section'):b.kind==='canvas'?'Canvas':(MK_LABELS[b.id]||b.id); }
function mkFind(id){ if(!id) return null; const pages=mkS().pages; for(const pg in pages){ const P=pages[pg]; const s=((P&&P.stickers)||[]).find(x=>x.id===id); if(s) return {page:pg,P,s}; } return null; }
function mkSrc(s){ const v=s.src||''; return v.indexOf('idb:')===0?(_mkImgs[v.slice(4)]||''):v; }
function mkKeyInUse(key){ const pages=mkS().pages; for(const pg in pages){ if(((pages[pg]&&pages[pg].stickers)||[]).some(s=>s.src==='idb:'+key)) return true; } return false; }
function mkDropAssets(list){ (list||[]).forEach(s=>{ if((s.src||'').indexOf('idb:')!==0) return; const key=s.src.slice(4); if(!mkKeyInUse(key)){ delete _mkImgs[key]; assetDel(key).catch(()=>{}); } }); }

/* ---------- composing editable pages ---------- */
function mkFromMarkers(page, html, opts){ const start=html.indexOf('<!--mk:'); if(start<0) return html; const end=html.lastIndexOf('</div>'); const parts=html.slice(start,end).split(/<!--mk:([\w-]+)-->/); const blocks=[]; for(let i=1;i<parts.length;i+=2){ blocks.push({id:parts[i], html:(parts[i+1]||'').trim(), w:((opts&&opts.w)||{})[parts[i]]||'full'}); } return mkCompose(page, blocks, opts&&opts.tid); }
function mkCompose(page, blocks, tid){
  const P=mkPage(page), edit=!!state.mkEdit, map={}, natural=[];
  blocks.forEach(b=>{ map[b.id]=b; natural.push(b.id); });
  P.widgets.forEach(w=>{ if(!MK_WIDGETS[w.type]) return; map[w.id]={id:w.id,kind:'widget',type:w.type,w:'half',html:mkWidgetHtml(w.type)}; natural.push(w.id); });
  P.canvases.forEach(c=>{ map[c.id]={id:c.id,kind:'canvas',w:'full',html:''}; natural.push(c.id); });
  const order=P.order.filter(id=>map[id]);
  natural.forEach((id,i)=>{ if(order.includes(id)) return; let at=-1; for(let j=i-1;j>=0;j--){ const k=order.indexOf(natural[j]); if(k>=0){ at=k; break; } } order.splice(at+1,0,id); });
  const body=order.map(id=>mkBlockHtml(page,map[id],P.blocks[id]||{},edit)).join('');
  return `<div class="mk-page${edit?' mk-editing':''}" data-mk-page="${page}" data-testid="${tid||('mk-page-'+page)}">${body}${mkLayerHtml(page)}</div>`;
}
function mkBlockHtml(page,b,cfg,edit){
  const hid=!!cfg.hidden; if(hid&&!edit) return '';
  const isCv=b.kind==='canvas'; if(!isCv&&!b.html) return '';
  const w=cfg.w||b.w||'full', surf=cfg.surf||(isCv?'glass':'default'), h=cfg.h||(isCv?240:0);
  const st=[]; if(cfg.radius!=null) st.push('--mk-r:'+cfg.radius+'px'); if(cfg.tint) st.push('--mk-tint:'+cfg.tint);
  const P=mkPage(page);
  const inner=hid?`<div class="mk-ph" data-testid="mk-hidden-${b.id}"><i data-lucide="eye-off" style="width:15px;height:15px"></i>${esc(mkLabel(b))} is hidden</div>`
    :isCv?`<div class="mk-canvas" data-mk-canvas="${b.id}" data-testid="mk-canvas-${b.id}">${P.stickers.filter(s=>s.cv===b.id).map(s=>mkStickerHtml(s,true)).join('')}${edit&&!P.stickers.some(s=>s.cv===b.id)?'<p class="mk-cv-hint">Blank canvas. Select it, then tap <b>Add a sticker</b> to drop images, emoji or text here.</p>':''}</div>`
    :b.html;
  const ist=(h&&!hid)?`height:${h}px;${isCv?'':'overflow:auto;'}`:'';
  return `<div class="mk-block mk-w-${w} mk-s-${surf}${isCv?' mk-cv':''}${cfg.tint?' mk-tinted':''}${hid?' mk-is-hidden':''}${edit&&state.mkSel===b.id?' mk-sel':''}" data-mk-id="${b.id}" data-testid="mk-block-${b.id}" style="${st.join(';')}">${edit?mkBarHtml(b,cfg):''}<div class="mk-inner${ist&&!isCv?' soft-scroll':''}" style="${ist}">${inner}</div>${edit&&!hid?`<span class="mk-ui mk-resize" data-mk-resize="${b.id}" data-testid="mk-resize-${b.id}" title="Drag to resize"></span>`:''}</div>`;
}
function mkBarHtml(b,cfg){ const hid=!!cfg.hidden; const rem=b.kind==='widget'||b.kind==='canvas';
  return `<div class="mk-ui mk-bar" data-testid="mk-bar-${b.id}"><button type="button" class="mk-grip" data-mk-drag="${b.id}" data-testid="mk-drag-${b.id}" aria-label="Drag to move"><i data-lucide="grip-vertical"></i></button><span class="mk-bar-label">${esc(mkLabel(b))}</span><button type="button" data-act="mk-sel" data-id="${b.id}" data-testid="mk-edit-${b.id}" aria-label="Style ${esc(mkLabel(b))}"><i data-lucide="paintbrush"></i></button><button type="button" data-act="mk-hide" data-id="${b.id}" data-testid="mk-hide-${b.id}" aria-label="${hid?'Show':'Hide'}"><i data-lucide="${hid?'eye':'eye-off'}"></i></button>${rem?`<button type="button" data-act="mk-remove" data-id="${b.id}" data-testid="mk-remove-${b.id}" aria-label="Remove"><i data-lucide="trash-2"></i></button>`:''}</div>`; }

/* ---------- stickers ---------- */
function mkLayerHtml(page){ const list=mkPage(page).stickers.filter(s=>!s.cv); return `<div class="mk-stickers" data-mk-layer="${page}">${list.map(s=>mkStickerHtml(s,false)).join('')}</div>`; }
function mkStickerHtml(s,inCv){ const edit=!!state.mkEdit;
  const pos=inCv?`left:${s.x*100}%;top:${s.y*100}%`:`left:${s.x*100}%;top:${s.y}px`;
  let body;
  if(s.kind==='emoji') body=`<span class="mk-st-emoji" style="font-size:${Math.round(s.w*0.8)}px">${esc(s.text)}</span>`;
  else if(s.kind==='text') body=`<span class="mk-st-text" style="font-size:${Math.max(10,Math.round(s.w/4))}px;color:${esc(s.color||'#ffffff')}">${esc(s.text)}</span>`;
  else { const src=mkSrc(s); body=src?`<img src="${esc(src)}" alt="" draggable="false" referrerpolicy="no-referrer" onerror="this.style.opacity='.25'">`:'<span class="mk-st-loading"></span>'; }
  const width=s.kind==='text'?'auto':s.w+'px';
  return `<div class="mk-st${s.react?' mk-react':''}${edit&&state.mkStSel===s.id?' mk-st-sel':''}" data-mk-st="${s.id}" data-testid="mk-sticker-${s.id}" style="${pos};width:${width};--rot:${s.rot||0}deg;z-index:${s.z||1};opacity:${s.op==null?1:s.op}">${body}${edit?`<span class="mk-ui mk-st-h mk-st-rs" data-mk-st-rs="${s.id}" data-testid="mk-sticker-resize-${s.id}"></span><span class="mk-ui mk-st-h mk-st-rot" data-mk-st-rot="${s.id}" data-testid="mk-sticker-rotate-${s.id}"><i data-lucide="rotate-cw"></i></span><button type="button" class="mk-ui mk-st-del" data-act="mk-st-del" data-id="${s.id}" data-testid="mk-sticker-del-${s.id}" aria-label="Delete sticker"><i data-lucide="x"></i></button>`:''}</div>`; }
function mkStApplySize(el,s){ const em=el.querySelector('.mk-st-emoji'); if(em) em.style.fontSize=Math.round(s.w*0.8)+'px'; const tx=el.querySelector('.mk-st-text'); if(tx) tx.style.fontSize=Math.max(10,Math.round(s.w/4))+'px'; else el.style.width=s.w+'px'; }
function mkAddSticker(s){ const page=mkCurPage(); if(!page){ toast('Open Library, Icons, Studios or Game','Stickers live on those pages'); return; } const P=mkPage(page); if(P.stickers.length>=60){ toast('Sticker limit reached','Up to 60 stickers per page'); return; }
  const cv=(state.mkSel&&P.canvases.some(c=>c.id===state.mkSel))?state.mkSel:null; s.cv=cv;
  if(cv){ s.x=0.5; s.y=0.5; } else { const pg=document.querySelector('#view [data-mk-page]'); const r=pg.getBoundingClientRect(); s.x=0.5; s.y=Math.max(40,Math.round(window.innerHeight*0.42-r.top)); }
  s.w=s.w||(s.kind==='text'?140:s.kind==='emoji'?96:180); s.rot=0; s.z=P.stickers.reduce((m,x)=>Math.max(m,x.z||1),0)+1; s.react=!!state.mkReactNew;
  P.stickers.push(s); state.mkStSel=s.id; mkSave(); renderView(); state.mkSheet='sticker-edit'; mkRenderSheet(); toast('Sticker added', cv?'Placed on your canvas':'Drag it anywhere on the page'); }
function mkReadImage(file){ return new Promise((res,rej)=>{ if(!file||!/^image\//.test(file.type||'')) return rej(new Error('type')); if(file.size>15*1024*1024) return rej(new Error('size')); const r=new FileReader(); r.onerror=()=>rej(r.error); r.onload=()=>{ const data=String(r.result||''); if(file.type==='image/svg+xml'||(file.type==='image/gif'&&file.size<4*1024*1024)) return res(data); const im=new Image(); im.onerror=()=>rej(new Error('decode')); im.onload=()=>{ const k=Math.min(1,900/Math.max(im.naturalWidth,im.naturalHeight)); const c=document.createElement('canvas'); c.width=Math.max(1,Math.round(im.naturalWidth*k)); c.height=Math.max(1,Math.round(im.naturalHeight*k)); c.getContext('2d').drawImage(im,0,0,c.width,c.height); let out=c.toDataURL('image/webp',0.9); if(out.indexOf('data:image/webp')!==0) out=c.toDataURL('image/png'); res(out); }; im.src=data; }; r.readAsDataURL(file); }); }
async function mkStoreSticker(dataUrl){ const id=mkUID('s'), key='mk_st_'+id; try{ await assetPut(key,dataUrl); }catch(e){ toast('Couldn\u2019t save sticker','Your device storage may be full'); return; } _mkImgs[key]=dataUrl; mkAddSticker({id,kind:'img',src:'idb:'+key}); }
function mkAddImageFile(f){ mkReadImage(f).then(mkStoreSticker).catch(err=>toast(err&&err.message==='size'?'Image too large':'Couldn\u2019t read that image', err&&err.message==='size'?'Use one under 15 MB':'Try a PNG, JPG, GIF or SVG')); }
function mkSvgData(code){ let s=String(code||'').trim(); const i=s.search(/<svg[\s>]/i); if(i<0) return null; s=s.slice(i); s=s.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/\son\w+\s*=\s*("[^"]*"|'[^']*')/gi,''); if(!/xmlns=/.test(s)) s=s.replace(/<svg/i,'<svg xmlns="http://www.w3.org/2000/svg"'); return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(s); }
function mkAddSvgCode(code){ const d=mkSvgData(code); if(!d){ toast('That doesn\u2019t look like SVG','Paste code that starts with <svg'); return; } mkStoreSticker(d); }
function mkAddUrlStr(u){ u=String(u||'').trim(); if(!/^(https?:\/\/|data:image\/)\S+$/i.test(u)){ toast('Paste a full image link','It should start with https://'); return; } mkAddSticker({id:mkUID('s'),kind:'img',src:u}); }

/* ---------- widgets pulled in from other pages ---------- */
function mkWidgetHtml(type){ const f={nowplaying:mkWNowPlaying,recent:mkWRecent,icons:mkWIcons,quick:mkWQuick,gamestats:mkWGame}[type]; return f?f():''; }
function mkWHead(ic,kicker,title,right){ return `<div class="mb-4 flex items-center justify-between gap-3"><div class="flex min-w-0 items-center gap-2.5"><span class="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[color:var(--treesh-purple)]/15 text-[color:var(--treesh-purple)]"><i data-lucide="${ic}" style="width:17px;height:17px"></i></span><div class="min-w-0"><p class="text-[10px] font-semibold uppercase tracking-[0.22em] text-white/45">${kicker}</p><h2 class="clamp-1 text-base font-bold">${title}</h2></div></div>${right||''}</div>`; }
function mkWNowPlaying(){ const s=curSong();
  if(!s) return `<section data-mk-widget="nowplaying" data-testid="mk-widget-nowplaying" class="h-full rounded-3xl border border-white/10 bg-white/[0.04] p-5">${mkWHead('disc-3','From the player','Now Playing')}<div class="flex flex-col items-start gap-3 rounded-2xl border border-dashed border-white/12 p-5"><p class="text-sm text-white/55">Nothing is playing right now.</p><button data-act="shuffle-all" data-testid="mk-np-shuffle" class="press inline-flex items-center gap-2 rounded-full bg-[color:var(--treesh-purple)] px-4 py-2 text-sm font-semibold text-white"><i data-lucide="shuffle" style="width:15px;height:15px"></i>Shuffle all</button></div></section>`;
  const pct=state.duration?(state.currentTime/state.duration*100):0;
  return `<section data-mk-widget="nowplaying" data-testid="mk-widget-nowplaying" class="dark-surface relative h-full overflow-hidden rounded-3xl border border-white/10 bg-white/[0.04] p-5"><div class="pointer-events-none absolute inset-0 scale-125 opacity-40 blur-3xl" style="background-image:url('${esc(s.coverArt||'')}');background-size:cover;background-position:center"></div><div class="pointer-events-none absolute inset-0" style="background:linear-gradient(135deg,rgba(10,10,14,.5),rgba(10,10,14,.84))"></div>
   <div class="relative"><p class="mb-3 text-[10px] font-semibold uppercase tracking-[0.22em] text-white/55">Now playing</p>
   <div class="flex items-center gap-4"><button data-act="mini-open" data-testid="mk-np-open" aria-label="Open player" class="h-20 w-20 shrink-0 overflow-hidden rounded-2xl border border-white/20 shadow-xl sm:h-24 sm:w-24">${img(s.coverArt,'h-full w-full object-cover')}</button><div class="min-w-0 flex-1"><p class="clamp-1 text-lg font-bold text-white" data-testid="mk-np-title">${esc(s.title)}</p><p class="clamp-1 text-sm text-white/65">${esc(s.artist)}</p><div class="mt-3 h-1.5 w-full overflow-hidden rounded-full bg-white/15"><div data-mk-np-prog class="h-full rounded-full bg-[color:var(--treesh-purple)]" style="width:${pct}%"></div></div></div></div>
   <div class="mt-4 flex items-center gap-2"><button data-act="prev" data-testid="mk-np-prev" aria-label="Previous" class="press grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-white/10 text-white"><i data-lucide="skip-back" style="width:18px;height:18px"></i></button><button data-act="toggle-play" data-testid="mk-np-play" aria-label="Play or pause" class="press grid h-12 w-12 place-items-center rounded-full bg-[color:var(--treesh-purple)] text-white"><i data-lucide="${state.isPlaying?'pause':'play'}" style="width:20px;height:20px"></i></button><button data-act="next" data-testid="mk-np-next" aria-label="Next" class="press grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-white/10 text-white"><i data-lucide="skip-forward" style="width:18px;height:18px"></i></button><button data-act="mini-open" class="press ml-auto inline-flex items-center gap-1.5 rounded-full border border-white/15 bg-white/10 px-3.5 py-2 text-xs font-semibold text-white">Open player<i data-lucide="chevron-up" style="width:14px;height:14px"></i></button></div></div></section>`; }
function mkRecentSongs(n){ const seen=new Set(), out=[], log=state.playLog||[]; for(let i=log.length-1;i>=0&&out.length<n;i--){ const e=log[i]; if(!e||seen.has(e.id)) continue; seen.add(e.id); const s=SONG_BY_ID[e.id]; if(s&&!isDisliked(s.id)&&vis([s]).length) out.push(s); } return out; }
function mkWRecent(){ const list=mkRecentSongs(12);
  const body=list.length?`<div class="-mx-1 flex gap-3 overflow-x-auto px-1 pb-1 no-scrollbar">${list.map(s=>`<button data-act="play" data-id="${s.id}" data-testid="mk-recent-${s.id}" class="group w-[112px] shrink-0 text-left"><span class="relative block aspect-square w-full overflow-hidden rounded-2xl border border-white/10">${img(s.coverArt,'h-full w-full object-cover transition-transform duration-500 group-hover:scale-105')}<span class="absolute bottom-1.5 right-1.5 grid h-8 w-8 place-items-center rounded-full bg-[color:var(--treesh-purple)] text-white opacity-0 shadow-lg transition group-hover:opacity-100"><i data-lucide="play" class="fill-current" style="width:13px;height:13px"></i></span></span><span class="clamp-1 mt-1.5 block text-[13px] font-semibold">${esc(s.title)}</span><span class="clamp-1 block text-[11px] text-white/50">${esc(s.artist)}</span></button>`).join('')}</div>`:`<p class="rounded-2xl border border-dashed border-white/12 p-5 text-center text-sm text-white/45">Songs you play will show up here.</p>`;
  return `<section data-mk-widget="recent" data-testid="mk-widget-recent" class="h-full rounded-3xl border border-white/10 bg-white/[0.04] p-5">${mkWHead('history','From your history','Recently Played')}${body}</section>`; }
function mkWIcons(){ const pc=state.playCounts||{}; const list=ARTISTS.map(a=>({a,n:artistSongs(a.id).reduce((t,s)=>t+(pc[s.id]||0),0)})).sort((x,y)=>y.n-x.n||x.a.name.localeCompare(y.a.name)).slice(0,12).map(x=>x.a);
  return `<section data-mk-widget="icons" data-testid="mk-widget-icons" class="h-full rounded-3xl border border-white/10 bg-white/[0.04] p-5">${mkWHead('sparkles','From Icons','Icons Spotlight',`<button data-act="nav" data-view="artists" data-testid="mk-icons-all" class="press shrink-0 rounded-full border border-white/12 bg-white/5 px-3 py-1.5 text-xs font-semibold text-white/75 hover:bg-white/10">See all</button>`)}<div class="-mx-1 flex gap-4 overflow-x-auto px-1 pb-1 no-scrollbar">${list.map(a=>`<button data-act="artist-open" data-id="${a.id}" data-testid="mk-icon-${a.id}" class="group flex w-[84px] shrink-0 flex-col items-center gap-2"><span class="block h-[76px] w-[76px] rounded-full border border-white/15 p-[2px] glow-purple transition-transform group-hover:scale-105"><span class="block h-full w-full overflow-hidden rounded-full">${img(a.image,'h-full w-full object-cover')}</span></span><span class="clamp-1 max-w-full text-center text-xs font-semibold">${esc(a.name)}</span></button>`).join('')}</div></section>`; }
function mkWQuick(){ const tile=(act,attrs,ic,label,on,tid)=>`<button data-act="${act}" ${attrs} data-testid="${tid}" aria-pressed="${on}" class="press flex flex-col items-start gap-2 rounded-2xl border p-3 text-left ${on?'border-[color:var(--treesh-purple)]/50 bg-[color:var(--treesh-purple)]/[0.14]':'border-white/10 bg-white/[0.03] hover:bg-white/[0.06]'}"><span class="grid h-9 w-9 place-items-center rounded-xl ${on?'bg-[color:var(--treesh-purple)] text-white':'bg-white/10 text-white/70'}"><i data-lucide="${ic}" style="width:17px;height:17px"></i></span><span class="text-[13px] font-semibold leading-tight">${label}</span><span class="text-[11px] text-white/45">${on?'On':'Off'}</span></button>`;
  const light=state.theme==='light';
  return `<section data-mk-widget="quick" data-testid="mk-widget-quick" class="h-full rounded-3xl border border-white/10 bg-white/[0.04] p-5">${mkWHead('sliders-horizontal','From Settings','Quick Settings',`<button data-act="nav" data-view="settings" data-testid="mk-quick-all" class="press shrink-0 rounded-full border border-white/12 bg-white/5 px-3 py-1.5 text-xs font-semibold text-white/75 hover:bg-white/10">All settings</button>`)}<div class="flex flex-wrap gap-2 [&>*]:min-w-[30%] [&>*]:flex-1">${tile('set-theme',`data-val="${light?'dark':'light'}"`,light?'sun':'moon','Light mode',light,'mk-quick-theme')}${tile('perf-mode-toggle','','zap','Performance',!!state.perfMode,'mk-quick-perf')}${tile('mk-xf-toggle','','blend','Crossfade',xfOn(),'mk-quick-xf')}${tile('toggle-anim-bg','','sparkles','Starfield',!!state.animBg,'mk-quick-anim')}${tile('toggle-ui-glow','','flashlight','Glow',!!state.uiGlow,'mk-quick-glow')}${tile('open-eq','','sliders-vertical','Equalizer',!!(state.eq&&state.eq.enabled),'mk-quick-eq')}</div></section>`; }
function mkWGame(){ const st=state.gameStats||{}, sr=state.stars||{}, tw=state.totWins||{}; const cell=(l,v,ic)=>`<div class="rounded-2xl border border-white/10 bg-white/[0.03] p-3"><div class="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-white/45"><i data-lucide="${ic}" style="width:12px;height:12px"></i>${l}</div><p class="mt-1 font-doto text-2xl font-bold">${v}</p></div>`;
  return `<section data-mk-widget="gamestats" data-testid="mk-widget-gamestats" class="h-full rounded-3xl border border-white/10 bg-white/[0.04] p-5">${mkWHead('trophy','From Game','Game Stats',`<button data-act="nav" data-view="game" data-testid="mk-game-play" class="press shrink-0 rounded-full bg-[color:var(--treesh-purple)] px-3.5 py-1.5 text-xs font-semibold text-white">Play</button>`)}<div class="mb-2.5 flex items-center gap-3 rounded-2xl border border-[color:var(--treesh-gold)]/25 bg-[color:var(--treesh-gold)]/[0.08] p-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-[color:var(--treesh-gold)]/20 text-[color:var(--treesh-gold)]"><i data-lucide="sparkles" style="width:18px;height:18px"></i></span><div><p class="text-[10px] font-semibold uppercase tracking-wide text-white/50">Starlites</p><p class="font-doto text-2xl font-bold leading-none" data-star-count>${fmtNum(sr.points||0)}</p></div><span class="ml-auto inline-flex items-center gap-1 rounded-full bg-white/10 px-2.5 py-1 text-xs font-semibold text-white/75"><i data-lucide="flame" style="width:13px;height:13px"></i>${sr.streak||0}d</span></div><div class="flex gap-2 [&>*]:flex-1">${cell('Games',(st.games||0)+(tw.plays||0),'gamepad-2')}${cell('Best',st.bestScore||0,'trophy')}${cell('Minutes',sr.totalMin||0,'clock')}</div></section>`; }
function mkRefreshNP(){ const els=document.querySelectorAll('#view [data-mk-widget="nowplaying"]'); if(!els.length) return; els.forEach(el=>{ el.outerHTML=mkWNowPlaying(); }); icons(); }

/* ---------- chrome: wand button, toolbar, editing sheet ---------- */
function mkRoot(id){ let el=document.getElementById(id); if(!el){ el=document.createElement('div'); el.id=id; document.body.appendChild(el); } return el; }
function mkAfterRender(){ document.documentElement.classList.toggle('mk-on',!!state.mkEdit); mkRenderChrome(); mkReactLoop(); }
function mkRenderChrome(){ const m=mkS(), edit=!!state.mkEdit;
  mkRoot('mk-fab').innerHTML=(m.fab!==false||edit)?`<button type="button" data-act="mk-toggle" data-testid="magic-markup-fab" aria-pressed="${edit}" aria-label="${edit?'Finish Magic Markup':'Magic Markup: customize this page'}" title="${edit?'Done editing':'Magic Markup'}" class="mk-fab-btn press${edit?' is-on':''}"><i data-lucide="${edit?'check':'wand-sparkles'}" style="width:22px;height:22px"></i></button>`:'';
  const pg=mkCurPage();
  mkRoot('mk-toolbar').innerHTML=edit?`<div class="mk-tb mk-ui dark-surface" data-testid="mk-toolbar"><span class="mk-tb-brand"><i data-lucide="wand-sparkles" style="width:16px;height:16px"></i><span class="hidden sm:inline">Magic Markup</span><span class="mk-tb-page" data-testid="mk-toolbar-page">${pg?MK_PAGE_LABEL[pg]:'View only'}</span></span>${pg?`<button type="button" data-act="mk-sheet" data-val="add" data-testid="mk-add-button" class="mk-tb-btn is-primary"><i data-lucide="plus" style="width:15px;height:15px"></i><span>Add</span></button>`:''}<button type="button" data-act="mk-sheet" data-val="pages" data-testid="mk-pages-button" class="mk-tb-btn"><i data-lucide="layout-panel-left" style="width:15px;height:15px"></i><span class="hidden sm:inline">Pages</span></button><button type="button" data-act="mk-toggle" data-testid="mk-done-button" class="mk-tb-btn"><i data-lucide="check" style="width:15px;height:15px"></i><span>Done</span></button></div>`:'';
  icons(); }
function mkSeg(act,cur,opts,tidp){ return `<div class="mk-seg">${opts.map(([v,l])=>`<button type="button" data-act="${act}" data-val="${v}" data-testid="${tidp}-${v}" aria-pressed="${cur===v}" class="${cur===v?'on':''}">${l}</button>`).join('')}</div>`; }
function mkSwitch(act,val,tid,on,ic,title,desc,locked){ return `<button type="button" data-act="${act}" data-val="${val||''}" data-testid="${tid}" aria-pressed="${on}" ${locked?'disabled':''} class="mk-toggle${on?' on':''}${locked?' is-locked':''}"><span class="mk-toggle-ic"><i data-lucide="${ic}"></i></span><span class="min-w-0 flex-1 text-left"><span class="block text-sm font-semibold text-white">${title}</span>${desc?`<span class="block text-[11px] text-white/50">${desc}</span>`:''}</span>${locked?'<span class="text-[11px] text-white/45">Always on</span>':'<span class="mk-sw"></span>'}</button>`; }
function mkRenderSheet(){ const el=mkRoot('mk-sheet'); const v=state.mkEdit?state.mkSheet:null; if(!v){ el.innerHTML=''; return; }
  const page=mkCurPage(); const m=mkS(); let title='', body='';
  if(v==='add'){ if(!page){ state.mkSheet=null; el.innerHTML=''; return; } const P=mkPage(page); const have=new Set(P.widgets.map(w=>w.type)); const hidden=Object.values(P.blocks).filter(c=>c&&c.hidden).length;
    title='Add to '+MK_PAGE_LABEL[page];
    body=`<p class="mk-lbl">Pull in from other pages</p><div class="space-y-1.5">${Object.entries(MK_WIDGETS).map(([k,w])=>{ const on=have.has(k); return `<button type="button" data-act="mk-add-widget" data-val="${k}" data-testid="mk-add-widget-${k}" ${on?'disabled':''} class="mk-pick${on?' is-added':''}"><span class="mk-pick-ic"><i data-lucide="${w.ic}"></i></span><span class="min-w-0 flex-1 text-left"><span class="block text-sm font-semibold text-white">${w.label}</span><span class="block text-[11px] text-white/50">From ${w.from}</span></span><span class="mk-pick-tag">${on?'Added':'Add'}</span></button>`; }).join('')}</div>
    <p class="mk-lbl mt-4">Make your own</p><div class="grid grid-cols-2 gap-2"><button type="button" data-act="mk-add-canvas" data-testid="mk-add-canvas" class="mk-tile"><i data-lucide="square-dashed"></i><span>Blank canvas</span></button><button type="button" data-act="mk-sheet" data-val="sticker-new" data-testid="mk-add-sticker" class="mk-tile"><i data-lucide="sticker"></i><span>Sticker</span></button></div>${hidden?`<p class="mk-hint mt-3">${hidden} hidden section${hidden!==1?'s':''} on this page. Tap the eye on a dashed section to bring it back.</p>`:''}`; }
  else if(v==='block'){ const id=state.mkSel, blk=id&&mkBlockEl(id); if(!page||!blk){ state.mkSheet=null; el.innerHTML=''; return; } const P=mkPage(page); const cfg=P.blocks[id]||{}; const wd=P.widgets.find(x=>x.id===id); const isCv=P.canvases.some(x=>x.id===id); const b={id,kind:wd?'widget':isCv?'canvas':'block',type:wd&&wd.type};
    const w=cfg.w||((blk.className.match(/mk-w-(\w+)/)||[])[1])||'full'; const inner=blk.querySelector(':scope > .mk-inner'); const curH=cfg.h||(isCv?240:Math.min(900,Math.max(100,Math.round(inner?inner.getBoundingClientRect().height:300))));
    title=esc(mkLabel(b));
    body=`${wd?`<p class="mk-hint">Pulled in from ${MK_WIDGETS[wd.type].from}.</p>`:''}
    <div class="mk-field"><p class="mk-lbl">Width</p>${mkSeg('mk-w',w,MK_WIDTHS,'mk-width')}<p class="mk-hint sm:hidden">Phones show every section full width.</p></div>
    <div class="mk-field"><div class="mk-lbl-row"><p class="mk-lbl">Height</p><button type="button" data-act="mk-h-auto" data-testid="mk-height-auto" class="mk-chip${(!cfg.h&&!isCv)?' on':''}">${isCv?'Reset':'Auto'}</button></div><input type="range" min="100" max="900" step="10" value="${curH}" data-mk-input="height" data-testid="mk-height-range" aria-label="Height" class="i-slider w-full"></div>
    <div class="mk-field"><p class="mk-lbl">Surface</p>${mkSeg('mk-surf',cfg.surf||(isCv?'glass':'default'),MK_SURF,'mk-surf')}</div>
    <div class="mk-field"><div class="mk-lbl-row"><p class="mk-lbl">Corners</p><span class="mk-val" id="mk-radius-val">${cfg.radius==null?'Auto':cfg.radius+'px'}</span></div><input type="range" min="0" max="56" step="2" value="${cfg.radius==null?28:cfg.radius}" data-mk-input="radius" data-testid="mk-radius-range" aria-label="Corner radius" class="i-slider w-full"></div>
    <div class="mk-field"><div class="mk-lbl-row"><p class="mk-lbl">Tint</p>${cfg.tint?`<button type="button" data-act="mk-tint-clear" data-testid="mk-tint-clear" class="mk-chip">None</button>`:''}</div><div class="flex flex-wrap items-center gap-2"><label class="mk-color" style="background:${cfg.tint||'conic-gradient(#ff2d78,#f59e0b,#34d399,#22d3ee,#9328ff,#ff2d78)'}"><input type="color" value="${cfg.tint||'#9328ff'}" data-mk-input="tint" data-testid="mk-tint-input" aria-label="Custom tint"></label>${MK_TINTS.map(c=>`<button type="button" data-act="mk-tint" data-val="${c}" data-testid="mk-tint-${c.slice(1)}" aria-label="Tint ${c}" class="mk-swatch${cfg.tint===c?' on':''}" style="background:${c}"></button>`).join('')}</div></div>
    <div class="mk-field"><p class="mk-lbl">Arrange</p><div class="grid grid-cols-2 gap-2"><button type="button" data-act="mk-move" data-val="up" data-testid="mk-move-up" class="mk-btn"><i data-lucide="arrow-up"></i>Move up</button><button type="button" data-act="mk-move" data-val="down" data-testid="mk-move-down" class="mk-btn"><i data-lucide="arrow-down"></i>Move down</button></div></div>
    ${isCv?`<button type="button" data-act="mk-sheet" data-val="sticker-new" data-testid="mk-canvas-add-sticker" class="mk-btn is-primary mb-3 w-full"><i data-lucide="sticker"></i>Add a sticker or text here</button>`:''}
    <div class="grid grid-cols-3 gap-2"><button type="button" data-act="mk-hide" data-id="${id}" data-testid="mk-sheet-hide" class="mk-btn"><i data-lucide="${cfg.hidden?'eye':'eye-off'}"></i>${cfg.hidden?'Show':'Hide'}</button><button type="button" data-act="mk-reset-block" data-testid="mk-reset-block" class="mk-btn"><i data-lucide="rotate-ccw"></i>Reset</button>${(wd||isCv)?`<button type="button" data-act="mk-remove" data-id="${id}" data-testid="mk-sheet-remove" class="mk-btn is-danger"><i data-lucide="trash-2"></i>Remove</button>`:''}</div>`; }
  else if(v==='sticker-new'){ if(!page){ state.mkSheet=null; el.innerHTML=''; return; } const cv=state.mkSel&&mkPage(page).canvases.some(c=>c.id===state.mkSel);
    title='Add a sticker';
    body=`<p class="mk-hint mb-3">${cv?'Adding to the selected canvas.':'Adding to the page. Drag it anywhere after.'}</p>
    <button type="button" data-act="mk-st-upload" data-testid="mk-sticker-upload" class="mk-btn is-primary w-full"><i data-lucide="upload"></i>Upload an image (PNG, JPG, GIF, SVG)</button><input type="file" accept="image/*,.svg" id="mk-st-file" data-testid="mk-sticker-file" class="hidden">
    <div class="mk-field mt-3"><p class="mk-lbl">Image link from the web</p><div class="flex gap-2"><input id="mk-st-url" data-testid="mk-sticker-url" placeholder="https://\u2026/sticker.png" autocomplete="off" class="mk-input"><button type="button" data-act="mk-add-url" data-testid="mk-sticker-url-add" class="mk-btn shrink-0">Add</button></div></div>
    <div class="mk-field"><p class="mk-lbl">Paste SVG code</p><textarea id="mk-st-svg" data-testid="mk-sticker-svg" rows="3" placeholder="<svg \u2026>\u2026</svg>" class="mk-input mk-ta"></textarea><button type="button" data-act="mk-add-svg" data-testid="mk-sticker-svg-add" class="mk-btn mt-2 w-full">Add SVG</button></div>
    <p class="mk-hint mb-3">Tip: copy any image, then paste (Ctrl/Cmd + V) while this panel is open.</p>
    <div class="mk-field"><p class="mk-lbl">Emoji</p><div class="mk-emoji-grid">${BG_EMOJIS.map((e,i)=>`<button type="button" data-act="mk-add-emoji" data-val="${e}" data-testid="mk-emoji-${i}" aria-label="Add ${e}">${e}</button>`).join('')}</div></div>
    <div class="mk-field"><p class="mk-lbl">Text</p><div class="flex gap-2"><input id="mk-st-text" data-testid="mk-sticker-text" maxlength="60" placeholder="Say something" autocomplete="off" class="mk-input"><label class="mk-color shrink-0" style="background:${state.mkTextColor||'#ffffff'}"><input type="color" id="mk-st-color" value="${state.mkTextColor||'#ffffff'}" aria-label="Text color"></label><button type="button" data-act="mk-add-text" data-testid="mk-sticker-text-add" class="mk-btn shrink-0">Add</button></div></div>
    ${mkSwitch('mk-react-new','','mk-react-new',!!state.mkReactNew,'audio-lines','Dance to the music','New stickers pulse with the beat, like the visualizer')}`; }
  else if(v==='sticker-edit'){ const f=mkFind(state.mkStSel); if(!f){ state.mkSheet=null; el.innerHTML=''; return; } const s=f.s; const op=s.op==null?1:s.op;
    title=s.kind==='text'?'Text sticker':s.kind==='emoji'?'Emoji sticker':'Image sticker';
    body=`<div class="mk-field"><div class="mk-lbl-row"><p class="mk-lbl">Size</p><span class="mk-val" id="mk-st-size-val">${s.w}px</span></div><input type="range" min="24" max="600" step="2" value="${s.w}" data-mk-input="st-size" data-testid="mk-st-size" aria-label="Sticker size" class="i-slider w-full"></div>
    <div class="mk-field"><div class="mk-lbl-row"><p class="mk-lbl">Rotation</p><span class="mk-val" id="mk-st-rot-val">${s.rot||0}\u00b0</span></div><input type="range" min="-180" max="180" step="1" value="${s.rot||0}" data-mk-input="st-rot" data-testid="mk-st-rot" aria-label="Rotation" class="i-slider w-full"></div>
    <div class="mk-field"><div class="mk-lbl-row"><p class="mk-lbl">Opacity</p><span class="mk-val" id="mk-st-op-val">${Math.round(op*100)}%</span></div><input type="range" min="0.1" max="1" step="0.05" value="${op}" data-mk-input="st-op" data-testid="mk-st-op" aria-label="Opacity" class="i-slider w-full"></div>
    ${s.kind==='text'?`<div class="mk-field"><p class="mk-lbl">Text</p><div class="flex gap-2"><input value="${esc(s.text)}" maxlength="60" data-mk-input="st-text" data-testid="mk-st-text-edit" class="mk-input"><label class="mk-color shrink-0" style="background:${esc(s.color||'#ffffff')}"><input type="color" value="${esc(s.color||'#ffffff')}" data-mk-input="st-color" data-testid="mk-st-color" aria-label="Text color"></label></div></div>`:''}
    <div class="mb-3">${mkSwitch('mk-st-react','','mk-st-react',!!s.react,'audio-lines','Dance to the music','Pulse with the beat while a song plays')}</div>
    <div class="grid grid-cols-2 gap-2"><button type="button" data-act="mk-st-z" data-val="up" data-testid="mk-st-front" class="mk-btn"><i data-lucide="bring-to-front"></i>Forward</button><button type="button" data-act="mk-st-z" data-val="down" data-testid="mk-st-back" class="mk-btn"><i data-lucide="send-to-back"></i>Back</button><button type="button" data-act="mk-st-dup" data-testid="mk-st-dup" class="mk-btn"><i data-lucide="copy"></i>Duplicate</button><button type="button" data-act="mk-st-del" data-id="${s.id}" data-testid="mk-st-delete" class="mk-btn is-danger"><i data-lucide="trash-2"></i>Delete</button></div>`; }
  else if(v==='pages'){ const home=mkHome();
    title='Pages & homepage';
    body=`<p class="mk-lbl">Show in navigation</p><div class="space-y-1.5">${MK_NAV.map(([id,label,ic])=>mkSwitch('mk-page-toggle',id,'mk-page-toggle-'+id,id==='settings'||!m.hidden.includes(id),ic,label,'',id==='settings')).join('')}</div>
    <p class="mk-lbl mt-4">Open the app on</p><div class="mk-seg mk-seg-wrap">${mkNav(MK_NAV).map(([id,label])=>`<button type="button" data-act="mk-home" data-val="${id}" data-testid="mk-home-${id}" aria-pressed="${home===id}" class="${home===id?'on':''}">${label}</button>`).join('')}</div>
    <div class="mt-4">${mkSwitch('mk-fab-toggle','','mk-fab-toggle-sheet',m.fab!==false,'wand-sparkles','Floating wand button','If hidden, open Magic Markup from Settings \u2192 Layout')}</div>
    <div class="mt-4 grid grid-cols-2 gap-2">${page?`<button type="button" data-act="mk-reset-page" data-testid="mk-reset-page" class="mk-btn"><i data-lucide="rotate-ccw"></i>Reset this page</button>`:''}<button type="button" data-act="mk-reset-all" data-testid="mk-reset-all" class="mk-btn is-danger"><i data-lucide="trash-2"></i>Reset everything</button></div>`; }
  el.innerHTML=`<div class="mk-sheet mk-ui dark-surface" data-testid="mk-sheet-${v}"><div class="mk-sheet-head"><p class="mk-sheet-title">${title}</p><button type="button" data-act="mk-sheet-close" data-testid="mk-sheet-close" aria-label="Close panel" class="mk-icon-btn"><i data-lucide="x" style="width:16px;height:16px"></i></button></div><div class="mk-sheet-body soft-scroll">${body}</div></div>`;
  icons(); el.querySelectorAll('input[type=range]').forEach(r=>{ try{ fillSlider(r); }catch(e){} }); }

/* ---------- actions ---------- */
function mkSetEdit(on){ state.mkEdit=!!on; state.mkSheet=null; state.mkSel=null; state.mkStSel=null;
  if(on && state.view==='library' && (state.genre!=='all'||state.query)){ state.genre='all'; state.query=''; }
  renderView(); mkRenderSheet();
  if(on) toast('Magic Markup on', mkCurPage()?'Drag, resize and restyle anything. Tap Done when finished.':'Open Library, Icons, Studios or Game to edit');
  else { mkSave(); toast('Layout saved'); } }
function mkStart(){ const target=MK_PAGES.includes(state.view)?state.view:(MK_PAGES.includes(mkHome())?mkHome():'library'); if(state.view!==target) navigate(target); mkSetEdit(true); }
function mkSelect(id){ if(!id) return; state.mkSel=id; state.mkStSel=null; document.querySelectorAll('#view .mk-sel').forEach(x=>x.classList.remove('mk-sel')); document.querySelectorAll('#view .mk-st-sel').forEach(x=>x.classList.remove('mk-st-sel')); const el=mkBlockEl(id); if(el) el.classList.add('mk-sel'); state.mkSheet='block'; mkRenderSheet(); }
function mkCfg(id){ const page=mkCurPage(); if(!page||!id) return null; const P=mkPage(page); return P.blocks[id]||(P.blocks[id]={}); }
function mkCfgSet(patch){ const cfg=mkCfg(state.mkSel); if(!cfg) return; Object.keys(patch).forEach(k=>{ const v=patch[k]; if(v===''||v===0||v==null) delete cfg[k]; else cfg[k]=v; }); mkSave(); renderView(); mkRenderSheet(); }
function mkDomOrder(){ const grid=document.querySelector('#view [data-mk-page]'); return grid?[...grid.children].filter(x=>x.dataset&&x.dataset.mkId).map(x=>x.dataset.mkId):[]; }
function mkCommitOrder(dom){ const page=mkCurPage(); if(!page) return; const P=mkPage(page); const old=P.order.length?P.order:dom; const merged=dom.slice(); old.forEach((id,i)=>{ if(merged.includes(id)) return; let at=-1; for(let j=i-1;j>=0;j--){ const k=merged.indexOf(old[j]); if(k>=0){ at=k; break; } } merged.splice(at+1,0,id); }); P.order=merged; mkSave(); }
function mkMove(dir){ const id=state.mkSel; const o=mkDomOrder(); const i=o.indexOf(id); const j=dir==='up'?i-1:i+1; if(i<0||j<0||j>=o.length) return; [o[i],o[j]]=[o[j],o[i]]; mkCommitOrder(o); renderView(); mkRenderSheet(); const el=mkBlockEl(id); if(el) el.scrollIntoView({behavior:'smooth',block:'center'}); }
function mkInsertNew(id){ const o=mkDomOrder(); const at=state.mkSel?o.indexOf(state.mkSel):0; o.splice(at<0?1:at+1,0,id); mkCommitOrder(o); }
function mkFocusNew(id){ state.mkSel=id; renderView(); requestAnimationFrame(()=>{ const el=mkBlockEl(id); if(el){ el.scrollIntoView({behavior:'smooth',block:'center'}); } mkSelect(id); }); }
function mkAddWidget(type){ const page=mkCurPage(); if(!page||!MK_WIDGETS[type]) return; const P=mkPage(page); if(P.widgets.some(w=>w.type===type)) return; const id=mkUID('w'); P.widgets.push({id,type}); mkInsertNew(id); mkFocusNew(id); toast(MK_WIDGETS[type].label+' added','Pulled in from '+MK_WIDGETS[type].from); }
function mkAddCanvas(){ const page=mkCurPage(); if(!page) return; const P=mkPage(page); if(P.canvases.length>=8){ toast('Canvas limit reached','Up to 8 canvases per page'); return; } const id=mkUID('c'); P.canvases.push({id}); mkInsertNew(id); mkFocusNew(id); toast('Blank canvas added','Add stickers or text to it'); }
function mkRemove(id){ const page=mkCurPage(); if(!page||!id) return; const P=mkPage(page); const gone=P.stickers.filter(s=>s.cv===id); P.widgets=P.widgets.filter(w=>w.id!==id); P.canvases=P.canvases.filter(c=>c.id!==id); P.stickers=P.stickers.filter(s=>s.cv!==id); P.order=P.order.filter(x=>x!==id); delete P.blocks[id]; mkDropAssets(gone); if(state.mkSel===id){ state.mkSel=null; state.mkSheet=null; } mkSave(); renderView(); mkRenderSheet(); toast('Removed'); }
function mkHideToggle(id){ const cfg=mkCfg(id); if(!cfg) return; cfg.hidden=!cfg.hidden; if(!cfg.hidden) delete cfg.hidden; mkSave(); renderView(); if(state.mkSheet==='block') mkRenderSheet(); toast(cfg.hidden?'Section hidden':'Section shown', cfg.hidden?'It stays as a dashed outline while you edit':''); }
function mkStSet(patch){ const f=mkFind(state.mkStSel); if(!f) return; Object.assign(f.s,patch); mkSave(); renderView(); mkRenderSheet(); }
function mkStDelete(id){ const f=mkFind(id); if(!f) return; f.P.stickers=f.P.stickers.filter(s=>s.id!==id); mkDropAssets([f.s]); if(state.mkStSel===id){ state.mkStSel=null; if(state.mkSheet==='sticker-edit') state.mkSheet=null; } mkSave(); renderView(); mkRenderSheet(); }
function mkStDup(){ const f=mkFind(state.mkStSel); if(!f) return; const c=Object.assign({},f.s,{id:mkUID('s'),x:Math.min(0.95,f.s.x+0.04),y:f.s.cv?Math.min(0.95,f.s.y+0.06):f.s.y+30,z:(f.s.z||1)+1}); f.P.stickers.push(c); state.mkStSel=c.id; mkSave(); renderView(); mkRenderSheet(); }
function mkTogglePage(id){ if(id==='settings') return; const m=mkS(); const i=m.hidden.indexOf(id); if(i>=0) m.hidden.splice(i,1); else m.hidden.push(id); mkSave(); renderShell(); renderView(); mkRenderSheet(); toast((MK_PAGE_LABEL[id]||id)+(i>=0?' shown':' hidden'), i>=0?'Back in the navigation':'Removed from the navigation bars'); }
function mkSetHome(id){ const m=mkS(); m.home=id; mkSave(); if(state.view==='settings') renderView(); mkRenderSheet(); toast('Homepage set', 'Treesh will open on '+(MK_PAGE_LABEL[id]||id)); }
function mkResetPage(page){ const m=mkS(); const P=m.pages[page]; const st=(P&&P.stickers)||[]; delete m.pages[page]; mkDropAssets(st); state.mkSel=null; state.mkStSel=null; state.mkSheet=null; mkSave(); renderView(); mkRenderSheet(); toast(MK_PAGE_LABEL[page]+' reset','Everything is back where it started'); }
function mkResetAll(){ const m=mkS(); const st=[]; Object.values(m.pages).forEach(P=>{ ((P&&P.stickers)||[]).forEach(s=>st.push(s)); }); m.pages={}; m.hidden=[]; m.home='library'; mkDropAssets(st); state.mkSel=null; state.mkStSel=null; state.mkSheet=null; mkSave(); renderShell(); renderView(); mkRenderSheet(); toast('All layouts reset'); }
function mkAct(act,t){ const val=t.dataset.val, id=t.dataset.id;
  switch(act){
    case 'mk-toggle': mkSetEdit(!state.mkEdit); break;
    case 'mk-start': mkStart(); break;
    case 'mk-sel': mkSelect(id); break;
    case 'mk-hide': mkHideToggle(id||state.mkSel); break;
    case 'mk-remove': mkRemove(id||state.mkSel); break;
    case 'mk-w': mkCfgSet({w:val}); break;
    case 'mk-h-auto': mkCfgSet({h:0}); break;
    case 'mk-surf': mkCfgSet({surf:val}); break;
    case 'mk-tint': mkCfgSet({tint:val}); break;
    case 'mk-tint-clear': mkCfgSet({tint:''}); break;
    case 'mk-move': mkMove(val); break;
    case 'mk-reset-block': { const page=mkCurPage(); if(page&&state.mkSel){ delete mkPage(page).blocks[state.mkSel]; mkSave(); renderView(); mkRenderSheet(); } break; }
    case 'mk-sheet': state.mkSheet=val; if(val!=='sticker-edit') state.mkStSel=null; mkRenderSheet(); break;
    case 'mk-sheet-close': state.mkSheet=null; mkRenderSheet(); break;
    case 'mk-add-widget': mkAddWidget(val); break;
    case 'mk-add-canvas': mkAddCanvas(); break;
    case 'mk-st-upload': { const f=document.getElementById('mk-st-file'); if(f) f.click(); break; }
    case 'mk-add-url': { const i=document.getElementById('mk-st-url'); mkAddUrlStr(i&&i.value); break; }
    case 'mk-add-svg': { const i=document.getElementById('mk-st-svg'); mkAddSvgCode(i&&i.value); break; }
    case 'mk-add-emoji': mkAddSticker({id:mkUID('s'),kind:'emoji',text:val}); break;
    case 'mk-add-text': { const i=document.getElementById('mk-st-text'); const tx=((i&&i.value)||'').trim().slice(0,60); if(!tx){ toast('Type some text first'); break; } mkAddSticker({id:mkUID('s'),kind:'text',text:tx,color:state.mkTextColor||'#ffffff'}); break; }
    case 'mk-react-new': state.mkReactNew=!state.mkReactNew; mkRenderSheet(); break;
    case 'mk-st-react': { const f=mkFind(state.mkStSel); if(f) mkStSet({react:!f.s.react}); break; }
    case 'mk-st-z': { const f=mkFind(state.mkStSel); if(f) mkStSet({z:Math.max(1,(f.s.z||1)+(val==='up'?1:-1))}); break; }
    case 'mk-st-dup': mkStDup(); break;
    case 'mk-st-del': mkStDelete(id||state.mkStSel); break;
    case 'mk-page-toggle': mkTogglePage(val); break;
    case 'mk-home': mkSetHome(val); break;
    case 'mk-fab-toggle': { const m=mkS(); m.fab=(m.fab===false); mkSave(); mkRenderChrome(); if(state.mkSheet==='pages') mkRenderSheet(); if(state.view==='settings') renderView(); toast(m.fab?'Wand button on':'Wand button hidden', m.fab?'':'Open Magic Markup from Settings \u2192 Layout'); break; }
    case 'mk-reset-page': { const page=mkCurPage(); if(page) openConfirm('Reset '+MK_PAGE_LABEL[page]+'?','Puts every section back where it started and removes this page\u2019s stickers, canvases and pulled-in sections.',()=>mkResetPage(page)); break; }
    case 'mk-reset-all': openConfirm('Reset every layout?','Restores all pages, shows hidden pages again, sets the homepage back to Library and deletes all stickers.',mkResetAll); break;
    case 'mk-glass': { LS.set('treesh_glass',val); applyGlass(); renderView(); toast('Glass: '+({auto:'Auto',strong:'Strong',medium:'Medium',solid:'Solid'}[val]||val)); break; }
    case 'mk-xf-toggle': xfToggle(); renderView(); break;
    case 'mk-pf-banner-remove': pfStashDraft(); assetDel('profile_banner').catch(()=>{}); state.profileBanner=''; renderView(); toast('Banner removed'); break;
  } }

/* ---------- pointer: drag blocks, resize, move/rotate/resize stickers ---------- */
function mkAutoScroll(y){ _mkScrollV=y<90?-14:(y>window.innerHeight-90?14:0); if(_mkScrollV&&!_mkScrollRAF){ const loop=()=>{ if(!_mkScrollV){ _mkScrollRAF=null; return; } window.scrollBy(0,_mkScrollV); _mkScrollRAF=requestAnimationFrame(loop); }; _mkScrollRAF=requestAnimationFrame(loop); } }
function mkTrack(move,up){ const mv=ev=>{ ev.preventDefault(); move(ev); }; const end=ev=>{ document.removeEventListener('pointermove',mv); document.removeEventListener('pointerup',end); document.removeEventListener('pointercancel',end); _mkScrollV=0; up(ev); }; document.addEventListener('pointermove',mv,{passive:false}); document.addEventListener('pointerup',end); document.addEventListener('pointercancel',end); }
function mkStartDrag(e,id){ const blk=mkBlockEl(id); if(!blk) return; const grid=blk.parentNode; blk.classList.add('mk-dragging'); document.querySelectorAll('#view .mk-sel').forEach(x=>x.classList.remove('mk-sel')); blk.classList.add('mk-sel'); state.mkSel=id;
  mkTrack(ev=>{ const el=document.elementFromPoint(ev.clientX,ev.clientY); const over=el&&el.closest&&el.closest('[data-mk-id]'); if(over&&over!==blk&&over.parentNode===grid){ const r=over.getBoundingClientRect(); const midY=r.top+r.height/2; const sameRow=Math.abs(ev.clientY-midY)<r.height*0.3 && r.width<grid.clientWidth*0.9; const before=sameRow?(ev.clientX<r.left+r.width/2):(ev.clientY<midY); if(before){ if(over.previousElementSibling!==blk) grid.insertBefore(blk,over); } else if(over.nextElementSibling!==blk) grid.insertBefore(blk,over.nextSibling); } mkAutoScroll(ev.clientY); },
  ()=>{ blk.classList.remove('mk-dragging'); mkCommitOrder(mkDomOrder()); renderView(); if(state.mkSheet==='block') mkRenderSheet(); }); }
function mkStartResize(e,id){ const blk=mkBlockEl(id); if(!blk) return; const inner=blk.querySelector(':scope > .mk-inner'); const grid=blk.parentNode; const r0=blk.getBoundingClientRect(); const gw=grid.getBoundingClientRect().width; const sx=e.clientX, sy=e.clientY, h0=inner.getBoundingClientRect().height; const wide=window.innerWidth>=640; const cfg=mkCfg(id); let w=cfg.w||((blk.className.match(/mk-w-(\w+)/)||[])[1])||'full', h=0;
  blk.classList.add('mk-resizing');
  mkTrack(ev=>{ if(wide){ const cols=Math.round((r0.width+(ev.clientX-sx))/(gw/12)); const best=[4,6,8,12].reduce((a,b)=>Math.abs(b-cols)<Math.abs(a-cols)?b:a); w={4:'third',6:'half',8:'twothird',12:'full'}[best]; blk.className=blk.className.replace(/mk-w-\w+/,'mk-w-'+w); } const dy=ev.clientY-sy; if(Math.abs(dy)>8||h){ h=Math.max(100,Math.min(1400,Math.round(h0+dy))); inner.style.height=h+'px'; if(!blk.classList.contains('mk-cv')) inner.style.overflow='auto'; } mkAutoScroll(ev.clientY); },
  ()=>{ blk.classList.remove('mk-resizing'); cfg.w=w; if(h) cfg.h=h; state.mkSel=id; mkSave(); renderView(); if(state.mkSheet==='block') mkRenderSheet(); }); }
function mkStStart(e,id,mode){ const el=document.querySelector('#view [data-mk-st="'+id+'"]'); const f=mkFind(id); if(!el||!f) return; const s=f.s;
  document.querySelectorAll('#view .mk-st-sel').forEach(x=>x.classList.remove('mk-st-sel')); el.classList.add('mk-st-sel'); state.mkStSel=id;
  const host=s.cv?el.closest('[data-mk-canvas]'):el.closest('[data-mk-page]'); const hr=host.getBoundingClientRect(); const er=el.getBoundingClientRect(); const cx=er.left+er.width/2, cy=er.top+er.height/2; const sx=e.clientX, sy=e.clientY; const x0=s.x, y0=s.y, w0=s.w, rot0=s.rot||0; const a0=Math.atan2(sy-cy,sx-cx), d0=Math.max(8,Math.hypot(sx-cx,sy-cy)); let moved=false;
  mkTrack(ev=>{ const dx=ev.clientX-sx, dy=ev.clientY-sy; if(Math.abs(dx)+Math.abs(dy)>3) moved=true;
    if(mode==='move'){ s.x=Math.max(0,Math.min(1,x0+dx/hr.width)); s.y=s.cv?Math.max(0,Math.min(1,y0+dy/hr.height)):Math.max(0,Math.round(y0+dy)); el.style.left=(s.x*100)+'%'; el.style.top=s.cv?(s.y*100)+'%':s.y+'px'; if(!s.cv) mkAutoScroll(ev.clientY); }
    else if(mode==='resize'){ s.w=Math.max(24,Math.min(900,Math.round(w0*Math.hypot(ev.clientX-cx,ev.clientY-cy)/d0))); mkStApplySize(el,s); }
    else { s.rot=Math.round(rot0+(Math.atan2(ev.clientY-cy,ev.clientX-cx)-a0)*180/Math.PI); if(s.rot>180) s.rot-=360; if(s.rot<-180) s.rot+=360; el.style.setProperty('--rot',s.rot+'deg'); } },
  ()=>{ mkSave(); if(mode==='move'&&!moved){ state.mkSheet='sticker-edit'; } if(state.mkSheet==='sticker-edit'||(mode==='move'&&!moved)) mkRenderSheet(); }); }

document.addEventListener('pointerdown',e=>{ if(!state.mkEdit) return; const t=e.target; if(!t||!t.closest||!t.closest('#view')) return;
  const go=(fn,...a)=>{ e.preventDefault(); e.stopPropagation(); fn(e,...a); };
  const rs=t.closest('[data-mk-resize]'); if(rs) return go(mkStartResize,rs.dataset.mkResize);
  const dg=t.closest('[data-mk-drag]'); if(dg) return go(mkStartDrag,dg.dataset.mkDrag);
  const srs=t.closest('[data-mk-st-rs]'); if(srs) return go(mkStStart,srs.dataset.mkStRs,'resize');
  const sro=t.closest('[data-mk-st-rot]'); if(sro) return go(mkStStart,sro.dataset.mkStRot,'rotate');
  if(t.closest('.mk-ui')) return;
  const st=t.closest('[data-mk-st]'); if(st) return go(mkStStart,st.dataset.mkSt,'move');
  if(t.closest('[data-mk-id]')) e.stopPropagation(); },{capture:true,passive:false});
document.addEventListener('click',e=>{ if(!state.mkEdit) return; const t=e.target; if(!t||!t.closest||!t.closest('#view')) return; if(t.closest('.mk-ui')) return; if(t.closest('[data-mk-st]')){ e.preventDefault(); e.stopPropagation(); return; } const blk=t.closest('[data-mk-id]'); if(blk){ e.preventDefault(); e.stopPropagation(); mkSelect(blk.dataset.mkId); } },true);
document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act]'); if(!t) return; const act=t.dataset.act; if(act&&act.indexOf('mk-')===0) mkAct(act,t); });
document.addEventListener('input',e=>{ const el=e.target; if(!el||!el.dataset) return;
  if(el.id==='mk-st-color'){ state.mkTextColor=el.value; const l=el.closest('label'); if(l) l.style.background=el.value; return; }
  if(el.id==='set-bio'){ const c=document.getElementById('set-bio-count'); if(c) c.textContent=el.value.length; return; }
  const k=el.dataset.mkInput; if(!k) return; if(el.type==='range'){ try{ fillSlider(el); }catch(_){} }
  if(k==='radius'||k==='tint'||k==='height'){ const cfg=mkCfg(state.mkSel); const blk=mkBlockEl(state.mkSel); if(!cfg) return;
    if(k==='radius'){ cfg.radius=+el.value; if(blk) blk.style.setProperty('--mk-r',cfg.radius+'px'); const v=document.getElementById('mk-radius-val'); if(v) v.textContent=cfg.radius+'px'; }
    else if(k==='tint'){ cfg.tint=el.value; if(blk){ blk.style.setProperty('--mk-tint',el.value); blk.classList.add('mk-tinted'); } const l=el.closest('label'); if(l) l.style.background=el.value; }
    else { cfg.h=+el.value; const inner=blk&&blk.querySelector(':scope > .mk-inner'); if(inner){ inner.style.height=cfg.h+'px'; if(!blk.classList.contains('mk-cv')) inner.style.overflow='auto'; } }
    mkSaveSoon(); return; }
  const f=mkFind(state.mkStSel); if(!f) return; const s=f.s; const sel=document.querySelector('#view [data-mk-st="'+s.id+'"]'); const setT=(i,v)=>{ const x=document.getElementById(i); if(x) x.textContent=v; };
  if(k==='st-size'){ s.w=+el.value; if(sel) mkStApplySize(sel,s); setT('mk-st-size-val',s.w+'px'); }
  else if(k==='st-rot'){ s.rot=+el.value; if(sel) sel.style.setProperty('--rot',s.rot+'deg'); setT('mk-st-rot-val',s.rot+'\u00b0'); }
  else if(k==='st-op'){ s.op=+el.value; if(sel) sel.style.opacity=s.op; setT('mk-st-op-val',Math.round(s.op*100)+'%'); }
  else if(k==='st-text'){ s.text=el.value.slice(0,60); const tx=sel&&sel.querySelector('.mk-st-text'); if(tx) tx.textContent=s.text; }
  else if(k==='st-color'){ s.color=el.value; const tx=sel&&sel.querySelector('.mk-st-text'); if(tx) tx.style.color=s.color; const l=el.closest('label'); if(l) l.style.background=el.value; }
  mkSaveSoon(); });
document.addEventListener('change',e=>{ const t=e.target; if(!t) return;
  if(t.id==='mk-st-file'){ const f=t.files&&t.files[0]; if(f) mkAddImageFile(f); t.value=''; }
  else if(t.id==='set-banner-input'){ const f=t.files&&t.files[0]; if(f) pfSetBanner(f); t.value=''; }
  else if(t.dataset&&t.dataset.mkInput==='tint'){ mkSave(); renderView(); mkRenderSheet(); } });
document.addEventListener('paste',e=>{ if(!state.mkEdit||state.mkSheet!=='sticker-new') return; const cd=e.clipboardData; if(!cd) return; let file=[...(cd.files||[])].find(f=>/^image\//.test(f.type)); if(!file){ for(const it of [...(cd.items||[])]){ if(it.kind==='file'){ const f=it.getAsFile(); if(f&&/^image\//.test(f.type)){ file=f; break; } } } } if(file){ e.preventDefault(); mkAddImageFile(file); return; } const tag=(e.target&&e.target.tagName)||''; if(tag==='INPUT'||tag==='TEXTAREA') return; const txt=(cd.getData('text/plain')||'').trim(); if(/<svg[\s>]/i.test(txt)){ e.preventDefault(); mkAddSvgCode(txt); } else if(/^(https?:\/\/|data:image\/)\S+$/i.test(txt)){ e.preventDefault(); mkAddUrlStr(txt); } });
document.addEventListener('keydown',e=>{ if(e.key!=='Escape'||!state.mkEdit) return; const tag=(e.target&&e.target.tagName)||''; if(tag==='INPUT'||tag==='TEXTAREA') return; const md=document.getElementById('modal'); if(md&&md.innerHTML) return; if(state.mkSheet){ state.mkSheet=null; mkRenderSheet(); } else mkSetEdit(false); });

/* ---------- stickers that dance to the music ---------- */
function mkReactLoop(){ if(_mkRAF||state.perfMode||!document.querySelector('.mk-react')) return; const tick=()=>{ const list=document.querySelectorAll('.mk-react'); if(!list.length||state.perfMode){ _mkRAF=null; return; } let lvl=0; if(state.isPlaying){ if(typeof _vizAnalyser!=='undefined'&&_vizAnalyser&&_vizBytes){ try{ _vizAnalyser.getByteFrequencyData(_vizBytes); }catch(_){} let s=0; for(let i=0;i<6;i++) s+=_vizBytes[i]; lvl=s/6/255; } else { lvl=Math.pow(Math.max(0,Math.sin(performance.now()/1000*Math.PI*4)),4)*0.8; } } const b=(1+lvl*0.32).toFixed(3); list.forEach(el=>el.style.setProperty('--beat',b)); _mkRAF=requestAnimationFrame(tick); }; _mkRAF=requestAnimationFrame(tick); }

/* ---------- glass intensity ---------- */
function mkGlassAuto(){ const cores=navigator.hardwareConcurrency||8, mem=navigator.deviceMemory||8; const small=Math.min(screen.width||1024,screen.height||1024)<768&&window.matchMedia&&matchMedia('(pointer:coarse)').matches; return (cores<=4||mem<=4||small)?'medium':'strong'; }
function applyGlass(){ const g=LS.get('treesh_glass','auto'); const lvl=g==='auto'?mkGlassAuto():g; const c=document.documentElement.classList; c.toggle('gl-medium',lvl==='medium'); c.toggle('gl-solid',lvl==='solid'); }
function mkGlassSettingsHtml(tab){ const g=LS.get('treesh_glass','auto'); return `<section data-testid="settings-glass" class="${tab==='display'?'':'hidden'} rounded-3xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"><div class="mb-1 flex items-center gap-2.5"><span class="grid h-9 w-9 place-items-center rounded-xl bg-[color:var(--treesh-purple)]/15 text-[color:var(--treesh-purple)]"><i data-lucide="droplets" style="width:18px;height:18px"></i></span><h2 class="text-lg font-bold">Glass</h2></div><p class="mb-4 pl-11 text-sm text-white/50">How frosted the floating bubbles look. Auto picks the best level for this device${g==='auto'?' (now '+(mkGlassAuto()==='medium'?'Medium':'Strong')+')':''}.</p>${pseg('mk-glass',g,[['auto','Auto'],['strong','Strong'],['medium','Medium'],['solid','Solid']])}</section>`; }

/* ---------- Settings: Layout tab ---------- */
function mkSettingsHtml(tab){ const m=mkS(), home=mkHome();
  const card=(ic,title,desc,inner,tid)=>`<div class="rounded-3xl border border-white/10 bg-white/[0.04] p-5 sm:p-6"${tid?` data-testid="${tid}"`:''}><div class="mb-1 flex items-center gap-2.5"><span class="grid h-9 w-9 place-items-center rounded-xl bg-[color:var(--treesh-purple)]/15 text-[color:var(--treesh-purple)]"><i data-lucide="${ic}" style="width:18px;height:18px"></i></span><h2 class="text-lg font-bold">${title}</h2></div><p class="mb-4 pl-11 text-sm text-white/50">${desc}</p>${inner}</div>`;
  const tog=(act,val,tid,on,ic,title,desc)=>`<button data-act="${act}" data-val="${val}" data-testid="${tid}" aria-pressed="${on}" role="switch" aria-checked="${on}" class="press flex w-full items-center gap-3 rounded-xl border p-3.5 text-left transition ${on?'border-[color:var(--treesh-purple)]/50 bg-[color:var(--treesh-purple)]/[0.12]':'border-white/10 bg-white/[0.03] hover:bg-white/[0.06]'}"><div class="grid h-9 w-9 shrink-0 place-items-center rounded-lg ${on?'bg-[color:var(--treesh-purple)] text-white':'bg-white/10 text-white/60'}"><i data-lucide="${ic}" style="width:16px;height:16px"></i></div><div class="min-w-0 flex-1"><p class="text-sm font-semibold">${title}</p><p class="text-xs text-white/50">${desc}</p></div><div class="grid h-5 w-5 shrink-0 place-items-center rounded-full border ${on?'border-[color:var(--treesh-purple)] bg-[color:var(--treesh-purple)] text-white':'border-white/25'}">${on?'<i data-lucide="check" style="width:12px;height:12px"></i>':''}</div></button>`;
  return `<section data-testid="settings-layout" class="${tab==='layout'?'':'hidden'} space-y-5">
   ${card('wand-sparkles','Magic Markup','Rearrange, resize and restyle sections, pull in sections from other pages, and drop stickers or blank canvases anywhere on Library, Icons, Studios and Game.',`<div class="flex flex-wrap gap-2"><button data-act="mk-start" data-testid="layout-start-magic-markup" class="press inline-flex items-center gap-2 rounded-full bg-[color:var(--treesh-purple)] px-5 py-2.5 text-sm font-semibold text-white glow-purple"><i data-lucide="wand-sparkles" style="width:16px;height:16px"></i>Start editing</button><button data-act="mk-reset-all" data-testid="layout-reset-all" class="press inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-4 py-2.5 text-sm font-semibold text-white/80 hover:bg-white/10"><i data-lucide="rotate-ccw" style="width:15px;height:15px"></i>Reset all layouts</button></div><div class="mt-4">${tog('mk-fab-toggle','','layout-fab-toggle',m.fab!==false,'wand-sparkles','Floating wand button','Keep the Magic Markup button on screen')}</div>`,'settings-magic-markup')}
   ${card('house','Homepage','The page Treesh opens on.',`<div class="flex flex-wrap gap-2" data-testid="layout-home-picker">${mkNav(MK_NAV).map(([id,label,ic])=>{ const on=home===id; return `<button data-act="mk-home" data-val="${id}" data-testid="layout-home-${id}" aria-pressed="${on}" class="press inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold transition-colors ${on?'border-[color:var(--treesh-purple)] bg-[color:var(--treesh-purple)]/15 text-white':'border-white/12 bg-white/5 text-white/70 hover:bg-white/10'}"><i data-lucide="${ic}" style="width:15px;height:15px"></i>${label}</button>`; }).join('')}</div>`,'settings-homepage')}
   ${card('panels-top-left','Pages','Hide pages you don\u2019t use from the navigation bars. Settings always stays.',`<div class="space-y-2.5">${MK_NAV.filter(n=>n[0]!=='settings').map(([id,label,ic])=>{ const on=!m.hidden.includes(id); return tog('mk-page-toggle',id,'layout-page-toggle-'+id,on,ic,label,on?'Shown in navigation':'Hidden from navigation'); }).join('')}</div>`,'settings-pages')}
  </section>`; }

/* ---------- Settings: real profile page ---------- */
const PF_BADGES=[
  {id:'first',ic:'play',label:'First Spin',desc:'Play a song',ok:s=>s.plays>=1},
  {id:'century',ic:'flame',label:'Century',desc:'100 plays',ok:s=>s.plays>=100},
  {id:'repeat',ic:'repeat',label:'On Repeat',desc:'One song 10\u00d7',ok:s=>s.topCount>=10},
  {id:'hearts',ic:'heart',label:'Heart Collector',desc:'Like 10 songs',ok:s=>s.likes>=10},
  {id:'curator',ic:'list-music',label:'Curator',desc:'3 playlists',ok:s=>s.playlists>=3},
  {id:'lyric',ic:'quote',label:'Lyric Lover',desc:'Save 5 lyrics',ok:s=>s.favLyrics>=5},
  {id:'explorer',ic:'compass',label:'Explorer',desc:'10 artists',ok:s=>s.artists>=10},
  {id:'owl',ic:'moon-star',label:'Night Owl',desc:'Play after midnight',ok:s=>s.owl},
  {id:'streak',ic:'calendar-check',label:'Week Streak',desc:'7 days in a row',ok:s=>s.streak>=7},
  {id:'marathon',ic:'timer',label:'Marathon',desc:'10 hours listened',ok:s=>s.minutes>=600},
  {id:'beat',ic:'drum',label:'Beat Maker',desc:'Make a beat',ok:s=>s.beats>=1},
  {id:'gamer',ic:'gamepad-2',label:'Player One',desc:'Finish 5 games',ok:s=>s.games>=5}
];
function pfStats(){ const pc=state.playCounts||{}; let plays=0, topCount=0, topId=null; const art={};
  for(const id in pc){ const n=+pc[id]||0; plays+=n; const s=SONG_BY_ID[id]; if(!s) continue; if(n>topCount){ topCount=n; topId=id; } const ids=(s.artistIds&&s.artistIds.length)?s.artistIds:['n:'+(s.artist||'')]; ids.forEach(a=>{ art[a]=(art[a]||0)+n; }); }
  let ta=null, taN=0; Object.keys(art).forEach(k=>{ if(art[k]>taN){ taN=art[k]; ta=k; } });
  const sr=state.stars||{}, gs=state.gameStats||{}, tw=state.totWins||{};
  return { plays, topCount, top:topId?SONG_BY_ID[topId]:null, topArtist:ta?(ta.indexOf('n:')===0?{name:ta.slice(2)}:ARTIST_BY_ID[ta]||null):null, topArtistN:taN, artists:Object.keys(art).length, likes:state.favorites.size, playlists:(state.playlists||[]).length, favLyrics:(state.favLyrics||[]).length, minutes:sr.totalMin||0, streak:sr.streak||0, points:sr.points||0, beats:sr.beats||0, games:(gs.games||0)+(tw.plays||0), owl:(state.playLog||[]).some(e=>e&&new Date(e.ts).getHours()<4) }; }
function pfJoined(p){ if(!p) return Date.now(); if(!p.joined){ const log=state.playLog||[]; p.joined=(log[0]&&log[0].ts)||Date.now(); try{ LS.set('treesh_profile',p); }catch(e){} } return p.joined; }
function pfStashDraft(){ const n=document.getElementById('set-nick'), b=document.getElementById('set-bio'), d=document.getElementById('set-bday'); if(n||b) state._pfDraft={nick:n?n.value:null, bio:b?b.value:null, bday:d?d.value:null}; }
function pfSetBanner(f){ if(!/^image\//.test(f.type||'')){ toast('Pick an image file'); return; } if(f.size>15*1024*1024){ toast('Image too large','Use one under 15 MB'); return; } const r=new FileReader(); r.onload=()=>{ compressImageDataUrl(r.result,1600,0.85).then(small=>assetPut('profile_banner',small).then(()=>{ pfStashDraft(); state.profileBanner=small; renderView(); toast('Banner updated'); })).catch(()=>toast('Couldn\u2019t save banner','Your device storage may be full')); }; r.readAsDataURL(f); }
function settingsProfileHtml(editing){ const p=state.profile||{}; const z=zodiac(p.birthday); const S=pfStats(); const banner=state.profileBanner||''; const dr=editing?(state._pfDraft||{}):{};
  const nick=(dr.nick!=null?dr.nick:p.nickname)||''; const shown=p.nickname||'Treesh Fan'; const avSrc=editing?(state._tmpAvatar||p.avatar):p.avatar;
  const bannerStyle=banner?`background-image:url('${banner}');background-size:cover;background-position:center`:'background:radial-gradient(120% 150% at 0% 0%, var(--treesh-purple) 0%, transparent 55%), radial-gradient(110% 140% at 100% 100%, color-mix(in srgb, var(--treesh-purple) 40%, #22d3ee) 0%, transparent 62%), #120f1c';
  const blurCover=(!banner&&S.top)?`<div class="pointer-events-none absolute inset-0 scale-125 opacity-45 blur-2xl" style="background-image:url('${esc(S.top.coverArt||'')}');background-size:cover;background-position:center"></div>`:'';
  const avatar=(cls,id)=>`<div${id?` id="${id}"`:''} class="pf-avatar ${cls} shrink-0 overflow-hidden rounded-full">${avSrc?img(avSrc,'h-full w-full object-cover'):`<span class="grid h-full w-full place-items-center text-3xl font-bold text-white/70">${esc(shown.charAt(0).toUpperCase())}</span>`}</div>`;
  if(editing){ const bday=dr.bday!=null?dr.bday:(p.birthday||''); const bio=dr.bio!=null?dr.bio:(p.bio||'');
    return `<section class="pf-hero relative overflow-hidden rounded-[32px] border border-white/12 bg-white/[0.04]" data-testid="settings-profile-edit">
     <div class="dark-surface relative h-32 overflow-hidden sm:h-44" style="${bannerStyle}" data-testid="profile-banner-edit">${blurCover}<div class="absolute inset-0 bg-black/30"></div><div class="absolute inset-0 flex items-center justify-center gap-2"><label class="pf-bubble press inline-flex cursor-pointer items-center gap-2 rounded-full px-4 py-2 text-sm font-semibold"><i data-lucide="image-plus" style="width:16px;height:16px"></i>${banner?'Change banner':'Add banner'}<input type="file" accept="image/*" id="set-banner-input" data-testid="profile-banner-input" class="hidden"></label>${banner?`<button data-act="mk-pf-banner-remove" data-testid="profile-banner-remove" class="pf-bubble press inline-flex items-center gap-1.5 rounded-full px-3.5 py-2 text-sm font-semibold"><i data-lucide="trash-2" style="width:15px;height:15px"></i>Remove</button>`:''}</div></div>
     <div class="relative px-5 pb-6 sm:px-8"><div class="-mt-12 flex items-end gap-3 sm:-mt-14">${avatar('h-24 w-24 sm:h-28 sm:w-28','set-avatar')}<label class="press mb-1 flex cursor-pointer items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-semibold hover:bg-white/10"><i data-lucide="camera" style="width:13px;height:13px"></i>Change photo<input type="file" accept="image/*" class="hidden" id="set-avatar-input" data-testid="settings-avatar-input"></label></div>
      <div class="mt-5 flex items-center gap-2.5"><span class="grid h-9 w-9 place-items-center rounded-xl bg-[color:var(--treesh-purple)]/15 text-[color:var(--treesh-purple)]"><i data-lucide="user" style="width:18px;height:18px"></i></span><h2 class="text-lg font-bold">Edit profile</h2></div>
      <div class="mt-4 grid gap-4 sm:grid-cols-2">
       <div><label class="mb-1.5 block text-xs uppercase tracking-wide text-white/50">Nickname</label><input id="set-nick" data-testid="settings-nickname-input" value="${esc(nick)}" maxlength="40" class="h-11 w-full rounded-2xl border border-white/15 bg-white/5 px-4 text-sm outline-none focus:border-[color:var(--treesh-purple)]"></div>
       <div><label class="mb-1.5 block text-xs uppercase tracking-wide text-white/50">Birthday</label>${dateFieldHTML({id:'set-bday',value:bday,placeholder:'Set birthday',disabled:bdayLocked(),boxClass:'h-11 rounded-2xl border border-white/15 bg-white/5 text-sm'})}<div class="mt-2 ${z?'':'hidden'}" id="set-zodiac-wrap"><span id="set-zodiac" class="inline-flex items-center gap-1 rounded-full border border-[color:var(--treesh-gold)]/40 bg-[color:var(--treesh-gold)]/10 px-3 py-1 text-xs text-[color:var(--treesh-gold)]">${esc(z)}</span></div>${bdayLocked()?`<p class="mt-1.5 flex items-center gap-1.5 text-[11px] text-white/40"><i data-lucide="lock" style="width:12px;height:12px"></i>Birthday is locked and can no longer be changed.</p>`:`<p class="mt-1.5 text-[11px] text-white/40">Heads up: you can change your birthday one more time, then it locks.</p>`}</div>
       <div class="sm:col-span-2"><label class="mb-1.5 block text-xs uppercase tracking-wide text-white/50">Bio</label><textarea id="set-bio" data-testid="settings-bio-input" maxlength="160" rows="3" placeholder="Tell people your vibe" class="w-full resize-none rounded-2xl border border-white/15 bg-white/5 px-4 py-3 text-sm outline-none focus:border-[color:var(--treesh-purple)]">${esc(bio)}</textarea><p class="mt-1 text-right text-[11px] text-white/40"><span id="set-bio-count">${bio.length}</span>/160</p></div>
      </div>
      <div class="mt-4 flex items-center gap-2"><button data-act="save-profile" data-testid="settings-save-profile-button" class="press inline-flex items-center gap-2 rounded-full bg-[color:var(--treesh-purple)] px-5 py-2.5 text-sm font-semibold text-white glow-purple"><i data-lucide="check" style="width:16px;height:16px"></i>Save</button><button data-act="settings-edit-profile" data-val="off" data-testid="settings-cancel-profile-button" class="press inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-5 py-2.5 text-sm font-semibold text-white/80 hover:bg-white/10">Cancel</button></div>
     </div></section>`; }
  const handle=(shown.toLowerCase().replace(/[^a-z0-9]+/g,'')||'treeshfan');
  let joined=''; try{ joined=new Date(pfJoined(p)).toLocaleDateString(undefined,{month:'long',year:'numeric'}); }catch(e){}
  const stat=(label,val,ic,tid)=>`<div class="pf-stat" data-testid="profile-stat-${tid}"><span class="pf-stat-ic"><i data-lucide="${ic}" style="width:14px;height:14px"></i></span><p class="font-doto text-2xl font-bold leading-none">${val}</p><p class="mt-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-white/45">${label}</p></div>`;
  const earned=PF_BADGES.filter(b=>b.ok(S)).length; const ta=S.topArtist;
  const topCard=(kicker,tid,act,media,title,sub)=>`<button ${act} data-testid="${tid}" class="press flex min-w-0 items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.03] p-2.5 text-left hover:bg-white/[0.06]">${media}<span class="min-w-0 flex-1"><span class="block text-[10px] font-semibold uppercase tracking-[0.18em] text-[color:var(--treesh-gold)]">${kicker}</span><span class="clamp-1 block text-sm font-semibold">${title}</span><span class="clamp-1 block text-xs text-white/50">${sub}</span></span><i data-lucide="chevron-right" class="shrink-0 text-white/35" style="width:16px;height:16px"></i></button>`;
  return `<section class="pf-hero relative overflow-hidden rounded-[32px] border border-white/12 bg-white/[0.04]" data-testid="settings-profile">
   <div class="dark-surface relative h-36 overflow-hidden sm:h-52" style="${bannerStyle}" data-testid="profile-banner">${blurCover}<div class="absolute inset-0" style="background:linear-gradient(180deg,rgba(0,0,0,0) 35%,rgba(0,0,0,.5))"></div><div class="absolute right-3 top-3 flex items-center gap-2"><button data-act="set-theme" data-val="${state.theme==='light'?'dark':'light'}" data-testid="hero-theme-toggle" aria-label="Toggle light or dark mode" class="pf-bubble press grid h-10 w-10 place-items-center rounded-full"><i data-lucide="${state.theme==='light'?'moon':'sun'}" style="width:17px;height:17px"></i></button><button data-act="settings-edit-profile" data-val="on" data-testid="hero-edit-profile" class="pf-bubble press inline-flex h-10 items-center gap-2 rounded-full px-4 text-sm font-semibold"><i data-lucide="pencil" style="width:15px;height:15px"></i>Edit profile</button></div></div>
   <div class="relative px-5 pb-6 sm:px-8">
    <div class="-mt-12 flex items-end justify-between gap-3 sm:-mt-16">${avatar('h-24 w-24 sm:h-32 sm:w-32')}<div class="mb-1 flex flex-wrap justify-end gap-1.5">${z?`<span class="inline-flex items-center gap-1 rounded-full border border-[color:var(--treesh-gold)]/40 bg-[color:var(--treesh-gold)]/10 px-2.5 py-1 text-xs font-semibold text-[color:var(--treesh-gold)]" data-testid="settings-profile-zodiac"><i data-lucide="sparkle" style="width:12px;height:12px"></i>${esc(z)}</span>`:''}${S.streak>1?`<span class="inline-flex items-center gap-1 rounded-full border border-white/12 bg-white/5 px-2.5 py-1 text-xs font-semibold text-white/70"><i data-lucide="flame" style="width:12px;height:12px"></i>${S.streak}-day streak</span>`:''}</div></div>
    <div class="mt-3 min-w-0"><p class="font-display text-[10px] uppercase tracking-[0.3em] text-[color:var(--treesh-gold)]">Your profile</p><h1 class="mt-1 truncate text-3xl font-bold sm:text-4xl" data-testid="settings-profile-name">${esc(shown)}</h1><p class="mt-0.5 text-sm text-white/50" data-testid="settings-profile-handle">@${esc(handle)}${joined?' \u00b7 Joined '+esc(joined):''}</p>
     ${p.bio?`<p class="selectable mt-3 max-w-xl whitespace-pre-line text-[15px] leading-relaxed text-white/80" data-testid="settings-profile-bio">${esc(p.bio)}</p>`:`<button data-act="settings-edit-profile" data-val="on" data-testid="settings-profile-add-bio" class="press mt-3 inline-flex items-center gap-1.5 rounded-full border border-dashed border-white/20 px-3 py-1.5 text-xs font-semibold text-white/55 hover:text-white"><i data-lucide="plus" style="width:13px;height:13px"></i>Add a bio</button>`}</div>
    <div class="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-5" data-testid="profile-stats-row">${stat('Plays',fmtNum(S.plays),'play','plays')}${stat('Minutes',fmtNum(S.minutes),'clock','minutes')}${stat('Liked',fmtNum(S.likes),'heart','liked')}${stat('Playlists',S.playlists,'list-music','playlists')}${stat('Starlites',fmtNum(S.points),'sparkles','starlites')}</div>
    ${(ta||S.top)?`<div class="mt-3 grid gap-2 sm:grid-cols-2">${ta?topCard('Top artist','profile-top-artist',ta.id?`data-act="artist-open" data-id="${ta.id}"`:'',`<span class="h-12 w-12 shrink-0 overflow-hidden rounded-full border border-white/15 bg-white/5">${ta.image?img(ta.image,'h-full w-full object-cover'):''}</span>`,esc(ta.name||''),S.topArtistN+' play'+(S.topArtistN!==1?'s':'')):''}${S.top?topCard('Top song','profile-top-song',`data-act="play" data-id="${S.top.id}"`,`<span class="h-12 w-12 shrink-0 overflow-hidden rounded-xl">${img(S.top.coverArt,'h-full w-full object-cover')}</span>`,esc(S.top.title),esc(S.top.artist)+' \u00b7 '+S.topCount+' play'+(S.topCount!==1?'s':'')):''}</div>`:''}
    <div class="mt-6"><div class="mb-2.5 flex items-center justify-between"><p class="text-xs font-bold uppercase tracking-[0.2em] text-white/50">Badges</p><span class="rounded-full bg-white/10 px-2.5 py-0.5 text-xs font-semibold text-white/60" data-testid="profile-badge-count">${earned}/${PF_BADGES.length}</span></div><div class="grid grid-cols-3 gap-2 sm:grid-cols-4 lg:grid-cols-6" data-testid="profile-badges">${PF_BADGES.map(b=>{ const ok=b.ok(S); return `<div class="pf-badge${ok?' is-on':''}" data-testid="profile-badge-${b.id}" data-earned="${ok}" title="${esc(b.desc)}"><span class="pf-badge-ic"><i data-lucide="${b.ic}" style="width:18px;height:18px"></i></span><span class="pf-badge-name">${b.label}</span><span class="pf-badge-desc">${ok?'Earned':b.desc}</span></div>`; }).join('')}</div></div>
   </div></section>`; }

/* ---------- boot hook (called from init) ---------- */
function mkInit(){ applyGlass(); mkS();
  if(!window._mkIdx && typeof SETTINGS_INDEX!=='undefined'){ window._mkIdx=true; SETTINGS_INDEX.push(
    {id:'magic-markup',label:'Magic Markup',desc:'Rearrange, resize and restyle your pages',kw:'magic markup customize layout edit rearrange drag resize sections stickers canvas widgets design personalize',ic:'wand-sparkles',type:'action',go:()=>{ closeSearch(); setTimeout(mkStart,220); }},
    {id:'mk-fab',label:'Magic Markup button',desc:'Show the floating wand button',kw:'magic markup wand button floating',ic:'wand-sparkles',type:'toggle',get:()=>mkS().fab!==false,toggle:()=>{ const m=mkS(); m.fab=(m.fab===false); mkSave(); mkRenderChrome(); }},
    _sGo('go-homepage','Homepage','Choose the page Treesh opens on','homepage home start default page open launch','house','layout','Homepage'),
    _sGo('go-pages','Show or hide pages','Pick which pages appear in the navigation','pages hide show navigation nav tabs menu','panels-top-left','layout','Pages'),
    _sGo('go-glass','Glass intensity','How frosted the floating bubbles look','glass blur frosted bubble translucent transparency intensity','droplets','display','Glass'),
    _sGo('go-motion','Motion & effects','Animations, glow and effects','motion effects animation glow vinyl','sparkles','motion','Motion & effects')
  ); }
  try{ audio.addEventListener('timeupdate',()=>{ const el=document.querySelector('#view [data-mk-np-prog]'); if(el&&state.duration) el.style.width=(audio.currentTime/state.duration*100)+'%'; }); ['play','pause','loadedmetadata','emptied'].forEach(ev=>audio.addEventListener(ev,()=>setTimeout(mkRefreshNP,0))); }catch(e){}
  assetGet('profile_banner').then(v=>{ if(v){ state.profileBanner=v; if(state.view==='settings') renderView(); } }).catch(()=>{});
  const keys=[]; Object.values(mkS().pages).forEach(P=>{ ((P&&P.stickers)||[]).forEach(s=>{ if((s.src||'').indexOf('idb:')===0) keys.push(s.src.slice(4)); }); });
  if(keys.length) Promise.all(keys.map(k=>assetGet(k).then(v=>{ if(v) _mkImgs[k]=v; }).catch(()=>{}))).then(()=>{ if(mkCurPage()) renderView(); });
  mkRenderChrome(); }
</script>
