/* ---------- P7: shared sub-tab bar ---------- */
function p7Tabs(act,cur,tabs,wrapTid,btnTid){ return `<div class="settings-tabs-bar -mx-1" data-testid="${wrapTid}"><div class="no-scrollbar flex gap-2 overflow-x-auto px-1 py-2">${tabs.map(([id,label,ic,badge])=>{ const on=cur===id; return `<button data-act="${act}" data-val="${id}" data-testid="${btnTid}-${id}" aria-pressed="${on}" class="press inline-flex shrink-0 items-center gap-2 rounded-full border px-4 py-2.5 text-sm font-semibold transition-colors ${on?'border-transparent bg-[color:var(--treesh-purple)] text-white glow-purple backdrop-blur-lg':'border-white/15 bg-white/10 text-white/70 shadow-[0_4px_18px_rgba(0,0,0,0.28)] backdrop-blur-lg hover:bg-white/20 hover:text-white'}"><i data-lucide="${ic}" style="width:16px;height:16px"></i>${label}${badge?`<span class="p7-new">${badge}</span>`:''}</button>`; }).join('')}</div></div>`; }

/* ---------- P7: Models (content/models) ---------- */
let MODELS=[], MODEL_BY_ID={}, _mdLoaded=false;
CONTENT_SOURCES.models=["content/models","/content/models","https://treesh.app/content/models"];
function mdUrl(u){ u=String(u||'').trim(); if(!u) return ''; if(/^\/\//.test(u)) return 'https:'+u; if(u.charAt(0)==='/') return 'https://treesh.app'+u; return u; }
function mdList(v){ return String(v||'').split(',').map(x=>x.trim()).filter(Boolean); }
function mdYes(v){ return /^(yes|true|y|1)$/i.test(String(v||'').trim()); }
function mdNo(v){ return /^(no|none|false|n|0|none visible)$/i.test(String(v||'').trim()); }
function parseModels(doc){ const out=[], used=new Set();
  doc.querySelectorAll('div.model,article.model').forEach((el,i)=>{ const d=Object.assign({},el.dataset); if(mdYes(d.hidden)||/^(inactive|hidden)$/i.test(d.status||'')||d.active==='false') return;
    const imgEl=el.querySelector('img.model__image'); const lbl=el.querySelector('.model__label p:not(.capital)');
    const name=String(d.stageName||d.name||(lbl&&lbl.textContent)||'').trim(); if(!name) return;
    let id=String(d.modelId||'').trim()||slug(name)||('m'+i); while(used.has(id)) id+='-'+i; used.add(id);
    const m={}; Object.keys(d).forEach(k=>{ const v=String(d[k]||'').trim(); if(v) m[k]=v; });
    const im=imgEl&&imgEl.getAttribute('src');
    m.id=id; m.display=name; m.fullName=[d.firstName,d.lastName].filter(Boolean).join(' ').trim()||String(d.name||'').trim();
    m.pic=mdUrl(d.profilePic||d.mainImage||d.thumbnail||im); m.thumb=mdUrl(d.thumbnail||d.profilePic||d.mainImage||im); m.backdrop=mdUrl(d.backdropPic||'');
    const photos=[...el.querySelectorAll('.model__photos img')].map(x=>mdUrl(x.getAttribute('src'))).filter(Boolean);
    m.photos=[...new Set([...photos,m.pic,mdUrl(d.mainImage),m.backdrop].filter(Boolean))];
    out.push(m); });
  out.sort((a,b)=>(+a.sortOrder||999)-(+b.sortOrder||999)||(+b.priority||0)-(+a.priority||0)||a.display.localeCompare(b.display));
  return out; }
function mdIndex(list){ MODELS=Array.isArray(list)?list:[]; MODEL_BY_ID={}; MODELS.forEach(m=>{ MODEL_BY_ID[m.id]=m; }); }
function mdRefreshView(){ if(state.view==='artists'||state.view==='model') renderView(); }
async function loadModels(){
  try{ const c=await assetGet('models_cache'); if(c&&Array.isArray(c.list)&&!MODELS.length){ mdIndex(c.list); _mdLoaded=true; mdRefreshView(); } }catch(e){}
  try{ const html=await fetchFirst(CONTENT_SOURCES.models); const list=parseModels(parseDoc(html)); const changed=JSON.stringify(list)!==JSON.stringify(MODELS); mdIndex(list); _mdLoaded=true; assetPut('models_cache',{list,ts:Date.now()}).catch(()=>{}); if(changed) mdRefreshView(); }
  catch(e){ if(!_mdLoaded){ _mdLoaded=true; mdRefreshView(); } } }
function mdPhoto(src,name,cls){ const ini=esc(String(name||'M').trim().charAt(0).toUpperCase()); return `<span class="md-ph ${cls||''}" data-initial="${ini}">${src?`<img src="${esc(src)}" alt="${esc(name||'')}" loading="lazy" referrerpolicy="no-referrer" draggable="false" onerror="this.onerror=null;this.classList.add('md-img-err')">`:''}</span>`; }

/* ---------- Icons hub: Artists + Models sub-pages ---------- */
function viewArtists(){ const tab=state.iconsTab==='models'?'models':'artists'; const seen=LS.get('treesh_models_seen',false);
  const head=`<div class="flex flex-wrap items-end justify-between gap-4"><div><p class="font-display text-xs uppercase tracking-[0.3em] text-[color:var(--treesh-gold)]">The Collective</p><h1 class="mt-1 text-3xl font-bold sm:text-4xl">The Icons</h1><p class="mt-1 text-sm text-white/55">The artists and models behind Treesh.</p></div><div class="flex gap-2"><span class="ic-count" data-testid="icons-count-artists"><b>${ARTISTS.length}</b>Artists</span><span class="ic-count" data-testid="icons-count-models"><b>${MODELS.length||'Soon'}</b>Models</span></div></div>`;
  const bar=p7Tabs('icons-tab',tab,[['artists','Artists','mic-vocal'],['models','Models','aperture',seen?'':'New']],'icons-tabs','icons-tab');
  return mkFromMarkers('artists', `<div class="space-y-6"><!--mk:icons-head-->${head}<!--mk:icons-grid--><div>${bar}<div class="min-h-[60vh] tr-fade-in pt-3" data-testid="icons-panel-${tab}">${tab==='models'?iconsModelsHtml():iconsArtistsHtml()}</div></div></div>`, {}); }
function iconsArtistsHtml(){ const list=ARTISTS.slice().sort((a,b)=>a.name.toLowerCase().localeCompare(b.name.toLowerCase()));
  return `<div class="space-y-6">${mdFeatureBanner()}<div class="grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4 md:grid-cols-4 xl:grid-cols-5" data-testid="icons-artist-grid">${list.map((a,i)=>artistCard(a,i)).join('')}</div></div>`; }
function artistCard(a,i){ const n=artistSongs(a.id).length;
  return `<button data-act="artist-open" data-id="${a.id}" data-testid="icon-card-${a.id}" class="ic-card press" style="--d:${Math.min(i,14)*40}ms"><span class="ic-card-media">${img(a.image,'ic-card-img',`alt="${esc(a.name)}"`)}</span><span class="ic-card-shade"></span><span class="ic-card-go"><i data-lucide="arrow-up-right"></i></span><span class="ic-card-body"><span class="ic-card-role">${esc(a.role||'Music Artist')}</span><span class="ic-card-name">${esc(a.name)}</span><span class="ic-card-meta"><i data-lucide="disc-3"></i>${n} track${n!==1?'s':''}</span></span></button>`; }
function mdFeatureBanner(){ const list=MODELS.slice(0,3);
  if(!list.length) return `<button data-act="icons-tab" data-val="models" data-testid="icons-models-teaser" class="md-teaser press"><span class="md-teaser-orbs" aria-hidden="true"><span></span><span></span></span><span class="md-teaser-txt"><span class="md-pill"><i data-lucide="aperture"></i>Coming soon</span><span class="md-teaser-t">Treesh Models</span><span class="md-teaser-d">The faces of the Woodz are on their way. Comp cards, looks and shoots, all in one place.</span></span><span class="md-teaser-cta">Take a peek<i data-lucide="arrow-right"></i></span></button>`;
  return `<button data-act="icons-tab" data-val="models" data-testid="icons-models-feature" class="md-teaser has-faces press"><span class="md-teaser-orbs" aria-hidden="true"><span></span><span></span></span><span class="md-faces">${list.map((m,i)=>`<span class="md-face" style="--i:${i}">${mdPhoto(m.thumb||m.pic,m.display,'h-full w-full')}</span>`).join('')}</span><span class="md-teaser-txt"><span class="md-pill"><i data-lucide="sparkles"></i>New on Treesh</span><span class="md-teaser-t">Meet the Models</span><span class="md-teaser-d">${MODELS.length} model${MODELS.length!==1?'s':''} with comp cards, looks and booking info.</span></span><span class="md-teaser-cta">Explore models<i data-lucide="arrow-right"></i></span></button>`; }
function mdComingSoonHtml(){ return `<section class="md-soon dark-surface" data-testid="models-coming-soon"><div class="md-soon-orbs" aria-hidden="true"><span></span><span></span><span></span></div><div class="md-soon-frames" aria-hidden="true"><span class="f1"><i data-lucide="aperture"></i></span><span class="f2"><i data-lucide="camera"></i></span><span class="f3"><i data-lucide="sparkles"></i></span></div><div class="md-soon-copy"><span class="md-pill"><i data-lucide="aperture"></i>Coming soon</span><h2 class="md-soon-t">Treesh <em>Models</em></h2><p class="md-soon-d">The faces of the Woodz are getting camera ready. Comp cards, lookbooks and shoots will land right here.</p><div class="md-soon-chips"><span>Comp cards</span><span>Lookbooks</span><span>Booking info</span></div></div></section>`; }
function iconsModelsHtml(){ if(!_mdLoaded&&!MODELS.length) return `<div class="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4" data-testid="models-loading">${'<div class="md-skel"></div>'.repeat(4)}</div>`;
  if(!MODELS.length) return mdComingSoonHtml();
  const cats=[...new Set(MODELS.map(m=>m.genderCategory).filter(Boolean))]; const f=(state.mdFilter&&cats.includes(state.mdFilter))?state.mdFilter:'all';
  const list=f==='all'?MODELS:MODELS.filter(m=>m.genderCategory===f); const feat=MODELS.find(m=>mdYes(m.featured));
  return `<div class="space-y-6">${(feat&&f==='all')?mdHeroCard(feat):''}${cats.length>1?`<div class="no-scrollbar flex gap-2 overflow-x-auto pb-1" data-testid="models-filters">${['all',...cats].map(c=>`<button data-act="md-filter" data-val="${esc(c)}" data-testid="models-filter-${pmSlug(c)}" aria-pressed="${f===c}" class="md-chip press${f===c?' on':''}">${c==='all'?'All models':esc(c)}</button>`).join('')}</div>`:''}<div class="grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4 md:grid-cols-4 xl:grid-cols-5" data-testid="models-grid">${list.map((m,i)=>modelCard(m,i)).join('')}</div></div>`; }
function mdHeroCard(m){ return `<button data-act="model-open" data-id="${esc(m.id)}" data-testid="models-featured" class="md-feat dark-surface press">${mdPhoto(m.backdrop||m.pic,m.display,'md-feat-bg')}<span class="md-feat-shade"></span><span class="md-feat-inner">${mdPhoto(m.pic,m.display,'md-feat-pic')}<span class="min-w-0"><span class="md-pill"><i data-lucide="star"></i>Featured model</span><span class="md-feat-name">${esc(m.display)}</span><span class="md-feat-sub">${esc([m.modelCategory,m.basedIn||m.location].filter(Boolean).join(' \u00b7 '))}</span><span class="md-teaser-cta mt-3">View profile<i data-lucide="arrow-right"></i></span></span></span></button>`; }
function modelCard(m,i){ const tags=mdList(m.modelType||m.tags).slice(0,3);
  return `<button data-act="model-open" data-id="${esc(m.id)}" data-testid="model-card-${esc(m.id)}" class="md-card press" style="--d:${Math.min(i,14)*45}ms">${mdPhoto(m.thumb||m.pic,m.display,'md-card-media')}<span class="md-card-shade"></span>${mdYes(m.new)?'<span class="md-card-flag">New</span>':''}${mdYes(m.verified)?'<span class="md-card-ver" title="Verified"><i data-lucide="badge-check"></i></span>':''}<span class="md-card-body"><span class="md-card-name">${esc(m.display)}</span>${(m.basedIn||m.location)?`<span class="md-card-meta"><i data-lucide="map-pin"></i>${esc(m.basedIn||m.location)}</span>`:''}${m.agency?`<span class="md-card-meta"><i data-lucide="building-2"></i>${esc(m.agency)}</span>`:''}<span class="md-card-row">${m.height?`<span class="md-card-h"><i data-lucide="ruler"></i>${esc(m.height)}</span>`:''}${tags.map(t=>`<span class="md-tag">${esc(t)}</span>`).join('')}</span></span></button>`; }

/* ---------- Model profile ---------- */
const MD_SECTIONS=[
  ['Profile','user-round',[['Full name','fullName'],['Pronouns','pronouns'],['Age','age'],['Nationality','nationality'],['Ethnicity','ethnicity'],['Languages','languages'],['Based in','basedIn'],['Country','country']]],
  ['Look','scan-face',[['Hair','hairColor'],['Hair length','hairLength'],['Hair texture','hairTexture'],['Hair style','hairStyle'],['Eyes','eyeColor'],['Eye shape','eyeShape'],['Face shape','faceShape'],['Skin tone','skinTone'],['Undertone','skinUndertone'],['Complexion','complexion'],['Facial hair','facialHair'],['Brows','eyebrowShape'],['Lips','lipShape'],['Body type','bodyType'],['Build','build']]],
  ['Sizes','shirt',[['Dress','dressSize'],['Top','topSize'],['Shirt','shirtSize'],['Jacket','jacketSize'],['Suit','suitSize'],['Pants','pantsSize'],['Jeans','jeansSize'],['Skirt','skirtSize'],['Shoe (US)','shoeSizeUs'],['Shoe (EU)','shoeSizeEu']]],
  ['Work','briefcase',[['Category','modelCategory'],['Specialty','specialty'],['Fashion','fashionCategory'],['Size category','sizeCategory'],['Experience','experience'],['Years modeling','yearsModeling'],['Runway','runwayExperience'],['Commercial','commercialExperience'],['Agency status','agencyStatus'],['Representation','representation']]],
  ['Skills','sparkles',[['Dance','dance'],['Acting','acting'],['Singing','singing'],['Instruments','musicalInstruments'],['Sports','sports'],['Athletic','athleticSkills'],['Acrobatics','acrobatics'],['Martial arts','martialArts'],['Yoga','yoga'],['Swimming','swimming'],['Horseback riding','horsebackRiding']]],
  ['Features','fingerprint',[['Tattoos','tattoos'],['Piercings','piercings'],['Scars','scars'],['Birthmarks','birthmarks'],['Freckles','freckles'],['Dimples','dimples'],['Distinctive','distinctiveFeatures']]],
  ['Booking','calendar-check',[['Availability','availability'],['Status','bookingStatus'],['Travel','travel'],['Passport','passport'],['Work permit','workPermit'],['Driver license','driverLicense'],['Agency','agency'],['Manager','manager']]]
];
const MD_WORK=[['editorial','Editorial'],['highFashion','High fashion'],['runway','Runway'],['commercial','Commercial'],['lookbook','Lookbook'],['campaign','Campaign'],['beauty','Beauty'],['luxury','Luxury'],['ecommerce','E-commerce'],['printModel','Print'],['catalogModel','Catalog'],['lifestyleModel','Lifestyle'],['fitness','Fitness'],['swimwear','Swimwear'],['lingerie','Lingerie'],['partsModel','Parts'],['handModel','Hands'],['footModel','Feet'],['hairModel','Hair'],['makeupModel','Makeup']];
function mdVal(m,k){ const v=m[k]; if(v==null||v==='') return ''; if(mdYes(v)) return 'Yes'; if(mdNo(v)) return ''; return String(v).split(',').map(x=>x.trim()).filter(Boolean).join(', '); }
function mdInfoCard(title,ic,rows,m){ const items=rows.map(([l,k])=>[l,mdVal(m,k)]).filter(r=>r[1]); if(!items.length) return '';
  return `<section class="md-info" data-testid="model-section-${pmSlug(title)}"><h3 class="md-info-h"><span><i data-lucide="${ic}"></i></span>${title}</h3><dl class="md-dl">${items.map(([l,v])=>`<div><dt>${esc(l)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></section>`; }
function mdChipsBlock(title,ic,list,tid){ if(!list.length) return ''; return `<section class="md-chipset" data-testid="${tid}"><h3 class="md-info-h"><span><i data-lucide="${ic}"></i></span>${title}</h3><div class="md-chiprow">${list.map(x=>`<span>${esc(x)}</span>`).join('')}</div></section>`; }
function mdLink(u){ u=String(u||'').trim(); return u.charAt(0)==='/'?mdUrl(u):u; }
function viewModelDetail(){ const back=`<button data-act="md-back" data-testid="model-back" class="flex items-center gap-2 text-sm text-white/60 hover:text-white"><i data-lucide="arrow-left" style="width:16px;height:16px"></i> Models</button>`;
  const m=MODEL_BY_ID[state.param]; if(!m) return `<div class="space-y-4">${back}${_mdLoaded?'<p class="text-white/60" data-testid="model-not-found">Model not found.</p>':'<div class="md-skel h-72"></div>'}</div>`;
  const cm=state.mdUnits==='cm'; const U=(k,unit)=>{ const v=cm?m[k+'Cm']:m[k]; if(!v) return ''; return cm?(String(v)+(/^\d+(\.\d+)?$/.test(String(v))?' cm':'')):String(v); };
  const comp=[['Height',U('height')],[m.bust?'Bust':'Chest',m.bust?U('bust'):U('chest')],['Waist',U('waist')],['Hips',U('hips')],['Inseam',U('inseam')],[cm?'Shoe EU':'Shoe US',cm?(m.shoeSizeEu||''):(m.shoeSizeUs||m.shoeSize||'')],['Eyes',m.eyeColor||''],['Hair',m.hairColor||'']].filter(x=>x[1]);
  const work=MD_WORK.filter(([k])=>mdYes(m[k])).map(x=>x[1]);
  const style=[...mdList(m.styles),...mdList(m.looks),...mdList(m.vibes)]; const roles=mdList(m.roles); const tags=mdList(m.tags);
  const badges=[mdYes(m.verified)?'<span class="md-badge"><i data-lucide="badge-check"></i>Verified</span>':'',mdYes(m.featured)?'<span class="md-badge gold"><i data-lucide="star"></i>Featured</span>':'',mdYes(m.new)?'<span class="md-badge"><i data-lucide="sparkles"></i>New</span>':'',m.availability?`<span class="md-badge ok"><i data-lucide="circle-check"></i>${esc(m.availability)}</span>`:''].join('');
  const handle=h=>String(h||'').replace(/^@/,''); const links=[m.instagram?['instagram','Instagram','https://instagram.com/'+handle(m.instagram),m.instagram]:null,m.tiktok?['music-2','TikTok','https://www.tiktok.com/@'+handle(m.tiktok),m.tiktok]:null,m.website?['globe','Website',mdLink(m.website),'']:null,m.portfolioUrl?['images','Portfolio',mdLink(m.portfolioUrl),'']:null,m.bookingUrl?['calendar-plus','Book',mdLink(m.bookingUrl),'']:null,m.email?['mail','Email','mailto:'+m.email,m.email]:null,m.phone?['phone','Call','tel:'+m.phone.replace(/[^+\d]/g,''),m.phone]:null].filter(Boolean);
  const cur=m.currency||''; const money=v=>v?(cur==='USD'||!cur?'$':'')+fmtNum(+v||0)+(cur&&cur!=='USD'?' '+cur:''):''; const rates=[['Day',money(m.dayRate||m.rate)],['Half day',money(m.halfDayRate)],['Hourly',money(m.hourlyRate)]].filter(x=>x[1]);
  const photos=(m.photos||[]).slice(0,12);
  return `<div class="md-detail space-y-6" data-testid="model-detail">${back}
  <section class="md-hero dark-surface" data-testid="model-hero">${mdPhoto(m.backdrop||m.pic,m.display,'md-hero-bg')}<span class="md-hero-shade"></span>
   <div class="md-hero-inner">${mdPhoto(m.pic,m.display,'md-hero-pic')}<div class="min-w-0"><p class="md-kicker">${esc(m.modelCategory||'Model')}${m.agency?` \u00b7 ${esc(m.agency)}`:''}</p><h1 class="md-hero-name" data-testid="model-name">${esc(m.display)}</h1><p class="md-hero-sub">${esc([m.fullName&&m.fullName.toLowerCase()!==m.display.toLowerCase()?m.fullName:'',m.pronouns].filter(Boolean).join(' \u00b7 '))}</p>${(m.basedIn||m.location)?`<p class="md-hero-loc"><i data-lucide="map-pin"></i>${esc(m.basedIn||m.location)}</p>`:''}<div class="md-badges">${badges}</div></div></div></section>
  ${comp.length?`<section class="md-comp" data-testid="model-comp-card"><div class="md-comp-h"><h3 class="md-info-h"><span><i data-lucide="ruler"></i></span>Comp card</h3><div class="md-seg" role="group" aria-label="Units"><button data-act="md-units" data-val="in" data-testid="model-units-in" aria-pressed="${!cm}" class="${!cm?'on':''}">in</button><button data-act="md-units" data-val="cm" data-testid="model-units-cm" aria-pressed="${cm}" class="${cm?'on':''}">cm</button></div></div><div class="md-comp-grid">${comp.map(([l,v])=>`<div class="md-stat"><b>${esc(v)}</b><span>${esc(l)}</span></div>`).join('')}</div></section>`:''}
  ${photos.length>1?`<section data-testid="model-photos"><h3 class="md-info-h mb-3"><span><i data-lucide="images"></i></span>Photos</h3><div class="md-strip no-scrollbar">${photos.map((p,i)=>`<button data-act="md-photo" data-id="${esc(m.id)}" data-i="${i}" data-testid="model-photo-${i}" class="md-shot press">${mdPhoto(p,m.display,'h-full w-full')}</button>`).join('')}</div></section>`:''}
  <div class="grid gap-4 md:grid-cols-2">${mdChipsBlock('Books for','briefcase',work,'model-work-types')}${mdChipsBlock('Style & vibe','palette',style,'model-style')}${mdChipsBlock('Roles','theater',roles,'model-roles')}${mdChipsBlock('Tags','tag',tags,'model-tags')}</div>
  <div class="grid gap-4 md:grid-cols-2">${MD_SECTIONS.map(([t,ic,rows])=>mdInfoCard(t,ic,rows,m)).join('')}${rates.length?`<section class="md-info" data-testid="model-section-rates"><h3 class="md-info-h"><span><i data-lucide="wallet"></i></span>Rates</h3><dl class="md-dl">${rates.map(([l,v])=>`<div><dt>${l}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></section>`:''}</div>
  ${links.length?`<section class="md-info" data-testid="model-links"><h3 class="md-info-h"><span><i data-lucide="link"></i></span>Connect &amp; book</h3><div class="md-links">${links.map(([ic,l,href,sub])=>`<a href="${esc(href)}" target="_blank" rel="noopener" class="md-linkbtn press" data-testid="model-link-${pmSlug(l)}"><i data-lucide="${ic}"></i><span class="min-w-0"><b>${l}</b>${sub?`<small>${esc(sub)}</small>`:''}</span></a>`).join('')}</div></section>`:''}
  </div>`; }
function mdOpenPhoto(id,i){ const m=MODEL_BY_ID[id]; if(!m) return; const p=(m.photos||[])[i]; if(!p) return;
  $("#modal").innerHTML=modalWrap(`${pmHead('image',esc(m.display),'Photo '+(i+1)+' of '+m.photos.length,'model-photo-close')}<div class="md-big">${mdPhoto(p,m.display,'h-full w-full')}</div>`,'model-photo-modal','lg'); icons(); syncScrollLock(); }

/* ---------- Icon (artist) profile ---------- */
function viewArtistDetail(){
  const a=ARTIST_BY_ID[state.param]; if(!a) return `<p class="text-white/60">Artist not found.</p>`;
  const songs=artistSongs(a.id); state.contextList=songs; const pc=state.playCounts||{};
  const plays=songs.reduce((t,s)=>t+(pc[s.id]||0),0), liked=songs.filter(s=>isFav(s.id)).length;
  const popular=songs.slice().sort((x,y)=>(pc[y.id]||0)-(pc[x.id]||0)).slice(0,5);
  const gc={}; songs.forEach(s=>{ if(s.genre) gc[s.genre]=(gc[s.genre]||0)+1; }); const topG=Object.keys(gc).sort((x,y)=>gc[y]-gc[x])[0]||'';
  const mine=new Set(songs.map(s=>s.id)); const collab=ARTISTS.filter(b=>b.id!==a.id).map(b=>({b,n:[...(ARTIST_SONG_IDS[b.id]||[])].filter(id=>mine.has(id)).length})).filter(x=>x.n>0).sort((x,y)=>y.n-x.n).slice(0,10);
  const longBio=(a.bio||'').length>260;
  return `<div class="ar-detail space-y-8" data-testid="artist-detail"><button data-act="back" data-testid="artist-back" class="flex items-center gap-2 text-sm text-white/60 hover:text-white"><i data-lucide="arrow-left" style="width:16px;height:16px"></i> Back</button>
  <section class="ar-hero dark-surface" data-testid="artist-hero"><div class="ar-hero-bg">${img(a.background||a.image,'h-full w-full object-cover',`style="object-position:${esc(a.bgPos||'center')}"`)}</div><span class="ar-hero-shade"></span>
   <div class="ar-hero-inner"><div class="ar-avatar"><span class="ar-ring" aria-hidden="true"></span><span class="ar-avatar-img">${img(a.image,'h-full w-full object-cover',`alt="${esc(a.name)}"`)}</span></div>
    <div class="min-w-0 flex-1"><p class="ar-kicker"><i data-lucide="badge-check"></i>${esc(a.role||'Music Artist')}</p><h1 class="ar-name" data-testid="artist-name">${esc(a.name)}</h1>${(a.location||topG)?`<p class="ar-loc">${a.location?`<span><i data-lucide="map-pin"></i>${esc(a.location)}</span>`:''}${topG?`<span><i data-lucide="disc-3"></i>${esc(topG)}</span>`:''}</p>`:''}
     <div class="ar-stats" data-testid="artist-stats"><span><b>${songs.length}</b>Track${songs.length!==1?'s':''}</span><span><b>${fmtNum(plays)}</b>Your plays</span><span><b>${liked}</b>Liked</span></div>
     <div class="ar-actions">${songs.length?`<button data-act="artist-playall" data-id="${a.id}" data-testid="artist-play" class="ar-btn primary press"><i data-lucide="play" class="fill-current"></i>Play</button><button data-act="artist-shuffle" data-id="${a.id}" data-testid="artist-shuffle" class="ar-btn press"><i data-lucide="shuffle"></i>Shuffle</button>`:''}${a.cashapp?`<a href="https://cash.app/$${esc(a.cashapp)}" target="_blank" rel="noopener" data-testid="artist-cashapp" class="ar-btn gold press"><i data-lucide="dollar-sign"></i>$${esc(a.cashapp)}</a>`:''}<button data-act="ar-share" data-id="${a.id}" data-testid="artist-share" aria-label="Share profile" class="ar-btn icon press"><i data-lucide="share-2"></i></button></div></div></div></section>
  ${a.bio?`<section class="ar-about" data-testid="artist-about"><h2 class="ar-h">About</h2><p class="ar-bio${longBio?' is-clamped':''}" id="ar-bio" data-testid="artist-bio">${esc(a.bio)}</p>${longBio?`<button data-act="ar-bio-more" data-testid="artist-bio-more" class="ar-more">Read more</button>`:''}</section>`:''}
  ${popular.length?`<section data-testid="artist-popular"><h2 class="ar-h">Popular</h2><div class="ar-pop">${popular.map((s,i)=>`<div class="ar-pop-row"><span class="ar-rank">${i+1}</span><div class="min-w-0 flex-1">${songRow(s,i,false)}</div></div>`).join('')}</div></section>`:''}
  ${songs.length>5?`<section data-testid="artist-all-tracks"><h2 class="ar-h">All tracks <span>${songs.length}</span></h2>${grid(songs)}</section>`:''}
  ${collab.length?`<section data-testid="artist-collabs"><h2 class="ar-h">Appears with</h2><div class="no-scrollbar -mx-1 flex gap-4 overflow-x-auto px-1 pb-1">${collab.map(({b,n})=>`<button data-act="artist-open" data-id="${b.id}" data-testid="artist-collab-${b.id}" class="ar-collab press"><span class="ar-collab-img">${img(b.image,'h-full w-full object-cover')}</span><span class="clamp-1 text-sm font-semibold">${esc(b.name)}</span><span class="text-[11px] text-white/45">${n} song${n!==1?'s':''} together</span></button>`).join('')}</div></section>`:''}
  </div>`; }

/* ---------- Profile panel (from the header avatar) ---------- */
function renderProfile(){
  const c=$("#profile"); const wasOpen=!!c.querySelector("#profile-panel"); const sc=c.querySelector('#profile-scroll'); const y=sc?sc.scrollTop:0;
  c.innerHTML=`<div data-act="profile-close" data-testid="profile-module-backdrop" class="fixed inset-0 z-[85] bg-black/55 backdrop-blur-sm ${wasOpen?'':'backdrop-in'}"></div>
  <div id="profile-panel" data-testid="profile-module-panel" role="dialog" aria-modal="true" aria-label="Your profile" class="pf-panel fixed z-[86] flex flex-col overflow-hidden glass-strong border border-white/12 shadow-[var(--treesh-shadow)] ${wasOpen?'':'profile-in'}">${profileInnerHtml()}</div>`;
  icons(); const ns=c.querySelector('#profile-scroll'); if(ns&&wasOpen) ns.scrollTop=y; pfWireEdit(); }
function profileInnerHtml(){ const editing=!!state.settingsEditProfile;
  return `<span class="pf-grab" aria-hidden="true"></span><button data-act="profile-close" aria-label="Close" data-testid="profile-module-close-button" class="pf-close press"><i data-lucide="x" style="width:18px;height:18px"></i></button>
  <div id="profile-scroll" class="min-h-0 flex-1 overflow-y-auto overflow-x-hidden soft-scroll overscroll-contain">
   <div class="pf-panel-hero">${settingsProfileHtml(editing)}</div>
   ${editing?'':`<div class="px-4 sm:px-5">${profileStarBannerHtml()}</div>
   <div class="pf-tabs-sticky"><div id="profile-tabs" class="flex gap-1 overflow-x-auto no-scrollbar rounded-full border border-white/10 bg-black/30 p-1" data-testid="profile-module-tabs">${profileTabsInner()}</div></div>
   <div id="profile-body" class="px-4 pb-8 pt-3 sm:px-5 pf-content-in">${profileBodyHtml()}</div>`}
  </div>`; }
function pfRerender(){ if(state.profileOpen) renderProfile(); else if(state.view==='settings') renderView(); }
function pfWireEdit(){ const bday=document.getElementById('set-bday'); if(bday&&!bday._pfw){ bday._pfw=1; const upd=()=>{ syncDateField(bday); const z=zodiac(bday.value); const el=document.getElementById('set-zodiac'); if(el) el.textContent=z; const zw=document.getElementById('set-zodiac-wrap'); if(zw) zw.classList.toggle('hidden',!z); }; bday.addEventListener('input',upd); bday.addEventListener('change',upd); }
  const ai=document.getElementById('set-avatar-input'); if(ai&&!ai._pfw){ ai._pfw=1; ai.addEventListener('change',e=>{ const f=e.target.files&&e.target.files[0]; e.target.value=''; if(f) pfPickAvatar(f,d=>{ state._tmpAvatar=d; const av=document.getElementById('set-avatar'); if(av) av.innerHTML=img(d,'h-full w-full object-cover'); toast('Photo ready','Tap Save to keep it'); }); }); } }
function pfPickAvatar(f,done){ if(!/^image\//.test(f.type||'')){ toast('Pick an image file'); return; } if(f.size>20*1024*1024){ toast('Image too large','Use one under 20 MB'); return; } openCoverStudio(URL.createObjectURL(f),'Crop your profile photo',true,{aspect:1,round:true,out:[512,512],q:0.86,title:'Profile photo',onApply:done}); }
function settingsHeadHtml(){ const p=state.profile||{}; return `<div class="flex flex-wrap items-end justify-between gap-4" data-testid="settings-head"><div><p class="font-display text-xs uppercase tracking-[0.3em] text-[color:var(--treesh-gold)]">Treesh</p><h1 class="mt-1 text-3xl font-bold sm:text-4xl">Settings</h1><p class="mt-1 text-sm text-white/55">Tune how Treesh looks, sounds and behaves.</p></div><button data-act="open-profile" data-testid="settings-open-profile" class="press inline-flex items-center gap-2.5 rounded-full border border-white/12 bg-white/5 py-1.5 pl-1.5 pr-4 text-sm font-semibold hover:bg-white/10"><span class="grid h-8 w-8 place-items-center overflow-hidden rounded-full border border-white/15 bg-white/5">${p.avatar?img(p.avatar,'h-full w-full object-cover'):`<span class="text-xs font-bold">${esc((p.nickname||'T').charAt(0).toUpperCase())}</span>`}</span>Your profile<i data-lucide="chevron-right" style="width:15px;height:15px" class="text-white/45"></i></button></div>`; }

/* ---------- Things ---------- */
const THING_EXTRA={ hoop:{img:'https://images.unsplash.com/photo-1558453975-d6c57ab62b20?crop=entropy&cs=srgb&fm=jpg&q=80&w=1400', chips:['Live court map','21, HORSE & Around the World','Workouts & drills']} };
function gameThingsHtml(){ const first=THINGS[0], rest=THINGS.slice(1);
  return `<div class="space-y-6" data-testid="things-section">
   <div class="th-head"><div class="min-w-0"><p class="font-display text-[11px] uppercase tracking-[0.28em] text-[color:var(--treesh-gold)]">Beyond the arcade</p><h2 class="mt-1 text-2xl font-extrabold sm:text-3xl">Things</h2><p class="mt-1 max-w-lg text-sm text-white/55">Treesh apps and tools for life off the screen. Open one, minimize it, keep vibing.</p></div><span class="th-count" data-testid="things-count"><b>${THINGS.length}</b>${THINGS.length===1?'thing':'things'}</span></div>
   ${first?thingSpotlight(first):''}
   ${rest.length?`<div class="grid gap-3 sm:grid-cols-2">${rest.map(thingCard).join('')}</div>`:''}
   <div class="th-soon" data-testid="things-coming-soon"><span class="th-soon-ic"><i data-lucide="sparkles"></i></span><div class="min-w-0"><p class="text-sm font-bold">More Things are on the way</p><p class="text-xs text-white/55">New Treesh tools land here first. Watch What\u2019s New for drops.</p></div></div>
  </div>`; }
function thingsSectionHtml(){ return gameThingsHtml(); }
function thingSpotlight(g){ const x=THING_EXTRA[g.key]||{}; const bg=g.banner||x.img||'';
  return `<article class="th-spot dark-surface" data-testid="thing-spotlight-${g.key}" style="--a:${g.a};--b:${g.b}">${bg?`<img class="th-spot-img" src="${esc(bg)}" alt="" loading="lazy" referrerpolicy="no-referrer" draggable="false">`:''}<span class="th-spot-shade"></span><span class="th-spot-glow"></span>
   <div class="th-spot-inner"><div class="th-spot-top"><span class="th-logo">${g.logo?`<img src="${esc(g.logo)}" alt="">`:`<span class="font-display">${g.mono}</span>`}</span><span class="th-label">${esc(g.label||'Treesh')}</span>${g.age?`<span class="th-age">${esc(g.age)}</span>`:''}</div>
   <h3 class="th-name">${esc(g.name)}</h3><p class="th-desc">${esc(g.desc||'')}</p>
   ${(x.chips||[]).length?`<div class="th-chips">${x.chips.map(c=>`<span>${esc(c)}</span>`).join('')}</div>`:''}
   <div class="th-actions"><button data-act="game-open" data-key="${g.key}" data-testid="game-open-${g.key}" class="th-cta press"><i data-lucide="arrow-up-right"></i>Open ${esc(g.name.split(' ')[0])}</button>${g.updated?`<span class="th-upd">Updated ${esc(g.updated)}</span>`:''}</div></div></article>`; }
function thingCard(g){ return `<button data-act="game-open" data-key="${g.key}" data-testid="game-open-${g.key}" class="th-card press" style="--a:${g.a};--b:${g.b}"><span class="th-logo">${g.logo?`<img src="${esc(g.logo)}" alt="">`:`<span class="font-display">${g.mono}</span>`}</span><span class="min-w-0 flex-1 text-left"><span class="th-label">${esc(g.label||'Treesh')}</span><span class="clamp-1 block text-base font-bold">${esc(g.name)}</span><span class="clamp-2 block text-xs text-white/55">${esc(g.desc||'')}</span></span><i data-lucide="arrow-up-right" class="shrink-0 text-white/40" style="width:18px;height:18px"></i></button>`; }

/* ---------- Navigation: auto "More" once there are more than 5 pages ---------- */
const NAV_DESC={library:'Music, picks & playlists',artists:'Artists & models',studios:'Instrum, LyricFlow & more',game:'Games & Things',settings:'Make Treesh yours',blog:'Stories & updates'};
function navIsActive(v){ return state.view===v||(v==='studios'&&state.view==='instrum')||(v==='artists'&&(state.view==='artist'||state.view==='model')); }
function navBar(){ const all=mkNav(NAV); if(all.length<=5) return {bar:all,more:false}; const ids=all.map(n=>n[0]); const m=mkS(); let pins=(Array.isArray(m.pins)?m.pins:[]).filter(id=>ids.includes(id)); if(!pins.length) pins=ids.slice(0,4); pins=pins.slice(0,4); return {bar:all.filter(n=>pins.includes(n[0])),more:true}; }
function navMobileHtml(){ const {bar,more}=navBar(); const off=more&&!bar.some(n=>navIsActive(n[0]));
  return bar.map(n=>navItem(n[0],n[1],n[2],true)).join('')+(more?`<button data-act="nav-more" data-testid="nav-mobile-more" aria-label="More pages" title="More" ${off?'aria-current="page"':''} class="gl-bnav-item ${off?'is-active ':''}flex flex-1 min-w-0 flex-col items-center gap-1 rounded-lg px-1 py-1.5 text-[10px] font-medium transition-colors ${off?'text-[color:var(--treesh-purple)]':'text-white/55'}"><span class="relative inline-flex"><i data-lucide="layout-grid" style="width:20px;height:20px"></i></span><span class="nav-label max-w-full truncate">More</span></button>`:''); }
function openNavMore(){ const all=mkNav(NAV); const pins=navBar().bar.map(n=>n[0]); const open=!!document.querySelector('#modal [data-testid="nav-more-sheet"]');
  const inner=`${pmHead('layout-grid','Navigate','All pages','nav-more-close')}<p class="pm-desc mb-3">Tap a page to open it. Pin up to 4 to the bottom bar.</p><div class="nm-grid" data-testid="nav-more-grid">${all.map(([id,label,ic])=>{ const on=pins.includes(id), cur=navIsActive(id); return `<div class="nm-tile${cur?' is-cur':''}"><button data-act="nav-more-go" data-view="${id}" data-testid="nav-more-${id}" class="nm-go press"><span class="nm-ic"><i data-lucide="${ic}"></i></span><span class="nm-l">${label}</span><span class="nm-d">${NAV_DESC[id]||''}</span></button><button data-act="nav-pin" data-val="${id}" data-testid="nav-pin-${id}" aria-pressed="${on}" aria-label="${on?'Unpin':'Pin'} ${label}" class="nm-pin${on?' on':''}"><i data-lucide="${on?'pin-off':'pin'}"></i></button></div>`; }).join('')}</div>`;
  $("#modal").innerHTML=modalWrap(inner,'nav-more-sheet','md'); if(open){ const w=document.querySelector('#modal [data-act="modal-backdrop"]'); if(w){ w.classList.remove('backdrop-in'); const p=w.querySelector('.pm-panel'); if(p) p.classList.remove('panel-in'); } } icons(); syncScrollLock(); }
function navTogglePin(id){ const m=mkS(); let pins=navBar().bar.map(n=>n[0]); if(pins.includes(id)){ if(pins.length<=1){ toast('Keep at least one page pinned'); return; } pins=pins.filter(x=>x!==id); } else { if(pins.length>=4){ toast('Bottom bar is full','Unpin a page first'); return; } pins.push(id); } m.pins=pins; mkSave(); renderShell(); renderView(); openNavMore(); }

/* ---------- P7 actions ---------- */
function p7Act(act,t){ const id=t.dataset.id, val=t.dataset.val;
  switch(act){
    case 'icons-tab': { const nv=val==='models'?'models':'artists'; const ch=(state.iconsTab||'artists')!==nv; state.iconsTab=nv; if(nv==='models') LS.set('treesh_models_seen',true); if(state.view!=='artists'){ navigate('artists'); } else { renderView(true); if(ch) requestAnimationFrame(scrollToStickyTabs); } return true; }
    case 'md-filter': state.mdFilter=val; renderView(); return true;
    case 'model-open': closeModal(); if(state.npOpen) closeNP(); navigate('model',id); return true;
    case 'md-back': state.iconsTab='models'; navigate('artists'); return true;
    case 'md-units': state.mdUnits=val==='cm'?'cm':'in'; LS.set('treesh_md_units',state.mdUnits); renderView(); return true;
    case 'md-photo': mdOpenPhoto(id,+t.dataset.i||0); return true;
    case 'ar-share': { const a=ARTIST_BY_ID[id]; const url=location.origin+location.pathname+'#/artist/'+encodeURIComponent(id); if(navigator.share){ navigator.share({title:a?a.name+' on Treesh':'Treesh',url}).catch(()=>{}); } else copyText(url).then(ok=>toast(ok?'Profile link copied':'Couldn\u2019t copy', a?a.name:'')); return true; }
    case 'ar-bio-more': { const b=document.getElementById('ar-bio'); if(b){ const c=b.classList.toggle('is-clamped'); t.textContent=c?'Read more':'Show less'; } return true; }
    case 'nav-more': openNavMore(); return true;
    case 'nav-more-go': closeModal(); navigate(t.dataset.view); return true;
    case 'nav-pin': navTogglePin(val); return true;
    case 'm-info': closeModal(); openMetadata(id); return true;
  }
  return false; }
document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act]'); if(!t) return; p7Act(t.dataset.act,t); });
