/* ---------- P7: live widgets (clock, date, weather via Open-Meteo) ---------- */
const MK_LIVE=['clock','date','weather'];
Object.assign(MK_WIDGETS,{ clock:{label:'Clock',ic:'clock',from:'Treesh',w:'third'}, date:{label:'Date',ic:'calendar-days',from:'Treesh',w:'third'}, weather:{label:'Weather',ic:'cloud-sun',from:'Open-Meteo',w:'third'} });
function mkClockStr(d,h24){ let h=d.getHours(); const m=String(d.getMinutes()).padStart(2,'0'), s=String(d.getSeconds()).padStart(2,'0'); let ap=''; if(!h24){ ap=h>=12?'PM':'AM'; h=h%12||12; } return `${h24?String(h).padStart(2,'0'):h}:${m}<small>${s}</small>${ap?`<em>${ap}</em>`:''}`; }
function mkGreet(d){ const h=d.getHours(); return h<5?'Up late':h<12?'Good morning':h<17?'Good afternoon':h<21?'Good evening':'Good night'; }
function mkZone(){ try{ const z=Intl.DateTimeFormat().resolvedOptions().timeZone||''; return z.split('/').pop().replace(/_/g,' '); }catch(e){ return ''; } }
function mkWClock(){ const d=new Date(); const h24=LS.get('treesh_clock24',false)===true;
  return `<section data-mk-widget="clock" data-testid="mk-widget-clock" class="mkw mkw-clock h-full"><span class="mkw-orb" aria-hidden="true"></span><div class="relative flex h-full flex-col justify-between gap-4"><div class="flex items-center justify-between gap-2"><span class="mkw-kicker"><i data-lucide="clock"></i><span data-clk-greet>${mkGreet(d)}</span></span><button data-act="w-clock-fmt" data-testid="mk-clock-format" class="mkw-chip press">${h24?'24h':'12h'}</button></div><div><p class="mkw-time" data-clk-time data-testid="mk-clock-time">${mkClockStr(d,h24)}</p><p class="mkw-sub">${esc(mkZone())} \u00b7 ${d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</p></div><div class="mkw-secbar"><span data-clk-sec style="width:${d.getSeconds()/59*100}%"></span></div></div></section>`; }
function mkWDate(){ const d=new Date(); const start=new Date(d); start.setDate(d.getDate()-d.getDay()); const days=[...Array(7)].map((_,i)=>{ const x=new Date(start); x.setDate(start.getDate()+i); return x; });
  const y0=new Date(d.getFullYear(),0,1), y1=new Date(d.getFullYear()+1,0,1); const pct=Math.round((d-y0)/(y1-y0)*100); const doy=Math.floor((d-y0)/864e5)+1;
  return `<section data-mk-widget="date" data-testid="mk-widget-date" class="mkw mkw-date h-full"><span class="mkw-orb gold" aria-hidden="true"></span><div class="relative flex h-full flex-col gap-3"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="mkw-kicker"><i data-lucide="calendar-days"></i>${d.toLocaleDateString(undefined,{weekday:'long'})}</p><p class="mkw-day" data-testid="mk-date-day">${d.getDate()}</p><p class="mkw-sub">${d.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</p></div><span class="mkw-doy"><b>${doy}</b>day</span></div><div class="mkw-week">${days.map(x=>`<span class="${x.toDateString()===d.toDateString()?'on':''}"><i>${x.toLocaleDateString(undefined,{weekday:'narrow'})}</i><b>${x.getDate()}</b></span>`).join('')}</div><div class="mt-auto"><div class="mkw-yr"><span style="width:${pct}%"></span></div><p class="mkw-tiny">${pct}% of ${d.getFullYear()} done</p></div></div></section>`; }
const WX={0:['Clear','sun','moon','clear'],1:['Mostly clear','sun','moon','clear'],2:['Partly cloudy','cloud-sun','cloud-moon','cloud'],3:['Overcast','cloud','cloud','cloud'],45:['Fog','cloud-fog','cloud-fog','fog'],48:['Icy fog','cloud-fog','cloud-fog','fog'],51:['Light drizzle','cloud-drizzle','cloud-drizzle','rain'],53:['Drizzle','cloud-drizzle','cloud-drizzle','rain'],55:['Heavy drizzle','cloud-drizzle','cloud-drizzle','rain'],56:['Freezing drizzle','cloud-drizzle','cloud-drizzle','snow'],57:['Freezing drizzle','cloud-drizzle','cloud-drizzle','snow'],61:['Light rain','cloud-rain','cloud-rain','rain'],63:['Rain','cloud-rain','cloud-rain','rain'],65:['Heavy rain','cloud-rain-wind','cloud-rain-wind','rain'],66:['Freezing rain','cloud-rain','cloud-rain','snow'],67:['Freezing rain','cloud-rain','cloud-rain','snow'],71:['Light snow','cloud-snow','cloud-snow','snow'],73:['Snow','cloud-snow','cloud-snow','snow'],75:['Heavy snow','snowflake','snowflake','snow'],77:['Snow grains','cloud-snow','cloud-snow','snow'],80:['Showers','cloud-rain','cloud-rain','rain'],81:['Showers','cloud-rain','cloud-rain','rain'],82:['Heavy showers','cloud-rain-wind','cloud-rain-wind','rain'],85:['Snow showers','cloud-snow','cloud-snow','snow'],86:['Snow showers','cloud-snow','cloud-snow','snow'],95:['Thunderstorm','cloud-lightning','cloud-lightning','storm'],96:['Storm & hail','cloud-lightning','cloud-lightning','storm'],99:['Storm & hail','cloud-lightning','cloud-lightning','storm']};
function wxInfo(c,day){ const x=WX[c]||['Weather','cloud','cloud','cloud']; return {label:x[0],ic:day?x[1]:x[2],k:x[3]==='clear'?(day?'clear-day':'clear-night'):x[3]}; }
function wxS(){ if(!state.wx){ const sv=LS.get('treesh_wx',null)||{}; state.wx={unit:sv.unit||((navigator.language||'').toLowerCase()==='en-us'?'f':'c'),loc:sv.loc||null,data:sv.data||null,ts:sv.ts||0}; } return state.wx; }
function wxSave(){ const w=wxS(); LS.set('treesh_wx',{unit:w.unit,loc:w.loc,data:w.data,ts:w.ts}); }
let _wxBusy=false;
async function wxFetch(force){ const w=wxS(); if(!w.loc||_wxBusy) return; if(!force&&(w.err||(w.data&&w.data.unit===w.unit&&Date.now()-(w.ts||0)<20*60e3))) return; _wxBusy=true;
  try{ const f=w.unit==='f'; const url=`https://api.open-meteo.com/v1/forecast?latitude=${w.loc.lat}&longitude=${w.loc.lon}&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,is_day,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min&timezone=auto&forecast_days=5${f?'&temperature_unit=fahrenheit&wind_speed_unit=mph':''}`;
    const r=await fetch(url); if(!r.ok) throw new Error('wx '+r.status); const j=await r.json();
    if(w.loc.auto&&j.timezone){ const nm=String(j.timezone).split('/').pop().replace(/_/g,' '); if(nm&&!/^(GMT|UTC)/.test(nm)) w.loc.name=nm; }
    w.data={cur:j.current||{},daily:j.daily||{},unit:w.unit}; w.ts=Date.now(); w.err=''; wxSave();
  }catch(e){ w.err='Couldn\u2019t load the weather'; }
  _wxBusy=false; mkRefreshW('weather'); }
function wxLocate(){ const w=wxS(); if(!navigator.geolocation){ w.mode='search'; w.denied=true; mkRefreshW('weather'); return; } w.locating=true; w.mode=''; mkRefreshW('weather');
  navigator.geolocation.getCurrentPosition(p=>{ w.locating=false; w.denied=false; w.loc={name:'Your location',lat:+p.coords.latitude.toFixed(3),lon:+p.coords.longitude.toFixed(3),auto:true}; w.data=null; w.err=''; wxSave(); mkRefreshW('weather'); wxFetch(true); },
    ()=>{ w.locating=false; w.denied=true; w.mode='search'; mkRefreshW('weather'); toast('Location is off','Search for your city instead'); setTimeout(()=>{ const q=document.getElementById('mk-wx-q'); if(q) q.focus(); },80); },{timeout:12000,maximumAge:30*60e3}); }
async function wxSearch(q){ const w=wxS(); q=String(q||'').trim(); if(q.length<2){ toast('Type a city name'); return; } w.q=q; w.searching=true; mkRefreshW('weather');
  try{ const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?count=6&language=en&format=json&name='+encodeURIComponent(q)); const j=await r.json(); w.results=(j.results||[]).map(x=>({name:x.name,sub:[x.admin1,x.country].filter(Boolean).join(', '),lat:x.latitude,lon:x.longitude})); }catch(e){ w.results=[]; toast('Couldn\u2019t search','Check your connection'); }
  w.searching=false; mkRefreshW('weather'); }
function wxPick(i){ const w=wxS(); const x=(w.results||[])[i]; if(!x) return; w.loc={name:x.name,sub:x.sub,lat:x.lat,lon:x.lon,auto:false}; w.results=null; w.mode=''; w.data=null; w.err=''; wxSave(); mkRefreshW('weather'); wxFetch(true); toast('Weather set',x.name); }
function mkWWeather(){ const w=wxS();
  const head=right=>`<div class="flex items-center justify-between gap-2"><span class="mkw-kicker min-w-0"><i data-lucide="map-pin"></i><span class="clamp-1" data-testid="wx-place">${esc(w.loc?w.loc.name:'Weather')}</span></span>${right||''}</div>`;
  const shell=(k,body)=>`<section data-mk-widget="weather" data-testid="mk-widget-weather" class="mkw mkw-wx wx-${k} h-full"><span class="wx-sky" aria-hidden="true"></span><div class="relative flex h-full flex-col gap-3">${body}</div></section>`;
  if(w.locating) return shell('none',`${head()}<div class="wx-mid"><span class="wx-spin"><i data-lucide="loader"></i></span><p class="text-sm font-semibold">Finding you\u2026</p><p class="mkw-sub">Allow location to see your local weather</p></div>`);
  if(w.mode==='search') return shell('none',`${head(w.loc?`<button data-act="wx-cancel" data-testid="wx-cancel" class="mkw-chip press">Cancel</button>`:'')}<div><p class="text-sm font-bold">${w.denied?'Location is off. Search a city':'Search a city'}</p><div class="mt-2 flex gap-2"><input id="mk-wx-q" data-testid="wx-search-input" class="wx-input" placeholder="e.g. Atlanta" value="${esc(w.q||'')}" autocomplete="off" enterkeyhint="search"><button data-act="wx-search" data-testid="wx-search-button" class="mkw-btn press" aria-label="Search"><i data-lucide="${w.searching?'loader':'search'}"></i></button></div>${w.results?`<div class="wx-res" data-testid="wx-results">${w.results.length?w.results.map((r,i)=>`<button data-act="wx-pick" data-i="${i}" data-testid="wx-result-${i}" class="press"><b>${esc(r.name)}</b><span>${esc(r.sub)}</span></button>`).join(''):'<p class="mkw-sub">No places found. Try another spelling.</p>'}</div>`:''}<button data-act="wx-locate" data-testid="wx-use-location" class="wx-link press"><i data-lucide="locate-fixed"></i>Use my location</button></div>`);
  if(!w.loc) return shell('none',`${head()}<div class="wx-mid"><span class="wx-hero-ic"><i data-lucide="cloud-sun"></i></span><p class="text-sm font-bold">See the weather where you are</p><div class="mt-2 flex flex-wrap justify-center gap-2"><button data-act="wx-locate" data-testid="wx-use-location" class="mkw-btn wide press"><i data-lucide="locate-fixed"></i>Use my location</button><button data-act="wx-search-mode" data-testid="wx-search-mode" class="mkw-btn ghost wide press"><i data-lucide="search"></i>Search a city</button></div></div>`);
  const D=w.data;
  if(!D||D.unit!==w.unit){ if(!w.err) setTimeout(()=>wxFetch(true),0); return shell('none',`${head()}<div class="wx-mid">${w.err?`<span class="wx-hero-ic"><i data-lucide="cloud-off"></i></span><p class="mkw-sub">${esc(w.err)}</p><button data-act="wx-refresh" data-testid="wx-retry" class="mkw-btn press mt-2"><i data-lucide="refresh-cw"></i>Try again</button>`:`<span class="wx-spin"><i data-lucide="loader"></i></span><p class="mkw-sub">Loading the forecast\u2026</p>`}</div>`); }
  const c=D.cur||{}, dd=D.daily||{}; const inf=wxInfo(c.weather_code,c.is_day!==0); const u=w.unit==='f'?'\u00b0F':'\u00b0C'; const r=v=>Math.round(+v||0);
  const days=(dd.time||[]).slice(0,5).map((t,i)=>{ const x=wxInfo((dd.weather_code||[])[i],true); const dt=new Date(t+'T12:00:00'); return `<div class="wx-day"><span>${i===0?'Today':dt.toLocaleDateString(undefined,{weekday:'short'})}</span><i data-lucide="${x.ic}"></i><b>${r((dd.temperature_2m_max||[])[i])}\u00b0</b><em>${r((dd.temperature_2m_min||[])[i])}\u00b0</em></div>`; }).join('');
  return shell(inf.k,`${head(`<div class="flex shrink-0 items-center gap-1"><button data-act="wx-unit" data-testid="wx-unit" class="mkw-chip press" aria-label="Switch units">${u}</button><button data-act="wx-search-mode" data-testid="wx-change-city" class="mkw-chip press" aria-label="Change city"><i data-lucide="search"></i></button></div>`)}
    <div class="flex items-center justify-between gap-3"><div class="min-w-0"><p class="wx-temp" data-testid="wx-temp">${r(c.temperature_2m)}<sup>${u}</sup></p><p class="wx-cond" data-testid="wx-condition">${inf.label}</p><p class="mkw-sub">H ${r((dd.temperature_2m_max||[])[0])}\u00b0 \u00b7 L ${r((dd.temperature_2m_min||[])[0])}\u00b0 \u00b7 Feels ${r(c.apparent_temperature)}\u00b0</p></div><span class="wx-big wx-k-${inf.k}"><i data-lucide="${inf.ic}"></i></span></div>
    <div class="wx-meta"><span><i data-lucide="droplets"></i>${r(c.relative_humidity_2m)}%</span><span><i data-lucide="wind"></i>${r(c.wind_speed_10m)} ${w.unit==='f'?'mph':'km/h'}</span><button data-act="wx-refresh" data-testid="wx-refresh" class="ml-auto press" aria-label="Refresh"><i data-lucide="refresh-cw"></i></button></div>
    ${days?`<div class="wx-days" data-testid="wx-forecast">${days}</div>`:''}`); }
function mkRefreshW(type){ const f={clock:mkWClock,date:mkWDate,weather:mkWWeather}[type]; if(!f) return; const els=document.querySelectorAll('#view [data-mk-widget="'+type+'"]'); if(!els.length) return; const h=f(); els.forEach(el=>{ el.outerHTML=h; }); icons(); }
let _wTickDay=new Date().getDate();
function mkWTick(){ const d=new Date(); const els=document.querySelectorAll('[data-clk-time]');
  if(els.length){ const t=mkClockStr(d,LS.get('treesh_clock24',false)===true); els.forEach(el=>{ if(el.innerHTML!==t) el.innerHTML=t; }); const sec=d.getSeconds();
    document.querySelectorAll('[data-clk-sec]').forEach(b=>{ if(sec===0){ b.style.transition='none'; b.style.width='0%'; void b.offsetWidth; b.style.transition=''; } else b.style.width=(sec/59*100)+'%'; });
    const g=mkGreet(d); document.querySelectorAll('[data-clk-greet]').forEach(x=>{ if(x.textContent!==g) x.textContent=g; }); }
  if(d.getDate()!==_wTickDay){ _wTickDay=d.getDate(); mkRefreshW('date'); }
  if(document.querySelector('#view [data-mk-widget="weather"]')) wxFetch(); }
function mkLiveAddHtml(have){ const d=new Date(); const prev={clock:`<b class="mk-live-big">${mkClockStr(d,false).replace(/<small>.*?<\/small>/,'').replace(/<em>.*?<\/em>/,'')}</b>`,date:`<b class="mk-live-big">${d.getDate()}</b>`,weather:`<i data-lucide="cloud-sun" class="mk-live-ic"></i>`};
  return `<div class="mk-live-grid">${MK_LIVE.map(k=>{ const w=MK_WIDGETS[k], on=have.has(k); return `<button data-act="mk-add-widget" data-val="${k}" data-testid="mk-add-widget-${k}" ${on?'disabled':''} class="mk-live mk-live-${k}${on?' is-on':''}"><span class="mk-live-prev">${prev[k]}</span><span class="mk-live-l">${on?'<i data-lucide="check"></i>':''}${w.label}</span></button>`; }).join('')}</div>`; }

/* ---------- P7: Treesh sticker pack + beat motions ---------- */
const MK_MOTIONS=[['off','Still'],['pulse','Pulse'],['bounce','Bounce'],['wiggle','Wiggle'],['spin','Spin']];
const _g=(a,b,v)=>`<defs><linearGradient id="g" x1="0" y1="0" x2="${v?0:1}" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs>`;
const MK_PACK=[
  {id:'note',name:'Music note',m:'bounce',svg:_g('#d8b4fe','#ff2d78')+'<path d="M38 18l42-8v52a12 12 0 1 1-8-11.3V27l-26 5v38a12 12 0 1 1-8-11.3z" fill="url(#g)" stroke="#fff" stroke-width="3.5" stroke-linejoin="round"/>'},
  {id:'heart',name:'Heart',m:'pulse',svg:_g('#ff8cc6','#e11d48',1)+'<path d="M50 86S12 63 12 37a19 19 0 0 1 38-6 19 19 0 0 1 38 6c0 26-38 49-38 49z" fill="url(#g)" stroke="#fff" stroke-width="4" stroke-linejoin="round"/><ellipse cx="32" cy="34" rx="7" ry="4" fill="#fff" opacity=".6" transform="rotate(-30 32 34)"/>'},
  {id:'star',name:'Star',m:'spin',svg:_g('#fff3c4','#f59e0b')+'<path d="M50 8l11.8 26.2 28.6 3-21.4 19.3 6 28.1L50 70.3 25 84.6l6-28.1L9.6 37.2l28.6-3z" fill="url(#g)" stroke="#fff" stroke-width="4" stroke-linejoin="round"/>'},
  {id:'bolt',name:'Lightning',m:'wiggle',svg:_g('#fef08a','#f97316')+'<path d="M58 6L20 56h24l-6 38 42-52H54z" fill="url(#g)" stroke="#fff" stroke-width="4" stroke-linejoin="round"/>'},
  {id:'flame',name:'Flame',m:'wiggle',svg:_g('#fdba74','#e11d48',1)+'<path d="M50 6c4 18 26 26 26 52a26 26 0 0 1-52 0c0-14 8-22 14-28 0 10 4 16 10 18-4-16 2-30 2-42z" fill="url(#g)" stroke="#fff" stroke-width="4" stroke-linejoin="round"/><path d="M50 60c6 6 10 11 10 18a10 10 0 0 1-20 0c0-7 4-12 10-18z" fill="#fff3c4"/>'},
  {id:'vinyl',name:'Vinyl',m:'spin',svg:'<circle cx="50" cy="50" r="44" fill="#111" stroke="#fff" stroke-width="3"/><circle cx="50" cy="50" r="35" fill="none" stroke="#333" stroke-width="2"/><circle cx="50" cy="50" r="27" fill="none" stroke="#2b2b2b" stroke-width="2"/><circle cx="50" cy="50" r="15" fill="#9328ff"/><circle cx="50" cy="50" r="3" fill="#fff"/><path d="M22 30a34 34 0 0 1 14-12" stroke="#fff" stroke-opacity=".4" stroke-width="4" fill="none" stroke-linecap="round"/>'},
  {id:'speaker',name:'Speaker',m:'pulse',svg:_g('#6d28d9','#1e1b4b',1)+'<rect x="22" y="8" width="56" height="84" rx="12" fill="url(#g)" stroke="#fff" stroke-width="4"/><circle cx="50" cy="30" r="9" fill="#0b0a10" stroke="#fff" stroke-width="3"/><circle cx="50" cy="64" r="18" fill="#0b0a10" stroke="#fff" stroke-width="3"/><circle cx="50" cy="64" r="7" fill="#22d3ee"/>'},
  {id:'headphones',name:'Headphones',m:'bounce',svg:_g('#22d3ee','#9328ff')+'<path d="M18 60V50a32 32 0 0 1 64 0v10" fill="none" stroke="url(#g)" stroke-width="10" stroke-linecap="round"/><rect x="10" y="54" width="20" height="32" rx="9" fill="url(#g)" stroke="#fff" stroke-width="3"/><rect x="70" y="54" width="20" height="32" rx="9" fill="url(#g)" stroke="#fff" stroke-width="3"/>'},
  {id:'crown',name:'Crown',m:'bounce',svg:_g('#fde68a','#d97706',1)+'<path d="M12 74L8 28l24 18L50 14l18 32 24-18-4 46z" fill="url(#g)" stroke="#fff" stroke-width="4" stroke-linejoin="round"/><rect x="12" y="74" width="76" height="12" rx="4" fill="#b45309" stroke="#fff" stroke-width="3"/><circle cx="50" cy="52" r="6" fill="#ff2d78"/>'},
  {id:'sparkle',name:'Sparkle',m:'spin',svg:_g('#a5f3fc','#9328ff')+'<path d="M50 4c4 26 10 34 40 46-30 12-36 20-40 46-4-26-10-34-40-46 30-12 36-20 40-46z" fill="url(#g)" stroke="#fff" stroke-width="3" stroke-linejoin="round"/><path d="M82 6c1 8 3 10 10 12-7 2-9 4-10 12-1-8-3-10-10-12 7-2 9-4 10-12z" fill="#fff"/>'},
  {id:'smile',name:'Smiley',m:'wiggle',svg:_g('#fde047','#f59e0b',1)+'<circle cx="50" cy="50" r="42" fill="url(#g)" stroke="#fff" stroke-width="4"/><ellipse cx="36" cy="40" rx="5" ry="8" fill="#1d1300"/><ellipse cx="64" cy="40" rx="5" ry="8" fill="#1d1300"/><path d="M30 58q20 22 40 0" fill="none" stroke="#1d1300" stroke-width="6" stroke-linecap="round"/>'},
  {id:'mic',name:'Mic',m:'wiggle',svg:_g('#f5f5f5','#a1a1aa',1)+'<rect x="34" y="8" width="32" height="50" rx="16" fill="url(#g)" stroke="#fff" stroke-width="4"/><path d="M40 22h20M40 32h20M40 42h20" stroke="#52525b" stroke-opacity=".5" stroke-width="3" stroke-linecap="round"/><path d="M24 46a26 26 0 0 0 52 0" fill="none" stroke="#ff2d78" stroke-width="5" stroke-linecap="round"/><path d="M50 72v16M36 90h28" stroke="#ff2d78" stroke-width="5" stroke-linecap="round"/>'},
  {id:'cassette',name:'Cassette',m:'bounce',svg:_g('#fb923c','#ec4899')+'<rect x="6" y="20" width="88" height="60" rx="8" fill="url(#g)" stroke="#fff" stroke-width="4"/><rect x="18" y="30" width="64" height="24" rx="6" fill="#fff" opacity=".92"/><circle cx="34" cy="42" r="7" fill="#0b0a10"/><circle cx="66" cy="42" r="7" fill="#0b0a10"/><path d="M26 80l6-14h36l6 14" fill="#0b0a10" opacity=".35"/>'},
  {id:'eq',name:'Equalizer',m:'pulse',svg:'<rect x="10" y="40" width="14" height="50" rx="5" fill="#22d3ee" stroke="#fff" stroke-width="3"/><rect x="31" y="20" width="14" height="70" rx="5" fill="#9328ff" stroke="#fff" stroke-width="3"/><rect x="52" y="50" width="14" height="40" rx="5" fill="#ff2d78" stroke="#fff" stroke-width="3"/><rect x="73" y="10" width="14" height="80" rx="5" fill="#f59e0b" stroke="#fff" stroke-width="3"/>'},
  {id:'disco',name:'Disco ball',m:'spin',svg:_g('#f4f4f5','#71717a')+'<path d="M50 4v12" stroke="#fff" stroke-width="3"/><circle cx="50" cy="56" r="38" fill="url(#g)" stroke="#fff" stroke-width="3"/><path d="M12 56h76M16 38h68M16 74h68M50 18v76M31 24q-12 32 0 64M69 24q12 32 0 64" stroke="#fff" stroke-opacity=".75" stroke-width="2" fill="none"/><circle cx="36" cy="40" r="6" fill="#fff" opacity=".85"/>'}
];
function mkPackSrc(id){ const p=MK_PACK.find(x=>x.id===id); if(!p) return ''; if(!p._u) p._u='data:image/svg+xml;charset=utf-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">'+p.svg+'</svg>'); return p._u; }
function mkMotion(s){ return s.motion||(s.react?'pulse':'off'); }
function mkPackHtml(){ return `<div class="mk-field"><p class="mk-lbl">Treesh sticker pack</p><div class="mk-pack-grid" data-testid="mk-pack-grid">${MK_PACK.map(p=>`<button data-act="mk-add-pack" data-val="${p.id}" data-testid="mk-pack-${p.id}" aria-label="Add ${esc(p.name)}" title="${esc(p.name)}" class="press"><img src="${mkPackSrc(p.id)}" alt=""></button>`).join('')}</div></div>`; }
function mkMotionNewHtml(){ const v=state.mkMotionNew||'auto'; return `<div class="mk-field"><p class="mk-lbl">Move to the beat</p>${mkSeg('mk-motion-new',v,[['auto','Auto']].concat(MK_MOTIONS),'mk-motion-new')}<p class="mk-hint">Stickers react to the real beat of whatever is playing. Auto picks a move for each pack sticker.</p></div>`; }
let _bt={avg:0,env:0,last:0,spin:0,t:0,zero:0,tried:false};
function mkReactLoop(){ if(_mkRAF||state.perfMode||!document.querySelector('.mk-react')) return;
  const tick=now=>{ const list=document.querySelectorAll('.mk-react'); if(!list.length||state.perfMode){ _mkRAF=null; return; }
    const dt=Math.min(0.05,Math.max(0,(now-(_bt.t||now))/1000)); _bt.t=now; let lvl=0, hit=false; const playing=!!state.isPlaying;
    if(playing){ if(!_vizAnalyser&&!_bt.tried){ _bt.tried=true; try{ if(ensureVizAudio()) vizResume(); }catch(_){} }
      let real=false; if(_vizAnalyser&&_vizBytes){ try{ _vizAnalyser.getByteFrequencyData(_vizBytes); let s=0; for(let i=1;i<7;i++) s+=_vizBytes[i]; lvl=s/6/255; real=true; }catch(_){} }
      _bt.zero=(real&&lvl===0)?_bt.zero+dt:0;
      if(!real||_bt.zero>2){ const ph=(now/500)%1; lvl=Math.pow(1-ph,3)*0.85; }
      _bt.avg=_bt.avg*0.94+lvl*0.06; if(lvl>_bt.avg*1.2+0.04&&lvl>0.2&&now-_bt.last>230){ hit=true; _bt.last=now; } }
    _bt.env=hit?1:_bt.env*Math.pow(0.015,dt); const e=Math.max(_bt.env,playing?lvl*0.5:0);
    _bt.spin=(_bt.spin+dt*(playing?(36+lvl*320+_bt.env*260):0))%360;
    const beat=(1+e*0.26).toFixed(3), bounce=(e*24).toFixed(1)+'px', wig=(playing?Math.sin(now/1000*13)*(2+e*16):0).toFixed(1)+'deg', spin=_bt.spin.toFixed(1)+'deg';
    list.forEach(el=>{ const st=el.style; st.setProperty('--beat',beat); st.setProperty('--bounce',bounce); st.setProperty('--wig',wig); st.setProperty('--spin',spin); });
    _mkRAF=requestAnimationFrame(tick); };
  _mkRAF=requestAnimationFrame(tick); }
