/* ---------- P7: Edit track, full-screen glass editor ---------- */
const TE_TABS=[['cover','Cover','image'],['details','Details','file-pen-line'],['lyrics','Lyrics','quote'],['timing','Timing','timer']];
function amEditorWrap(inner){ return `<div data-act="modal-backdrop" data-testid="edit-track-sheet" class="pm-bd te-bd fixed inset-0 z-[210] backdrop-in"><div data-act="modal-stop" role="dialog" aria-label="Edit track" class="te-sheet st-modal gl-modal pm-panel panel-in text-white"><span class="pm-grab" aria-hidden="true"></span>${inner}</div></div>`; }
function amEditorHtml(ed,o){ const tab=state._teTab||'cover'; state._teTab=null; state._teDirty=false; const V=o.V;
  const lines=(ed.lyrics||[]).filter(l=>l&&l.text&&l.text.trim()&&!l.secOnly); const stamped=lines.filter(l=>l.t!=null).length; const pct=lines.length?Math.round(stamped/lines.length*100):0; const dur=ed.duration||0;
  const lbl=t=>`<span class="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-white/45">${t}</span>`;
  const pane=(id,html)=>`<section class="te-pane${tab===id?'':' hidden'}" data-te-pane="${id}" data-testid="te-pane-${id}">${html}</section>`;
  const cover=`<div class="te-cover-wrap"><label for="am-cover" class="te-cover press" data-testid="te-cover-drop"><img id="am-cover-preview" alt="" class="absolute inset-0 h-full w-full object-cover" style="display:${o.hasCover?'block':'none'}"${o.hasCover?` src="${esc(ed.coverArt)}"`:''}><div id="am-cover-ph" class="absolute inset-0 flex flex-col items-center justify-center gap-2 text-white/45"${o.hasCover?' style="display:none"':''}><i data-lucide="image-plus" style="width:34px;height:34px"></i><span class="text-sm font-semibold">Add cover art</span></div><span class="te-cover-cta"><i data-lucide="upload"></i>Change cover</span></label><input id="am-cover" type="file" accept="image/*,.png,.jpg,.jpeg,.webp,.heic,.heif" class="sr-only" data-testid="te-cover-input">
    <div class="space-y-3"><div class="te-card"><p class="te-k">Cover art</p><p class="te-d">Square images look best. New covers open in Image Studio so you can crop, filter and add text.</p><div class="mt-3 flex flex-wrap gap-2"><label for="am-cover" class="te-btn primary press" data-testid="te-cover-upload"><i data-lucide="image-plus"></i>Upload new cover</label><button type="button" data-act="am-adjust-cover" id="am-adjust-cover" data-testid="am-adjust-cover" class="te-btn press ${o.hasCover?'':'hidden'}"><i data-lucide="wand-2"></i>Open in Image Studio</button></div></div>
    <div class="te-card te-facts"><div><span>Title</span><b class="clamp-1">${esc(ed.title||'Untitled')}</b></div><div><span>Artist</span><b class="clamp-1">${esc(ed.artist||'You')}</b></div><div><span>Length</span><b>${dur?fmt(dur):'--'}</b></div><div><span>Lyrics</span><b>${lines.length?(pct?pct+'% synced':lines.length+' lines'):'None'}</b></div></div></div></div>`;
  const details=`<div class="grid gap-3 sm:grid-cols-2">${amField('am-title','Title','Track title',V('title'),{req:true})}${amField('am-artist','Artist','Artist name',V('artist'))}<label class="block">${lbl('Genre')}<select id="am-genre" class="w-full rounded-xl border border-white/12 bg-white/5 px-3 py-2.5 text-sm text-white outline-none focus:border-[color:var(--treesh-purple)]"><option value="">Select</option>${o.genOpts}</select></label>${amField('am-album','Album','Album / EP',V('album'))}</div>
    <p class="te-k mt-6 mb-2">Credits</p><div class="grid gap-3 sm:grid-cols-2">${amField('am-featuring','Featuring','Guest artists',V('featuring'))}${amField('am-writtenBy','Written by','Songwriters',V('writtenBy'))}${amField('am-producer','Producer','Producer',V('producer'))}${amField('am-mixer','Mixed by','Mix engineer',V('mixer'))}${amField('am-videographer','Videographer','Video credit',V('videographer'))}${amField('am-label','Label','Record label',V('label'))}</div>
    <p class="te-k mt-6 mb-2">More</p><div class="grid gap-3 sm:grid-cols-2">${amField('am-mood','Mood','e.g. Chill',V('mood'))}${amField('am-date','Release date','',V('creationDate'),{type:'date'})}</div>
    <label class="mt-3 block">${lbl('Description')}<textarea id="am-desc" rows="3" placeholder="Tell the story behind the track" class="w-full resize-none rounded-xl border border-white/12 bg-white/5 px-3.5 py-2.5 text-sm text-white placeholder-white/30 outline-none focus:border-[color:var(--treesh-purple)]">${esc(V('desc'))}</textarea></label>
    <button type="button" data-act="am-explicit" id="am-explicit" data-on="${o.exOn?'1':'0'}" data-testid="te-explicit" class="press mt-3 flex w-full items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-3.5 text-left"><span class="grid h-6 w-6 shrink-0 place-items-center rounded-md border-2 ${o.exOn?'border-[color:var(--treesh-purple)] bg-[color:var(--treesh-purple)] text-white':'border-white/30 text-transparent'}"><i data-lucide="check" style="width:14px;height:14px"></i></span><span><span class="block text-sm font-semibold">Explicit content</span><span class="block text-xs text-white/50">Shows an E badge next to the title</span></span></button>`;
  const lyr=`<div class="te-card"><div class="flex items-center gap-3"><span class="te-ic"><i data-lucide="quote"></i></span><div class="min-w-0 flex-1"><p class="text-sm font-bold" data-testid="te-lyrics-count">${lines.length?lines.length+' lyric line'+(lines.length!==1?'s':''):'No lyrics yet'}</p><p class="te-d">${lines.length?(stamped?pct+'% synced to the music':'Not synced yet'):'Write them yourself or pull them from the web.'}</p></div></div>${lines.length?`<div class="te-lyr" data-testid="te-lyrics-preview">${lines.slice(0,8).map(l=>`<p>${esc(l.text)}</p>`).join('')}${lines.length>8?`<p class="opacity-50">+${lines.length-8} more lines</p>`:''}</div>`:''}<div class="mt-4 flex flex-wrap gap-2"><button type="button" data-act="te-lyrics" data-val="ls" data-id="${ed.id}" data-testid="te-lyrics-edit" class="te-btn primary press"><i data-lucide="captions"></i>${lines.length?'Edit lyrics':'Write lyrics'}</button><button type="button" data-act="te-lyrics" data-val="find" data-id="${ed.id}" data-testid="te-lyrics-find" class="te-btn press"><i data-lucide="sparkles"></i>Find lyrics online</button></div><p class="te-d mt-3">Any detail changes are saved first.</p></div>`;
  const timing=`<div class="te-card"><p class="te-k">Audio</p><div id="am-preview" class="hidden mt-2.5"></div><label for="am-audio" class="te-drop press mt-3" data-testid="te-audio-drop"><span class="te-ic"><i data-lucide="file-audio-2"></i></span><span class="min-w-0 flex-1"><span id="am-audio-name" class="clamp-1 block text-sm font-semibold">Replace audio file (optional)</span><span class="block text-[11px] opacity-50">Keep the current audio, or pick a new file \u00b7 up to 30 MB</span></span><i data-lucide="upload" class="shrink-0 opacity-40" style="width:18px;height:18px"></i></label><input id="am-audio" type="file" accept="audio/*,.mp3,.wav,.m4a,.aac,.ogg,.flac,.opus,.webm" class="sr-only" data-testid="te-audio-input">${dur?`<p class="te-d mt-2">Current length ${fmt(dur)}</p>`:''}</div>
    <div class="te-card mt-3"><p class="te-k">Lyric timing</p><div class="te-sync"><div class="te-sync-bar"><span style="width:${pct}%"></span></div><b data-testid="te-sync-pct">${pct}%</b></div><p class="te-d">${lines.length?(pct===100?'Every line is timed. Lyrics will follow along perfectly.':stamped+' of '+lines.length+' lines are timed.'):'Add lyrics first, then tap along to time them.'}</p><button type="button" data-act="te-lyrics" data-val="ls" data-id="${ed.id}" data-testid="te-sync-open" class="te-btn primary press mt-3"><i data-lucide="timer"></i>${lines.length?'Sync lyrics to the beat':'Add lyrics'}</button></div>`;
  return `<div id="am-glow" class="te-glow"></div>
  <header class="te-head"><button type="button" data-act="modal-close" aria-label="Close" data-testid="custom-studio-close" class="te-x press"><i data-lucide="x"></i></button><div class="min-w-0 flex-1"><p class="st-eyebrow">Edit track</p><h2 class="te-title clamp-1" data-testid="te-title">${esc(ed.title||'Untitled')}</h2></div><button type="button" data-act="am-save" data-testid="am-save-btn" class="te-save press"><i data-lucide="check"></i>Save</button></header>
  <div class="te-tabs no-scrollbar" data-testid="te-tabs">${TE_TABS.map(([id,l,ic])=>`<button type="button" data-act="te-tab" data-val="${id}" data-testid="te-tab-${id}" aria-pressed="${tab===id}" class="te-tab press${tab===id?' on':''}"><i data-lucide="${ic}"></i>${l}</button>`).join('')}</div>
  <div class="te-body soft-scroll" id="te-body">${pane('cover',cover)}${pane('details',details)}${pane('lyrics',lyr)}${pane('timing',timing)}</div>`; }
function teTab(v){ document.querySelectorAll('#modal .te-tab').forEach(b=>{ const on=b.dataset.val===v; b.classList.toggle('on',on); b.setAttribute('aria-pressed',on); }); document.querySelectorAll('#modal [data-te-pane]').forEach(p=>p.classList.toggle('hidden',p.dataset.tePane!==v)); const b=document.getElementById('te-body'); if(b) b.scrollTop=0; }
function teLyrics(mode,id){ const go=()=>{ if(mode==='find') openFindLyrics(id); else openLyricSync(id); };
  if(!state._teDirty&&!_amCoverBlob){ closeModal(); setTimeout(go,240); return; }
  saveCustomTrack().then(()=>{ if(_amEditId) return; setTimeout(go,240); }); }

/* ---------- P7: Manage uploads list (titles first, actions in a menu) ---------- */
function manageUploadsHtml(){
  if(!USER_SONGS.length) return `<div class="flex flex-col items-center gap-3 rounded-2xl border border-dashed border-white/12 bg-white/[0.03] px-6 py-12 text-center" data-testid="manage-empty"><span class="grid h-14 w-14 place-items-center rounded-2xl bg-[color:var(--treesh-purple)]/15 text-[color:var(--treesh-purple)]"><i data-lucide="music-2" style="width:24px;height:24px"></i></span><p class="text-sm font-bold">No tracks yet</p><p class="text-xs text-white/50">Add your first song from the Add tab.</p></div>`;
  return `<p class="mb-2.5 px-1 text-xs text-white/45">Tap a cover to play. Tap <i data-lucide="ellipsis" style="width:13px;height:13px;display:inline;vertical-align:-2px"></i> to edit, add lyrics or delete.</p><div class="um-list" data-testid="manage-list">${USER_SONGS.slice().reverse().map(s=>{ const ly=(s.lyrics||[]).filter(l=>l&&l.text&&l.text.trim()); const syn=ly.some(l=>l.t!=null); const d=+s.duration||0;
    return `<div class="um-row" data-testid="upload-row-${s.id}"><button data-act="upload-play" data-id="${s.id}" data-testid="upload-play-${s.id}" aria-label="Play ${esc(s.title)}" class="um-art press">${img(s.coverArt,'h-full w-full object-cover')}<span class="um-play"><i data-lucide="play"></i></span></button><div class="um-txt"><p class="um-t" data-testid="upload-title-${s.id}">${esc(s.title)}</p><p class="um-a">${esc(s.artist||'You')}${s.album?' \u00b7 '+esc(s.album):''}</p><div class="um-tags">${s.genre?`<span>${esc(s.genre)}</span>`:''}${ly.length?`<span class="${syn?'ok':''}">${syn?'Synced':'Lyrics'}</span>`:''}${d?`<span>${fmt(d)}</span>`:''}${s.explicit?'<span>E</span>':''}</div></div><button data-act="um-menu" data-id="${s.id}" data-testid="upload-menu-${s.id}" aria-label="Options for ${esc(s.title)}" class="um-more press"><i data-lucide="ellipsis"></i></button></div>`; }).join('')}</div>`; }
function umHead(s){ return `<div class="pm-song"><span class="h-12 w-12 shrink-0 overflow-hidden rounded-xl">${img(s.coverArt,'h-full w-full object-cover')}</span><div class="min-w-0 flex-1"><p class="clamp-1 text-sm font-bold">${esc(s.title)}</p><p class="clamp-1 text-xs text-white/55">${esc(s.artist||'You')}</p></div><button data-act="um-close" aria-label="Close" data-testid="upload-menu-close" class="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white/5 text-white/70"><i data-lucide="x" style="width:16px;height:16px"></i></button></div>`; }
function umOpenMenu(id){ const s=USER_SONGS.find(x=>x.id===id)||SONG_BY_ID[id]; if(!s) return; const hasLy=(s.lyrics||[]).some(l=>l&&l.text&&l.text.trim());
  const it=(act,ic,label,o)=>pmItem(Object.assign({act,ic,label,attrs:`data-id="${id}"${act==='um-del'?'':' data-um="1"'}`,tid:'upload-menu-'+act},o||{}));
  const inner=`${umHead(s)}<div class="pm-list mt-2">${it('upload-play','play','Play now')}${it('edit-upload','pencil','Edit track',{desc:'Cover, details, lyrics & timing'})}${it('ls-open','captions',hasLy?'Edit or sync lyrics':'Add lyrics')}${it('lyrics-find','sparkles','Find lyrics online')}<div class="pm-sep"></div>${it('um-del','trash-2','Delete track',{danger:true})}</div>`;
  $("#modal2").innerHTML=modal2Wrap(inner,'upload-menu').replace('data-act="modal2-backdrop"','data-act="modal2-backdrop" data-p7bd="1"'); icons(); syncScrollLock(); }
function umConfirmDelete(id){ const s=USER_SONGS.find(x=>x.id===id); if(!s) return; const p=document.querySelector('#modal2 .pm-list'); if(!p) return;
  p.innerHTML=`<div class="pm-alert"><span class="pm-alert-ic"><i data-lucide="triangle-alert"></i></span><h3 class="pm-title">Delete \u201c${esc(s.title)}\u201d?</h3><p class="pm-desc">The audio, cover and lyrics are removed from this device. This can\u2019t be undone.</p></div><div class="pm-actions"><button type="button" data-act="um-close" data-testid="upload-delete-cancel" class="st-btn lg">Cancel</button><button type="button" data-act="um-del-yes" data-id="${id}" data-testid="upload-delete-confirm" class="st-btn lg danger">Delete</button></div>`; icons(); }

/* ---------- P7: phones, drag any sheet down to close (handle, header or from the top of its scroll) ---------- */
(function(){ let S=null; const HEAD='.pm-grab,.pf-grab,.pm-head,.pm-song,.st-head,.te-head,.te-tabs,[data-sheet-drag]';
  const scrollerOf=(el,stop)=>{ for(let n=el;n&&n!==stop;n=n.parentElement){ const oy=getComputedStyle(n).overflowY; if((oy==='auto'||oy==='scroll')&&n.scrollHeight>n.clientHeight+1) return n; } return null; };
  document.addEventListener('touchstart',e=>{ S=null; if(window.innerWidth>=640||e.touches.length!==1) return; const t=e.target; if(!t||!t.closest) return;
    const p=t.closest('.pm-panel,#profile-panel'); if(!p) return; const head=!!t.closest(HEAD);
    if(!head&&t.closest('input,textarea,select,[contenteditable="true"],canvas,.st-frame,[data-no-swipe]')) return;
    if(p.classList.contains('st-modal')&&!p.classList.contains('te-sheet')&&!head) return;
    const sc=head?null:scrollerOf(t,p.parentElement); if(sc&&sc.scrollTop>0) return;
    S={p,sc,x0:e.touches[0].clientX,y0:e.touches[0].clientY,t0:performance.now(),dy:0,on:false,dead:false}; },{passive:true,capture:true});
  document.addEventListener('touchmove',e=>{ if(!S||S.dead) return; const tc=e.touches[0]; const dx=tc.clientX-S.x0, dy=tc.clientY-S.y0;
    if(!S.on){ if(Math.abs(dx)>10&&Math.abs(dx)>Math.abs(dy)){ S.dead=true; return; } if(dy<-6){ S.dead=true; return; } if(dy<8) return; if(S.sc&&S.sc.scrollTop>0){ S.dead=true; return; }
      S.on=true; S.y0=tc.clientY; S.t0=performance.now(); S.p.classList.add('pm-dragging'); S.p.style.transition='none'; S.p.style.animation='none'; S.bd=sheetBackdrop(S.p); }
    if(e.cancelable) e.preventDefault(); const d=Math.max(0,tc.clientY-S.y0); S.dy=d; S.p.style.transform='translate3d(0,'+d+'px,0)'; if(S.bd) S.bd.style.opacity=String(Math.max(.2,1-d/650)); },{passive:false,capture:true});
  const end=()=>{ const s=S; S=null; if(!s||!s.on) return; const p=s.p; p.classList.remove('pm-dragging'); const v=s.dy/Math.max(1,performance.now()-s.t0);
    if(s.dy>110||(v>.5&&s.dy>40)){ p.style.transition='transform .22s cubic-bezier(.4,0,1,1)'; p.style.transform='translate3d(0,110%,0)'; if(s.bd){ s.bd.style.transition='opacity .22s ease'; s.bd.style.opacity='0'; } setTimeout(()=>sheetClose(p),190); }
    else { p.style.transition='transform .4s cubic-bezier(.34,1.4,.64,1)'; p.style.transform=''; if(s.bd){ s.bd.style.transition='opacity .3s ease'; s.bd.style.opacity=''; } setTimeout(()=>{ p.style.transition=''; p.style.animation=''; if(s.bd) s.bd.style.transition=''; },420); } };
  document.addEventListener('touchend',end,{capture:true}); document.addEventListener('touchcancel',end,{capture:true});
})();
function sheetBackdrop(p){ if(p.id==='profile-panel') return document.querySelector('#profile [data-act="profile-close"]'); const bd=p.parentElement; return bd&&/backdrop$/.test(bd.dataset.act||'')?bd:null; }
function sheetClose(p){ if(p.id==='profile-panel'){ closeProfile(true); return; } const bd=p.parentElement; if(!bd) return; bd.style.animation='none'; p.style.animation='none'; if(bd.closest('#modal2')) closeModal2(); else if(bd.closest('#modal')) closeModal(); else bd.click(); }
