/* ---------- P8: Magic Markup, page themes (MySpace style) ---------- */
const MK_BGS=[
  {id:'none',name:'None',css:''},
  {id:'aurora',name:'Aurora',css:'radial-gradient(60% 50% at 18% 8%,rgba(124,58,237,.6),transparent 70%),radial-gradient(50% 45% at 88% 28%,rgba(34,211,238,.42),transparent 70%),radial-gradient(70% 60% at 50% 105%,rgba(255,45,120,.42),transparent 70%),#07060d',anim:'aurora'},
  {id:'sunset',name:'Sunset',css:'linear-gradient(172deg,#ff8a5b 0%,#ff2d78 32%,#6d1b7b 66%,#140a22 100%)'},
  {id:'ocean',name:'Ocean',css:'linear-gradient(180deg,#0ea5e9 0%,#1e3a8a 52%,#040a1c 100%)'},
  {id:'midnight',name:'Midnight',css:'radial-gradient(90% 60% at 50% -5%,#3b0d6b,#05040a 72%)'},
  {id:'candy',name:'Candy',css:'linear-gradient(135deg,#f472b6 0%,#a855f7 50%,#60a5fa 100%)'},
  {id:'forest',name:'Forest',css:'radial-gradient(80% 60% at 50% 0%,#15803d,#052e16 60%,#020a05)'},
  {id:'y2k',name:'Y2K grid',css:'linear-gradient(180deg,#14052b 0%,#3b0764 55%,#a21caf 100%)',anim:'grid'},
  {id:'stars',name:'Starfield',css:'radial-gradient(120% 80% at 50% 0%,#1b1340,#04030a 70%)',anim:'stars'},
  {id:'lava',name:'Lava lamp',css:'linear-gradient(180deg,#1a0526,#0d0214)',anim:'lava'},
  {id:'glitter',name:'Glitter',css:'linear-gradient(160deg,#4c0d78,#1e0533 55%,#0b0213)',anim:'glitter'}
];
const MK_LOOKS=[
  {id:'y2k',name:'Y2K Glam',bg:'y2k',accent:'#ff2d78',font:'fredoka',surf:'bubble',glow:'rainbow'},
  {id:'emo',name:'Emo Night',bg:'midnight',accent:'#e11d48',font:'playfair',surf:'solid',glow:'accent'},
  {id:'vapor',name:'Vaporwave',bg:'sunset',accent:'#22d3ee',font:'spacegrotesk',surf:'glass',glow:'beat'},
  {id:'galaxy',name:'Galaxy',bg:'stars',accent:'#a78bfa',font:'montserrat',surf:'glass',glow:'accent'},
  {id:'lava',name:'Lava Lamp',bg:'lava',accent:'#f97316',font:'poppins',surf:'bubble',glow:'beat'},
  {id:'candy',name:'Candy Pop',bg:'candy',accent:'#ec4899',font:'nunito',surf:'bubble',glow:'off'},
  {id:'clean',name:'Clean',bg:'none',accent:'',font:'',surf:'',glow:'off'}
];
const MK_GLOWS=[['off','Off'],['accent','Accent'],['rainbow','Rainbow'],['beat','Beat']];
const MK_ACCENTS=['#9328ff','#3b82f6','#22d3ee','#34d399','#f59e0b','#f97316','#ff2d78','#e11d48','#a78bfa'];
let _mkAccNow=null, _mkBgKey='';
function mkTheme(page){ const P=page&&mkS().pages[page]; return (P&&P.theme)||null; }
function mkThemeCls(P){ const T=P.theme||{}; return (T.glow&&T.glow!=='off'?' mk-glow mk-glow-'+T.glow:'')+(T.font?' mk-has-font':'')+(mkS().snap&&state.mkEdit?' mk-snap':''); }
function mkThemeStyle(P){ const T=P.theme||{}; return T.font?'--mk-font:'+bgFontStack(T.font):''; }
function mkFxHtml(a){ if(a==='lava') return '<div class="mk-fx mk-fx-lava"><i></i><i></i><i></i><i></i></div>';
  if(a==='stars') return '<div class="mk-fx mk-fx-stars"><i></i><i></i><i></i></div>';
  if(a==='aurora') return '<div class="mk-fx mk-fx-aurora"><i></i><i></i></div>';
  if(a==='grid') return '<div class="mk-fx mk-fx-sun"></div><div class="mk-fx mk-fx-grid"></div>';
  if(a==='glitter'){ let h=''; for(let i=0;i<26;i++){ const x=(i*37+11)%100, y=(i*53+7)%100, d=(i%7)*.45, s=6+(i*13)%14; h+=`<i style="left:${x}%;top:${y}%;width:${s}px;height:${s}px;animation-delay:${d}s"></i>`; } return '<div class="mk-fx mk-fx-glitter">'+h+'</div>'; }
  return ''; }
function mkPbgInner(T){ const b=MK_BGS.find(x=>x.id===T.bg); let bg='', fx='';
  if(T.bg==='color') bg='background:'+(T.color||'#1a1033');
  else if(T.bg==='photo'){ const src=T.photo?mkSrc({src:T.photo}):''; if(!src) return ''; const bl=+T.blur||0; bg=`background:#000 url('${src}') center/cover no-repeat;${bl?`filter:blur(${bl}px);inset:-${bl*2}px`:''}`; }
  else if(b&&b.css){ bg='background:'+b.css; if(b.anim) fx=mkFxHtml(b.anim); }
  else return '';
  const dim=T.dim!=null?+T.dim:(T.bg==='photo'?30:0);
  return `<div class="mk-pbg-base" data-testid="mk-page-bg-base" style="${bg}"></div>${fx}<div class="mk-pbg-dim" style="opacity:${dim/100}"></div>`; }
function mkThemeApply(force){ const page=mkCurPage(); const T=mkTheme(page);
  const want=(T&&T.accent)||state.accent||'#9328ff'; if(_mkAccNow!==want){ _mkAccNow=want; try{ applyAccent(want); }catch(e){} }
  let el=document.getElementById('mk-pbg'); if(!el){ el=document.createElement('div'); el.id='mk-pbg'; el.setAttribute('aria-hidden','true'); el.setAttribute('data-testid','mk-page-bg'); const bl=document.getElementById('bg-layer'); document.body.insertBefore(el,bl?bl.nextSibling:document.body.firstChild); }
  const on=!!(T&&T.bg&&T.bg!=='none'); const key=on?JSON.stringify([page,T.bg,T.color,T.photo,T.blur,T.photo&&!!_mkImgs[String(T.photo).slice(4)]]):'';
  document.documentElement.classList.toggle('mk-has-pbg',on);
  if(!force&&key===_mkBgKey){ const d=el.querySelector('.mk-pbg-dim'); if(d&&T) d.style.opacity=((T.dim!=null?+T.dim:(T.bg==='photo'?30:0))/100); return; }
  _mkBgKey=key; el.innerHTML=on?mkPbgInner(T):''; el.dataset.bg=on?T.bg:''; }
function mkThSet(patch){ const page=mkCurPage(); if(!page) return; const P=mkPage(page); const T=P.theme||(P.theme={});
  Object.keys(patch).forEach(k=>{ const v=patch[k]; if(v===''||v==null) delete T[k]; else T[k]=v; }); if(!Object.keys(T).length) delete P.theme;
  mkSave(); renderView(); mkRenderSheet(); }
function mkBgAspect(){ return Math.max(.46,Math.min(2.2,(window.innerWidth||390)/(window.innerHeight||844))); }
function mkBgStudio(src,own,label){ const page=mkCurPage(); if(!page) return; const A=mkBgAspect(); const W=A>=1?1600:Math.round(1600*A), H=A>=1?Math.round(1600/A):1600;
  openCoverStudio(src,label||'Page background',own,{aspect:A,out:[W,H],q:.82,applyLabel:'Set background',onApply:d=>{ const key='mk_bg_'+page; assetPut(key,d).then(()=>{ _mkImgs[key]=d; mkThSet({bg:'photo',photo:'idb:'+key}); toast('Background set',(MK_PAGE_LABEL[page]||'This page')+' has a new look'); }).catch(()=>toast('Couldn\u2019t save background','Your device storage may be full')); }}); }
function mkThemeHtml(page){ const T=mkTheme(page)||{}; const cur=T.bg||'none';
  const tile=(b)=>`<button type="button" data-act="mk-bg" data-val="${b.id}" data-testid="mk-bg-${b.id}" aria-pressed="${cur===b.id}" class="mk-bgt${cur===b.id?' on':''}${b.id==='none'?' is-none':''}"><span class="mk-bgt-sw" style="${b.css?'background:'+b.css:''}">${b.id==='none'?'<i data-lucide="ban"></i>':''}${b.anim?'<em>Live</em>':''}</span><span class="mk-bgt-l">${b.name}</span></button>`;
  const photo=T.photo&&_mkImgs[String(T.photo).slice(4)];
  const extra=`<button type="button" data-act="mk-bg" data-val="color" data-testid="mk-bg-color" aria-pressed="${cur==='color'}" class="mk-bgt${cur==='color'?' on':''}"><span class="mk-bgt-sw" style="background:${T.color||'conic-gradient(#ff2d78,#f59e0b,#34d399,#22d3ee,#9328ff,#ff2d78)'}"></span><span class="mk-bgt-l">Color</span></button><button type="button" data-act="mk-bg" data-val="photo" data-testid="mk-bg-photo" aria-pressed="${cur==='photo'}" class="mk-bgt${cur==='photo'?' on':''}"><span class="mk-bgt-sw" style="${photo?`background:url('${photo}') center/cover`:''}">${photo?'':'<i data-lucide="image-plus"></i>'}</span><span class="mk-bgt-l">Photo</span></button>`;
  const dim=T.dim!=null?+T.dim:(cur==='photo'?30:0);
  return `<p class="mk-lbl">One-tap looks</p><div class="mk-looks no-scrollbar" data-testid="mk-looks">${MK_LOOKS.map(l=>{ const b=MK_BGS.find(x=>x.id===l.bg)||MK_BGS[0]; const f=(FONTS.find(x=>x.id===l.font)||{}).stack||''; return `<button type="button" data-act="mk-look" data-val="${l.id}" data-testid="mk-look-${l.id}" class="mk-look" style="${b.css?'background:'+b.css+';':''}--la:${l.accent||'#ffffff'}"><span class="mk-look-dot"></span><span class="mk-look-n" style="${f?'font-family:'+f:''}">${l.name}</span></button>`; }).join('')}</div>
   <p class="mk-lbl mt-4">Background</p><div class="mk-bgts" data-testid="mk-bg-grid">${MK_BGS.map(tile).join('')}${extra}</div>
   <input type="file" accept="image/*,.heic,.heif" id="mk-bg-file" data-testid="mk-bg-file" class="hidden">
   ${cur==='color'?`<div class="mk-field mt-3"><div class="mk-lbl-row"><p class="mk-lbl">Pick a color</p></div><label class="mk-color" style="width:100%;height:44px;border-radius:14px;background:${T.color||'#1a1033'}"><input type="color" value="${T.color||'#1a1033'}" data-mk-th="color" data-testid="mk-bg-color-input" aria-label="Background color"></label></div>`:''}
   ${cur==='photo'&&photo?`<div class="mt-3 grid grid-cols-2 gap-2"><button type="button" data-act="mk-bg" data-val="photo" data-testid="mk-bg-change" class="mk-btn"><i data-lucide="image-up"></i>New photo</button><button type="button" data-act="mk-bg-edit" data-testid="mk-bg-edit" class="mk-btn"><i data-lucide="wand-sparkles"></i>Edit in Studio</button></div>`:''}
   ${cur!=='none'?`<div class="mk-field mt-3"><div class="mk-lbl-row"><p class="mk-lbl">Dim</p><span class="mk-val" id="mk-th-dim-val">${dim}%</span></div><input type="range" min="0" max="85" step="1" value="${dim}" data-mk-th="dim" data-testid="mk-bg-dim" aria-label="Dim background" class="i-slider w-full"></div>`:''}
   ${cur==='photo'?`<div class="mk-field"><div class="mk-lbl-row"><p class="mk-lbl">Blur</p><span class="mk-val" id="mk-th-blur-val">${+T.blur||0}px</span></div><input type="range" min="0" max="24" step="1" value="${+T.blur||0}" data-mk-th="blur" data-testid="mk-bg-blur" aria-label="Blur background" class="i-slider w-full"></div>`:''}
   <div class="mk-field mt-4"><div class="mk-lbl-row"><p class="mk-lbl">Accent color</p>${T.accent?`<button type="button" data-act="mk-th-accent" data-val="" data-testid="mk-th-accent-clear" class="mk-chip">App accent</button>`:''}</div><div class="flex flex-wrap items-center gap-2"><label class="mk-color" style="background:${T.accent||'conic-gradient(#ff2d78,#f59e0b,#34d399,#22d3ee,#9328ff,#ff2d78)'}"><input type="color" value="${T.accent||state.accent||'#9328ff'}" data-mk-th="accent" data-testid="mk-th-accent-input" aria-label="Custom accent"></label>${MK_ACCENTS.map(c=>`<button type="button" data-act="mk-th-accent" data-val="${c}" data-testid="mk-th-accent-${c.slice(1)}" aria-label="Accent ${c}" class="mk-swatch${T.accent===c?' on':''}" style="background:${c}"></button>`).join('')}</div></div>
   <div class="mk-field"><p class="mk-lbl">Font</p><div class="mk-fonts no-scrollbar" data-testid="mk-th-fonts"><button type="button" data-act="mk-th-font" data-val="" data-testid="mk-th-font-default" class="mk-font${!T.font?' on':''}">App font</button>${FONTS.map(f=>{ try{ if(f.g) loadGoogleFont(f.g); }catch(e){} return `<button type="button" data-act="mk-th-font" data-val="${f.id}" data-testid="mk-th-font-${f.id}" class="mk-font${T.font===f.id?' on':''}" style="font-family:${f.stack}">${f.name}</button>`; }).join('')}</div></div>
   <div class="mk-field"><p class="mk-lbl">Section style</p>${mkSeg('mk-th-surf',T.surf||'default',MK_SURF,'mk-th-surf').replace('class="mk-seg"','class="mk-seg mk-seg-wrap"')}<p class="mk-hint mt-1.5">Applies to every section without its own style.</p></div>
   <div class="mk-field"><p class="mk-lbl">Glow</p>${mkSeg('mk-th-glow',T.glow||'off',MK_GLOWS,'mk-th-glow')}<p class="mk-hint mt-1.5">${T.glow==='beat'?'Cards pulse with the music.':'A soft halo around your cards.'}</p></div>
   <button type="button" data-act="mk-th-reset" data-testid="mk-th-reset" class="mk-btn w-full"><i data-lucide="rotate-ccw"></i>Reset this page\u2019s theme</button>`; }
function mkApplyLook(id){ const l=MK_LOOKS.find(x=>x.id===id); if(!l) return; const page=mkCurPage(); const T=mkTheme(page)||{}; const keepPhoto=T.bg==='photo'&&l.id!=='clean';
  mkThSet({bg:keepPhoto?'photo':l.bg,accent:l.accent,font:l.font,surf:l.surf,glow:l.glow==='off'?'':l.glow}); toast(l.name+' look applied',keepPhoto?'Kept your photo background':'Tweak anything below'); }

/* ---------- P8: stickers stick to the section they are dropped on ---------- */
function mkSecLayer(P,id){ const list=P.stickers.filter(s=>s.cv===id); return list.length?`<div class="mk-sec-layer" data-mk-sec-layer="${id}">${list.map(s=>mkStickerHtml(s,true)).join('')}</div>`:''; }
function mkBlocksAt(cx,cy){ let hit=null; document.querySelectorAll('#view [data-mk-page] > [data-mk-id]').forEach(b=>{ if(hit||b.classList.contains('mk-is-hidden')) return; const r=b.getBoundingClientRect(); if(cx>=r.left&&cx<=r.right&&cy>=r.top&&cy<=r.bottom) hit=b; }); return hit; }
function mkStHost(P){ const vy=window.innerHeight*0.42;
  const pick=b=>{ const host=b.querySelector('[data-mk-canvas]')||b; const r=host.getBoundingClientRect(); const isC=host!==b; return {id:b.dataset.mkId,x:0.5,y:isC?0.5:(r.height?Math.max(0.08,Math.min(0.92,(vy-r.top)/r.height)):0.5)}; };
  const sel=state.mkSel&&mkBlockEl(state.mkSel); if(sel&&!sel.classList.contains('mk-is-hidden')) return pick(sel);
  let hit=null; document.querySelectorAll('#view [data-mk-page] > [data-mk-id]').forEach(b=>{ if(hit||b.classList.contains('mk-is-hidden')) return; const r=b.getBoundingClientRect(); if(r.top<=vy&&r.bottom>=vy) hit=b; });
  if(hit) return pick(hit);
  const pg=document.querySelector('#view [data-mk-page]'); const r=pg.getBoundingClientRect(); return {id:null,x:0.5,y:Math.max(40,Math.round(vy-r.top))}; }
function mkStCenter(el){ const r=el.getBoundingClientRect(); return [r.left+r.width/2,r.top+r.height/2]; }
function mkStToPage(s,el){ const pg=document.querySelector('#view [data-mk-page]'); if(!pg) return; const [cx,cy]=mkStCenter(el); const r=pg.getBoundingClientRect(); s.cv=null; s.x=Math.max(0,Math.min(1,(cx-r.left)/r.width)); s.y=Math.max(0,Math.round(cy-r.top)); }
function mkStReparent(s,el){ if(s.free||!el) return false; const [cx,cy]=mkStCenter(el); const hit=mkBlocksAt(cx,cy); const nid=hit?hit.dataset.mkId:null;
  if(nid===(s.cv||null)) return false;
  if(!nid){ mkStToPage(s,el); return true; }
  const host=hit.querySelector('[data-mk-canvas]')||hit; const r=host.getBoundingClientRect(); s.cv=nid; s.x=Math.max(0,Math.min(1,(cx-r.left)/r.width)); s.y=Math.max(0,Math.min(1,(cy-r.top)/r.height)); return true; }
function mkStName(s){ if(s.pack){ const p=MK_PACK.find(x=>x.id===s.pack); return p?p.name:'Sticker'; } if(s.kind==='emoji') return 'Emoji '+(s.text||''); if(s.kind==='text') return '\u201c'+(s.text||'Text')+'\u201d'; return 'Image sticker'; }
function mkStThumb(s){ if(s.kind==='emoji') return `<b>${esc(s.text||'')}</b>`; if(s.kind==='text') return '<b class="is-t">Aa</b>'; const src=mkSrc(s); return src?`<img src="${esc(src)}" alt="">`:'<i data-lucide="image"></i>'; }
function mkStPinHtml(s){ const blk=s.cv&&mkBlockEl(s.cv); const pg=mkCurPage(); const P=pg?mkPage(pg):{widgets:[],canvases:[]}; const wd=s.cv&&P.widgets.find(x=>x.id===s.cv); const isCv=s.cv&&P.canvases.some(x=>x.id===s.cv); const lbl=blk?mkLabel({id:s.cv,kind:wd?'widget':isCv?'canvas':'block',type:wd&&wd.type}):'';
  return `<div class="mk-field"><p class="mk-lbl">Stick to</p>${mkSeg('mk-st-pin',s.free?'page':'sec',[['sec','Its section'],['page','The page']],'mk-st-pin')}<p class="mk-hint mt-1.5" data-testid="mk-st-pin-hint">${s.free?'Floats over the page wherever you drop it.':(lbl?'Locked to <b>'+esc(lbl)+'</b>, so it moves with that section.':'Drop it on a section to lock it there.')}</p></div>
   <div class="mk-field">${mkSwitch('mk-st-lock','','mk-st-lock',!!s.locked,s.locked?'lock':'lock-open','Lock in place','Stops accidental drags while you edit')}</div>`; }

/* ---------- P8: layers panel + snap ---------- */
function mkLayersHtml(page){ const P=mkPage(page), m=mkS(); const order=mkDomOrder();
  const blk=id=>{ const wd=P.widgets.find(x=>x.id===id); const isCv=P.canvases.some(x=>x.id===id); return {id,kind:wd?'widget':isCv?'canvas':'block',type:wd&&wd.type}; };
  const ic=b=>b.kind==='widget'?((MK_WIDGETS[b.type]||{}).ic||'square'):b.kind==='canvas'?'square-dashed':'layout-template';
  const stRow=s=>`<div class="mk-ly-st${state.mkStSel===s.id?' on':''}" data-testid="mk-layer-st-${s.id}"><button type="button" data-act="mk-ly-st" data-id="${s.id}" data-testid="mk-layer-st-open-${s.id}" class="mk-ly-st-main"><span class="mk-ly-thumb">${mkStThumb(s)}</span><span class="clamp-1 text-left">${esc(mkStName(s))}</span></button><button type="button" data-act="mk-ly-st-lock" data-id="${s.id}" data-testid="mk-layer-st-lock-${s.id}" aria-pressed="${!!s.locked}" aria-label="${s.locked?'Unlock':'Lock'} sticker" class="mk-ly-ib${s.locked?' on':''}"><i data-lucide="${s.locked?'lock':'lock-open'}"></i></button><button type="button" data-act="mk-st-del" data-id="${s.id}" data-testid="mk-layer-st-del-${s.id}" aria-label="Delete sticker" class="mk-ly-ib is-danger"><i data-lucide="trash-2"></i></button></div>`;
  const rows=order.map((id,i)=>{ const b=blk(id), cfg=P.blocks[id]||{}; const sts=P.stickers.filter(s=>s.cv===id);
    return `<div class="mk-ly${state.mkSel===id?' on':''}${cfg.hidden?' is-hidden':''}" data-testid="mk-layer-${id}"><div class="mk-ly-row"><button type="button" data-act="mk-ly-sel" data-id="${id}" data-testid="mk-layer-sel-${id}" class="mk-ly-main"><span class="mk-ly-ic"><i data-lucide="${ic(b)}"></i></span><span class="min-w-0 flex-1 text-left"><span class="clamp-1 block text-[13px] font-semibold">${esc(mkLabel(b))}</span><span class="block text-[10.5px] text-white/45">${cfg.hidden?'Hidden':(sts.length?sts.length+' sticker'+(sts.length>1?'s':''):(b.kind==='widget'?'Widget':b.kind==='canvas'?'Canvas':'Section'))}</span></span></button><button type="button" data-act="mk-ly-move" data-id="${id}" data-val="up" ${i===0?'disabled':''} data-testid="mk-layer-up-${id}" aria-label="Move up" class="mk-ly-ib"><i data-lucide="chevron-up"></i></button><button type="button" data-act="mk-ly-move" data-id="${id}" data-val="down" ${i===order.length-1?'disabled':''} data-testid="mk-layer-down-${id}" aria-label="Move down" class="mk-ly-ib"><i data-lucide="chevron-down"></i></button><button type="button" data-act="mk-ly-hide" data-id="${id}" data-testid="mk-layer-hide-${id}" aria-label="${cfg.hidden?'Show':'Hide'}" class="mk-ly-ib"><i data-lucide="${cfg.hidden?'eye-off':'eye'}"></i></button></div>${sts.length?`<div class="mk-ly-sts">${sts.map(stRow).join('')}</div>`:''}</div>`; }).join('');
  const free=P.stickers.filter(s=>!s.cv||!order.includes(s.cv));
  return `${mkSwitch('mk-snap','','mk-snap-toggle',!!m.snap,'grid-3x3','Snap to grid','Stickers line up neatly and turn in 15\u00b0 steps')}
   <p class="mk-lbl mt-4">Sections, top to bottom</p><div class="mk-ly-list" data-testid="mk-layers-list">${rows||'<p class="mk-hint">Nothing on this page yet.</p>'}</div>
   ${free.length?`<p class="mk-lbl mt-4">Floating on the page</p><div class="mk-ly-sts is-free" data-testid="mk-layers-free">${free.map(stRow).join('')}</div>`:''}
   <p class="mk-hint mt-3">Tap a section to style it. Stickers stick to the section you drop them on, so they travel with it.</p>`; }
function mkSheetShell(v,title,body){ return `<div class="mk-sheet mk-ui dark-surface" data-testid="mk-sheet-${v}"><span class="mk-sheet-grab" aria-hidden="true"></span><div class="mk-sheet-head"><p class="mk-sheet-title">${title}</p><button type="button" data-act="mk-sheet-close" data-testid="mk-sheet-close" aria-label="Close panel" class="mk-icon-btn"><i data-lucide="x" style="width:16px;height:16px"></i></button></div><div class="mk-sheet-body soft-scroll">${body}</div></div>`; }
const _mkRS0=mkRenderSheet;
mkRenderSheet=function(){ const v=state.mkEdit?state.mkSheet:null;
  if(v==='layers'||v==='theme'){ const el=mkRoot('mk-sheet'); const page=mkCurPage(); if(!page){ state.mkSheet=null; el.innerHTML=''; mkTbSync(); return; }
    const sc=el.querySelector('.mk-sheet-body'); const keep=sc&&el.querySelector('[data-testid="mk-sheet-'+v+'"]')?sc.scrollTop:0;
    el.innerHTML=mkSheetShell(v,v==='layers'?'Layers \u00b7 '+MK_PAGE_LABEL[page]:'Theme \u00b7 '+MK_PAGE_LABEL[page],v==='layers'?mkLayersHtml(page):mkThemeHtml(page));
    icons(); el.querySelectorAll('input[type=range]').forEach(r=>{ try{ fillSlider(r); }catch(e){} }); const nb=el.querySelector('.mk-sheet-body'); if(nb&&keep) nb.scrollTop=keep; mkTbSync(); return; }
  _mkRS0(); const el=document.getElementById('mk-sheet'); const sh=el&&el.querySelector('.mk-sheet'); if(sh&&!sh.querySelector('.mk-sheet-grab')) sh.insertAdjacentHTML('afterbegin','<span class="mk-sheet-grab" aria-hidden="true"></span>'); mkTbSync(); };
function mkTbSync(){ document.querySelectorAll('#mk-toolbar [data-act="mk-sheet"]').forEach(b=>{ const on=b.dataset.val===state.mkSheet; b.classList.toggle('is-on',on); b.setAttribute('aria-pressed',on); }); }
function mkRenderChrome(){ const m=mkS(), edit=!!state.mkEdit;
  mkRoot('mk-fab').innerHTML=(m.fab!==false||edit)?`<button type="button" data-act="mk-toggle" data-testid="magic-markup-fab" aria-pressed="${edit}" aria-label="${edit?'Finish Magic Markup':'Magic Markup: customize this page'}" title="${edit?'Done editing':'Magic Markup \u00b7 drag to move'}" class="mk-fab-btn press${edit?' is-on':''}"><i data-lucide="${edit?'check':'wand-sparkles'}" style="width:22px;height:22px"></i></button>`:''; mkFabPlace();
  const pg=mkCurPage(), sh=state.mkSheet;
  const tb=(v,ic,l,tid,pri)=>`<button type="button" data-act="mk-sheet" data-val="${v}" data-testid="${tid}" aria-pressed="${sh===v}" title="${l}" aria-label="${l}" class="mk-tb-btn${pri?' is-primary':' is-ic'}${sh===v?' is-on':''}"><i data-lucide="${ic}" style="width:15px;height:15px"></i><span class="${pri?'':'mk-tb-l'}">${l}</span></button>`;
  mkRoot('mk-toolbar').innerHTML=edit?`<div class="mk-tb mk-ui dark-surface" data-testid="mk-toolbar"><span class="mk-tb-brand"><i data-lucide="wand-sparkles" style="width:16px;height:16px"></i><span class="hidden lg:inline">Magic Markup</span><span class="mk-tb-page" data-testid="mk-toolbar-page">${pg?MK_PAGE_LABEL[pg]:'View only'}</span></span>${pg?tb('add','plus','Add','mk-add-button',true)+tb('theme','palette','Theme','mk-theme-button')+tb('layers','layers','Layers','mk-layers-button'):''}${tb('pages','layout-panel-left','Pages','mk-pages-button')}<button type="button" data-act="mk-toggle" data-testid="mk-done-button" class="mk-tb-btn is-done"><i data-lucide="check" style="width:15px;height:15px"></i><span>Done</span></button></div>`:'';
  icons(); }
function mkAfterRender(){ document.documentElement.classList.toggle('mk-on',!!state.mkEdit); mkRenderChrome(); mkThemeApply(); mkReactLoop(); }

/* ---------- P8: more widgets (countdown, sticky note, quote, visualizer, lyric line) ---------- */
const MK_FUN=['countdown','note','quote','viz','lyric'];
const MK_MULTI=['countdown','note','quote'];
Object.assign(MK_WIDGETS,{ countdown:{label:'Countdown',ic:'hourglass',from:'Treesh',w:'half'}, note:{label:'Sticky note',ic:'sticky-note',from:'Treesh',w:'third'}, quote:{label:'Music quote',ic:'quote',from:'Treesh',w:'half'}, viz:{label:'Mini visualizer',ic:'audio-waveform',from:'the Player',w:'half'}, lyric:{label:'Lyric line',ic:'mic-vocal',from:'the Player',w:'full'} });
const MK_QUOTES=[['Where words fail, music speaks.','Hans Christian Andersen'],['One good thing about music, when it hits you, you feel no pain.','Bob Marley'],['Without music, life would be a mistake.','Friedrich Nietzsche'],['If it sounds good, it is good.','Duke Ellington'],['The only truth is music.','Jack Kerouac'],['Music expresses that which cannot be put into words and that which cannot remain silent.','Victor Hugo'],['I think music in itself is healing.','Billy Joel'],['Music gives a soul to the universe, wings to the mind, flight to the imagination.','Plato'],['Music is the strongest form of magic.','Marilyn Manson'],['People haven\u2019t always been there for me but music always has.','Taylor Swift'],['Music can change the world because it can change people.','Bono'],['Welcome to the Woodz.','Treesh']];
const MK_FUN_PREV={countdown:'<b class="mk-fun-big">03<small>d</small></b>',note:'<span class="mk-fun-note">Don\u2019t forget the hook!</span>',quote:'<span class="mk-fun-q">\u201c</span>',viz:'<span class="mk-fun-bars"><i></i><i></i><i></i><i></i><i></i></span>',lyric:'<span class="mk-fun-ly">\u266a la la la</span>'};
function mkFunAddHtml(have){ return `<div class="mk-fun-grid" data-testid="mk-fun-grid">${MK_FUN.map(k=>{ const w=MK_WIDGETS[k], on=!MK_MULTI.includes(k)&&have.has(k); return `<button type="button" data-act="mk-add-widget" data-val="${k}" data-testid="mk-add-widget-${k}" ${on?'disabled':''} class="mk-fun mk-fun-${k}${on?' is-on':''}"><span class="mk-fun-prev">${MK_FUN_PREV[k]}</span><span class="mk-live-l"><i data-lucide="${on?'check':w.ic}"></i>${w.label}</span></button>`; }).join('')}</div>`; }
function mkLocalDT(d){ const p=n=>String(n).padStart(2,'0'); return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate())+'T'+p(d.getHours())+':'+p(d.getMinutes()); }
function mkWDefaults(w){ if(w.type==='countdown'){ const d=new Date(); d.setDate(d.getDate()+7); d.setHours(18,0,0,0); w.at=mkLocalDT(d); w.title='Next drop'; w.style='neon'; } else if(w.type==='note'){ w.text=''; w.color='yellow'; } else if(w.type==='quote'){ w.qi=Math.floor(Math.random()*MK_QUOTES.length); w.style='serif'; } else if(w.type==='viz'){ w.style='bars'; w.color='accent'; } else if(w.type==='lyric'){ w.size='l'; } return w; }
function mkCdParts(at){ let ms=Math.max(0,at-Date.now()); const d=Math.floor(ms/864e5); ms-=d*864e5; const h=Math.floor(ms/36e5); ms-=h*36e5; const m=Math.floor(ms/6e4); ms-=m*6e4; const s=Math.floor(ms/1e3); const p=n=>String(n).padStart(2,'0'); return {d:String(d),h:p(h),m:p(m),s:p(s),done:at<=Date.now()}; }
function mkWCountdown(w){ const at=w.at?new Date(w.at).getTime():0; const ok=at&&!isNaN(at); const st=w.style||'neon'; const P=ok?mkCdParts(at):null;
  return `<section data-mk-widget="countdown" data-testid="mk-widget-countdown" class="mkw mkw-cd cd-${st} h-full"><span class="mkw-orb${st==='gold'?' gold':''}" aria-hidden="true"></span><div class="relative flex h-full flex-col justify-between gap-4"><div class="flex items-center justify-between gap-2"><span class="mkw-kicker"><i data-lucide="hourglass"></i>Countdown</span>${ok?`<span class="mkw-chip">${new Date(at).toLocaleDateString(undefined,{month:'short',day:'numeric'})} \u00b7 ${new Date(at).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</span>`:''}</div><div><p class="mkw-cd-title clamp-2" data-testid="cd-title">${esc(w.title||'Countdown')}</p>${ok?`<div class="mkw-cd-grid${P.done?' hidden':''}" data-cd="${at}" data-testid="cd-grid">${[['d','Days'],['h','Hours'],['m','Min'],['s','Sec']].map(([k,l])=>`<div><b data-cd-${k}>${P[k]}</b><span>${l}</span></div>`).join('')}</div><p class="mkw-cd-done${P.done?'':' hidden'}" data-cd-done="${at}" data-testid="cd-done">It\u2019s here! \u{1F389}</p>`:'<p class="mkw-sub">Pick a date in Magic Markup to start counting.</p>'}</div></div></section>`; }
function mkWNote(w){ const c=w.color||'yellow'; const t=(w.text||'').trim();
  return `<section data-mk-widget="note" data-testid="mk-widget-note" class="mkw-note note-${c} h-full"><span class="mkw-note-tape" aria-hidden="true"></span><p class="mkw-note-t${t?'':' is-empty'}" data-testid="note-text">${t?esc(t).replace(/\n/g,'<br>'):'Edit this note in Magic Markup. Lyrics, shout-outs, to-dos\u2026'}</p></section>`; }
function mkWQuote(w){ const q=MK_QUOTES[((+w.qi||0)%MK_QUOTES.length+MK_QUOTES.length)%MK_QUOTES.length];
  return `<section data-mk-widget="quote" data-testid="mk-widget-quote" class="mkw mkw-q q-${w.style||'serif'} h-full"><span class="mkw-q-mark" aria-hidden="true">\u201c</span><div class="relative flex h-full flex-col justify-between gap-4"><span class="mkw-kicker"><i data-lucide="quote"></i>Music quote</span><blockquote class="mkw-q-t" data-testid="quote-text">${esc(q[0])}</blockquote><div class="flex items-center justify-between gap-2"><p class="mkw-q-by">\u2014 ${esc(q[1])}</p><button type="button" data-act="mk-quote-next" data-id="${w.id}" data-testid="quote-next" aria-label="Another quote" class="mkw-chip press"><i data-lucide="shuffle"></i></button></div></div></section>`; }
function mkWViz(w){ const s=curSong();
  return `<section data-mk-widget="viz" data-testid="mk-widget-viz" class="mkw mkw-viz h-full"><div class="relative flex h-full flex-col gap-3"><div class="flex items-center justify-between gap-2"><span class="mkw-kicker"><i data-lucide="audio-waveform"></i>Visualizer</span><span class="mkw-chip" data-viz-state>${state.isPlaying?'\u25cf Live':'Paused'}</span></div><canvas data-mk-viz="${w.style||'bars'}" data-viz-color="${w.color||'accent'}" data-testid="viz-canvas" class="mkw-viz-cv"></canvas><p class="mkw-sub clamp-1" data-viz-sub>${s?esc(s.title)+' \u00b7 '+esc(s.artist):'Play a song to see it move'}</p></div></section>`; }
function mkWLyric(w){ const s=curSong(); const p=s?npPeekLines(s):null;
  return `<section data-mk-widget="lyric" data-testid="mk-widget-lyric" class="mkw mkw-ly ly-${w.size||'l'} h-full">${s&&s.coverArt?`<span class="mkw-ly-bg" style="background-image:url('${esc(s.coverArt)}')" aria-hidden="true"></span>`:''}<div class="relative flex h-full flex-col gap-3"><div class="flex items-center justify-between gap-2"><span class="mkw-kicker"><i data-lucide="mic-vocal"></i>${p&&p.synced?'Live lyrics':'Lyric line'}</span>${s?'<button type="button" data-act="mini-open" data-testid="lyric-open-player" class="mkw-chip press">Open player</button>':''}</div><div class="grid flex-1 content-center gap-2"><p class="mkw-ly-cur" data-mk-ly-cur data-testid="lyric-current">${p?esc(p.cur):(s?'No lyrics for this song yet':'Play a song to sing along')}</p><p class="mkw-ly-next" data-mk-ly-next>${p?esc(p.next||''):''}</p></div><p class="mkw-sub clamp-1">${s?esc(s.title)+' \u00b7 '+esc(s.artist):'Synced lyrics light up line by line'}</p></div></section>`; }
function mkWidgetHtml(type,w){ const f={nowplaying:mkWNowPlaying,recent:mkWRecent,icons:mkWIcons,quick:mkWQuick,gamestats:mkWGame,clock:mkWClock,date:mkWDate,weather:mkWWeather,countdown:mkWCountdown,note:mkWNote,quote:mkWQuote,viz:mkWViz,lyric:mkWLyric}[type]; return f?f(w||{}):''; }
function mkCurWidget(id){ const page=mkCurPage(); return page?mkPage(page).widgets.find(x=>x.id===id):null; }
function mkWRefreshId(id){ const w=mkCurWidget(id); const blk=mkBlockEl(id); if(!w||!blk) return; const el=blk.querySelector('[data-mk-widget]'); if(el){ el.outerHTML=mkWidgetHtml(w.type,w); icons(); mkReactLoop(); } }
function mkRefreshType(type){ const page=mkCurPage(); if(!page) return; mkPage(page).widgets.filter(w=>w.type===type).forEach(w=>mkWRefreshId(w.id)); }
function mkWCfgHtml(wd){ const t=wd.type; const hint=`<p class="mk-hint">${MK_FUN.includes(t)?'Made right here in Magic Markup.':'Pulled in from '+MK_WIDGETS[t].from+'.'}</p>`;
  const seg=(key,cur,opts)=>`<div class="mk-seg mk-seg-wrap">${opts.map(([v,l])=>`<button type="button" data-act="mk-wcfg" data-key="${key}" data-val="${v}" data-testid="mk-wcfg-${key}-${v}" aria-pressed="${cur===v}" class="${cur===v?'on':''}">${l}</button>`).join('')}</div>`;
  let f='';
  if(t==='countdown') f=`<div class="mk-field mt-3"><p class="mk-lbl">Counting down to</p><input class="mk-input w-full" data-mk-wcfg="title" data-testid="mk-cd-title" maxlength="40" value="${esc(wd.title||'')}" placeholder="Album drop, birthday, show\u2026"><input type="datetime-local" class="mk-input mt-2 w-full" data-mk-wcfg="at" data-testid="mk-cd-at" value="${esc(wd.at||'')}"></div><div class="mk-field"><p class="mk-lbl">Style</p>${seg('style',wd.style||'neon',[['neon','Neon'],['gold','Gold'],['mono','Mono']])}</div>`;
  else if(t==='note') f=`<div class="mk-field mt-3"><p class="mk-lbl">Note</p><textarea class="mk-input mk-ta mk-ta-note w-full" rows="4" maxlength="280" data-mk-wcfg="text" data-testid="mk-note-text" placeholder="Write anything\u2026">${esc(wd.text||'')}</textarea></div><div class="mk-field"><p class="mk-lbl">Paper</p>${seg('color',wd.color||'yellow',[['yellow','Lemon'],['pink','Bubblegum'],['blue','Sky'],['mint','Mint'],['glass','Glass']])}</div>`;
  else if(t==='quote') f=`<div class="mk-field mt-3"><p class="mk-lbl">Look</p>${seg('style',wd.style||'serif',[['serif','Classic'],['bold','Bold'],['neon','Neon']])}</div><button type="button" data-act="mk-quote-next" data-id="${wd.id}" data-testid="mk-quote-shuffle" class="mk-btn mb-3 w-full"><i data-lucide="shuffle"></i>Show another quote</button>`;
  else if(t==='viz') f=`<div class="mk-field mt-3"><p class="mk-lbl">Shape</p>${seg('style',wd.style||'bars',[['bars','Bars'],['wave','Wave'],['orb','Orb']])}</div><div class="mk-field"><p class="mk-lbl">Color</p>${seg('color',wd.color||'accent',[['accent','Accent'],['rainbow','Rainbow'],['white','White']])}</div>`;
  else if(t==='lyric') f=`<div class="mk-field mt-3"><p class="mk-lbl">Text size</p>${seg('size',wd.size||'l',[['m','Medium'],['l','Large'],['xl','Huge']])}</div>`;
  return hint+f; }
function mkCdTick(){ document.querySelectorAll('[data-cd]').forEach(el=>{ const at=+el.dataset.cd; const p=mkCdParts(at); ['d','h','m','s'].forEach(k=>{ const b=el.querySelector('[data-cd-'+k+']'); if(b&&b.textContent!==p[k]) b.textContent=p[k]; }); if(p.done){ el.classList.add('hidden'); const dn=el.parentNode&&el.parentNode.querySelector('[data-cd-done]'); if(dn) dn.classList.remove('hidden'); } }); }
function mkLyricTick(){ const els=document.querySelectorAll('[data-mk-ly-cur]'); if(!els.length) return; const s=curSong(); const p=s?npPeekLines(s):null; if(!p) return;
  els.forEach(el=>{ if(el.textContent!==p.cur){ el.textContent=p.cur; el.classList.remove('is-new'); void el.offsetWidth; el.classList.add('is-new'); const nx=el.parentNode.querySelector('[data-mk-ly-next]'); if(nx) nx.textContent=p.next||''; } }); }
function mkSongChanged(){ mkRefreshType('lyric'); const s=curSong(); document.querySelectorAll('#view [data-viz-sub]').forEach(el=>{ el.textContent=s?s.title+' \u00b7 '+s.artist:'Play a song to see it move'; }); document.querySelectorAll('#view [data-viz-state]').forEach(el=>{ el.textContent=state.isPlaying?'\u25cf Live':'Paused'; }); mkReactLoop(); }

/* ---------- P8: more animated stickers + beat motions ---------- */
MK_MOTIONS.push(['float','Float'],['jelly','Jelly'],['swing','Swing'],['shake','Shake'],['glow','Glow'],['flash','Flash']);
const _an=(attr,vals,dur,extra)=>`<animate attributeName="${attr}" values="${vals}" dur="${dur}s" repeatCount="indefinite"${extra||''}/>`;
const _at=(type,vals,dur,extra)=>`<animateTransform attributeName="transform" type="${type}" values="${vals}" dur="${dur}s" repeatCount="indefinite"${extra||''}/>`;
const _bar=(x,c,h,d,b)=>{ const ys=h.map(v=>90-v).join(';'); return `<rect x="${x}" y="${90-h[0]}" width="14" height="${h[0]}" rx="6" fill="${c}" stroke="#fff" stroke-width="3">${_an('height',h.join(';'),d,` begin="${b}s"`)}${_an('y',ys,d,` begin="${b}s"`)}</rect>`; };
const _star4='M0 -15C2 -4 4 -2 15 0C4 2 2 4 0 15C-2 4 -4 2 -15 0C-4 -2 -2 -4 0 -15Z';
const _note='M44 18v42a11 11 0 1 1-7-10.2V10l28 9v11z';
MK_PACK.push(
  {id:'eqlive',name:'Live EQ',m:'off',anim:1,svg:_bar(8,'#22d3ee',[56,22,70,38,56],1.05,0)+_bar(31,'#9328ff',[30,72,40,64,30],.9,-.2)+_bar(54,'#ff2d78',[66,34,58,20,66],1.2,-.5)+_bar(77,'#f59e0b',[24,58,30,74,24],.95,-.3)},
  {id:'pulsering',name:'Pulse rings',m:'off',anim:1,svg:`<circle cx="50" cy="50" r="12" fill="none" stroke="#ff2d78" stroke-width="5">${_an('r','12;46','1.6')}${_an('opacity','1;0','1.6')}</circle><circle cx="50" cy="50" r="12" fill="none" stroke="#22d3ee" stroke-width="5">${_an('r','12;46','1.6',' begin="-.8s"')}${_an('opacity','1;0','1.6',' begin="-.8s"')}</circle><circle cx="50" cy="50" r="15" fill="#fff"/><circle cx="50" cy="50" r="10" fill="#9328ff"/>`},
  {id:'risingnotes',name:'Rising notes',m:'off',anim:1,svg:_g('#e9d5ff','#9328ff')+`<g>${_at('translate','-14 20;-14 -18','2.4')}${_an('opacity','0;1;1;0','2.4')}<path d="${_note}" transform="scale(.7)" fill="url(#g)" stroke="#fff" stroke-width="4" stroke-linejoin="round"/></g><g>${_at('translate','34 26;34 -14','2.4',' begin="-1.2s"')}${_an('opacity','0;1;1;0','2.4',' begin="-1.2s"')}<path d="${_note}" transform="scale(.55)" fill="#ff2d78" stroke="#fff" stroke-width="5" stroke-linejoin="round"/></g>`},
  {id:'twinkle',name:'Twinkles',m:'off',anim:1,svg:`<g transform="translate(32 36)"><path d="${_star4}" fill="#fde68a" stroke="#fff" stroke-width="2.5">${_at('scale','1;.35;1','1.4')}</path></g><g transform="translate(70 30) scale(.7)"><path d="${_star4}" fill="#a5f3fc" stroke="#fff" stroke-width="3">${_at('scale','.35;1;.35','1.4')}</path></g><g transform="translate(56 72) scale(.9)"><path d="${_star4}" fill="#f5d0fe" stroke="#fff" stroke-width="2.5">${_at('scale','.7;.25;1;.7','1.8')}</path></g>`},
  {id:'cdspin',name:'Spinning CD',m:'off',anim:1,svg:`<defs><linearGradient id="cd" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#f0abfc"/><stop offset=".3" stop-color="#a5f3fc"/><stop offset=".55" stop-color="#fef08a"/><stop offset=".8" stop-color="#c4b5fd"/><stop offset="1" stop-color="#f9a8d4"/></linearGradient></defs><g>${_at('rotate','0 50 50;360 50 50','2.6')}<circle cx="50" cy="50" r="44" fill="url(#cd)" stroke="#fff" stroke-width="3"/><path d="M50 50L50 6A44 44 0 0 1 81 19z" fill="#fff" opacity=".55"/><path d="M50 50L19 81A44 44 0 0 1 10 64z" fill="#fff" opacity=".35"/></g><circle cx="50" cy="50" r="13" fill="#e5e7eb" stroke="#fff" stroke-width="3"/><circle cx="50" cy="50" r="5" fill="#111"/>`},
  {id:'ufo',name:'UFO',m:'off',anim:1,svg:`<g>${_at('translate','0 0;0 -6;0 0','2.2')}<path d="M34 72L22 96h56L66 72z" fill="#a3e635" opacity=".45">${_an('opacity','.15;.55;.15','1.1')}</path><ellipse cx="50" cy="40" rx="18" ry="16" fill="#a5f3fc" stroke="#fff" stroke-width="3" opacity=".9"/><ellipse cx="50" cy="56" rx="42" ry="14" fill="#9328ff" stroke="#fff" stroke-width="3.5"/><circle cx="30" cy="58" r="4" fill="#fde047">${_an('opacity','1;.2;1','.8')}</circle><circle cx="50" cy="62" r="4" fill="#fde047">${_an('opacity','.2;1;.2','.8')}</circle><circle cx="70" cy="58" r="4" fill="#fde047">${_an('opacity','1;.2;1','.8')}</circle></g>`},
  {id:'ghost',name:'Ghost',m:'off',anim:1,svg:`<g>${_at('translate','0 3;0 -5;0 3','2.6')}<path d="M20 50a30 30 0 0 1 60 0v38l-10-8-10 8-10-8-10 8-10-8-10 8z" fill="#f5f5f5" stroke="#c4b5fd" stroke-width="3.5" stroke-linejoin="round"/><ellipse cx="40" cy="48" rx="5" ry="7" fill="#1e1b4b"/><ellipse cx="60" cy="48" rx="5" ry="7" fill="#1e1b4b"/><ellipse cx="50" cy="62" rx="5" ry="4" fill="#f472b6"/></g>`},
  {id:'butterfly',name:'Butterfly',m:'off',anim:1,svg:_g('#f0abfc','#9328ff')+`<g transform="translate(50 50)"><g>${_at('scale','1 1;.25 1;1 1','.7')}<path d="M0 0C-10-26-40-34-42-14S-22 4 0 0zM0 0C-8 10-30 30-36 18S-18 0 0 0z" fill="url(#g)" stroke="#fff" stroke-width="3" stroke-linejoin="round"/><path d="M0 0C10-26 40-34 42-14S22 4 0 0zM0 0C8 10 30 30 36 18S18 0 0 0z" fill="url(#g)" stroke="#fff" stroke-width="3" stroke-linejoin="round"/></g><rect x="-3.5" y="-20" width="7" height="40" rx="3.5" fill="#1e1b4b" stroke="#fff" stroke-width="2"/></g>`},
  {id:'heartbeat',name:'Heartbeat',m:'off',anim:1,svg:_g('#ff8cc6','#e11d48',1)+`<g transform="translate(50 52)"><g>${_at('scale','1;1.16;1;1.1;1','1')}<path d="M0 34S-38 11-38-15a19 19 0 0 1 38-6 19 19 0 0 1 38 6c0 26-38 49-38 49z" fill="url(#g)" stroke="#fff" stroke-width="4" stroke-linejoin="round"/></g></g>`},
  {id:'boombox',name:'Boombox',m:'pulse',anim:1,svg:`<rect x="6" y="28" width="88" height="58" rx="12" fill="#1f1b2e" stroke="#fff" stroke-width="3.5"/><path d="M28 28V16h44v12" fill="none" stroke="#fff" stroke-width="4" stroke-linecap="round"/><rect x="38" y="36" width="24" height="10" rx="3" fill="#22d3ee"/><circle cx="27" cy="62" r="15" fill="#9328ff" stroke="#fff" stroke-width="3"/><circle cx="73" cy="62" r="15" fill="#ff2d78" stroke="#fff" stroke-width="3"/><circle cx="27" cy="62" r="7" fill="#111">${_an('r','6;9;6','.5')}</circle><circle cx="73" cy="62" r="7" fill="#111">${_an('r','6;9;6','.5',' begin="-.25s"')}</circle>`},
  {id:'wave',name:'Sound wave',m:'off',anim:1,svg:[10,23,36,50,64,77,90].map((x,i)=>{ const c=['#22d3ee','#60a5fa','#9328ff','#ff2d78','#9328ff','#60a5fa','#22d3ee'][i]; const a=[8,18,28,36,28,18,8][i]; return `<line x1="${x}" x2="${x}" y1="${50-a}" y2="${50+a}" stroke="${c}" stroke-width="8" stroke-linecap="round">${_an('y1',`${50-a};${50-a*.3};${50-a}`,'.9',` begin="-${i*.13}s"`)}${_an('y2',`${50+a};${50+a*.3};${50+a}`,'.9',` begin="-${i*.13}s"`)}</line>`; }).join('')},
  {id:'moon',name:'Moon',m:'off',anim:1,svg:_g('#fef9c3','#facc15',1)+`<path d="M62 12a38 38 0 1 0 26 54A30 30 0 0 1 62 12z" fill="url(#g)" stroke="#fff" stroke-width="3.5" stroke-linejoin="round"/><g transform="translate(78 24) scale(.55)"><path d="${_star4}" fill="#fff">${_at('scale','1;.3;1','1.6')}</path></g>`},
  {id:'planet',name:'Planet',m:'swing',svg:_g('#fdba74','#c026d3')+'<circle cx="50" cy="50" r="26" fill="url(#g)" stroke="#fff" stroke-width="3.5"/><ellipse cx="50" cy="52" rx="46" ry="12" fill="none" stroke="#fff" stroke-width="4" transform="rotate(-18 50 52)"/><ellipse cx="50" cy="52" rx="46" ry="12" fill="none" stroke="#22d3ee" stroke-width="2" transform="rotate(-18 50 52)"/>'},
  {id:'rainbow',name:'Rainbow',m:'bounce',svg:'<path d="M8 76a42 42 0 0 1 84 0" fill="none" stroke="#ff2d78" stroke-width="9" stroke-linecap="round"/><path d="M19 76a31 31 0 0 1 62 0" fill="none" stroke="#f59e0b" stroke-width="9" stroke-linecap="round"/><path d="M30 76a20 20 0 0 1 40 0" fill="none" stroke="#34d399" stroke-width="9" stroke-linecap="round"/><path d="M41 76a9 9 0 0 1 18 0" fill="none" stroke="#60a5fa" stroke-width="9" stroke-linecap="round"/><circle cx="14" cy="80" r="10" fill="#fff"/><circle cx="86" cy="80" r="10" fill="#fff"/>'},
  {id:'lips',name:'Kiss',m:'pulse',svg:'<path d="M8 50c10-14 24-22 34-14 4-4 12-4 16 0 10-8 24 0 34 14-10 20-26 30-42 30S18 70 8 50z" fill="#e11d48" stroke="#fff" stroke-width="4" stroke-linejoin="round"/><path d="M10 50c16 6 30 8 40 4 10 4 24 2 40-4" fill="none" stroke="#7f1d1d" stroke-width="3" stroke-linecap="round"/><ellipse cx="36" cy="42" rx="6" ry="3" fill="#fff" opacity=".6"/>'},
  {id:'peace',name:'Peace',m:'spin',svg:'<circle cx="50" cy="50" r="40" fill="#34d399" stroke="#fff" stroke-width="5"/><path d="M50 12v76M50 50L23 77M50 50l27 27" stroke="#fff" stroke-width="7" stroke-linecap="round" fill="none"/>'}
);
function mkPackHtml(){ const btn=p=>`<button data-act="mk-add-pack" data-val="${p.id}" data-testid="mk-pack-${p.id}" aria-label="Add ${esc(p.name)}" title="${esc(p.name)}"><img src="${mkPackSrc(p.id)}" alt=""></button>`;
  return `<div class="mk-field"><p class="mk-lbl">Animated stickers <span class="mk-new-tag">Live</span></p><div class="mk-pack-grid" data-testid="mk-pack-grid-anim">${MK_PACK.filter(p=>p.anim).map(btn).join('')}</div></div><div class="mk-field"><p class="mk-lbl">Treesh sticker pack</p><div class="mk-pack-grid" data-testid="mk-pack-grid">${MK_PACK.filter(p=>!p.anim).map(btn).join('')}</div></div>`; }
function mkMotionNewHtml(){ const v=state.mkMotionNew||'auto'; return `<div class="mk-field"><p class="mk-lbl">Move to the beat</p>${mkSeg('mk-motion-new',v,[['auto','Auto']].concat(MK_MOTIONS),'mk-motion-new').replace('class="mk-seg"','class="mk-seg mk-seg-wrap mk-seg-motion"')}<p class="mk-hint">New stickers react to the real beat of whatever is playing.</p></div>`; }
function mkVizColor(mode,i,n){ if(mode==='white') return 'rgba(255,255,255,.92)'; if(mode==='rainbow') return `hsl(${Math.round(i/n*300+(performance.now()/40))%360} 90% 62%)`; return _mkVizAcc; }
let _mkVizAcc='#9328ff', _mkVizAccT=0;
function mkVizDraw(list,now,bins,playing,e){ if(now-_mkVizAccT>800){ _mkVizAccT=now; _mkVizAcc=(getComputedStyle(document.documentElement).getPropertyValue('--treesh-purple')||'#9328ff').trim()||'#9328ff'; }
  list.forEach(cv=>{ const dpr=Math.min(2,window.devicePixelRatio||1); const W=Math.round(cv.clientWidth*dpr), H=Math.round(cv.clientHeight*dpr); if(!W||!H) return; if(cv.width!==W||cv.height!==H){ cv.width=W; cv.height=H; }
    const ctx=cv.getContext('2d'); const N=cv.dataset.mkViz==='wave'?48:32; const mode=cv.dataset.vizColor||'accent'; const v=cv._v||(cv._v=new Float32Array(N));
    for(let i=0;i<N;i++){ let t; if(bins){ const k=Math.floor(Math.pow(i/N,1.6)*Math.min(bins.length,96)); t=bins[k]/255; } else t=playing?(0.25+0.75*Math.abs(Math.sin(now/1000*(1.2+i*.11)+i*1.9)))*(0.45+e*0.55):0.04+0.03*Math.sin(now/900+i*.5); v[i]+=(t-v[i])*(t>v[i]?.45:.12); }
    ctx.clearRect(0,0,W,H); const st=cv.dataset.mkViz;
    if(st==='wave'){ ctx.lineWidth=3*dpr; ctx.lineJoin='round'; ctx.lineCap='round'; for(let pass=0;pass<2;pass++){ ctx.beginPath(); for(let i=0;i<N;i++){ const x=i/(N-1)*W; const y=H/2+(pass?-1:1)*v[i]*H*.42*Math.sin(i/(N-1)*Math.PI); if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y); } const g=ctx.createLinearGradient(0,0,W,0); g.addColorStop(0,mkVizColor(mode,0,N)); g.addColorStop(.5,mode==='accent'?'#ff2d78':mkVizColor(mode,N/2,N)); g.addColorStop(1,mkVizColor(mode,N,N)); ctx.strokeStyle=g; ctx.globalAlpha=pass?.55:1; ctx.stroke(); } ctx.globalAlpha=1; }
    else if(st==='orb'){ const cx=W/2, cy=H/2, R=Math.min(W,H)*.2*(1+e*.25); ctx.save(); ctx.translate(cx,cy); for(let i=0;i<N;i++){ const a=i/N*Math.PI*2; const L=R*.25+v[i]*Math.min(W,H)*.28; ctx.strokeStyle=mkVizColor(mode,i,N); ctx.lineWidth=Math.max(2,R*.12); ctx.lineCap='round'; ctx.beginPath(); ctx.moveTo(Math.cos(a)*R*1.08,Math.sin(a)*R*1.08); ctx.lineTo(Math.cos(a)*(R*1.08+L),Math.sin(a)*(R*1.08+L)); ctx.stroke(); } const g=ctx.createRadialGradient(0,0,R*.1,0,0,R); g.addColorStop(0,'rgba(255,255,255,.95)'); g.addColorStop(1,mkVizColor(mode,0,N)); ctx.fillStyle=g; ctx.beginPath(); ctx.arc(0,0,R,0,Math.PI*2); ctx.fill(); ctx.restore(); }
    else { const gap=W/N*.28, bw=W/N-gap; for(let i=0;i<N;i++){ const h=Math.max(4*dpr,v[i]*H*.96); const x=i*(bw+gap)+gap/2; ctx.fillStyle=mkVizColor(mode,i,N); const r=Math.min(bw/2,8*dpr); ctx.beginPath(); if(ctx.roundRect) ctx.roundRect(x,H-h,bw,h,[r,r,2,2]); else ctx.rect(x,H-h,bw,h); ctx.fill(); } } }); }
function mkReactLoop(){ if(_mkRAF||state.perfMode||!document.querySelector('.mk-react,.mk-glow-beat,[data-mk-viz]')) return;
  const tick=now=>{ const list=document.querySelectorAll('.mk-react'), pages=document.querySelectorAll('.mk-glow-beat'), viz=document.querySelectorAll('[data-mk-viz]');
    if((!list.length&&!pages.length&&!viz.length)||state.perfMode){ _mkRAF=null; return; }
    const dt=Math.min(0.05,Math.max(0,(now-(_bt.t||now))/1000)); _bt.t=now; let lvl=0, hit=false, real=false; const playing=!!state.isPlaying;
    if(playing){ if(!_vizAnalyser&&!_bt.tried){ _bt.tried=true; try{ if(ensureVizAudio()) vizResume(); }catch(_){} }
      if(_vizAnalyser&&_vizBytes){ try{ _vizAnalyser.getByteFrequencyData(_vizBytes); let s=0; for(let i=1;i<7;i++) s+=_vizBytes[i]; lvl=s/6/255; real=true; }catch(_){} }
      _bt.zero=(real&&lvl===0)?_bt.zero+dt:0;
      if(!real||_bt.zero>2){ real=false; const ph=(now/500)%1; lvl=Math.pow(1-ph,3)*0.85; }
      _bt.avg=_bt.avg*0.94+lvl*0.06; if(lvl>_bt.avg*1.2+0.04&&lvl>0.2&&now-_bt.last>230){ hit=true; _bt.last=now; } }
    _bt.env=hit?1:_bt.env*Math.pow(0.015,dt); const e=Math.max(_bt.env,playing?lvl*0.5:0);
    _bt.spin=(_bt.spin+dt*(playing?(36+lvl*320+_bt.env*260):0))%360; const T=now/1000;
    const vars=[['--beat',(1+e*0.26).toFixed(3)],['--bounce',(e*24).toFixed(1)+'px'],['--wig',(playing?Math.sin(T*13)*(2+e*16):0).toFixed(1)+'deg'],['--spin',_bt.spin.toFixed(1)+'deg'],['--e',e.toFixed(3)],['--flt',(Math.sin(T*2.1)*(5+e*12)).toFixed(1)+'px'],['--sh',(playing?Math.sin(T*44)*e*7:0).toFixed(1)+'px'],['--swg',(Math.sin(T*(playing?3.2:1.6))*(playing?8+e*16:5)).toFixed(1)+'deg']];
    list.forEach(el=>{ const st=el.style; vars.forEach(v=>st.setProperty(v[0],v[1])); });
    pages.forEach(el=>el.style.setProperty('--e',vars[4][1]));
    if(viz.length) mkVizDraw(viz,now,real?_vizBytes:null,playing,e);
    _mkRAF=requestAnimationFrame(tick); };
  _mkRAF=requestAnimationFrame(tick); }

/* ---------- P8: Magic Markup actions + inputs ---------- */
function mkAct8(act,t){ const val=t.dataset.val, id=t.dataset.id;
  switch(act){
    case 'mk-look': mkApplyLook(val); break;
    case 'mk-bg': if(val==='photo'){ const f=document.getElementById('mk-bg-file'); if(f) f.click(); } else mkThSet(val==='color'?{bg:'color',color:(mkTheme(mkCurPage())||{}).color||'#2a0f4d'}:{bg:val==='none'?'':val,dim:''}); break;
    case 'mk-bg-edit': { const T=mkTheme(mkCurPage())||{}; const src=T.photo&&_mkImgs[String(T.photo).slice(4)]; if(src) mkBgStudio(src,false,'Edit background'); break; }
    case 'mk-th-accent': mkThSet({accent:val}); break;
    case 'mk-th-font': mkThSet({font:val}); break;
    case 'mk-th-surf': mkThSet({surf:val==='default'?'':val}); break;
    case 'mk-th-glow': mkThSet({glow:val==='off'?'':val}); break;
    case 'mk-th-reset': { const page=mkCurPage(); if(!page) break; delete mkPage(page).theme; assetDel('mk_bg_'+page).catch(()=>{}); delete _mkImgs['mk_bg_'+page]; mkSave(); renderView(); mkRenderSheet(); toast('Theme reset',MK_PAGE_LABEL[page]+' is back to the app look'); break; }
    case 'mk-snap': { const m=mkS(); m.snap=!m.snap; mkSave(); renderView(); mkRenderSheet(); toast(m.snap?'Snap to grid on':'Snap to grid off'); break; }
    case 'mk-ly-sel': { mkSelect(id); const el=mkBlockEl(id); if(el) el.scrollIntoView({behavior:'smooth',block:'center'}); break; }
    case 'mk-ly-move': state.mkSel=id; mkMove(val); break;
    case 'mk-ly-hide': mkHideToggle(id); mkRenderSheet(); break;
    case 'mk-ly-st': { const f=mkFind(id); if(!f) break; state.mkStSel=id; state.mkSheet='sticker-edit'; renderView(); mkRenderSheet(); const el=document.querySelector('#view [data-mk-st="'+id+'"]'); if(el) el.scrollIntoView({behavior:'smooth',block:'center'}); break; }
    case 'mk-ly-st-lock': { const f=mkFind(id); if(!f) break; f.s.locked=!f.s.locked; if(!f.s.locked) delete f.s.locked; mkSave(); renderView(); mkRenderSheet(); toast(f.s.locked?'Sticker locked':'Sticker unlocked'); break; }
    case 'mk-st-lock': { const f=mkFind(state.mkStSel); if(!f) break; const on=!f.s.locked; if(on) f.s.locked=true; else delete f.s.locked; mkSave(); renderView(); mkRenderSheet(); toast(on?'Locked in place':'Unlocked','You can drag it again'); break; }
    case 'mk-st-pin': { const f=mkFind(state.mkStSel); if(!f) break; const s=f.s; const el=document.querySelector('#view [data-mk-st="'+s.id+'"]'); if(val==='page'){ if(el&&s.cv) mkStToPage(s,el); s.free=true; } else { delete s.free; if(el) mkStReparent(s,el); } mkSave(); renderView(); mkRenderSheet(); toast(val==='page'?'Floating on the page':'Locked to its section'); break; }
    case 'mk-wcfg': { const w=mkCurWidget(state.mkSel); if(!w) break; w[t.dataset.key]=val; mkSave(); mkWRefreshId(w.id); mkRenderSheet(); break; }
    case 'mk-quote-next': { const w=mkCurWidget(id); if(!w) break; w.qi=((+w.qi||0)+1)%MK_QUOTES.length; mkSave(); mkWRefreshId(id); break; }
  } }
document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act]'); if(!t) return; const a=t.dataset.act; if(a&&a.indexOf('mk-')===0) mkAct8(a,t); });
document.addEventListener('input',e=>{ const el=e.target; if(!el||!el.dataset) return;
  if(el.dataset.mkWcfg){ const w=mkCurWidget(state.mkSel); if(!w) return; w[el.dataset.mkWcfg]=el.value.slice(0,el.dataset.mkWcfg==='text'?280:60); mkSaveSoon(); mkWRefreshId(w.id); return; }
  const k=el.dataset.mkTh; if(!k) return; const page=mkCurPage(); if(!page) return; const P=mkPage(page); const T=P.theme||(P.theme={}); try{ if(el.type==='range') fillSlider(el); }catch(_){}
  if(k==='dim'){ T.dim=+el.value; const d=document.querySelector('#mk-pbg .mk-pbg-dim'); if(d) d.style.opacity=T.dim/100; const v=document.getElementById('mk-th-dim-val'); if(v) v.textContent=T.dim+'%'; }
  else if(k==='blur'){ T.blur=+el.value; const b=document.querySelector('#mk-pbg .mk-pbg-base'); if(b){ b.style.filter=T.blur?'blur('+T.blur+'px)':''; b.style.inset=T.blur?(-T.blur*2)+'px':''; } const v=document.getElementById('mk-th-blur-val'); if(v) v.textContent=T.blur+'px'; }
  else if(k==='color'){ T.color=el.value; T.bg='color'; const b=document.querySelector('#mk-pbg .mk-pbg-base'); if(b) b.style.background=el.value; const l=el.closest('label'); if(l) l.style.background=el.value; }
  else if(k==='accent'){ T.accent=el.value; _mkAccNow=el.value; try{ applyAccent(el.value); }catch(_){} const l=el.closest('label'); if(l) l.style.background=el.value; }
  mkSaveSoon(); });
document.addEventListener('change',e=>{ const t=e.target; if(!t) return;
  if(t.id==='mk-bg-file'){ const f=t.files&&t.files[0]; t.value=''; if(!f) return; if(!/^image\//.test(f.type||'')&&!/\.(heic|heif)$/i.test(f.name||'')){ toast('Pick an image file'); return; } if(f.size>25*1024*1024){ toast('Image too large','Use one under 25 MB'); return; } mkBgStudio(URL.createObjectURL(f),true); return; }
  if(t.dataset&&(t.dataset.mkTh==='color'||t.dataset.mkTh==='accent'||t.dataset.mkTh==='blur')){ mkSave(); _mkBgKey=''; renderView(); mkRenderSheet(); }
  if(t.dataset&&t.dataset.mkWcfg==='at'){ mkSave(); mkRenderSheet(); } });
function p8MkInit(){ try{ loadGoogleFont('Caveat:wght@500;700'); }catch(e){}
  const pages=mkS().pages; const keys=Object.keys(pages).filter(k=>pages[k]&&pages[k].theme&&pages[k].theme.photo).map(k=>String(pages[k].theme.photo).slice(4));
  if(keys.length) Promise.all(keys.map(k=>assetGet(k).then(v=>{ if(v) _mkImgs[k]=v; }).catch(()=>{}))).then(()=>{ _mkBgKey=''; mkThemeApply(true); });
  setInterval(mkCdTick,1000);
  try{ audio.addEventListener('timeupdate',mkLyricTick); ['play','pause','loadedmetadata','emptied'].forEach(ev=>audio.addEventListener(ev,()=>setTimeout(mkSongChanged,0))); }catch(e){} }
