/* ---------- P8: Music Manager, full-screen glass studio ---------- */
const UM_SORTS=[['new','Newest'],['old','Oldest'],['title','Title A\u2013Z'],['artist','Artist'],['long','Longest'],['plays','Most played']];
const UM_FILTERS=[['all','All'],['nolyrics','Needs lyrics'],['unsynced','Not synced'],['synced','Synced'],['explicit','Explicit']];
function umS(){ if(!state.um){ const v=LS.get('treesh_um',null)||{}; state.um={view:v.view==='list'?'list':'grid',sort:v.sort||'new',filter:'all',q:''}; } return state.um; }
function umSave(){ const u=umS(); LS.set('treesh_um',{view:u.view,sort:u.sort}); }
function umLy(s){ const ly=(s.lyrics||[]).filter(l=>l&&l.text&&l.text.trim()); return {n:ly.length,synced:ly.some(l=>l.t!=null)}; }
function umList(){ const u=umS(), pc=state.playCounts||{}, q=u.q.trim().toLowerCase(); let list=USER_SONGS.map((s,i)=>({s,i}));
  if(q) list=list.filter(({s})=>[s.title,s.artist,s.album,s.genre,s.mood].some(v=>String(v||'').toLowerCase().includes(q)));
  if(u.filter!=='all') list=list.filter(({s})=>{ const L=umLy(s); return u.filter==='nolyrics'?!L.n:u.filter==='unsynced'?(L.n&&!L.synced):u.filter==='synced'?L.synced:!!s.explicit; });
  const by={old:(a,b)=>a.i-b.i,title:(a,b)=>a.s.title.localeCompare(b.s.title),artist:(a,b)=>String(a.s.artist||'').localeCompare(String(b.s.artist||''))||a.s.title.localeCompare(b.s.title),long:(a,b)=>(+b.s.duration||0)-(+a.s.duration||0),plays:(a,b)=>(pc[b.s.id]||0)-(pc[a.s.id]||0)||b.i-a.i}[u.sort]||((a,b)=>b.i-a.i);
  return list.sort(by).map(x=>x.s); }
function umStats(){ let dur=0, ly=0, syn=0, plays=0; const pc=state.playCounts||{}; USER_SONGS.forEach(s=>{ dur+=+s.duration||0; const L=umLy(s); if(L.n) ly++; if(L.synced) syn++; plays+=pc[s.id]||0; }); return {n:USER_SONGS.length,dur,ly,syn,plays}; }
function umDur(sec){ sec=Math.round(sec||0); const h=Math.floor(sec/3600), m=Math.floor(sec%3600/60); return h?h+'h '+m+'m':m+'m'; }
function umHeaderHtml(){ const S=umStats(); const cov=USER_SONGS.slice(-3).reverse();
  return `<header class="um-head" data-testid="um-head"><div class="um-head-glow" aria-hidden="true">${cov[0]?img(cov[0].coverArt,'h-full w-full object-cover'):''}</div>
   <div class="um-head-top"><button type="button" data-act="um-studio-close" data-testid="um-close" aria-label="Close Music Manager" class="te-x press"><i data-lucide="x"></i></button><div class="min-w-0 flex-1"><p class="st-eyebrow">Custom Music</p><h2 class="um-title" data-testid="um-title">Your Music Studio</h2></div><button type="button" data-act="add-music-open" data-testid="um-add" class="te-save press"><i data-lucide="plus"></i><span>Add tracks</span></button></div>
   <div class="um-hero"><div class="um-stack" aria-hidden="true">${cov.length?cov.map((s,i)=>`<span style="--i:${i}">${img(s.coverArt,'h-full w-full object-cover')}</span>`).join(''):'<span style="--i:0" class="is-empty"><i data-lucide="disc-3"></i></span>'}</div>
    <div class="um-stats" data-testid="um-stats">${[['music-2','Tracks',S.n,'tracks'],['clock','Total time',umDur(S.dur),'time'],['quote','With lyrics',S.ly,'lyrics'],['timer','Synced',S.syn,'synced'],['flame','Plays',fmtNum(S.plays),'plays']].map(([ic,l,v,k])=>`<div class="um-stat" data-testid="um-stat-${k}"><i data-lucide="${ic}"></i><b>${v}</b><span>${l}</span></div>`).join('')}</div></div>
   ${S.n?`<div class="um-head-acts"><button type="button" data-act="um-play-all" data-testid="um-play-all" class="um-pill is-primary press"><i data-lucide="play"></i>Play all</button><button type="button" data-act="um-shuffle" data-testid="um-shuffle" class="um-pill press"><i data-lucide="shuffle"></i>Shuffle</button>${S.n-S.ly>0?`<button type="button" data-act="um-filter" data-val="nolyrics" data-testid="um-need-lyrics" class="um-pill press"><i data-lucide="circle-alert"></i>${S.n-S.ly} need lyrics</button>`:''}</div>`:''}</header>`; }
function umToolsHtml(){ const u=umS();
  return `<div class="um-tools" data-testid="um-tools"><label class="um-search"><i data-lucide="search"></i><input id="um-q" type="search" data-testid="um-search" value="${esc(u.q)}" placeholder="Search your tracks" autocomplete="off" enterkeyhint="search"></label><div class="um-tools-r"><select id="um-sort" data-testid="um-sort" aria-label="Sort tracks">${UM_SORTS.map(([v,l])=>`<option value="${v}" ${u.sort===v?'selected':''}>${l}</option>`).join('')}</select><div class="um-vsw" role="group" aria-label="Layout"><button type="button" data-act="um-view" data-val="grid" data-testid="um-view-grid" aria-pressed="${u.view==='grid'}" class="${u.view==='grid'?'on':''}" aria-label="Grid"><i data-lucide="layout-grid"></i></button><button type="button" data-act="um-view" data-val="list" data-testid="um-view-list" aria-pressed="${u.view==='list'}" class="${u.view==='list'?'on':''}" aria-label="List"><i data-lucide="list"></i></button></div></div></div>
   <div class="um-filters no-scrollbar" data-testid="um-filters">${UM_FILTERS.map(([v,l])=>`<button type="button" data-act="um-filter" data-val="${v}" data-testid="um-filter-${v}" aria-pressed="${u.filter===v}" class="um-fchip${u.filter===v?' on':''}">${l}</button>`).join('')}</div>`; }
function umBadge(s){ const L=umLy(s); return L.synced?'<span class="um-b ok"><i data-lucide="timer"></i>Synced</span>':L.n?'<span class="um-b"><i data-lucide="quote"></i>Lyrics</span>':'<span class="um-b warn"><i data-lucide="circle-plus"></i>No lyrics</span>'; }
function umBodyHtml(){ const u=umS();
  if(!USER_SONGS.length) return `<div class="um-empty" data-testid="manage-empty"><span class="um-empty-ic"><i data-lucide="disc-3"></i></span><h3>Your studio is empty</h3><p>Upload songs from your device. They stay saved right here, even offline.</p><button type="button" data-act="add-music-open" data-testid="um-empty-add" class="te-save press"><i data-lucide="upload"></i>Upload your first track</button></div>`;
  const list=umList(); if(!list.length) return `<div class="um-empty is-sm" data-testid="um-no-results"><span class="um-empty-ic"><i data-lucide="search-x"></i></span><h3>No tracks match</h3><p>Try a different search or filter.</p></div>`;
  const cur=curSong(), pc=state.playCounts||{}; const now=s=>cur&&cur.id===s.id; const pIc=s=>now(s)&&state.isPlaying?'audio-lines':'play';
  const count=`<p class="um-count" data-testid="um-count">${list.length} of ${USER_SONGS.length} track${USER_SONGS.length!==1?'s':''}</p>`;
  if(u.view==='list') return count+`<div class="um-list um-list-x" data-testid="manage-list">${list.map((s,i)=>{ const d=+s.duration||0; return `<div class="um-row${now(s)?' is-now':''}" style="--d:${Math.min(i,14)*25}ms" data-testid="upload-row-${s.id}"><button type="button" data-act="upload-play" data-id="${s.id}" data-testid="upload-play-${s.id}" aria-label="Play ${esc(s.title)}" class="um-art press">${img(s.coverArt,'h-full w-full object-cover')}<span class="um-play"><i data-lucide="${pIc(s)}"></i></span></button><div class="um-txt"><p class="um-t" data-testid="upload-title-${s.id}">${esc(s.title)}</p><p class="um-a">${esc(s.artist||'You')}${s.album?' \u00b7 '+esc(s.album):''}</p><div class="um-tags">${umBadge(s)}${s.genre?`<span class="um-b">${esc(s.genre)}</span>`:''}${d?`<span class="um-b">${fmt(d)}</span>`:''}${s.explicit?'<span class="um-b">E</span>':''}</div></div>${pc[s.id]?`<span class="um-plays"><i data-lucide="flame"></i>${fmtNum(pc[s.id])}</span>`:''}<button type="button" data-act="um-menu" data-id="${s.id}" data-testid="upload-menu-${s.id}" aria-label="Options for ${esc(s.title)}" class="um-more press"><i data-lucide="ellipsis"></i></button></div>`; }).join('')}</div>`;
  return count+`<div class="um-grid" data-testid="manage-grid">${list.map((s,i)=>{ const d=+s.duration||0; return `<article class="um-card${now(s)?' is-now':''}" style="--d:${Math.min(i,16)*28}ms" data-testid="upload-card-${s.id}"><div class="um-card-art"><button type="button" data-act="upload-play" data-id="${s.id}" data-testid="upload-play-${s.id}" aria-label="Play ${esc(s.title)}" class="um-card-cov press">${img(s.coverArt,'h-full w-full object-cover')}<span class="um-card-play"><i data-lucide="${pIc(s)}"></i></span></button><div class="um-card-badges">${umBadge(s)}${s.explicit?'<span class="um-b">E</span>':''}</div><button type="button" data-act="um-menu" data-id="${s.id}" data-testid="upload-menu-${s.id}" aria-label="Options for ${esc(s.title)}" class="um-card-more press"><i data-lucide="ellipsis"></i></button></div><button type="button" data-act="edit-upload" data-id="${s.id}" data-testid="upload-edit-${s.id}" class="um-card-txt"><p class="um-t" data-testid="upload-title-${s.id}">${esc(s.title)}</p><p class="um-a">${esc(s.artist||'You')}</p><p class="um-meta">${[d?fmt(d):'',s.genre||'',pc[s.id]?fmtNum(pc[s.id])+' plays':''].filter(Boolean).map(esc).join(' \u00b7 ')||'&nbsp;'}</p></button></article>`; }).join('')}</div>`; }
function openMusicManager(){ umS(); state.umOpen=true; let r=document.getElementById('um-root'); if(!r){ r=document.createElement('div'); r.id='um-root'; document.body.appendChild(r); }
  r.innerHTML=`<div class="um-bd" data-testid="music-manager"><div class="um-panel dark-surface" role="dialog" aria-label="Music Manager"><span class="pm-grab" aria-hidden="true"></span><div class="um-scroll soft-scroll" id="um-scroll">${umHeaderHtml()}<div class="um-sticky" id="um-tools-wrap">${umToolsHtml()}</div><div id="um-body" class="um-body">${umBodyHtml()}</div></div></div></div>`;
  icons(); syncScrollLock(); try{ pmEnhance(); }catch(e){} }
function closeMusicManager(fast){ if(!state.umOpen) return; state.umOpen=false; const r=document.getElementById('um-root'); const bd=r&&r.querySelector('.um-bd'); if(!bd||fast){ if(r) r.innerHTML=''; syncScrollLock(); return; } bd.classList.add('is-out'); setTimeout(()=>{ if(!state.umOpen&&r) r.innerHTML=''; syncScrollLock(); },220); }
function umRenderBody(){ const b=document.getElementById('um-body'); if(b){ b.innerHTML=umBodyHtml(); icons(); } }
function umRenderTools(){ const w=document.getElementById('um-tools-wrap'); if(!w) return; const q=document.getElementById('um-q'); const f=q&&document.activeElement===q; w.innerHTML=umToolsHtml(); icons(); try{ pmEnhance(); }catch(e){} if(f){ const n=document.getElementById('um-q'); if(n){ n.focus(); n.selectionStart=n.selectionEnd=n.value.length; } } }
function umRefresh(){ if(!state.umOpen) return; const h=document.querySelector('#um-root .um-head'); if(h){ h.outerHTML=umHeaderHtml(); } umRenderBody(); icons(); }
function umShuffleList(a){ a=a.slice(); for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function umAct(act,t){ const val=t.dataset.val;
  switch(act){
    case 'um-studio-close': closeMusicManager(); return true;
    case 'um-view': { const u=umS(); u.view=val==='list'?'list':'grid'; umSave(); umRenderTools(); umRenderBody(); return true; }
    case 'um-filter': { const u=umS(); u.filter=val; umRenderTools(); umRenderBody(); const sc=document.getElementById('um-scroll'), w=document.getElementById('um-tools-wrap'); if(sc&&w&&sc.scrollTop>w.offsetTop) sc.scrollTop=w.offsetTop; return true; }
    case 'um-play-all': case 'um-shuffle': { let list=umList(); if(!list.length) list=USER_SONGS.slice(); if(act==='um-shuffle') list=umShuffleList(list); if(list[0]){ playSong(list[0],list); toast(act==='um-shuffle'?'Shuffling your music':'Playing your music',list.length+' track'+(list.length!==1?'s':'')); } return true; }
  }
  return false; }
document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act]'); if(!t) return; if(t.dataset.act.indexOf('um-')===0) umAct(t.dataset.act,t); });
document.addEventListener('input',e=>{ if(e.target&&e.target.id==='um-q'){ umS().q=e.target.value; umRenderBody(); } });
document.addEventListener('change',e=>{ if(e.target&&e.target.id==='um-sort'){ umS().sort=e.target.value; umSave(); umRenderBody(); } });
document.addEventListener('keydown',e=>{ if(e.key!=='Escape'||!state.umOpen) return; const m=document.getElementById('modal'), m2=document.getElementById('modal2'); if((m&&m.childElementCount)||(m2&&m2.childElementCount)||state.lsOpen) return; closeMusicManager(); });
const _lus8=loadUserSongs;
loadUserSongs=async function(){ const r=await _lus8.apply(this,arguments); try{ umRefresh(); }catch(e){} return r; };

/* ---------- P8: profile photo + banner always go through Image Studio ---------- */
function pfBannerApply(d){ assetPut('profile_banner',d).then(()=>{ if(typeof pfStashDraft==='function') pfStashDraft(); state.profileBanner=d; pfRerender(); toast('Banner updated'); }).catch(()=>toast('Couldn\u2019t save banner','Your device storage may be full')); }
function pfAvatarEdit(){ const p=state.profile||{}; const src=state._tmpAvatar||p.avatar; if(!src){ const i=document.getElementById('set-avatar-input'); if(i) i.click(); return; }
  openCoverStudio(src,'Edit your profile photo',false,{aspect:1,round:true,out:[512,512],q:.86,applyLabel:'Use photo',onApply:d=>{ state._tmpAvatar=d; const av=document.getElementById('set-avatar'); if(av) av.innerHTML=img(d,'h-full w-full object-cover'); toast('Photo updated','Tap Save to keep it'); }}); }
function obAvatarEdit(){ if(!onboard.avatar) return; openCoverStudio(onboard.avatar,'Edit your profile photo',false,{aspect:1,round:true,out:[512,512],q:.86,applyLabel:'Use photo',onApply:d=>{ onboard.avatar=d; renderOnboarding(); }}); }
function p8Act(act,t){ switch(act){
  case 'pf-avatar-edit': pfAvatarEdit(); break;
  case 'pf-banner-edit': if(state.profileBanner) openCoverStudio(state.profileBanner,'Edit your banner',false,{aspect:3,out:[1500,500],q:.85,applyLabel:'Use as banner',onApply:pfBannerApply}); break;
  case 'ob-avatar-edit': obAvatarEdit(); break;
} }
document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act]'); if(t) p8Act(t.dataset.act,t); });

function p8Init(){ try{ p8MkInit(); }catch(e){ console.warn('p8 mk init',e); }
  try{ ['play','pause','emptied'].forEach(ev=>audio.addEventListener(ev,()=>{ if(state.umOpen) setTimeout(umRenderBody,0); })); }catch(e){}
  try{ if(typeof SETTINGS_INDEX!=='undefined'&&!window._p8Idx){ window._p8Idx=true; SETTINGS_INDEX.push(
    {id:'go-music-manager',label:'Music Manager',desc:'Browse, edit and sync your uploaded tracks',kw:'custom music manage uploads tracks my music edit delete studio library',ic:'disc-3',type:'action',go:()=>{ closeSearch(); setTimeout(openMusicManager,220); }},
    {id:'go-page-theme',label:'Page themes',desc:'Backgrounds, fonts, accent and glow for any page',kw:'theme background wallpaper page font glow myspace customize magic markup look',ic:'palette',type:'action',go:()=>{ closeSearch(); setTimeout(()=>{ mkStart(); setTimeout(()=>{ state.mkSheet='theme'; mkRenderSheet(); },120); },220); }},
    {id:'go-fun-widgets',label:'Countdown, notes & visualizer widgets',desc:'Add creative widgets to any page with Magic Markup',kw:'countdown timer sticky note quote visualizer lyric widget magic markup',ic:'hourglass',type:'action',go:()=>{ closeSearch(); setTimeout(()=>{ mkStart(); setTimeout(()=>{ state.mkSheet='add'; mkRenderSheet(); },120); },220); }}
  ); } }catch(e){} }
