/* ---------- P9: beat engine (live analyser, or an offline beat map so iPhone stays in sync) ---------- */
const _bm={}; let _bmBusy=false, _bmDBp=null;
function bmDB(){ if(_bmDBp) return _bmDBp; _bmDBp=new Promise((res,rej)=>{ try{ const r=indexedDB.open('treesh_beatmaps',1); r.onupgradeneeded=()=>{ r.result.createObjectStore('m'); }; r.onsuccess=()=>res(r.result); r.onerror=()=>rej(r.error); }catch(e){ rej(e); } }); return _bmDBp; }
function bmGet(k){ return bmDB().then(db=>new Promise(res=>{ try{ const q=db.transaction('m').objectStore('m').get(k); q.onsuccess=()=>res(q.result||null); q.onerror=()=>res(null); }catch(e){ res(null); } })).catch(()=>null); }
function bmPut(k,v){ return bmDB().then(db=>new Promise(res=>{ try{ const tx=db.transaction('m','readwrite'); tx.objectStore('m').put(v,k); tx.oncomplete=()=>res(true); tx.onerror=()=>res(false); }catch(e){ res(false); } })).catch(()=>false); }
function bmKey(s){ return s&&s.id?'v1:'+s.id:''; }
async function bmBuild(s){ const k=bmKey(s); if(!k||_bm[k]||_bmBusy) return; _bm[k]='pending'; _bmBusy=true;
  try{ const c=await bmGet(k); if(c&&c.low){ _bm[k]=c; return; }
    if(navigator.connection&&navigator.connection.saveData){ _bm[k]='skip'; return; }
    const r=await fetch(s.audioUrl); if(!r.ok) throw new Error('fetch'); const buf=await r.arrayBuffer();
    const OAC=window.OfflineAudioContext||window.webkitOfflineAudioContext; if(!OAC) throw new Error('oac');
    let ctx=null; for(const sr of [11025,22050,44100]){ try{ ctx=new OAC(1,sr,sr); break; }catch(e){} } if(!ctx) throw new Error('ctx');
    const ab=await new Promise((res,rej)=>{ try{ const p=ctx.decodeAudioData(buf,res,rej); if(p&&p.then) p.then(res,rej); }catch(e){ rej(e); } });
    const m=await bmAnalyse(ab); _bm[k]=m; bmPut(k,m);
  }catch(e){ _bm[k]='fail'; }
  finally{ _bmBusy=false; } }
async function bmAnalyse(ab){ const sr=ab.sampleRate, n=ab.length, d0=ab.getChannelData(0), d1=ab.numberOfChannels>1?ab.getChannelData(1):null;
  const hop=Math.max(64,Math.round(sr*0.04)), F=Math.ceil(n/hop); const lo=new Float32Array(F), mi=new Float32Array(F), hi=new Float32Array(F);
  const aL=1-Math.exp(-2*Math.PI*160/sr), aM=1-Math.exp(-2*Math.PI*1800/sr); let yL=0, yM=0;
  for(let f=0;f<F;f++){ let sL=0,sM=0,sH=0; const a=f*hop, e=Math.min(n,a+hop); for(let i=a;i<e;i++){ const x=d1?(d0[i]+d1[i])*0.5:d0[i]; yL+=aL*(x-yL); yM+=aM*(x-yM); const m=yM-yL, h=x-yM; sL+=yL*yL; sM+=m*m; sH+=h*h; } const c=Math.max(1,e-a); lo[f]=Math.sqrt(sL/c); mi[f]=Math.sqrt(sM/c); hi[f]=Math.sqrt(sH/c); if((f&1023)===1023) await new Promise(r=>setTimeout(r,0)); }
  const q=arr=>{ const s=Array.from(arr).sort((x,y)=>x-y); const p=s[Math.floor(s.length*0.97)]||1e-6; const o=new Uint8Array(arr.length); for(let i=0;i<arr.length;i++) o[i]=Math.min(255,Math.round(arr[i]/p*230)); return o; };
  return {hop:hop/sr, low:q(lo), mid:q(mi), high:q(hi)}; }
const _bmOut={low:0,mid:0,high:0}, _bmBins=new Uint8Array(96);
function bmAt(t){ const s=curSong(); const k=bmKey(s); const m=k&&_bm[k]; if(!m){ if(k&&s.audioUrl) bmBuild(s); return null; } if(typeof m!=='object') return null; const x=t/m.hop, i=Math.floor(x), f=x-i; if(i<0||i>=m.low.length-1) return null; const g=a=>(a[i]*(1-f)+a[i+1]*f)/255; _bmOut.low=g(m.low); _bmOut.mid=g(m.mid); _bmOut.high=g(m.high); return _bmOut; }
function bmBins(m,now){ for(let k=0;k<96;k++){ const f=k/95; const wl=Math.max(0,1-f/0.2), wm=Math.max(0,1-Math.abs(f-0.32)/0.3), wh=Math.max(0,(f-0.4)/0.6); const v=(m.low*wl+m.mid*wm+m.high*wh)/Math.max(0.6,wl+wm+wh)*(0.8+0.2*Math.sin(now*0.006+k*1.7)); _bmBins[k]=Math.max(0,Math.min(255,v*255)); } return _bmBins; }
function beatFrame(now){ if(_bt.fnow===now&&_bt.out) return _bt.out; _bt.fnow=now;
  const dt=Math.min(0.05,Math.max(0,(now-(_bt.t||now))/1000)); _bt.t=now; let lvl=0, hit=false, real=false, bins=null; const playing=!!state.isPlaying;
  if(playing){ if(!_vizAnalyser&&!_bt.tried){ _bt.tried=true; try{ if(ensureVizAudio()) vizResume(); }catch(_){} }
    if(_vizAnalyser&&_vizBytes){ try{ _vizAnalyser.getByteFrequencyData(_vizBytes); let s=0; for(let i=1;i<7;i++) s+=_vizBytes[i]; lvl=s/6/255; real=true; bins=_vizBytes; }catch(_){} }
    _bt.zero=(real&&lvl===0)?(_bt.zero||0)+dt:0; if(_bt.zero>2){ real=false; bins=null; lvl=0; }
    if(!real){ const m=bmAt(audio.currentTime||0); if(m){ lvl=Math.min(1,m.low*0.78+m.mid*0.3); real=true; bins=bmBins(m,now); } }
    if(!real){ const ph=(now/500)%1; lvl=Math.pow(1-ph,3)*0.85; }
    _bt.avg=_bt.avg*0.94+lvl*0.06; if(lvl>_bt.avg*1.2+0.04&&lvl>0.2&&now-_bt.last>230){ hit=true; _bt.last=now; } }
  _bt.env=hit?1:_bt.env*Math.pow(0.015,dt); const e=Math.max(_bt.env,playing?lvl*0.5:0);
  _bt.spin=(_bt.spin+dt*(playing?(36+lvl*320+_bt.env*260):0))%360;
  _bt.out={dt,lvl,e,real,bins,playing,hit}; return _bt.out; }
function mkAnimFree(){ document.querySelectorAll('svg[data-mk-anim]').forEach(sv=>{ try{ sv.unpauseAnimations(); }catch(_){} sv._mt=null; }); }
function mkReactLoop(){ mkLyLoop(); if(_mkRAF) return; if(state.perfMode){ mkAnimFree(); return; } if(!document.querySelector('.mk-react,.mk-glow-beat,[data-mk-viz],svg[data-mk-anim]')) return;
  const tick=now=>{ const list=document.querySelectorAll('.mk-react'), pages=document.querySelectorAll('.mk-glow-beat'), viz=document.querySelectorAll('[data-mk-viz]'), anim=document.querySelectorAll('svg[data-mk-anim]');
    if((!list.length&&!pages.length&&!viz.length&&!anim.length)||state.perfMode){ _mkRAF=null; if(state.perfMode) mkAnimFree(); return; }
    const b=beatFrame(now), e=b.e, playing=b.playing, T=now/1000;
    const vars=[['--beat',(1+e*0.26).toFixed(3)],['--bounce',(e*24).toFixed(1)+'px'],['--wig',(playing?Math.sin(T*13)*(2+e*16):0).toFixed(1)+'deg'],['--spin',_bt.spin.toFixed(1)+'deg'],['--e',e.toFixed(3)],['--flt',(Math.sin(T*2.1)*(5+e*12)).toFixed(1)+'px'],['--sh',(playing?Math.sin(T*44)*e*7:0).toFixed(1)+'px'],['--swg',(Math.sin(T*(playing?3.2:1.6))*(playing?8+e*16:5)).toFixed(1)+'deg']];
    list.forEach(el=>{ const st=el.style; vars.forEach(v=>st.setProperty(v[0],v[1])); });
    pages.forEach(el=>el.style.setProperty('--e',vars[4][1]));
    if(viz.length) mkVizDraw(viz,now,b.bins,playing,e);
    if(anim.length){ const rate=playing?(0.5+Math.min(1.7,e*1.9)):0.1; anim.forEach(sv=>{ if(sv._mt==null){ sv._mt=0; try{ sv.pauseAnimations(); }catch(_){} } sv._mt+=b.dt*rate; try{ sv.setCurrentTime(sv._mt); }catch(_){} }); }
    _mkRAF=requestAnimationFrame(tick); };
  _mkRAF=requestAnimationFrame(tick); }
function mkAnimPack(s){ if(!s||s.kind!=='img'||!s.pack) return null; const p=MK_PACK.find(x=>x.id===s.pack); return p&&p.anim?p:null; }
function mkAnimSvg(s){ const p=mkAnimPack(s); const u=String(s.id).replace(/[^a-zA-Z0-9_-]/g,''); const body=p.svg.replace(/id="([^"]+)"/g,'id="$1_'+u+'"').replace(/url\(#([^)]+)\)/g,'url(#$1_'+u+')'); return `<svg class="mk-st-svg" data-mk-anim viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${body}</svg>`; }

/* ---------- P9: Live Lyrics widget ---------- */
MK_WIDGETS.lyric.label='Live lyrics';
MK_FUN_PREV.lyric='<span class="mk-fun-ly2"><i>la la la</i><b>Sing along</b><i>oh oh</i></span>';
function mkLySz(w){ const v=w&&w.size; return (v==='sm'||v==='m')?'sm':(v==='lg'||v==='xl')?'lg':'md'; }
function mkLyLines(s){ return ((s&&s.lyrics)||[]).filter(l=>l&&l.text&&l.text.trim()&&!l.secOnly); }
function mkWLyric(w){ const s=curSong(), sz=mkLySz(w), L=mkLyLines(s), synced=L.some(l=>l.t!=null), pal=state.palette;
  const ctrl=s?`<div class="ly2-ctrl"><button type="button" data-act="prev" data-testid="mk-ly-prev" aria-label="Previous" class="press"><i data-lucide="skip-back" class="fill-current"></i></button><button type="button" data-act="toggle-play" data-testid="mk-ly-play" aria-label="Play or pause" class="ly2-pp press" data-ly-pp><i data-lucide="${state.isPlaying?'pause':'play'}" class="fill-current"></i></button><button type="button" data-act="next" data-testid="mk-ly-next" aria-label="Next" class="press"><i data-lucide="skip-forward" class="fill-current"></i></button></div>`:'';
  const lines=L.length?L.map((l,i)=>`<p class="ly2-l" data-i="${i}" data-testid="lyric-line-${i}">${esc(l.text).split(/(\s+)/).map(x=>/^\s*$/.test(x)?x:`<span class="w">${x}</span>`).join('')}</p>`).join(''):`<p class="ly2-l is-on ly2-empty" data-testid="lyric-current">${s?'No lyrics for this song yet':'Play a song to sing along'}</p>`;
  return `<section data-mk-widget="lyric" data-testid="mk-widget-lyric" data-mk-ly2 data-song="${s?esc(s.id):''}" data-synced="${synced}" class="mkw mkw-ly2 ly2-${sz} h-full" style="--ly-a:${rgb(pal&&pal[0],1)};--ly-b:${rgb(pal&&(pal[1]||pal[0]),1)}">${s&&s.coverArt?`<span class="ly2-bg" style="background-image:url('${esc(s.coverArt)}')" aria-hidden="true"></span>`:''}<span class="ly2-tint" aria-hidden="true"></span>
   <div class="ly2-in"><div class="ly2-head"><span class="ly2-cov">${s?img(s.coverArt,'h-full w-full object-cover'):'<i data-lucide="mic-vocal"></i>'}</span><div class="min-w-0 flex-1"><span class="ly2-k"><i data-lucide="mic-vocal"></i>${synced?'Live lyrics':'Lyrics'}<span class="ly2-live${state.isPlaying&&s?'':' hidden'}" data-ly-live></span></span><p class="ly2-song clamp-1">${s?esc(s.title)+' \u00b7 '+esc(s.artist):'Nothing playing'}</p></div>${ctrl}</div>
   <div class="ly2-win" ${s?'data-act="mini-open" role="button" aria-label="Open the player"':''} data-testid="lyric-open-player"><div class="ly2-track">${lines}</div></div></div></section>`; }
let _lyRAF=0, _mkLySid=null;
function mkLyLoop(){ if(_lyRAF) return; const tick=()=>{ const ws=document.querySelectorAll('[data-mk-ly2]'); if(!ws.length){ _lyRAF=0; return; } const s=curSong(), t=audio.currentTime||0; ws.forEach(w=>mkLyUpdate(w,s,t)); _lyRAF=requestAnimationFrame(tick); }; _lyRAF=requestAnimationFrame(tick); }
function mkLyUpdate(w,s,t){ if(!s||w.dataset.song!==s.id) return; const L=mkLyLines(s); if(!L.length) return; const synced=w.dataset.synced==='true'; let i=-1;
  if(synced){ for(let k=0;k<L.length;k++){ if(L[k].t!=null&&L[k].t<=t+0.15) i=k; else if(L[k].t!=null&&L[k].t>t+0.15) break; } } else { const d=state.duration||audio.duration||0; i=d?Math.min(L.length-1,Math.floor(t/d*L.length)):0; }
  const els=w._ly||(w._ly=[...w.querySelectorAll('.ly2-l')]); const win=w.querySelector('.ly2-win'), tr=w.querySelector('.ly2-track');
  if(w._i!==i||w._h!==(win&&win.clientHeight)){ w._h=win&&win.clientHeight; if(w._i!==i){ els.forEach((el,k)=>{ el.classList.toggle('is-past',k<i); el.classList.toggle('is-on',k===i); el.classList.toggle('is-next',k===i+1); if(k!==i) el.querySelectorAll('.w.on').forEach(x=>{ x.classList.remove('on'); x._on=false; }); }); w._i=i; w._ws=els[i]?[...els[i].querySelectorAll('.w')]:[]; }
    const cur=els[Math.max(0,i)]; if(cur&&win&&tr){ const y=cur.offsetTop-(win.clientHeight/2-cur.offsetHeight/2); tr.style.transform='translate3d(0,'+(-Math.max(0,Math.round(y)))+'px,0)'; } }
  if(synced&&i>=0&&w._ws&&w._ws.length){ const st=L[i].t, nt=(L[i+1]&&L[i+1].t!=null)?L[i+1].t:st+4; const dur=Math.max(0.6,Math.min(8,nt-st)*0.88); const p=Math.max(0,Math.min(1,(t-st)/dur)); const n=Math.ceil(p*w._ws.length); w._ws.forEach((x,k)=>{ const on=k<n; if(x._on!==on){ x._on=on; x.classList.toggle('on',on); } }); } }
function mkSongChanged(){ const s=curSong(), sid=s?s.id:''; if(sid!==_mkLySid){ _mkLySid=sid; mkRefreshType('lyric'); } else { document.querySelectorAll('#view [data-ly-pp]').forEach(b=>setIconIn(b,state.isPlaying?'pause':'play',16,true)); document.querySelectorAll('#view [data-ly-live]').forEach(x=>x.classList.toggle('hidden',!state.isPlaying)); icons(); }
  document.querySelectorAll('#view [data-viz-sub]').forEach(el=>{ el.textContent=s?s.title+' \u00b7 '+s.artist:'Play a song to see it move'; }); document.querySelectorAll('#view [data-viz-state]').forEach(el=>{ el.textContent=state.isPlaying?'\u25cf Live':'Paused'; }); mkReactLoop(); }

/* ---------- P9: Studio widgets (Instrum, LyricFlow, Image Studio) ---------- */
MK_FUN.push('instrum','lyricflow','imagestudio');
Object.assign(MK_WIDGETS,{ instrum:{label:'Instrum Studio',ic:'sliders-horizontal',from:'Studios',w:'half'}, lyricflow:{label:'LyricFlow',ic:'captions',from:'Studios',w:'half'}, imagestudio:{label:'Image Studio',ic:'wand-sparkles',from:'Studios',w:'half'} });
Object.assign(MK_FUN_PREV,{ instrum:'<span class="mk-fun-g16">'+'<i></i>'.repeat(8)+'</span>', lyricflow:'<span class="mk-fun-pen">Verse 1</span>', imagestudio:'<span class="mk-fun-sw"><i></i><i></i><i></i></span>' });
function swHead(ic,k,t,chip){ return `<div class="sw-head"><span class="sw-ic"><i data-lucide="${ic}"></i></span><div class="min-w-0 flex-1"><span class="sw-k">${k}</span><p class="sw-t">${t}</p></div>${chip?`<span class="sw-chip">${chip}</span>`:''}</div>`; }
function swAgo(ts){ if(!ts) return ''; const m=Math.round((Date.now()-ts)/60000); if(m<1) return 'just now'; if(m<60) return m+'m ago'; const h=Math.round(m/60); if(h<24) return h+'h ago'; const d=Math.round(h/24); return d<7?d+'d ago':new Date(ts).toLocaleDateString(undefined,{month:'short',day:'numeric'}); }
function swRow(act,id,tid,i,art,title,meta){ return `<button type="button" data-act="${act}" data-id="${esc(id)}" data-testid="${tid}" class="sw-rc press" style="--i:${i}">${art}<span class="sw-rc-t"><b class="clamp-1">${esc(title)}</b><small class="clamp-1">${esc(meta)}</small></span><i data-lucide="chevron-right" class="sw-rc-go"></i></button>`; }
function swList(label,rows){ return `<div class="sw-rlist"><p class="sw-lbl">${label}</p><div class="sw-recent">${rows.join('')}</div></div>`; }
function swRefresh(type){ const f={instrum:mkWInstrum,lyricflow:mkWLyricFlow,imagestudio:mkWImage}[type]; if(!f) return; document.querySelectorAll(`#view [data-mk-widget="${type}"]`).forEach(el=>{ const tmp=document.createElement('div'); tmp.innerHTML=f(); if(tmp.firstElementChild) el.replaceWith(tmp.firstElementChild); }); icons(); }
function mkWInstrum(){ const beats=state.beats||[], b=beats[0]; const tr=((b&&b.tracks)||[]).slice(0,b?2:4); const demo=['1000100010001000','0000100000001000','1010101010101011','0001001000010100'];
  const rows=tr.length?tr.map(t=>(t.steps||[]).slice(0,16).map(Boolean)):demo.map(r=>r.split('').map(c=>c==='1'));
  const bpm=(b&&b.bpm)||92, step=60/bpm/4;
  const grid=`<div class="sw-grid" style="--step:${step.toFixed(3)}s" aria-hidden="true">${rows.map(r=>`<div class="sw-row">${Array.from({length:16},(_,i)=>`<i class="${r[i]?'on':''}" style="--c:${i}"></i>`).join('')}</div>`).join('')}</div>`;
  const art=x=>`<span class="sw-rc-art sw-rc-beat" aria-hidden="true">${[0,1,2,3].map(k=>{ const st=(((x.tracks||[])[k]||{}).steps)||[]; const n=st.filter(Boolean).length; return `<i style="height:${Math.max(16,Math.min(100,Math.round(n/Math.max(1,st.length)*220)))}%"></i>`; }).join('')}</span>`;
  const list=b?swList('Recent beats',beats.slice(0,3).map((x,i)=>swRow('sw-beat-open',x.id,'mk-instrum-recent-'+i,i,art(x),x.name||'Untitled beat',`${x.bpm||92} BPM \u00b7 ${x.bars||1} bar${(x.bars||1)>1?'s':''} \u00b7 ${(x.tracks||[]).length} track${(x.tracks||[]).length!==1?'s':''}`))):`<p class="sw-sub clamp-1">Drums, 808s, leads and pads on a step grid</p>`;
  return `<section data-mk-widget="instrum" data-testid="mk-widget-instrum" class="mkw mkw-sw sw-instrum h-full"><span class="sw-glow" aria-hidden="true"></span><div class="sw-in">${swHead('sliders-horizontal','Beat studio','Instrum Studio',beats.length?beats.length+' beat'+(beats.length!==1?'s':''):'New')}${grid}${list}<div class="sw-acts"><button type="button" data-act="nav" data-view="instrum" data-testid="mk-instrum-open" class="sw-btn is-primary press"><i data-lucide="${b?'arrow-up-right':'play'}"></i>${b?'Open studio':'Make a beat'}</button></div></div></section>`; }
function mkWLyricFlow(){ const drafts=(state.lyricDrafts||[]).slice().sort((a,b)=>(b.updated||0)-(a.updated||0)), d=drafts[0]; const s=curSong(); const lineN=x=>(x.items||[]).filter(y=>y.type==='line'&&(y.text||'').trim()).length;
  const body=d?swList('Recent drafts',drafts.slice(0,3).map((x,i)=>{ const n=lineN(x); return swRow('ls-open-draft',x.id,'mk-lf-recent-'+i,i,`<span class="sw-rc-art sw-rc-paper" aria-hidden="true">${esc(((x.title||'U').trim()[0]||'U').toUpperCase())}</span>`,x.title||'Untitled draft',`${n} line${n!==1?'s':''}${x.updated?' \u00b7 '+swAgo(x.updated):''}`); }))
    :`<div class="sw-paper"><p class="sw-pt clamp-1">Your next verse</p>${['Start with one honest line','and let the rhymes find you'].map(x=>`<p class="sw-pl clamp-1">${x}</p>`).join('')}</div>`;
  return `<section data-mk-widget="lyricflow" data-testid="mk-widget-lyricflow" class="mkw mkw-sw sw-lf h-full"><span class="sw-glow" aria-hidden="true"></span><div class="sw-in">${swHead('captions','Songwriting','LyricFlow',drafts.length?drafts.length+' draft'+(drafts.length!==1?'s':''):'Write')}${body}<div class="sw-acts"><button type="button" data-act="ls-picker" data-testid="mk-lf-open" class="sw-btn is-primary press"><i data-lucide="${d?'arrow-up-right':'pen-line'}"></i>${d?'Open studio':'Start writing'}</button>${s&&(s.lyrics||[]).length?`<button type="button" data-act="open-lyric-studio" data-testid="mk-lf-card" class="sw-btn press" title="Make a lyric card"><i data-lucide="image"></i>Card</button>`:''}</div></div></section>`; }
let _isRec=[];
function isRecLoad(){ return assetGet('is_recent').then(v=>{ _isRec=Array.isArray(v)?v:[]; if(_isRec.length) swRefresh('imagestudio'); }).catch(()=>{}); }
function isRecSave(d){ const im=new Image(); im.onload=()=>{ const S=220, k=Math.min(1,S/Math.max(im.width,im.height)); const c=document.createElement('canvas'); c.width=Math.max(1,Math.round(im.width*k)); c.height=Math.max(1,Math.round(im.height*k)); c.getContext('2d').drawImage(im,0,0,c.width,c.height); let th=''; try{ th=c.toDataURL('image/jpeg',.8); }catch(e){ return; }
  _isRec=[{id:'isr'+Date.now().toString(36),at:Date.now(),thumb:th,d}].concat(_isRec).slice(0,6); assetPut('is_recent',_isRec).catch(()=>toast('Couldn\u2019t keep a copy','Your device storage is full')); swRefresh('imagestudio'); }; im.src=d; }
function isEditImage(src,own){ const im=new Image(); im.onload=()=>{ const A=(im.naturalWidth||1)/(im.naturalHeight||1); const W=Math.min(2048,im.naturalWidth||1024); openCoverStudio(src,'Image Studio',own,{aspect:A,out:[W,Math.round(W/A)],q:.9,applyLabel:'Save image',onApply:d=>{ isRecSave(d); isResult(d); }}); }; im.onerror=()=>toast('Couldn\u2019t open that image','Try a JPG or PNG'); im.src=src; }
function mkWImage(){ const s=curSong(); const src=(state.profile&&state.profile.avatar)||(s&&s.coverArt)||(SONGS[0]&&SONGS[0].coverArt)||''; const F=[['none','Original'],['saturate(1.8) contrast(1.1)','Vivid'],['grayscale(1) contrast(1.15)','Mono'],['sepia(.7) saturate(1.3) hue-rotate(-12deg)','Film']]; const rec=_isRec.slice(0,3);
  const body=rec.length?`<div class="sw-rlist"><p class="sw-lbl">Recent edits</p><div class="sw-thumbs">${rec.map((x,i)=>`<button type="button" data-act="is-recent-open" data-id="${x.id}" data-testid="mk-is-recent-${i}" class="sw-th press" style="--i:${i}" aria-label="Open recent edit"><img src="${x.thumb}" alt="" loading="lazy"><small>${swAgo(x.at)}</small></button>`).join('')}</div></div>`
    :`<div class="sw-sw">${F.map(([f,l],i)=>`<span style="--i:${i}"><span class="sw-sw-img">${src?`<img src="${esc(src)}" alt="" loading="lazy" style="filter:${f}">`:''}</span><b>${l}</b></span>`).join('')}</div>`;
  return `<section data-mk-widget="imagestudio" data-testid="mk-widget-imagestudio" class="mkw mkw-sw sw-is h-full"><span class="sw-glow" aria-hidden="true"></span><div class="sw-in">${swHead('wand-sparkles','Photo editor','Image Studio',rec.length?_isRec.length+' edit'+(_isRec.length!==1?'s':''):'Filters \u00b7 Text')}${body}<div class="sw-acts"><button type="button" data-act="mk-is-pick" data-testid="mk-is-pick" class="sw-btn is-primary press"><i data-lucide="image-plus"></i>Open studio</button>${state.profileBanner?`<button type="button" data-act="pf-banner-edit" data-testid="mk-is-banner" class="sw-btn press"><i data-lucide="image"></i>Banner</button>`:''}</div></div></section>`; }
function mkWidgetHtml(type,w){ const f={nowplaying:mkWNowPlaying,recent:mkWRecent,icons:mkWIcons,quick:mkWQuick,gamestats:mkWGame,clock:mkWClock,date:mkWDate,weather:mkWWeather,countdown:mkWCountdown,note:mkWNote,quote:mkWQuote,viz:mkWViz,lyric:mkWLyric,instrum:mkWInstrum,lyricflow:mkWLyricFlow,imagestudio:mkWImage}[type]; return f?f(w||{}):''; }
function isPickPhoto(){ const i=document.createElement('input'); i.type='file'; i.accept='image/*'; i.onchange=()=>{ const f=i.files&&i.files[0]; if(!f) return; if(f.size>25*1024*1024){ toast('Image too large','Use one under 25 MB'); return; } isEditImage(URL.createObjectURL(f),true); }; i.click(); }
function isResult(d,rec){ let r=document.getElementById('is-result'); if(!r){ r=document.createElement('div'); r.id='is-result'; document.body.appendChild(r); }
  r.innerHTML=`<div class="isr-bd" data-act="is-result-close"></div><div class="isr-card dark-surface" role="dialog" aria-label="Your edited image" data-testid="is-result"><p class="sw-k">Image Studio${rec?' \u00b7 '+swAgo(rec.at):''}</p><h3 class="isr-t">${rec?'Your recent edit':'Your image is ready'}</h3><img src="${d}" alt="Edited image" class="isr-img"><p class="isr-hint">On iPhone, press and hold the picture to save it to Photos.</p><div class="isr-acts"><a href="${d}" download="treesh-image-${Date.now()}.jpg" data-testid="is-result-download" class="sw-btn is-primary press"><i data-lucide="download"></i>Download</a>${navigator.share?`<button type="button" data-act="is-result-share" data-testid="is-result-share" class="sw-btn press"><i data-lucide="share-2"></i>Share</button>`:''}${rec?`<button type="button" data-act="is-recent-edit" data-id="${rec.id}" data-testid="is-result-edit" class="sw-btn press"><i data-lucide="sliders-horizontal"></i>Edit again</button><button type="button" data-act="is-recent-del" data-id="${rec.id}" data-testid="is-result-remove" class="sw-btn press"><i data-lucide="trash-2"></i>Remove</button>`:''}<button type="button" data-act="is-result-close" data-testid="is-result-close" class="sw-btn press">Close</button></div></div>`; r._d=d; icons(); }
async function isShare(){ const r=document.getElementById('is-result'); if(!r||!r._d) return; try{ const b=await (await fetch(r._d)).blob(); const f=new File([b],'treesh-image.jpg',{type:'image/jpeg'}); if(navigator.canShare&&navigator.canShare({files:[f]})) await navigator.share({files:[f],title:'Made in Treesh'}); else toast('Sharing isn\u2019t available here','Use Download instead'); }catch(e){} }

/* ---------- P9: Magic Markup polish (drag anywhere, real resizing, top bar takeover, edge glow) ---------- */
let _mkLP=null, _mkTouchLock=false;
function mkTrack(move,up){ let done=false; _mkTouchLock=true;
  const mv=ev=>{ if(ev.cancelable) ev.preventDefault(); move(ev); };
  const tmv=ev=>{ const t=ev.touches&&ev.touches[0]; if(!t) return; if(ev.cancelable) ev.preventDefault(); move({clientX:t.clientX,clientY:t.clientY,pointerType:'touch',preventDefault(){}}); };
  const off=()=>{ document.removeEventListener('pointermove',mv); document.removeEventListener('pointerup',end); document.removeEventListener('pointercancel',cancel); document.removeEventListener('touchmove',tmv); document.removeEventListener('touchend',end); document.removeEventListener('touchcancel',end); };
  const end=ev=>{ if(done) return; done=true; off(); _mkTouchLock=false; _mkScrollV=0; up(ev); };
  const cancel=ev=>{ if(ev&&ev.pointerType==='touch') return; end(ev); };
  document.addEventListener('pointermove',mv,{passive:false}); document.addEventListener('pointerup',end); document.addEventListener('pointercancel',cancel);
  document.addEventListener('touchmove',tmv,{passive:false}); document.addEventListener('touchend',end); document.addEventListener('touchcancel',end); }
document.addEventListener('pointerdown',e=>{ if(!state.mkEdit||(e.button&&e.button>0)||e.isPrimary===false) return; const t=e.target; if(!t||!t.closest||!t.closest('#view')||t.closest('.mk-ui,[data-mk-st],input,textarea,select')) return; const blk=t.closest('.mk-block[data-mk-id]'); if(!blk) return;
  const id=blk.dataset.mkId, x0=e.clientX, y0=e.clientY, mouse=e.pointerType==='mouse'; let tm=0, fired=false;
  const clear=()=>{ clearTimeout(tm); document.removeEventListener('pointermove',mv,true); document.removeEventListener('pointerup',clear,true); document.removeEventListener('pointercancel',clear,true); };
  const go=()=>{ if(fired) return; fired=true; clear(); _mkLP=id; blk.classList.add('mk-lift'); try{ navigator.vibrate&&navigator.vibrate(12); }catch(_){} mkStartDrag(e,id); if(!blk.classList.contains('mk-dragging')){ _mkLP=null; blk.classList.remove('mk-lift'); } };
  const mv=ev=>{ const d=Math.hypot(ev.clientX-x0,ev.clientY-y0); if(mouse){ if(d>6) go(); } else if(d>10) clear(); };
  if(!mouse) tm=setTimeout(go,300);
  document.addEventListener('pointermove',mv,true); document.addEventListener('pointerup',clear,true); document.addEventListener('pointercancel',clear,true); },true);
document.addEventListener('touchmove',e=>{ if((_mkLP||_mkTouchLock)&&e.cancelable) e.preventDefault(); },{passive:false,capture:true});
document.addEventListener('contextmenu',e=>{ if(state.mkEdit&&e.target&&e.target.closest&&e.target.closest('#view .mk-block')) e.preventDefault(); });
function mkStartResize(e,id){ const blk=mkBlockEl(id); if(!blk) return; const inner=blk.querySelector(':scope > .mk-inner'); const grid=blk.parentNode; const r0=blk.getBoundingClientRect(); const gw=grid.getBoundingClientRect().width; const sx=e.clientX, sy=e.clientY, h0=inner.getBoundingClientRect().height; const wide=window.innerWidth>=640; const cfg=mkCfg(id); const key=wide?'w':'mw'; let w=cfg[key]||(wide?((blk.className.match(/mk-w-(\w+)/)||[])[1]):'')||'full', h=0, wm=false;
  blk.classList.add('mk-resizing','mk-sel'); state.mkSel=id; mkSizeTip(blk,w,h0);
  mkTrack(ev=>{ const dx=ev.clientX-sx; if(Math.abs(dx)>14||wm){ wm=true; const cols=Math.round((r0.width+dx)/(gw/12)); const best=[4,6,8,12].reduce((a,b)=>Math.abs(b-cols)<Math.abs(a-cols)?b:a); w={4:'third',6:'half',8:'twothird',12:'full'}[best]; if(wide) blk.className=blk.className.replace(/mk-w-\w+/,'mk-w-'+w); else { blk.className=blk.className.replace(/\s?mk-mw-\w+/g,''); if(w!=='full') blk.classList.add('mk-mw-'+w); } } const dy=ev.clientY-sy; if(Math.abs(dy)>6||h){ h=Math.max(60,Math.min(1600,Math.round(h0+dy))); inner.style.height=h+'px'; if(!blk.classList.contains('mk-cv')) inner.style.overflow='auto'; } mkSizeTip(blk,w,h||h0); mkAutoScroll(ev.clientY); },
  ()=>{ blk.classList.remove('mk-resizing'); mkSizeTip(null); if(wm){ if(!wide&&w==='full') delete cfg.mw; else cfg[key]=w; } if(h) cfg.h=h; state.mkSel=id; mkSave(); renderView(); if(state.mkSheet==='block') mkRenderSheet(); }); }
function mkSizeTip(blk,w,h){ let t=document.getElementById('mk-size-tip'); if(!blk){ if(t) t.remove(); return; } if(!t){ t=document.createElement('div'); t.id='mk-size-tip'; t.className='mk-size-tip mk-ui'; t.setAttribute('data-testid','mk-size-tip'); blk.appendChild(t); } else if(t.parentNode!==blk) blk.appendChild(t); const L={full:'Full width',twothird:'Two thirds',half:'Half',third:'One third'}; t.textContent=(L[w]||'Full width')+' \u00b7 '+Math.round(h)+'px'; }
function mkRaysSync(){ let r=document.getElementById('mk-rays'); if(!r){ r=document.createElement('div'); r.id='mk-rays'; r.setAttribute('aria-hidden','true'); r.innerHTML='<i class="r1"></i><i class="r2"></i><i class="r3"></i><i class="r4"></i><span class="mk-rays-edge"></span>'; document.body.appendChild(r); } }
function mkStartDrag(e,id){ const blk=mkBlockEl(id); if(!blk) return; const grid=blk.parentNode; document.querySelectorAll('#view .mk-sel').forEach(x=>x.classList.remove('mk-sel')); blk.classList.add('mk-sel','mk-dragging'); state.mkSel=id;
  const r0=blk.getBoundingClientRect(); const ox=e.clientX-r0.left, oy=e.clientY-r0.top; let lx=e.clientX, ly=e.clientY;
  const place=()=>{ blk.style.transform=''; const r=blk.getBoundingClientRect(); blk.style.transform='translate3d('+Math.round(lx-ox-r.left)+'px,'+Math.round(ly-oy-r.top)+'px,0) rotate(-.6deg)'; };
  const onScroll=()=>place(); window.addEventListener('scroll',onScroll,{passive:true});
  mkTrack(ev=>{ lx=ev.clientX; ly=ev.clientY; const el=document.elementFromPoint(lx,ly); const over=el&&el.closest&&el.closest('[data-mk-id]');
    if(over&&over!==blk&&over.parentNode===grid){ const r=over.getBoundingClientRect(); const midY=r.top+r.height/2; const sameRow=Math.abs(ly-midY)<r.height*0.3&&r.width<grid.clientWidth*0.9; const before=sameRow?(lx<r.left+r.width/2):(ly<midY); if(before){ if(over.previousElementSibling!==blk) grid.insertBefore(blk,over); } else if(over.nextElementSibling!==blk) grid.insertBefore(blk,over.nextSibling); }
    place(); mkAutoScroll(ly); },
  ()=>{ window.removeEventListener('scroll',onScroll); _mkLP=null; blk.classList.remove('mk-dragging','mk-lift'); blk.style.transform=''; mkCommitOrder(mkDomOrder()); renderView(); if(state.mkSheet==='block') mkRenderSheet(); });
  place(); }
