/* ---------- P9: Zodiac, numerology & fortune hub (offline first, daily reading from the web) ---------- */
const ZH_SIGNS=[['aries','Aries','Mar 21 \u2013 Apr 19','Fire','Cardinal','Mars','#ff5a4e',['bold','driven','spontaneous']],['taurus','Taurus','Apr 20 \u2013 May 20','Earth','Fixed','Venus','#34d399',['steady','sensual','loyal']],['gemini','Gemini','May 21 \u2013 Jun 20','Air','Mutable','Mercury','#facc15',['curious','witty','restless']],['cancer','Cancer','Jun 21 \u2013 Jul 22','Water','Cardinal','the Moon','#93c5fd',['tender','intuitive','protective']],['leo','Leo','Jul 23 \u2013 Aug 22','Fire','Fixed','the Sun','#f59e0b',['radiant','generous','dramatic']],['virgo','Virgo','Aug 23 \u2013 Sep 22','Earth','Mutable','Mercury','#a3e635',['precise','helpful','thoughtful']],['libra','Libra','Sep 23 \u2013 Oct 22','Air','Cardinal','Venus','#f9a8d4',['charming','fair','artistic']],['scorpio','Scorpio','Oct 23 \u2013 Nov 21','Water','Fixed','Pluto','#f43f5e',['intense','magnetic','loyal']],['sagittarius','Sagittarius','Nov 22 \u2013 Dec 21','Fire','Mutable','Jupiter','#a78bfa',['free','optimistic','honest']],['capricorn','Capricorn','Dec 22 \u2013 Jan 19','Earth','Cardinal','Saturn','#cbd5e1',['ambitious','patient','grounded']],['aquarius','Aquarius','Jan 20 \u2013 Feb 18','Air','Fixed','Uranus','#22d3ee',['inventive','independent','visionary']],['pisces','Pisces','Feb 19 \u2013 Mar 20','Water','Mutable','Neptune','#818cf8',['dreamy','empathetic','creative']]];
const ZH_IC=['zodiac-aries','zodiac-taurus','zodiac-gemini','zodiac-cancer','zodiac-leo','zodiac-virgo','zodiac-libra','zodiac-scorpio','zodiac-sagittarius','zodiac-capricorn','zodiac-aquarius','zodiac-pisces'];
const ZH_OPEN=["The sky leans your way today, {s}.","{s}, the Moon is stirring something {t0} in you.","A quiet shift overhead asks you to slow down, {s}.","Today rewards your {t1} side, {s}.","{s}, {r} is lighting a clear path forward.","The air feels electric today, {s}, and so do you."];
const ZH_MID=["A conversation you have been putting off could open a surprising door.","Small creative sparks add up, so write down the ideas that arrive out of nowhere.","Someone close may need your {t2} energy more than they say.","Plans want structure. Make one list and stick to it.","Let music set the tone, a song you forgot about holds a message.","Your instincts are sharper than usual. Trust the first answer.","An old habit is ready to be traded for something that fits who you are now.","A message or invitation could shift your plans in a good way.","Patience pays off. What feels slow is actually settling into place."];
const ZH_END=["By evening, give yourself room to rest and recharge.","Keep your heart open and your phone on silent for an hour.","Lead with kindness and the rest falls into place.","Celebrate one small win before the day ends.","The more honest you are, the lighter you will feel.","Let the night be soft. Tomorrow builds on what you start today."];
const ZH_METER={love:['Keep it light and playful','Say what you feel','Sparks are flying','Romance runs deep today'],career:['Ease in and focus','Steady progress','Your ideas land','Big moves are favored'],mood:['Be gentle with yourself','Calm and clear','Bright and social','Glowing from the inside']};
const ZH_COLORS=[['Electric Violet','#9328ff'],['Rose Quartz','#f7a8c4'],['Ocean Teal','#14b8a6'],['Sunset Gold','#f59e0b'],['Midnight Blue','#1e3a8a'],['Ember Red','#ef4444'],['Mint Leaf','#34d399'],['Lavender Mist','#c4b5fd'],['Silver Moon','#cbd5e1'],['Peach Glow','#fdba74'],['Emerald','#10b981'],['Cosmic Pink','#ff2d78']];
const ZH_CN=[['Rat','\u9f20','quick witted and resourceful'],['Ox','\u725b','dependable and strong'],['Tiger','\u864e','brave and confident'],['Rabbit','\u5154','gentle and elegant'],['Dragon','\u9f8d','bold and lucky'],['Snake','\u86c7','wise and mysterious'],['Horse','\u99ac','energetic and free'],['Goat','\u7f8a','calm and creative'],['Monkey','\u7334','clever and playful'],['Rooster','\u96de','sharp and hardworking'],['Dog','\u72d7','loyal and honest'],['Pig','\u8c6c','kind and generous']];
const ZH_NUM={1:['The Leader','Independent, original and driven. You start things others only dream about.'],2:['The Peacemaker','Sensitive, patient and cooperative. You bring people together.'],3:['The Creator','Expressive, joyful and social. Words, art and music flow through you.'],4:['The Builder','Practical, loyal and hardworking. You turn ideas into solid ground.'],5:['The Free Spirit','Adventurous, curious and adaptable. Change is your favorite song.'],6:['The Nurturer','Caring, responsible and warm. Home and heart come first.'],7:['The Seeker','Thoughtful, intuitive and deep. You look for the truth under everything.'],8:['The Powerhouse','Ambitious, confident and strong. You were built for big goals.'],9:['The Humanitarian','Compassionate, wise and generous. You care about the bigger picture.'],11:['The Visionary','A master number. Inspired, intuitive and here to light the way.'],22:['The Master Builder','A master number. Big dreams with the discipline to make them real.'],33:['The Master Teacher','A master number. Pure compassion that lifts others up.']};
const ZH_PY={1:'New beginnings. Plant seeds and start fresh.',2:'Patience and partnership. Let things grow.',3:'Creativity and fun. Share your voice.',4:'Hard work and foundations. Build it right.',5:'Change and freedom. Say yes to adventure.',6:'Love and home. Take care of your people.',7:'Reflection and learning. Go within.',8:'Power and reward. Aim high.',9:'Endings and release. Clear space for what is next.',11:'Inspiration arrives. Trust your intuition.',22:'Big plans become real. Think long term.',33:'Lead with your heart and lift others.'};
const ZH_FORTUNES=["A song you love will find you at the perfect moment.","Your next idea is closer than you think.","Someone is quietly proud of you.","The best verse is the one you have not written yet.","Good news travels to you this week.","Say yes to the small adventure.","Your kindness is a melody others remember.","A door opens when you stop knocking so hard.","Today, your vibe attracts your tribe.","The beat drops when you least expect it.","Trust the process, even the slow parts.","An old friend brings new energy.","You are the main character today.","Luck favors the one who presses record.","What you practice in private shows in public.","A surprise makes you laugh out loud soon.","Your patience is about to pay off.","Rest is part of the rhythm.","Big things start as tiny sparks.","Your voice matters more than you know.","The universe likes your playlist.","Be bold. The crowd is already on your side.","Something you lost will return in a new form.","Follow the feeling, not the noise.","A risk taken with love is never wasted.","Your energy today could light up a city.","Write it down. Future you will thank you.","Good things come in loops. Keep going.","Your next chapter has a great soundtrack.","The stars say: treat yourself today."];
const ZH_TAROT=[['0','The Fool','footprints','New starts, faith, spontaneity','Hesitation, holding back','Leap with an open heart. A fresh journey begins.'],['I','The Magician','wand-sparkles','Skill, willpower, creation','Scattered focus','You already have every tool you need. Make it happen.'],['II','The High Priestess','moon-star','Intuition, mystery, inner voice','Ignoring your gut','Listen to the quiet voice inside. It knows.'],['III','The Empress','flower-2','Abundance, beauty, creativity','Creative block','Let things grow naturally. Nurture what you love.'],['IV','The Emperor','crown','Structure, leadership, stability','Rigid control','Take charge with calm confidence and clear rules.'],['V','The Hierophant','book-open','Tradition, learning, guidance','Breaking the mold','Learn from those who came before, then make it yours.'],['VI','The Lovers','heart-handshake','Love, harmony, choices','Mixed signals','Choose with your heart and stay true to your values.'],['VII','The Chariot','swords','Drive, victory, momentum','Losing direction','Focus your energy and charge forward. You can win this.'],['VIII','Strength','biceps-flexed','Courage, patience, compassion','Self doubt','Real strength is gentle. Stay soft and steady.'],['IX','The Hermit','lamp','Reflection, solitude, wisdom','Isolation','Step back from the noise and find your own light.'],['X','Wheel of Fortune','ferris-wheel','Cycles, luck, turning points','Resistance to change','The wheel is turning in your favor. Ride it.'],['XI','Justice','scale','Truth, fairness, balance','Avoiding the truth','Be honest and fair. Balance comes back around.'],['XII','The Hanged One','anchor','Pause, new perspective, surrender','Stalling','Flip the view. A pause shows you something new.'],['XIII','Death','skull','Transformation, endings, renewal','Fear of change','Something ends so something better can begin.'],['XIV','Temperance','glass-water','Balance, patience, flow','Excess','Blend it all slowly. Moderation is your magic.'],['XV','The Devil','flame','Desire, attachment, temptation','Breaking free','Notice what has a hold on you, then loosen the grip.'],['XVI','The Tower','castle','Sudden change, awakening','Avoiding the storm','Shake ups clear the way for what is real.'],['XVII','The Star','star','Hope, healing, inspiration','Lost faith','You are healing. Keep shining, the future is bright.'],['XVIII','The Moon','moon','Dreams, illusion, intuition','Confusion clears','Not everything is as it seems. Trust your dreams.'],['XIX','The Sun','sun','Joy, success, warmth','Clouded joy','Pure good vibes. Celebrate and let yourself shine.'],['XX','Judgement','bell-ring','Awakening, calling, rebirth','Self judgment','A calling is getting louder. Answer it.'],['XXI','The World','globe','Completion, wholeness, travel','Unfinished business','A chapter completes. Take a bow, you earned it.']];
const ZH_ASPECT={0:['Mirror match','You get each other instantly, sometimes a little too well.'],1:['Neighbors','Different rhythms that can teach each other a lot.'],2:['Easy flow','Natural chemistry and easy conversation.'],3:['Spicy tension','Sparks fly, in both directions. Worth it with patience.'],4:['Soul trine','Same element, same wavelength. A rare easy match.'],5:['Growth pair','You stretch each other in unexpected ways.'],6:['Opposites attract','Magnetic and intense. You complete each other\u2019s sentences.']};

function zhHash(s){ let h=2166136261>>>0; for(let i=0;i<s.length;i++){ h^=s.charCodeAt(i); h=Math.imul(h,16777619); } return h>>>0; }
function zhRng(seed){ let a=zhHash(String(seed)); return ()=>{ a|=0; a=a+0x6D2B79F5|0; let t=Math.imul(a^a>>>15,1|a); t=t+Math.imul(t^t>>>7,61|t)^t; return ((t^t>>>14)>>>0)/4294967296; }; }
const zhPick=(r,a)=>a[Math.floor(r()*a.length)];
function zhDay(d){ d=d||new Date(); const p=n=>String(n).padStart(2,'0'); return d.getFullYear()+'-'+p(d.getMonth()+1)+'-'+p(d.getDate()); }
function zhState(){ return state.zh||(state.zh={tab:'today',sign:null,match:null}); }
function zhBday(){ const b=(state.profile&&state.profile.birthday)||''; const p=String(b).split('-'); return p.length===3&&+p[0]&&+p[1]&&+p[2]?{y:+p[0],m:+p[1],d:+p[2]}:null; }
function zhSignIdx(){ const z=zhState(); if(z.sign!=null) return z.sign; const n=zodiac((state.profile&&state.profile.birthday)||''); const i=ZH_SIGNS.findIndex(x=>x[1]===n); return i<0?null:i; }
function zhSeed(k){ const p=state.profile||{}; return k+'|'+zhDay()+'|'+(p.nickname||'')+'|'+(p.birthday||'')+'|'+zhSignIdx(); }

function zhOfflineReading(i){ const S=ZH_SIGNS[i], r=zhRng('read|'+zhDay()+'|'+S[0]); const f=x=>x.replace('{s}',S[1]).replace('{r}',S[5]).replace('{t0}',S[7][0]).replace('{t1}',S[7][1]).replace('{t2}',S[7][2]); return [zhPick(r,ZH_OPEN),zhPick(r,ZH_MID),zhPick(r,ZH_END)].map(f).join(' '); }
function zhCache(){ return LS.get('treesh_horo',{})||{}; }
function zhReading(i){ const c=zhCache()[ZH_SIGNS[i][0]]; return (c&&c.d===zhDay()&&c.t)?{t:c.t,src:'online'}:null; }
let _zhFetching='';
async function zhFetch(i){ const id=ZH_SIGNS[i][0]; if(zhReading(i)||_zhFetching===id||navigator.onLine===false) return; _zhFetching=id; let ok=false;
  try{ const ac=typeof AbortController!=='undefined'?new AbortController():null; const tm=setTimeout(()=>{ try{ ac&&ac.abort(); }catch(e){} },7000);
    const r=await fetch('https://api.api-ninjas.com/v1/horoscope?zodiac='+id,ac?{signal:ac.signal}:{}); clearTimeout(tm);
    if(r.ok){ const j=await r.json(); const t=String((j&&(j.horoscope||(j.data&&j.data.horoscope)))||'').trim(); if(t.length>20){ const c=zhCache(); Object.keys(c).forEach(k=>{ if(c[k].d!==zhDay()) delete c[k]; }); c[id]={d:zhDay(),t:t.slice(0,1400)}; LS.set('treesh_horo',c); ok=true; } } }catch(e){}
  _zhFetching=''; if(ok&&zhSignIdx()===i){ const el=document.getElementById('zh-reading'); if(el) el.outerHTML=zhReadingHtml(i); } }
function zhReadingHtml(i){ const on=zhReading(i); const txt=on?on.t:zhOfflineReading(i); return `<div id="zh-reading" class="zh-card zh-read" data-testid="zh-reading" data-source="${on?'online':'offline'}"><div class="zh-card-k"><i data-lucide="telescope"></i>Today\u2019s reading<span class="zh-src">${on?'Live':'Offline'}</span></div><p class="zh-read-t">${esc(txt)}</p></div>`; }

function zhMoon(d){ d=d||new Date(); const syn=29.530588853; const ref=Date.UTC(2000,0,6,18,14)/864e5; const days=d.getTime()/864e5-ref; const age=((days%syn)+syn)%syn; const f=age/syn; const illum=(1-Math.cos(2*Math.PI*f))/2; const names=['New Moon','Waxing Crescent','First Quarter','Waxing Gibbous','Full Moon','Waning Gibbous','Last Quarter','Waning Crescent']; const toFull=((0.5-f+1)%1)*syn; return {f,age,illum,name:names[Math.floor(f*8+0.5)%8],toFull:Math.round(toFull)}; }
function zhMoonSvg(f){ const rx=(50*Math.abs(Math.cos(2*Math.PI*f))).toFixed(2); let d;
  if(f<0.5){ d=`M50 0 A50 50 0 0 1 50 100 A${rx} 50 0 0 ${f<0.25?0:1} 50 0Z`; } else { d=`M50 0 A50 50 0 0 0 50 100 A${rx} 50 0 0 ${f>0.75?1:0} 50 0Z`; }
  return `<svg viewBox="0 0 100 100" class="zh-moon-svg" aria-hidden="true"><circle cx="50" cy="50" r="50" fill="rgba(255,255,255,.08)"/><path d="${d}" fill="url(#zhMoonG)"/><defs><radialGradient id="zhMoonG" cx="40%" cy="35%"><stop offset="0" stop-color="#fffbea"/><stop offset="1" stop-color="#d8d2ff"/></radialGradient></defs></svg>`; }
function zhCN(b){ if(!b) return null; let y=b.y; if(b.m===1||(b.m===2&&b.d<4)) y--; const a=ZH_CN[((y-4)%12+12)%12]; const el=['Metal','Metal','Water','Water','Wood','Wood','Fire','Fire','Earth','Earth'][((y%10)+10)%10]; return {name:a[0],ch:a[1],desc:a[2],el,y}; }
function zhRed(n){ n=Math.abs(+n||0); while(n>9&&n!==11&&n!==22&&n!==33){ n=String(n).split('').reduce((a,b)=>a+(+b),0); } return n; }
function zhDigits(n){ return String(n).split('').reduce((a,b)=>a+(+b||0),0); }
function zhNums(){ const b=zhBday(); if(!b) return null; const now=new Date(); const lp=zhRed(zhRed(zhDigits(b.y))+zhRed(b.m)+zhRed(b.d)); const py=zhRed(zhRed(b.m)+zhRed(b.d)+zhRed(zhDigits(now.getFullYear()))); const pm=zhRed(py+now.getMonth()+1); const pd=zhRed(pm+now.getDate());
  const nm=String((state.profile&&state.profile.nickname)||'').toLowerCase().replace(/[^a-z]/g,''); const name=nm?zhRed(nm.split('').reduce((a,c)=>a+((c.charCodeAt(0)-97)%9)+1,0)):null; return {lp,bd:zhRed(b.d),py,pm,pd,name,nm}; }
function zhCompat(a,b){ const d=Math.min((a-b+12)%12,(b-a+12)%12); const base={0:78,1:62,2:86,3:56,4:93,5:52,6:74}[d]; const r=zhRng('m'+Math.min(a,b)+'-'+Math.max(a,b)); const cl=v=>Math.max(18,Math.min(99,Math.round(v))); const love=cl(base+(r()-0.5)*14), friend=cl(base+6+(r()-0.5)*12), work=cl(base-4+(r()-0.5)*14); return {d,score:Math.round((love+friend+work)/3),love,friend,work,a:ZH_ASPECT[d]}; }

/* ----- render ----- */
function zhMeter(k,label,ic,v){ const n=ZH_METER[k][Math.min(3,Math.floor(v/25.5))]; return `<div class="zh-meter" data-testid="zh-meter-${k}" style="--v:${v}"><div class="zh-meter-top"><span><i data-lucide="${ic}"></i>${label}</span><b class="font-doto">${v}%</b></div><span class="zh-bar"><i></i></span><p>${n}</p></div>`; }
function zhSignOrb(i,cls){ const S=ZH_SIGNS[i]; return `<span class="zh-orb ${cls||''}" style="--zc:${S[6]}"><span class="zh-orb-ring"></span><i data-lucide="${ZH_IC[i]}"></i></span>`; }
function zhTodayHtml(i){ const S=ZH_SIGNS[i], r=zhRng(zhSeed('today')); const love=35+Math.floor(r()*65), career=35+Math.floor(r()*65), mood=35+Math.floor(r()*65); const num=1+Math.floor(r()*99); const col=zhPick(r,ZH_COLORS);
  const pool=(SONGS||[]).filter(s=>!s._user&&!isDisliked(s.id)); const song=pool.length?pool[Math.floor(r()*pool.length)]:null; const m=zhMoon(); const cn=zhCN(zhBday());
  return `${zhReadingHtml(i)}
  <div class="zh-card"><div class="zh-card-k"><i data-lucide="orbit"></i>Your day in the stars</div><div class="zh-meters">${zhMeter('love','Love','heart',love)}${zhMeter('career','Career','briefcase',career)}${zhMeter('mood','Mood','smile',mood)}</div></div>
  <div class="zh-grid3"><div class="zh-mini" data-testid="zh-lucky-number"><span class="zh-mini-k">Lucky number</span><b class="zh-big font-doto">${num}</b></div><div class="zh-mini" data-testid="zh-lucky-color"><span class="zh-mini-k">Lucky color</span><span class="zh-swatch" style="background:${col[1]};box-shadow:0 0 24px ${col[1]}"></span><b class="zh-mini-v">${col[0]}</b></div>${song?`<button data-act="play" data-id="${esc(song.id)}" data-testid="zh-lucky-song" class="zh-mini zh-song press"><span class="zh-mini-k">Lucky song</span><span class="zh-song-art">${img(song.coverArt,'h-full w-full object-cover')}<i data-lucide="play" class="fill-current"></i></span><b class="zh-mini-v clamp-1">${esc(song.title)}</b></button>`:''}</div>
  <div class="zh-grid2"><div class="zh-card zh-moon" data-testid="zh-moon"><div class="zh-card-k"><i data-lucide="moon"></i>Moon phase</div><div class="zh-moon-row">${zhMoonSvg(m.f)}<div><b class="zh-moon-n">${m.name}</b><p>${Math.round(m.illum*100)}% lit${m.name==='Full Moon'?'':' \u00b7 full moon in '+m.toFull+' day'+(m.toFull===1?'':'s')}</p></div></div></div>
  ${cn?`<div class="zh-card zh-cn" data-testid="zh-chinese"><div class="zh-card-k"><i data-lucide="sparkle"></i>Chinese zodiac</div><div class="zh-moon-row"><span class="zh-cn-ch">${cn.ch}</span><div><b class="zh-moon-n">${cn.el} ${cn.name}</b><p>Born ${cn.y}. ${cn.desc.charAt(0).toUpperCase()+cn.desc.slice(1)}.</p></div></div></div>`:`<div class="zh-card zh-cn"><div class="zh-card-k"><i data-lucide="sparkle"></i>Chinese zodiac</div><p class="zh-muted">Add your birthday to see your animal sign.</p></div>`}</div>
  <div class="zh-card"><div class="zh-card-k"><i data-lucide="${ZH_IC[i]}"></i>About ${S[1]}</div><div class="zh-chips"><span>${S[3]}</span><span>${S[4]}</span><span>Ruled by ${S[5]}</span>${S[7].map(t=>`<span>${t}</span>`).join('')}</div></div>`; }
function zhNumCard(k,label,n,sub,big){ const M=ZH_NUM[n]||ZH_NUM[zhRed(n)]||['','']; return `<div class="zh-num${big?' is-big':''}" data-testid="zh-num-${k}"><span class="zh-num-n font-doto">${n}</span><div class="min-w-0"><span class="zh-mini-k">${label}</span><b>${M[0]}</b><p>${sub||M[1]}</p></div></div>`; }
function zhNumHtml(){ const N=zhNums(); if(!N) return zhNeedBday('Numerology uses your birthday to find your life path.');
  return `<div class="zh-card"><div class="zh-card-k"><i data-lucide="hash"></i>Core numbers</div>${zhNumCard('lifepath','Life path',N.lp,'',true)}${zhNumCard('birthday','Birthday number',N.bd)}${N.name!=null?zhNumCard('name','Name number \u00b7 '+esc((state.profile&&state.profile.nickname)||''),N.name):''}</div>
  <div class="zh-card"><div class="zh-card-k"><i data-lucide="calendar-days"></i>Your timing right now</div><div class="zh-grid3 zh-cycles">${[['year','Personal year',N.py],['month','Personal month',N.pm],['day','Personal day',N.pd]].map(([k,l,n])=>`<div class="zh-mini" data-testid="zh-num-${k}"><span class="zh-mini-k">${l}</span><b class="zh-big font-doto">${n}</b><p class="zh-mini-p">${ZH_PY[n]||ZH_PY[zhRed(n)]||''}</p></div>`).join('')}</div></div>
  <p class="zh-foot">Numbers are reduced the Pythagorean way. 11, 22 and 33 stay as master numbers.</p>`; }
function zhFortuneHtml(){ const day=zhDay(), r=zhRng(zhSeed('fortune')); const fc=LS.get('treesh_cookie',null); const open=!!(fc&&fc.d===day); const msg=zhPick(r,ZH_FORTUNES); const lucky=[...new Set(Array.from({length:12},()=>1+Math.floor(r()*49)))].slice(0,6).sort((a,b)=>a-b);
  const rt=zhRng(zhSeed('tarot')); const ci=Math.floor(rt()*ZH_TAROT.length), rev=rt()<0.28, C=ZH_TAROT[ci]; const tc=LS.get('treesh_tarot',null); const flipped=!!(tc&&tc.d===day);
  return `<div class="zh-card zh-cookie-card"><div class="zh-card-k"><i data-lucide="cookie"></i>Fortune cookie</div><button data-act="zh-cookie" data-testid="zh-cookie" class="zh-cookie press${open?' is-open':''}" aria-label="${open?'Your fortune':'Crack open your fortune cookie'}"><span class="zh-ck-l"></span><span class="zh-ck-r"></span><span class="zh-ck-paper" data-testid="zh-fortune-text">${esc(msg)}</span></button><p class="zh-hint">${open?`Lucky numbers <b class="font-doto">${lucky.join(' \u00b7 ')}</b>`:'Tap to crack it open. A new one bakes every day.'}</p></div>
  <div class="zh-card"><div class="zh-card-k"><i data-lucide="sparkles"></i>Tarot card of the day</div><div class="zh-tarot-wrap"><button data-act="zh-tarot" data-testid="zh-tarot" class="zh-tarot press${flipped?' is-flipped':''}" aria-label="${flipped?C[1]:'Flip your card'}"><span class="zh-t-in"><span class="zh-t-back"><i data-lucide="moon-star"></i><b>Tap to reveal</b></span><span class="zh-t-face${rev?' is-rev':''}"><span class="zh-t-num">${C[0]}</span><i data-lucide="${C[2]}"></i><b>${C[1]}</b><small>${rev?'Reversed':'Upright'}</small></span></span></button><div class="zh-t-text${flipped?'':' is-hidden'}" data-testid="zh-tarot-text"><b>${C[1]}${rev?' \u00b7 reversed':''}</b><p class="zh-t-kw">${rev?C[4]:C[3]}</p><p>${C[5]}</p></div></div></div>`; }
function zhMatchHtml(i){ const z=zhState(); const j=z.match;
  const chips=ZH_SIGNS.map((S,k)=>`<button data-act="zh-match" data-val="${k}" data-testid="zh-match-${S[0]}" aria-pressed="${j===k}" class="zh-sg press${j===k?' is-on':''}" style="--zc:${S[6]}"><i data-lucide="${ZH_IC[k]}"></i><span>${S[1]}</span></button>`).join('');
  let res=`<p class="zh-muted zh-center">Pick a sign to see how you vibe together.</p>`;
  if(j!=null){ const c=zhCompat(i,j); res=`<div class="zh-match-res" data-testid="zh-match-result"><div class="zh-pair">${zhSignOrb(i,'sm')}<span class="zh-score font-doto" style="--v:${c.score}">${c.score}<small>%</small></span>${zhSignOrb(j,'sm')}</div><b class="zh-match-t">${c.a[0]}</b><p class="zh-muted">${ZH_SIGNS[i][1]} + ${ZH_SIGNS[j][1]}. ${c.a[1]}</p><div class="zh-meters">${zhMeter('love','Love','heart',c.love)}${zhMeter('mood','Friendship','users',c.friend)}${zhMeter('career','Teamwork','briefcase',c.work)}</div></div>`; }
  return `<div class="zh-card"><div class="zh-card-k"><i data-lucide="heart-handshake"></i>Compatibility</div><div class="zh-signs">${chips}</div>${res}</div>`; }
function zhNeedBday(msg){ return `<div class="zh-card zh-center"><p class="zh-muted">${msg}</p><button data-act="zh-bday" data-testid="zh-add-birthday" class="zh-btn press"><i data-lucide="calendar-days"></i>Add your birthday</button></div>`; }
function zhPickerHtml(){ return `<div class="zh-card"><div class="zh-card-k"><i data-lucide="sparkles"></i>Pick a sign to explore</div><div class="zh-signs">${ZH_SIGNS.map((S,k)=>`<button data-act="zh-sign" data-val="${k}" data-testid="zh-pick-${S[0]}" class="zh-sg press" style="--zc:${S[6]}"><i data-lucide="${ZH_IC[k]}"></i><span>${S[1]}</span></button>`).join('')}</div></div>${zhNeedBday('Or add your birthday so Treesh can read your own stars.')}`; }
function zhBodyHtml(){ const z=zhState(), i=zhSignIdx(); if(i==null) return zhPickerHtml(); return z.tab==='numbers'?zhNumHtml():z.tab==='fortune'?zhFortuneHtml():z.tab==='match'?zhMatchHtml(i):zhTodayHtml(i); }
function zhHtml(){ const z=zhState(), i=zhSignIdx(), S=i!=null?ZH_SIGNS[i]:null; const own=z.sign==null;
  const tabs=[['today','Today','sun'],['numbers','Numbers','hash'],['fortune','Fortune','cookie'],['match','Match','heart-handshake']];
  const d=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
  return `<div class="zh-bd" data-act="zh-close" data-testid="zh-backdrop"></div><div class="zh-sheet dark-surface" role="dialog" aria-label="Your stars" data-testid="zodiac-hub" style="--zc:${S?S[6]:'#9328ff'}"><span class="zh-grab" aria-hidden="true"></span><div class="zh-sky" aria-hidden="true"><i></i><i></i><i></i></div>
   <header class="zh-head" data-sheet-drag><button data-act="zh-close" data-testid="zh-close" aria-label="Close" class="zh-x press"><i data-lucide="chevron-down"></i></button><div class="min-w-0 flex-1"><p class="zh-kick">Your stars</p><p class="zh-date">${d}</p></div>${S&&!own?`<button data-act="zh-sign" data-val="" data-testid="zh-reset-sign" class="zh-chip-btn press">My sign</button>`:''}</header>
   ${S?`<div class="zh-hero">${zhSignOrb(i)}<div class="min-w-0"><h2 class="zh-name" data-testid="zh-sign-name">${S[1]}</h2><p class="zh-dates">${S[2]} \u00b7 ${S[3]} sign</p></div></div>
   <div class="zh-tabs" role="tablist">${tabs.map(([k,l,ic])=>`<button data-act="zh-tab" data-val="${k}" data-testid="zh-tab-${k}" role="tab" aria-selected="${z.tab===k}" class="zh-tab press${z.tab===k?' is-on':''}"><i data-lucide="${ic}"></i>${l}</button>`).join('')}</div>`:''}
   <div class="zh-body soft-scroll" id="zh-body" data-testid="zh-body">${zhBodyHtml()}</div></div>`; }
function zhRender(keep){ const r=document.getElementById('zh-root'); if(!r) return; const sc=r.querySelector('.zh-body'); const top=keep&&sc?sc.scrollTop:0; r.innerHTML=zhHtml(); if(keep) r.classList.add('is-still'); icons(); const n=r.querySelector('.zh-body'); if(n&&top) n.scrollTop=top; const i=zhSignIdx(); if(i!=null&&zhState().tab==='today') zhFetch(i); }
function zhOpen(){ let r=document.getElementById('zh-root'); if(!r){ r=document.createElement('div'); r.id='zh-root'; document.body.appendChild(r); } r.className=''; state.zhOpen=true; zhRender(false); syncScrollLock(); }
function zhClose(){ const r=document.getElementById('zh-root'); state.zhOpen=false; if(!r||!r.firstChild) return; r.classList.add('is-out'); setTimeout(()=>{ if(!state.zhOpen){ r.innerHTML=''; r.className=''; syncScrollLock(); } },260); }
function zhProfileCard(z){ if(!z) return ''; const i=ZH_SIGNS.findIndex(x=>x[1]===z); if(i<0) return ''; const m=zhMoon(); const r=zhRng(zhSeed('today')); r(); r(); r(); const num=1+Math.floor(r()*99);
  return `<button data-act="zh-open" data-testid="profile-stars-card" class="zh-pcard press" style="--zc:${ZH_SIGNS[i][6]}">${zhSignOrb(i,'sm')}<span class="min-w-0 flex-1"><span class="zh-pcard-k">Your stars today</span><span class="zh-pcard-t clamp-1">${z} \u00b7 ${m.name}</span><span class="zh-pcard-s clamp-1">Horoscope, numerology, tarot and fortune \u00b7 lucky number ${num}</span></span><i data-lucide="chevron-right"></i></button>`; }
function zhAct(act,t){ const z=zhState(), val=t.dataset.val;
  switch(act){
    case 'zh-open': zhOpen(); break;
    case 'zh-close': zhClose(); break;
    case 'zh-tab': z.tab=val; zhRender(false); break;
    case 'zh-sign': z.sign=val===''?null:+val; z.match=null; zhRender(false); break;
    case 'zh-match': z.match=+val; zhRender(true); break;
    case 'zh-cookie': { const fc=LS.get('treesh_cookie',null); if(fc&&fc.d===zhDay()) break; LS.set('treesh_cookie',{d:zhDay()}); t.classList.add('is-open'); try{ navigator.vibrate&&navigator.vibrate(18); }catch(e){} setTimeout(()=>zhRender(true),650); break; }
    case 'zh-tarot': { const tc=LS.get('treesh_tarot',null); if(tc&&tc.d===zhDay()) break; LS.set('treesh_tarot',{d:zhDay()}); t.classList.add('is-flipped'); setTimeout(()=>zhRender(true),700); break; }
    case 'zh-bday': zhClose(); state.settingsEditProfile=true; state._pfDraft=null; setTimeout(()=>{ if(!state.profileOpen) openProfile(); else pfRerender(); },280); break;
  } }
document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act]'); if(!t) return; const a=t.dataset.act; if(a&&a.indexOf('zh-')===0) zhAct(a,t); });
document.addEventListener('keydown',e=>{ if(e.key==='Escape'&&state.zhOpen){ e.stopImmediatePropagation(); zhClose(); } },true);
