/* ---------- P9l: accounts. Welcome after confirming, refresh after sign in, wipe after delete, change email + password ---------- */
let _sbRecovery=false;
async function sbWipeDevice(){ try{ audio.pause(); }catch(e){} try{ _lsAudio.pause(); }catch(e){}
  const close=async p=>{ try{ const d=await Promise.race([p,new Promise(r=>setTimeout(()=>r(null),800))]); if(d&&d.close) d.close(); }catch(e){} };
  try{ if(_idbPromise) await close(_idbPromise); }catch(e){} try{ if(typeof _bmDBp!=='undefined'&&_bmDBp) await close(_bmDBp); }catch(e){}
  let names=['treesh_media','treesh_beatmaps']; try{ if(indexedDB.databases){ const l=await indexedDB.databases(); (l||[]).forEach(d=>{ if(d&&d.name&&names.indexOf(d.name)<0) names.push(d.name); }); } }catch(e){}
  await Promise.all(names.map(n=>new Promise(res=>{ try{ const r=indexedDB.deleteDatabase(n); r.onsuccess=r.onerror=r.onblocked=()=>res(); setTimeout(res,1500); }catch(e){ res(); } })));
  try{ localStorage.clear(); }catch(e){} try{ sessionStorage.clear(); sessionStorage.setItem('treesh_wiped','1'); }catch(e){}
  try{ if(window.caches&&caches.keys){ const ks=await caches.keys(); await Promise.all(ks.filter(k=>/user|media|audio|cover|img/i.test(k)).map(k=>caches.delete(k))); } }catch(e){} }
function sbWelcomeSetup(){ const p=state.profile||{}; if(state._sbHadProfile&&p.birthday&&p.nickname) return;
  onboard={step:0,nick:(p.nickname&&p.nickname!=='Treesh Fan')?p.nickname:'',bday:p.birthday||'',avatar:p.avatar||''}; try{ renderOnboarding(); }catch(e){ console.warn('welcome',e); } }
function cfType(){ return ((typeof SB_CB!=='undefined'&&SB_CB&&SB_CB.type)||CF_Q.type||'signup'); }
const _cfClose9l=cfClose; cfClose=function(){ const ok=CF.st==='ok'||CF.st==='already', t=cfType();
  if(ok&&CF.reload&&t!=='email_change'&&!state._sbHadProfile){ try{ sessionStorage.setItem('treesh_ob_welcome','1'); }catch(e){} }
  const r=_cfClose9l.apply(this,arguments); if(ok&&!CF.reload&&t!=='email_change'&&t!=='recovery'&&!CF.half) setTimeout(sbWelcomeSetup,360); return r; };
const _cfHtml9l=cfHtml; cfHtml=function(){ let h=_cfHtml9l.apply(this,arguments);
  if(CF.half&&CF.st==='already') return h.replace('You\u2019re all set','One more step').replace(esc('This email is already confirmed and you\u2019re signed in.'),esc(CF.half));
  if(cfType()==='email_change'&&(CF.st==='ok'||CF.st==='already')) return h.replace(/Email confirmed!|You\u2019re all set/,'Email updated').replace(/Welcome to Treesh\. You\u2019re signed in[^<]*|This email is already confirmed and you\u2019re signed in\./,'Your Treesh account now uses this email address. Use it next time you sign in.');
  return h; };
const _cfBoot9l=cfBoot; cfBoot=async function(){ if((typeof SB_CB!=='undefined'&&SB_CB&&SB_CB.type==='recovery')||CF_Q.type==='recovery') _sbRecovery=true; if(CF.on){ const m=/(?:^|[#&])message=([^&]+)/.exec(location.hash||''); if(m){ try{ CF.half=decodeURIComponent(m[1].replace(/\+/g,' ')); history.replaceState(null,'',location.pathname+location.search); }catch(e){ CF.half='Check your other inbox to finish.'; } } } return _cfBoot9l.apply(this,arguments); };
const _sbAO9l=sbAuthOpen; sbAuthOpen=function(mode){ if((mode==='email'||mode==='newpw')&&!sbUser()&&!_sbRecovery) mode='signin'; return _sbAO9l.call(this,mode); };
const _sbHC9l=sbHandleCallback; sbHandleCallback=function(cb){ if(cb&&cb.type==='recovery') _sbRecovery=true; if(cb&&cb.type==='email_change'&&!CF.on) setTimeout(()=>toast('Email updated','Use your new email next time you sign in'),900); return _sbHC9l.apply(this,arguments); };
const _sbInit9l=sbInit; sbInit=function(){ const r=_sbInit9l.apply(this,arguments); try{ if(sb) sb.auth.onAuthStateChange(ev=>{ if(ev==='PASSWORD_RECOVERY') _sbRecovery=true; if(ev==='USER_UPDATED') setTimeout(()=>{ try{ sbPaint(); if(state.profileOpen&&state.settingsEditProfile){ const c=document.querySelector('[data-testid="pf-account-card"]'); if(c){ const t=document.createElement('div'); t.innerHTML=pfAcctHtml(); c.replaceWith(t.firstElementChild); icons(); } } }catch(e){} },0); }); }catch(e){}
  try{ if(sessionStorage.getItem('treesh_wiped')){ sessionStorage.removeItem('treesh_wiped'); setTimeout(()=>toast('Account deleted','Treesh is fresh on this device'),900); } if(sessionStorage.getItem('treesh_ob_welcome')){ sessionStorage.removeItem('treesh_ob_welcome'); setTimeout(sbWelcomeSetup,1200); } }catch(e){} return r; };
function sbPwField(id,label,ac,ph){ return `<label class="sba-f"><span>${label}</span><span class="sba-pw"><input id="${id}" type="password" autocomplete="${ac}" placeholder="${ph}" data-testid="${id.replace('sb-','sb-auth-')}"><button type="button" data-act="sb-pw-eye" data-for="${id}" aria-label="Show password" data-testid="${id}-toggle"><i data-lucide="eye"></i></button></span></label>`; }
function sbAcctFormHtml(){ const m=_sbMode, u=sbUser(), rec=_sbRecovery||!u;
  const hero=(ic,t,d)=>`<div class="sba-hero"><span class="sba-orb"><i data-lucide="${ic}"></i></span></div><h3 class="sba-mt">${t}</h3><p class="sba-md">${d}</p>`;
  if(m==='sent-email') return `<div class="sba-modal" data-testid="sb-email-sent">${hero('mail-check','Confirm your new email',`We sent a link to <b>${esc(_sbSentTo)}</b>. Open it to finish the change. If an email also lands in your current inbox, confirm that one too.`)}<div class="sba-col"><button type="button" data-act="sb-auth-close" data-testid="sb-email-sent-done" class="sba-btn is-primary lg press">Got it</button></div><p class="sba-fine">Until you confirm, you keep signing in with ${esc((u&&u.email)||'your current email')}.</p></div>`;
  if(m==='email') return `<div class="sba-modal" data-testid="sb-change-email-sheet">${hero('at-sign','Change your email','We\u2019ll email a confirmation link to your new address. Nothing changes until you open it.')}<form data-sb-acct class="sba-form" novalidate><div class="sba-cur" data-testid="sb-current-email"><i data-lucide="mail"></i><span>Current</span><b class="clamp-1">${esc((u&&u.email)||'')}</b></div><label class="sba-f"><span>New email</span><input id="sb-email" type="email" autocomplete="email" inputmode="email" autocapitalize="none" spellcheck="false" placeholder="new@example.com" data-testid="sb-new-email"></label><label class="sba-f"><span>Confirm new email</span><input id="sb-email2" type="email" autocomplete="email" inputmode="email" autocapitalize="none" spellcheck="false" placeholder="Type it again" data-testid="sb-new-email-confirm"></label>${sbPwField('sb-pw-cur','Current password','current-password','Your password')}<p id="sb-msg" class="sba-msg" role="status" aria-live="polite" data-testid="sb-auth-msg"></p><button type="submit" data-testid="sb-auth-submit" class="sba-btn is-primary lg press"><i data-lucide="loader-circle" class="sba-spin"></i><span>Send confirmation link</span></button><button type="button" data-act="sb-auth-close" data-testid="sb-auth-cancel" class="sba-btn lg press">Cancel</button></form></div>`;
  return `<div class="sba-modal" data-testid="sb-auth" data-mode="newpw">${hero('key-round',rec?'Choose a new password':'Change your password','Use at least 8 characters. Mixing letters, numbers and symbols makes it stronger.')}<form data-sb-acct class="sba-form" novalidate>${rec?'':sbPwField('sb-pw-cur','Current password','current-password','Your current password')}${sbPwField('sb-pw','New password','new-password','At least 8 characters')}<div class="sba-meter" aria-hidden="true"><i id="sb-pw-bar"></i></div><p class="sba-uhint" id="sb-pw-tip" data-testid="sb-pw-strength">Strength shows here as you type</p>${sbPwField('sb-pw2','Confirm new password','new-password','Type it again')}<p id="sb-msg" class="sba-msg" role="status" aria-live="polite" data-testid="sb-auth-msg"></p><button type="submit" data-testid="sb-auth-submit" class="sba-btn is-primary lg press"><i data-lucide="loader-circle" class="sba-spin"></i><span>Update password</span></button><button type="button" data-act="sb-auth-close" data-testid="sb-auth-cancel" class="sba-btn lg press">Cancel</button></form></div>`; }
const _sbAH9l=sbAuthHtml; sbAuthHtml=function(){ if(_sbMode==='email'||_sbMode==='sent-email'||_sbMode==='newpw') return sbAcctFormHtml(); return _sbAH9l.apply(this,arguments); };
function sbPwScore(p){ let s=0; if(p.length>=8) s++; if(p.length>=12) s++; if(/[a-z]/.test(p)&&/[A-Z]/.test(p)) s++; if(/\d/.test(p)) s++; if(/[^A-Za-z0-9]/.test(p)) s++; return Math.min(4,s); }
document.addEventListener('input',e=>{ if(!e.target||e.target.id!=='sb-pw'||!document.querySelector('form[data-sb-acct]')) return; const v=e.target.value, sc=v?sbPwScore(v):0; const bar=document.getElementById('sb-pw-bar'), tip=document.getElementById('sb-pw-tip');
  if(bar){ bar.style.width=(v?(sc+1)*20:0)+'%'; bar.dataset.s=sc; } if(tip) tip.textContent=!v?'Strength shows here as you type':['Too weak','Weak','Okay','Strong','Very strong'][sc]; });
async function sbAcctSubmit(){ const m=_sbMode, u=sbUser(); const val=id=>((document.getElementById(id)||{}).value||'');
  const busy=on=>{ const b=document.querySelector('#modal2 [data-testid="sb-auth-submit"]'); if(b){ b.disabled=on; b.classList.toggle('is-busy',on); } };
  if(!sb) return sbMsg('err','Accounts aren\u2019t switched on yet.'); if(!navigator.onLine) return sbMsg('err','You\u2019re offline. Connect to the internet and try again.');
  const recheck=async pw=>{ if(!u||!u.email) return true; const {error}=await sb.auth.signInWithPassword({email:u.email,password:pw}); return !error; };
  if(m==='email'){ const e1=val('sb-email').trim().toLowerCase(), e2=val('sb-email2').trim().toLowerCase(), pw=val('sb-pw-cur');
    if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e1)) return sbMsg('err','Enter a valid new email address.'); if(e1!==e2) return sbMsg('err','The two emails don\u2019t match.');
    if(u&&u.email&&e1===u.email.toLowerCase()) return sbMsg('err','That\u2019s already your email.'); if(!pw) return sbMsg('err','Enter your current password to confirm it\u2019s you.');
    busy(true); sbMsg('','');
    try{ if(!(await recheck(pw))){ sbMsg('err','Your current password isn\u2019t right.'); return; } const {error}=await sb.auth.updateUser({email:e1},{emailRedirectTo:SB_CONFIRM_URL}); if(error) throw error; _sbSentTo=e1; try{ localStorage.setItem('sbx_last_email',e1); }catch(_){} sbAuthRender('sent-email'); }
    catch(e){ sbMsg('err',/already/i.test((e&&e.message)||'')?'That email already has a Treesh account.':sbErrText(e)); } finally{ busy(false); } return; }
  const cur=val('sb-pw-cur'), p1=val('sb-pw'), p2=val('sb-pw2'), rec=_sbRecovery||!u;
  if(!rec&&!cur) return sbMsg('err','Enter your current password.'); if(p1.length<8) return sbMsg('err','Use at least 8 characters for your new password.'); if(p1!==p2) return sbMsg('err','The new passwords don\u2019t match.'); if(!rec&&p1===cur) return sbMsg('err','Pick a password that\u2019s different from your current one.');
  busy(true); sbMsg('','');
  try{ if(!rec&&!(await recheck(cur))){ sbMsg('err','Your current password isn\u2019t right.'); return; } const {error}=await sb.auth.updateUser({password:p1}); if(error) throw error; _sbRecovery=false; closeModal2(); toast('Password updated','Use it next time you sign in'); }
  catch(e){ sbMsg('err',/different from the old|same as/i.test((e&&e.message)||'')?'Pick a password you haven\u2019t used before.':sbErrText(e)); } finally{ busy(false); } }
document.addEventListener('submit',e=>{ const f=e.target; if(f&&f.matches&&f.matches('form[data-sb-acct]')){ e.preventDefault(); sbAcctSubmit(); } });
document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act="sb-pw-eye"]'); if(!t) return; const i=document.getElementById(t.dataset.for); if(!i) return; const show=i.type==='password'; i.type=show?'text':'password'; t.setAttribute('aria-label',show?'Hide password':'Show password'); t.innerHTML=`<i data-lucide="${show?'eye-off':'eye'}"></i>`; icons(); });

/* ---------- P9l: manage the online account from Edit profile ---------- */
function pfAcctHtml(){ const u=sbUser(), st=state.sbSync||{s:'idle'};
  const row=(act,val,tid,ic,k,v,cta)=>`<button type="button" data-act="${act}"${val?` data-val="${val}"`:''} data-testid="${tid}" class="pfa-row press"><span class="pfa-row-ic"><i data-lucide="${ic}"></i></span><span class="min-w-0 flex-1"><b>${k}</b><small class="clamp-1">${v}</small></span><em>${cta}<i data-lucide="chevron-right"></i></em></button>`;
  if(!sbReady()||!u) return `<section class="pfa-card" data-testid="pf-account-card"><div class="pfa-head"><span class="pfa-ic"><i data-lucide="cloud"></i></span><div class="min-w-0 flex-1"><h3>Online account</h3><p>${sbReady()?'Sign in to back up your profile, find friends and share your page.':'Accounts aren\u2019t available right now. Your profile is saved on this device.'}</p></div></div>${sbReady()?`<div class="pfa-foot"><button type="button" data-act="sb-auth-open" data-val="signin" data-testid="pf-acct-signin" class="sba-btn is-primary press"><i data-lucide="log-in"></i>Sign in</button><button type="button" data-act="sb-auth-open" data-val="signup" data-testid="pf-acct-signup" class="sba-btn press"><i data-lucide="user-plus"></i>Create account</button></div>`:''}</section>`;
  const syncTxt={saving:'Syncing\u2026',offline:'Waiting for internet',error:'Needs attention',synced:'Up to date'}[st.s]||(sbMeta().at?'Synced '+swAgo(sbMeta().at):'Signed in');
  return `<section class="pfa-card" data-testid="pf-account-card"><div class="pfa-head"><span class="pfa-ic"><i data-lucide="shield-check"></i></span><div class="min-w-0 flex-1"><h3>Online account</h3><p class="clamp-1">Signed in as ${esc(u.email||'')}</p></div>${sbPill()}</div>
   <div class="pfa-rows">${row('sb-auth-open','email','pf-acct-email','at-sign','Email',esc(u.email||''),'Change')}${row('sb-auth-open','newpw','pf-acct-password','key-round','Password','\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022','Change')}${typeof sxPrivacyRow==='function'?sxPrivacyRow():''}${row('sb-sync-now','','pf-acct-sync','refresh-cw','Sync',esc(syncTxt),'Sync now')}</div>
   <div class="pfa-foot"><button type="button" data-act="sb-signout" data-testid="pf-acct-signout" class="sba-btn press"><i data-lucide="log-out"></i>Sign out</button><button type="button" data-act="sb-delete-open" data-testid="pf-acct-delete" class="sba-btn is-danger press"><i data-lucide="trash-2"></i>Delete account</button></div></section>`; }
const _sph9l=settingsProfileHtml; settingsProfileHtml=function(editing){ const h=_sph9l.apply(this,arguments); if(!editing) return h; const k='<div class="mt-4 flex items-center gap-2"><button data-act="save-profile"'; const i=h.indexOf(k); if(i<0) return h; return h.slice(0,i)+'<div class="mt-6">'+pfAcctHtml()+'</div>'+h.slice(i); };
const _sbPaint9l=sbPaint; sbPaint=function(){ const r=_sbPaint9l.apply(this,arguments); try{ const c=document.querySelector('[data-testid="pf-account-card"]'); if(c){ const t=document.createElement('div'); t.innerHTML=pfAcctHtml(); c.replaceWith(t.firstElementChild); icons(); } }catch(e){} return r; };

/* ---------- P9l: badges live with games, Things and Starlites (Stats tab) ---------- */
function pfBadgesSec(){ const S=pfStats(); const earned=PF_BADGES.filter(b=>{ try{ return b.ok(S); }catch(e){ return false; } }).length;
  return `<section class="pf-bdg pf-bdg-stats${pfBdgOpen()?' is-open':''}" data-testid="profile-badges-section"><button type="button" data-act="pf-badges-toggle" data-testid="profile-badges-toggle" aria-expanded="${pfBdgOpen()}" class="pf-bdg-head press mb-2.5 flex w-full items-center gap-2"><h3 class="flex items-center gap-2 text-sm font-bold uppercase tracking-wide text-white/70"><i data-lucide="award" class="text-[color:var(--treesh-gold)]" style="width:15px;height:15px"></i>Badges</h3><span class="ml-auto"></span><span class="rounded-full bg-white/10 px-2.5 py-0.5 text-xs font-semibold text-white/60" data-testid="profile-badge-count">${earned}/${PF_BADGES.length}</span><i data-lucide="chevron-down" class="pf-bdg-chev"></i></button><div class="pf-bdg-peek" data-testid="profile-badges-peek">${pfBdgPeek(S)}</div><div class="grid grid-cols-3 gap-2 sm:grid-cols-4" data-testid="profile-badges">${PF_BADGES.map(b=>{ let ok=false; try{ ok=b.ok(S); }catch(e){} return `<div class="pf-badge${ok?' is-on':''}" data-testid="profile-badge-${b.id}" data-earned="${ok}" title="${esc(b.desc)}"><span class="pf-badge-ic"><i data-lucide="${b.ic}" style="width:18px;height:18px"></i></span><span class="pf-badge-name">${b.label}</span><span class="pf-badge-desc">${ok?'Earned':b.desc}</span></div>`; }).join('')}</div></section>`; }
const _pst9l=profileStatsHtml; profileStatsHtml=function(){ const h=_pst9l.apply(this,arguments); const i=h.indexOf('</section>'); return i<0?h+pfBadgesSec():h.slice(0,i+10)+pfBadgesSec()+h.slice(i+10); };

/* ---------- P9l: Support + Feedback forms (Settings, System & About) ---------- */
const TS_TOPICS=[
  {id:'play',ic:'play-circle',l:'Playback & sound',sym:['A song won\u2019t play','No sound','Skips or stutters','Stops in the background','Lyrics out of sync','Equalizer or volume'],tips:['Check your phone isn\u2019t on silent and the Treesh volume is up.','Turn off Low Power Mode, then play again.','Settings \u2192 Audio & Playback \u2192 turn the equalizer off and on.']},
  {id:'music',ic:'disc-3',l:'My music & uploads',sym:['Upload fails','A link won\u2019t add','Cover art missing','Songs disappeared','Storage full','Editing a track'],tips:['Songs must be audio files under 30 MB.','Links need to point straight to the audio file (Dropbox or GitHub links work).','Custom music lives on this device. Clearing browser data removes it.']},
  {id:'lyrics',ic:'quote',l:'Lyrics & Lyric Studio',sym:['Can\u2019t save lyrics','Timing is off','Formatting looks wrong','Find lyrics online fails','Lyric cards'],tips:['Tap Save before closing Lyric Studio.','In Sync, tap a timestamp to jump there and re-set it.']},
  {id:'acct',ic:'user-round',l:'Account & sync',sym:['Can\u2019t sign in','No confirmation email','Changes not syncing','Change email or password','Delete my account'],tips:['Check your spam folder for Treesh emails.','Settings \u2192 Account & Data \u2192 Sync now.','Use Forgot password on the sign in screen.']},
  {id:'social',ic:'users-round',l:'Profile & friends',sym:['Can\u2019t find someone','Friend request stuck','Privacy settings','Report a profile','Profile looks wrong'],tips:['Search Users by their @username.','Private profiles show after they accept your friend request.']},
  {id:'games',ic:'gamepad-2',l:'Games & Things',sym:['Game won\u2019t start','Score didn\u2019t save','Hoop or a Thing won\u2019t open','Starlites or badges'],tips:['Starlites update after each game ends.','Allow pop-ups so Things can open in their own window.']},
  {id:'look',ic:'wand-sparkles',l:'Magic Markup & themes',sym:['Edits didn\u2019t save','Page looks broken','Theme or accent','Widgets'],tips:['In Magic Markup, use Reset on an element to undo it.','Settings \u2192 Appearance to switch themes.']},
  {id:'voice',ic:'mic',l:'Voice assistant',sym:['It can\u2019t hear me','Wrong command','Spoken replies'],tips:['Allow microphone access for Treesh in your browser settings.','Tap the keyboard to type a command instead.']},
  {id:'other',ic:'circle-help',l:'Something else',sym:[],tips:[]}];
const TS_FAV=['Now Playing','Lyrics & karaoke','Lyric Studio','Instrum beats','Games','Magic Markup','Image Studio','Voice assistant','Things','Profiles & friends'];
const TS_USE=['Listening','Karaoke','Writing lyrics','Making beats','Games','Customizing','Things'];
let _ts=null;
function tsEmail(){ const u=sbUser(); return (u&&u.email)||''; }
function tsDevice(){ const n=navigator, s=screen||{}; let os='Unknown'; const ua=n.userAgent||''; if(/iPhone|iPad|iPod/.test(ua)) os='iOS'; else if(/Android/.test(ua)) os='Android'; else if(/Mac OS X/.test(ua)) os='macOS'; else if(/Windows/.test(ua)) os='Windows'; else if(/Linux/.test(ua)) os='Linux';
  const br=/Edg\//.test(ua)?'Edge':/OPR\//.test(ua)?'Opera':/CriOS|Chrome\//.test(ua)?'Chrome':/FxiOS|Firefox\//.test(ua)?'Firefox':/Safari\//.test(ua)?'Safari':'Browser';
  return {OS:os,Browser:br,Screen:(s.width||0)+'\u00d7'+(s.height||0)+' @'+(window.devicePixelRatio||1)+'x',Window:innerWidth+'\u00d7'+innerHeight,Installed:(matchMedia('(display-mode: standalone)').matches||n.standalone)?'Yes':'No',Online:n.onLine?'Yes':'No',Theme:(state.theme||'dark')+' / '+(typeof glTheme==='function'?glTheme():''),'Signed in':sbUser()?'Yes':'No (guest)',Language:n.language||'',App:'Treesh 3.0',UserAgent:ua}; }
function tsOpen(kind){ _ts={kind,topic:null,sym:[],sev:'',when:'',stars:0,ease:0,nps:-1,use:[],dev:true}; $("#modal2").innerHTML=modal2Wrap(`<div class="tsf" data-testid="${kind}-form-sheet">${kind==='support'?tsSupportHtml():tsFeedbackHtml()}</div>`,kind+'-modal','xl'); syncScrollLock(); icons(); }
function tsEmailField(){ const em=tsEmail(); return em?`<div class="tsf-me" data-testid="ts-email-signed-in"><span class="tsf-me-ic"><i data-lucide="mail-check"></i></span><span class="min-w-0 flex-1"><small>We\u2019ll reply to</small><b class="clamp-1">${esc(em)}</b></span><span class="tsf-tag">Your account</span></div>`
  :`<label class="sba-f"><span>Your email <i class="tsf-req">required</i></span><input id="ts-email" type="email" autocomplete="email" inputmode="email" autocapitalize="none" spellcheck="false" placeholder="you@example.com" data-testid="ts-email-input"></label>`; }
function tsHead(ic,t,d){ return `<div class="tsf-head"><span class="sba-orb"><i data-lucide="${ic}"></i></span><div class="min-w-0 flex-1"><h3 class="tsf-t">${t}</h3><p class="tsf-d">${d}</p></div><button type="button" data-act="modal2-close" aria-label="Close" data-testid="ts-close" class="tsf-x press"><i data-lucide="x"></i></button></div>`; }
function tsSupportHtml(){ const T=TS_TOPICS.find(x=>x.id===_ts.topic);
  return `${tsHead('life-buoy','Contact support','Pick what\u2019s going on and we\u2019ll point you to a fix, or send it straight to the Treesh team.')}<form data-ts-form="support" class="tsf-form" novalidate>
   <div class="tsf-q"><p class="tsf-k">What do you need help with?</p><div class="tsf-topics" data-testid="ts-topics">${TS_TOPICS.map(t=>`<button type="button" data-act="ts-topic" data-val="${t.id}" data-testid="ts-topic-${t.id}" aria-pressed="${_ts.topic===t.id}" class="tsf-topic press${_ts.topic===t.id?' on':''}"><i data-lucide="${t.ic}"></i><span>${t.l}</span></button>`).join('')}</div></div>
   <div id="ts-topic-more">${T?tsTopicMore(T):''}</div>
   <div class="tsf-q"><p class="tsf-k">How much is it affecting you?</p><div class="tsf-seg" data-testid="ts-severity">${[['q','Just a question'],['a','It\u2019s annoying'],['b','I can\u2019t use Treesh']].map(([k,l])=>`<button type="button" data-act="ts-sev" data-val="${k}" data-testid="ts-sev-${k}" class="tsf-seg-b${_ts.sev===k?' on':''}">${l}</button>`).join('')}</div></div>
   <div class="tsf-grid"><label class="sba-f"><span>When did it start?</span><select id="ts-when" class="tsf-sel" data-testid="ts-when"><option value="">Pick one</option>${['Just now','Today','This week','After an update','A while ago','Not sure'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="sba-f"><span>Your name <i class="tsf-opt">optional</i></span><input id="ts-name" maxlength="60" autocomplete="name" placeholder="${esc((state.profile&&state.profile.nickname)||'Your name')}" data-testid="ts-name-input"></label></div>
   <label class="sba-f"><span>Tell us more</span><textarea id="ts-msg" rows="5" maxlength="4000" placeholder="What happened? What did you expect? Steps help us fix it fast." class="tsf-ta" data-testid="ts-message-input"></textarea></label>
   ${tsEmailField()}
   <label class="tsf-chk"><input type="checkbox" id="ts-dev" checked data-testid="ts-device-toggle"><span><b>Include device info</b><small>${esc(Object.entries(tsDevice()).filter(([k])=>k!=='UserAgent').slice(0,4).map(([k,v])=>v).join(' \u00b7 '))}</small></span></label>
   <p id="ts-msg-out" class="sba-msg" role="status" aria-live="polite" data-testid="ts-status"></p>
   <button type="submit" class="sba-btn is-primary lg press" data-testid="ts-submit"><i data-lucide="loader-circle" class="sba-spin"></i><i data-lucide="send"></i><span>Send to support</span></button>
   <p class="sba-fine">Goes to support@treesh.app. We usually reply within 2 days.</p></form>`; }
function tsTopicMore(T){ return `${T.sym.length?`<div class="tsf-q tsf-in"><p class="tsf-k">What\u2019s happening? <i class="tsf-opt">pick any</i></p><div class="tsf-chips" data-testid="ts-symptoms">${T.sym.map((s,i)=>`<button type="button" data-act="ts-sym" data-val="${esc(s)}" data-testid="ts-sym-${i}" aria-pressed="${_ts.sym.includes(s)}" class="tsf-chip press${_ts.sym.includes(s)?' on':''}">${esc(s)}</button>`).join('')}</div></div>`:''}${T.tips.length?`<div class="tsf-tips tsf-in" data-testid="ts-tips"><p><i data-lucide="lightbulb"></i>Try this first</p><ul>${T.tips.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}`; }
function tsFeedbackHtml(){ const S=['','Not for me','Needs work','It\u2019s okay','I like it','I love it!'];
  return `${tsHead('message-square-heart','Send feedback','Tell us how Treesh feels. Every answer shapes what we build next.')}<form data-ts-form="feedback" class="tsf-form" novalidate>
   <div class="tsf-q tsf-stars-q"><p class="tsf-k">How would you rate Treesh?</p><div class="tsf-stars" role="radiogroup" aria-label="Rating" data-testid="ts-stars">${[1,2,3,4,5].map(n=>`<button type="button" role="radio" aria-checked="${_ts.stars===n}" data-act="ts-star" data-val="${n}" data-testid="ts-star-${n}" aria-label="${n} star${n>1?'s':''}" class="tsf-star press${_ts.stars>=n?' on':''}"><i data-lucide="star"></i></button>`).join('')}</div><input type="range" min="0" max="5" step="1" value="${_ts.stars}" id="ts-stars-range" class="tr tsf-range" aria-label="Rating out of 5" data-testid="ts-stars-range"><p class="tsf-star-l" id="ts-star-l" data-testid="ts-star-label">${_ts.stars?S[_ts.stars]:'Tap a star or slide'}</p></div>
   <div class="tsf-q"><p class="tsf-k">What do you use Treesh for most? <i class="tsf-opt">pick any</i></p><div class="tsf-chips" data-testid="ts-uses">${TS_USE.map((u,i)=>`<button type="button" data-act="ts-use" data-val="${esc(u)}" data-testid="ts-use-${i}" aria-pressed="${_ts.use.includes(u)}" class="tsf-chip press${_ts.use.includes(u)?' on':''}">${esc(u)}</button>`).join('')}</div></div>
   <div class="tsf-q"><p class="tsf-k">How easy is Treesh to use?</p><div class="tsf-seg is-5" data-testid="ts-ease">${['Very hard','Hard','Okay','Easy','Very easy'].map((l,i)=>`<button type="button" data-act="ts-ease" data-val="${i+1}" data-testid="ts-ease-${i+1}" class="tsf-seg-b${_ts.ease===i+1?' on':''}">${l}</button>`).join('')}</div></div>
   <div class="tsf-q"><p class="tsf-k">How likely are you to recommend Treesh to a friend?</p><div class="tsf-nps" data-testid="ts-nps">${Array.from({length:11},(_,n)=>`<button type="button" data-act="ts-nps" data-val="${n}" data-testid="ts-nps-${n}" class="tsf-nps-b${_ts.nps===n?' on':''}">${n}</button>`).join('')}</div><div class="tsf-nps-l"><span>Not likely</span><span>Very likely</span></div></div>
   <label class="sba-f"><span>Favorite feature</span><select id="ts-fav" class="tsf-sel" data-testid="ts-fav"><option value="">Pick one</option>${TS_FAV.map(x=>`<option>${x}</option>`).join('')}</select></label>
   <label class="sba-f"><span>What should we improve or add?</span><textarea id="ts-better" rows="4" maxlength="3000" placeholder="Ideas, wishes, things that bug you\u2026" class="tsf-ta" data-testid="ts-improve-input"></textarea></label>
   <label class="sba-f"><span>Anything else? <i class="tsf-opt">optional</i></span><textarea id="ts-else" rows="2" maxlength="2000" class="tsf-ta" data-testid="ts-else-input"></textarea></label>
   ${tsEmailField()}
   <p id="ts-msg-out" class="sba-msg" role="status" aria-live="polite" data-testid="ts-status"></p>
   <button type="submit" class="sba-btn is-primary lg press" data-testid="ts-submit"><i data-lucide="loader-circle" class="sba-spin"></i><i data-lucide="send"></i><span>Send feedback</span></button>
   <p class="sba-fine">Goes to feedback@treesh.app. Thank you for helping Treesh grow.</p></form>`; }
function tsSetStars(n){ _ts.stars=n; const S=['','Not for me','Needs work','It\u2019s okay','I like it','I love it!']; document.querySelectorAll('#modal2 .tsf-star').forEach(b=>{ const v=+b.dataset.val; b.classList.toggle('on',v<=n); b.setAttribute('aria-checked',String(v===n)); }); const r=document.getElementById('ts-stars-range'); if(r){ r.value=n; try{ fillSlider(r); }catch(e){} } const l=document.getElementById('ts-star-l'); if(l) l.textContent=n?S[n]:'Tap a star or slide'; }
/* sending is off until the Resend edge function (treesh-mail) is set up; flip to true then */
const TS_SEND_ON=false;
function tsAboutRows(){ const r=(v,ic,t,d)=>`<button type="button" data-act="ts-open" data-val="${v}" data-testid="about-${v}-open" class="press flex w-full items-center justify-between gap-3 px-4 py-3.5 text-left transition-colors hover:bg-white/5"><span class="flex min-w-0 items-center gap-3"><i data-lucide="${ic}" class="shrink-0 text-white/60" style="width:17px;height:17px"></i><span class="min-w-0"><span class="block text-sm font-semibold">${t}</span><span class="block text-xs text-white/45">${d}</span></span></span><i data-lucide="chevron-right" class="shrink-0 text-white/40" style="width:16px;height:16px"></i></button>`;
  return `<p class="mb-2 mt-5 text-xs font-bold uppercase tracking-[0.2em] text-white/50">Help &amp; feedback</p><div class="overflow-hidden rounded-2xl border border-white/10 divide-y divide-white/10" data-testid="settings-help">${r('support','life-buoy','Contact support','Get help from the Treesh team')}${r('feedback','message-square-heart','Send feedback','Rate Treesh and tell us what to build next')}</div>`; }
async function tsSend(kind,p){ if(!TS_SEND_ON||!sb||!sb.functions) throw new Error('sending off');
  const {data,error}=await sb.functions.invoke('treesh-mail',{body:{kind,to:kind==='support'?'support@treesh.app':'feedback@treesh.app',subject:p.subject,replyTo:p.email,name:p.name||'',fields:p.fields,text:p.text}});
  if(error||!(data&&data.ok)) throw new Error((error&&error.message)||'send failed'); return 'resend'; }
async function tsSubmit(kind){ const out=document.getElementById('ts-msg-out'), btn=document.querySelector('#modal2 [data-testid="ts-submit"]'); const say=(k,t)=>{ if(out){ out.innerHTML=t; out.className='sba-msg'+(k?' is-'+k:''); } };
  const v=id=>((document.getElementById(id)||{}).value||'').trim(); const email=tsEmail()||v('ts-email');
  if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){ say('err','Enter your email so we can get back to you.'); const i=document.getElementById('ts-email'); if(i) i.focus(); return; }
  const u=sbUser(), p=state.profile||{}; let subject, fields, text;
  if(kind==='support'){ const T=TS_TOPICS.find(x=>x.id===_ts.topic); const msg=v('ts-msg');
    if(!T){ say('err','Pick what you need help with.'); return; } if(!msg&&!_ts.sym.length){ say('err','Pick what\u2019s happening or tell us a bit more.'); document.getElementById('ts-msg').focus(); return; }
    const sev={q:'Just a question',a:'Annoying',b:'Blocking'}[_ts.sev]||'Not set';
    subject='[Support] '+T.l+(_ts.sym[0]?' \u00b7 '+_ts.sym[0]:'')+(_ts.sev==='b'?' (blocking)':'');
    fields={Topic:T.l,Symptoms:_ts.sym.join(', ')||'None picked',Impact:sev,Started:v('ts-when')||'Not set',Name:v('ts-name')||p.nickname||'',Email:email,Username:p.username?'@'+p.username:'',Account:u?'Signed in ('+u.id+')':'Guest'};
    if(document.getElementById('ts-dev')&&document.getElementById('ts-dev').checked) Object.entries(tsDevice()).forEach(([k,x])=>{ fields['Device '+k]=x; });
    text=msg||'(No extra details)'; }
  else { if(!_ts.stars){ say('err','Give Treesh a star rating first.'); return; }
    subject='[Feedback] '+'\u2605'.repeat(_ts.stars)+'\u2606'.repeat(5-_ts.stars)+(v('ts-fav')?' \u00b7 loves '+v('ts-fav'):'');
    fields={Rating:_ts.stars+' / 5',Uses:_ts.use.join(', ')||'Not set','Ease of use':_ts.ease?_ts.ease+' / 5':'Not set',Recommend:_ts.nps>=0?_ts.nps+' / 10':'Not set','Favorite feature':v('ts-fav')||'Not set',Email:email,Username:p.username?'@'+p.username:'',Account:u?'Signed in':'Guest',Device:Object.values(tsDevice()).slice(0,3).join(' \u00b7 ')};
    text='Improve or add:\n'+(v('ts-better')||'-')+'\n\nAnything else:\n'+(v('ts-else')||'-'); }
  if(!navigator.onLine){ say('err','You\u2019re offline. Connect to the internet and try again.'); return; }
  if(btn){ btn.disabled=true; btn.classList.add('is-busy'); } say('','Sending\u2026');
  try{ await tsSend(kind,{subject,email,name:fields.Name||p.nickname||'',fields,text}); const sheet=document.querySelector('#modal2 .tsf');
    if(sheet) sheet.innerHTML=`<div class="tsf-done" data-testid="ts-sent"><span class="sba-orb is-ok"><i data-lucide="${kind==='support'?'mail-check':'heart-handshake'}"></i></span><h3 class="sba-mt">${kind==='support'?'Message sent':'Thank you!'}</h3><p class="sba-md">${kind==='support'?`We\u2019ll reply to <b>${esc(email)}</b> as soon as we can.`:'Your feedback went straight to the Treesh team.'}</p><button type="button" data-act="modal2-close" data-testid="ts-done" class="sba-btn is-primary lg press mt-6">Done</button></div>`; icons(); }
  catch(e){ console.warn('send',e); const to=kind==='support'?'support@treesh.app':'feedback@treesh.app'; const mail='mailto:'+to+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(Object.entries(fields).map(([k,x])=>k+': '+x).join('\n')+'\n\n'+text);
    say('err',`${TS_SEND_ON?'Couldn\u2019t send right now.':'Sending from Treesh isn\u2019t switched on yet.'} <a href="${esc(mail)}" class="sba-link" data-testid="ts-mailto">Email ${to} instead</a>`); }
  finally{ if(btn){ btn.disabled=false; btn.classList.remove('is-busy'); } } }
document.addEventListener('submit',e=>{ const f=e.target; if(f&&f.matches&&f.matches('form[data-ts-form]')){ e.preventDefault(); tsSubmit(f.dataset.tsForm); } });
document.addEventListener('input',e=>{ if(e.target&&e.target.id==='ts-stars-range'&&_ts) tsSetStars(+e.target.value); });
document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act]'); if(!t) return; const a=t.dataset.act, v=t.dataset.val;
  if(a==='ts-open'){ tsOpen(v==='feedback'?'feedback':'support'); return; }
  if(a==='modal2-close'&&t.closest('.tsf')){ closeModal2(); return; }
  if(!_ts||!t.closest('.tsf')) return;
  const tog=(arr,x)=>{ const i=arr.indexOf(x); if(i<0) arr.push(x); else arr.splice(i,1); };
  switch(a){
    case 'ts-topic': { _ts.topic=v; _ts.sym=[]; document.querySelectorAll('#modal2 .tsf-topic').forEach(b=>{ const on=b.dataset.val===v; b.classList.toggle('on',on); b.setAttribute('aria-pressed',String(on)); }); const m=document.getElementById('ts-topic-more'); if(m){ m.innerHTML=tsTopicMore(TS_TOPICS.find(x=>x.id===v)); icons(); } break; }
    case 'ts-sym': tog(_ts.sym,v); t.classList.toggle('on'); t.setAttribute('aria-pressed',String(t.classList.contains('on'))); break;
    case 'ts-use': tog(_ts.use,v); t.classList.toggle('on'); t.setAttribute('aria-pressed',String(t.classList.contains('on'))); break;
    case 'ts-sev': _ts.sev=v; t.parentElement.querySelectorAll('.tsf-seg-b').forEach(b=>b.classList.toggle('on',b===t)); break;
    case 'ts-ease': _ts.ease=+v; t.parentElement.querySelectorAll('.tsf-seg-b').forEach(b=>b.classList.toggle('on',b===t)); break;
    case 'ts-nps': _ts.nps=+v; t.parentElement.querySelectorAll('.tsf-nps-b').forEach(b=>b.classList.toggle('on',b===t)); break;
    case 'ts-star': tsSetStars(+v); break;
  } });
