/* ---------- P9m: people. Search users, public profiles, friends, blocking, privacy ---------- */
const SX_SECS=[['zodiac','Zodiac & birthday','sparkles'],['badges','Badges & stats','award'],['favorites','Favorites','heart'],['lyrics','Favorite lyrics','quote'],['disliked','Disliked','heart-crack'],['playlists','Playlists','list-music'],['listening','Top listening','chart-no-axes-column'],['friendlist','Friend list','users-round']];
const SX_VIS=[['everyone','Everyone','globe'],['friends','Friends','users-round'],['me','Only me','lock']];
let _sxQ={q:null,res:[],err:null,pend:null,t:0,seq:0}, _sxV=null, _sxF=null, _sxPubT=0;
function sxCfg(){ const d=LS.get('treesh_social',null)||{}; const s=Object.assign({},d.sections||{}); SX_SECS.forEach(([k])=>{ if(!['everyone','friends','me'].includes(s[k])) s[k]='everyone'; }); return {private:!!d.private,sections:s}; }
function sxSaveCfg(c){ LS.set('treesh_social',c); sxPublishSoon(true); }
async function sxRpc(fn,args){ if(!sb) throw new Error('offline'); const {data,error}=await sb.rpc(fn,args||{}); if(error){ if(error.code==='PGRST202'||error.code==='42883'||/Could not find the function/i.test(error.message||'')) state._sxNoSql=true; throw error; } return data; }
function sxErr(e){ if(state._sxNoSql) return 'Friends and public profiles aren\u2019t switched on yet.'; if(!navigator.onLine||sbIsNet((e&&e.message)||'')) return 'You\u2019re offline. Connect to the internet and try again.'; return sbErrText(e); }
function sxAv(u,cls){ const n=(u&&(u.display_name||u.username))||'T'; return `<span class="sx-av ${cls||''}">${u&&u.avatar_url?`<img src="${esc(u.avatar_url)}" alt="" loading="lazy">`:`<b>${esc(n.charAt(0).toUpperCase())}</b>`}</span>`; }
const SX_REL={friends:['user-check','Friends','is-ok'],outgoing:['clock','Requested','is-wait'],incoming:['user-plus','Wants to be friends','is-hot'],blocked:['ban','Blocked','is-err']};
function sxRelChip(r){ const k=SX_REL[r]; return k?`<span class="sx-rel ${k[2]}"><i data-lucide="${k[0]}"></i>${k[1]}</span>`:''; }

/* publish my public page: profile row columns, banner in the avatars bucket */
function sxSong(s){ return s?{id:s.id,t:s.title||'',a:s.artist||'',c:/^https?:/.test(s.coverArt||'')?s.coverArt:''}:null; }
function sxSnapshot(){ const p=state.profile||{}; const S=pfStats(); let lyr=[]; try{ lyr=favLyricGroups(); }catch(e){}
  const D=(mkS().pages||{}).profile, deep={}; if(D&&D.deep) Object.keys(D.deep).forEach(k=>{ if(k.indexOf('T:')===0&&Object.keys(deep).length<40) deep[k]=D.deep[k]; });
  return {v:1,nickname:p.nickname||'',zodiac:zodiac(p.birthday)||'',bday:bdMd(p.birthday),joined:pfJoined(p),accent:state.accent||'',theme:glTheme(),
    stats:{plays:S.plays,minutes:S.minutes,likes:S.likes,playlists:S.playlists,points:S.points,streak:S.streak},
    badges:PF_BADGES.filter(b=>{ try{ return b.ok(S); }catch(e){ return false; } }).map(b=>b.id),
    top:{song:sxSong(S.top),artist:S.topArtist?{n:S.topArtist.name||'',img:S.topArtist.image||''}:null},
    favorites:favSongs().slice(0,80).map(sxSong), disliked:dislikedSongs().slice(0,80).map(sxSong),
    lyrics:lyr.slice(0,30).map(g=>({id:g.songId,t:g.title||'',a:g.artist||'',c:/^https?:/.test(g.coverArt||'')?g.coverArt:'',lines:(g.lines||[]).slice(0,6).map(l=>l.text||'')})),
    playlists:(state.playlists||[]).slice(0,20).map(pl=>({id:pl.id,name:pl.name||'Playlist',songs:(pl.songIds||[]).map(id=>SONG_BY_ID[id]).filter(Boolean).slice(0,60).map(sxSong)})),
    custom:{deep}}; }
function sxPublishSoon(now){ clearTimeout(_sxPubT); _sxPubT=setTimeout(()=>sxPublish(!!now),now?200:1500); }
async function sxPublish(force){ const u=sbUser(); if(!sb||!u||state._sxNoCols||!navigator.onLine) return;
  try{ const c=sxCfg(), snap=sxSnapshot(), m=sbMeta(); let banner=m.bannerUrl||null; const bd=state.profileBanner||'';
    if(stMuted()){ if(bd&&/^data:image\//.test(bd)) localStorage.setItem('sbx_bn_held','1'); } else if(!bd) banner=null; else if(/^data:image\//.test(bd)){ const sig=sbSig(bd); if(sig!==m.bannerSig||!banner){ const b=await (await fetch(bd)).blob(); const path=u.id+'/banner.jpg'; const {error}=await sb.storage.from('avatars').upload(path,b,{upsert:true,contentType:b.type||'image/jpeg',cacheControl:'3600'}); if(error) throw error; banner=sb.storage.from('avatars').getPublicUrl(path).data.publicUrl+'?v='+Date.now(); sbMeta({bannerSig:sig}); } } else if(/^https?:/.test(bd)) banner=bd;
    const row={is_private:c.private,privacy:c.sections,public_data:snap,banner_url:banner}; const sig=sbSig(JSON.stringify(row)); if(!force&&sig===m.pubSig) return;
    const {error}=await sb.from('profiles').update(row).eq('id',u.id); if(error){ if(error.code==='42703'||error.code==='PGRST204'||/column/i.test(error.message||'')){ state._sxNoCols=true; console.warn('Treesh social: run supabase_social.sql to switch on public profiles'); return; } throw error; }
    sbMeta({pubSig:sig,bannerUrl:banner}); }
  catch(e){ console.warn('Treesh public profile',e); } }
const _sbPush9m=sbPush; sbPush=async function(){ const r=await _sbPush9m.apply(this,arguments); try{ if(sbUser()&&state.sbSync&&state.sbSync.s==='synced') sxPublish(false); }catch(e){} return r; };

/* search: Users tab */
function sxSearchSoon(q){ if(_sxQ.pend===q) return; _sxQ.pend=q; clearTimeout(_sxQ.t); const seq=++_sxQ.seq;
  _sxQ.t=setTimeout(async()=>{ let res=[], err=null; try{ res=(await sxRpc('search_users',{q}))||[]; }catch(e){ err=e; } if(seq!==_sxQ.seq) return; _sxQ.q=q; _sxQ.res=res; _sxQ.err=err; _sxQ.pend=null;
    if(state.searchOpen&&state.searchTab==='users'){ const r=document.getElementById('search-results'); if(r){ r.innerHTML=searchResultsHtml(); icons(); } } },260); }
function sxEmpty(ic,t,d,extra){ return `<div class="sx-empty" data-testid="users-search-empty"><span class="sx-empty-ic"><i data-lucide="${ic}"></i></span><p class="sx-empty-t">${t}</p>${d?`<p class="sx-empty-d">${d}</p>`:''}${extra||''}</div>`; }
function sxSearchHtml(){ const q=(state.searchQuery||'').trim().replace(/^@+/,'').toLowerCase();
  if(!sb) return sxEmpty('cloud-off','People search is offline','Connect to the internet to find friends on Treesh.');
  if(!q) return sxEmpty('users-round','Find people on Treesh','Search by @username or name to see their profile and add them as a friend.',sbUser()?`<button type="button" data-act="sx-friends" data-testid="users-search-my-friends" class="sba-btn press mt-4"><i data-lucide="users-round"></i>Your friends</button>`:`<button type="button" data-act="sb-auth-open" data-val="signin" data-testid="users-search-signin" class="sba-btn is-primary press mt-4"><i data-lucide="log-in"></i>Sign in to add friends</button>`);
  if(_sxQ.q!==q){ sxSearchSoon(q); return `<div class="sx-list" data-testid="users-search-loading">${[0,1,2].map(i=>`<div class="sx-row is-skel" style="--d:${i*60}ms"><span class="sx-av"></span><span class="flex-1"><i></i><i></i></span></div>`).join('')}</div>`; }
  if(_sxQ.err) return sxEmpty('triangle-alert','Couldn\u2019t search people',esc(sxErr(_sxQ.err)));
  if(!_sxQ.res.length) return sxEmpty('search-x','No one matches \u201c'+esc(q)+'\u201d','Check the spelling or try their exact @username.');
  return `<div class="sx-list" data-testid="users-search-results">${_sxQ.res.map((u,i)=>`<button type="button" data-act="sx-open" data-u="${esc(u.username)}" data-testid="search-result-user-${esc(u.username)}" class="sx-row press" style="--d:${Math.min(i,8)*40}ms">${sxAv(u)}<span class="min-w-0 flex-1"><b class="sx-nm"><span class="clamp-1">${hlMatch(u.display_name||u.username,q)}</span>${sxNameBadges(u,false,u.username)}</b><small class="clamp-1">@${hlMatch(u.username,q)}${u.is_private?' \u00b7 <i data-lucide="lock" class="sx-lock"></i>Private':''}${u.suspended?' \u00b7 <span class="sx-susp">Suspended</span>':''}</small></span>${sxRelChip(u.relation)}<i data-lucide="chevron-right" class="sx-chev"></i></button>`).join('')}</div>`; }
const _srh9m=searchResultsHtml; searchResultsHtml=function(){ if(state.searchTab==='users') return sxSearchHtml(); return _srh9m.apply(this,arguments); };
const _sph9m=searchPlaceholder; searchPlaceholder=function(){ return state.searchTab==='users'?'Search people by @username or name\u2026':_sph9m.apply(this,arguments); };
const _ust9m=updateSearchTabs; updateSearchTabs=function(){ const r=_ust9m.apply(this,arguments); const i=document.getElementById('search-input'); if(i) i.placeholder=searchPlaceholder(); return r; };

/* someone else's profile */
function sxClose(){ const r=document.getElementById('sx-root'); _sxV=null; if(!r) return; r.classList.add('is-out'); setTimeout(()=>{ if(!_sxV) r.remove(); syncScrollLock(); },260); }
async function sxOpenProfile(uname){ uname=String(uname||'').replace(/^@+/,'').toLowerCase(); if(!uname) return; const me=state.profile&&state.profile.usernameSynced;
  if(sbUser()&&me&&me===uname){ if(state.searchOpen) closeSearch(); openProfile(); return; }
  _sxV={u:uname,d:null,tab:'listening',busy:true}; sxRender(); let d=null, err=null; try{ d=await sxRpc('get_user_profile',{uname}); }catch(e){ err=e; }
  if(!_sxV||_sxV.u!==uname) return; _sxV.busy=false; _sxV.d=d; _sxV.err=err; if(d&&d.data){ const T=sxTabs(d); if(T.length&&!T.some(t=>t[0]===_sxV.tab)) _sxV.tab=T[0][0]; } sxRender(); }
function sxTabs(d){ const D=(d&&d.data)||{}, L=(d&&d.locked)||[]; return [['listening','Top','chart-no-axes-column'],['favorites','Favorites','heart'],['lyrics','Lyrics','quote'],['disliked','Disliked','heart-crack'],['playlists','Playlists','list-music'],['badges','Badges','award'],['friendlist','Friends','users-round']].filter(([k])=>(k==='friendlist'?d.friend_list!=null:D[k]!=null)||L.includes(k)); }
function sxRender(){ let r=document.getElementById('sx-root'); const fresh=!r; if(!r){ r=document.createElement('div'); r.id='sx-root'; document.body.appendChild(r); }
  const V=_sxV, d=V&&V.d, acc=d&&d.data&&/^#[0-9a-f]{3,8}$/i.test(d.data.accent||'')?d.data.accent:'';
  r.innerHTML=`<div class="sx-bd${fresh?' is-in':''}" data-act="sx-close" data-testid="user-profile-backdrop"></div><div class="sx-panel dark-surface${fresh?' is-in':''}" role="dialog" aria-modal="true" aria-label="Profile" data-testid="user-profile" ${acc?`style="--treesh-purple:${acc}"`:''}><div class="sx-top"><button type="button" data-act="sx-close" aria-label="Back" data-testid="user-profile-close" class="sx-x press"><i data-lucide="arrow-left"></i></button><span class="sx-top-t clamp-1">${d?'@'+esc(d.username):'Profile'}</span><span class="sx-top-r">${d&&d.mod&&d.relation!=='self'?`<button type="button" data-act="mod-open" aria-label="Moderate" title="Moderate" data-testid="user-profile-moderate" class="sx-x press is-mod"><i data-lucide="gavel"></i></button>`:''}${d&&sbUser()&&d.relation!=='self'?`<button type="button" data-act="sx-menu" aria-label="More" data-testid="user-profile-menu" class="sx-x press"><i data-lucide="ellipsis"></i></button>`:'<span class="w-10"></span>'}</span></div><div class="sx-scroll soft-scroll" id="sx-scroll">${sxBodyHtml()}</div></div>`;
  icons(); syncScrollLock(); sxApplyCustom(); }
function sxBodyHtml(){ const V=_sxV; if(!V) return ''; if(V.busy) return `<div class="sx-load" data-testid="user-profile-loading"><span class="sx-spin"></span><p>Opening @${esc(V.u)}\u2026</p></div>`;
  if(V.err) return sxEmpty('triangle-alert','Couldn\u2019t open this profile',esc(sxErr(V.err)),`<button type="button" data-act="sx-retry" data-testid="user-profile-retry" class="sba-btn press mt-4"><i data-lucide="rotate-ccw"></i>Try again</button>`);
  const d=V.d; if(!d) return sxEmpty('user-x','Profile not found','@'+esc(V.u)+' doesn\u2019t exist or isn\u2019t available.');
  const D=d.data||{}, name=d.display_name||D.nickname||d.username; let joined=''; try{ const j=D.joined||Date.parse(d.created_at||''); if(j) joined=new Date(j).toLocaleDateString(undefined,{month:'long',year:'numeric'}); }catch(e){}
  const banner=d.banner_url?`background-image:url('${esc(d.banner_url)}');background-size:cover;background-position:center`:'background:radial-gradient(120% 150% at 0% 0%, var(--treesh-purple) 0%, transparent 55%), radial-gradient(110% 140% at 100% 100%, color-mix(in srgb, var(--treesh-purple) 40%, #22d3ee) 0%, transparent 62%), #120f1c';
  const zi=D.zodiac?ZH_IC[ZH_SIGNS.findIndex(x=>x[1]===D.zodiac)]||'sparkle':'';
  const isBd=bdIsToday(D.bday); const hero=`<section class="sx-hero${isBd?' is-bday':''}" data-testid="uprof-hero"><div class="sx-banner" style="${banner}" data-testid="uprof-banner"></div><div class="sx-hero-in"><div class="sx-hero-row">${isBd?`<span class="bd-avw" data-testid="uprof-birthday-badge" title="It\u2019s their birthday">${sxAv(d,'is-big')}<span class="bd-av-cake"><i data-lucide="cake"></i></span></span>`:sxAv(d,'is-big')}<div class="sx-acts" data-testid="uprof-actions">${sxActsHtml(d)}</div></div>
    <h1 class="sx-name" data-testid="uprof-name"><span class="clamp-2">${esc(name)}</span>${sxNameBadges(d,true,'uprof')}</h1><p class="sx-uname" data-testid="uprof-username">@${esc(d.username)}</p>${(()=>{ const tb=tlBadge(D.talents,'them','uprof-talent-badge'), nf=fvCount(fvShown(D.talents,D.favs)); return tb||nf?`<div class="tl-row">${tb}${nf?`<button type="button" data-act="tl-view" data-val="them" data-testid="uprof-favorites-badge" class="tl-fav press"><i data-lucide="heart"></i>${nf} favorite${nf===1?'':'s'}</button>`:''}</div>`:''; })()}
    <div class="sx-meta">${isBd?`<span class="sx-chip is-bday" data-testid="uprof-birthday"><i data-lucide="cake"></i>Birthday today</span>`:''}${d.suspended?`<span class="sx-chip is-err" data-testid="uprof-suspended"><i data-lucide="ban"></i>Suspended</span>`:''}${sxIconChip(d)}${D.zodiac?`<span class="sx-chip is-gold" data-testid="uprof-zodiac"><i data-lucide="${zi}"></i>${esc(D.zodiac)}</span>`:''}${joined?`<span class="sx-chip" data-testid="uprof-joined"><i data-lucide="calendar"></i>Joined ${esc(joined)}</span>`:''}<span class="sx-chip" data-testid="uprof-friends"><i data-lucide="users-round"></i>${d.friends||0} friend${d.friends===1?'':'s'}</span>${d.is_private?`<span class="sx-chip"><i data-lucide="lock"></i>Private</span>`:''}</div>
    ${d.bio?`<p class="sx-bio" data-testid="uprof-bio">${esc(d.bio)}</p>`:''}${D.stats?`<div class="sx-stats" data-testid="uprof-stats">${[['Plays',D.stats.plays,'play'],['Minutes',D.stats.minutes,'clock'],['Liked',D.stats.likes,'heart'],['Starlites',D.stats.points,'sparkles']].map(([l,v,ic])=>`<div><i data-lucide="${ic}"></i><b class="font-doto">${fmtNum(v||0)}</b><span>${l}</span></div>`).join('')}</div>`:''}</div></section>`;
  if(d.relation==='blocked') return hero+sxEmpty('ban','You blocked @'+esc(d.username),'They can\u2019t find you, see your page or send you requests.',`<button type="button" data-act="sx-unblock" data-testid="uprof-unblock" class="sba-btn press mt-4"><i data-lucide="undo-2"></i>Unblock</button>`);
  if(d.locked_all) return hero+`<div class="sx-locked" data-testid="uprof-private"><span class="sx-locked-ic"><i data-lucide="lock"></i></span><p class="sx-empty-t">This profile is private</p><p class="sx-empty-d">${d.relation==='outgoing'?'Your friend request is waiting. You\u2019ll see '+esc(name)+'\u2019s page once they accept.':d.relation==='guest'?'Sign in and add '+esc(name)+' as a friend to see their page.':'Add '+esc(name)+' as a friend. Once they accept, you\u2019ll see their page.'}</p></div>`;
  const T=sxTabs(d); if(!T.length) return hero+sxEmpty('eye-off','Nothing shared yet','@'+esc(d.username)+' keeps their library to themselves.');
  return hero+`<div class="sx-tabs no-scrollbar" role="tablist" data-testid="uprof-tabs">${T.map(([k,l,ic])=>`<button type="button" role="tab" aria-selected="${V.tab===k}" data-act="sx-tab" data-val="${k}" data-testid="uprof-tab-${k}" class="sx-tab${V.tab===k?' on':''}"><i data-lucide="${(d.locked||[]).includes(k)?'lock':ic}"></i>${l}</button>`).join('')}</div><div class="sx-body" data-testid="uprof-body">${sxTabHtml(d,V.tab)}</div>`; }
function sxActsHtml(d){ const r=d.relation, b=(act,ic,l,cls,tid)=>`<button type="button" data-act="${act}" data-testid="${tid}" class="sx-btn press${cls?' '+cls:''}"><i data-lucide="${ic}"></i><span>${l}</span></button>`;
  if(r==='guest') return b('sb-auth-open','user-plus','Add friend','is-primary','uprof-add-friend').replace('data-act="sb-auth-open"','data-act="sb-auth-open" data-val="signin"');
  if(r==='none') return b('sx-add','user-plus','Add friend','is-primary','uprof-add-friend');
  if(r==='outgoing') return b('sx-cancel','clock','Requested','','uprof-cancel-request');
  if(r==='incoming') return b('sx-accept','check','Accept','is-primary','uprof-accept')+b('sx-decline','x','Decline','','uprof-decline');
  if(r==='friends') return b('sx-remove-ask','user-check','Friends','is-ok','uprof-friends-btn');
  return ''; }
function sxSongRows(list,ctx,ranked){ const L=(list||[]).filter(Boolean); if(!L.length) return `<p class="sx-none">Nothing here yet.</p>`;
  return `<div class="sx-songs">${L.map((s,i)=>{ const have=!!SONG_BY_ID[s.id]; const c=s.c||(have&&SONG_BY_ID[s.id].coverArt)||''; return `<button type="button" data-act="sx-play" data-id="${esc(s.id)}" data-ctx="${ctx}" data-testid="uprof-song-${ctx}-${i}" class="sx-song press${have?'':' is-off'}"${have?'':' title="Only on their device"'}>${ranked?`<span class="sx-rank font-doto">${i+1}</span>`:''}<span class="sx-song-art">${c?`<img src="${esc(c)}" alt="" loading="lazy">`:'<i data-lucide="music-4"></i>'}</span><span class="min-w-0 flex-1"><b class="clamp-1">${esc(s.t)}</b><small class="clamp-1">${esc(s.a)}${ranked&&s.n?' \u00b7 '+fmtNum(s.n)+' play'+(s.n===1?'':'s'):''}</small></span>${have?'<i data-lucide="play" class="sx-play-ic"></i>':'<i data-lucide="smartphone" class="sx-play-ic"></i>'}</button>`; }).join('')}</div>`; }
function sxTabHtml(d,tab){ const D=d.data||{}; if((d.locked||[]).includes(tab)) return `<div class="sx-locked is-sm" data-testid="uprof-locked-${tab}"><span class="sx-locked-ic"><i data-lucide="users-round"></i></span><p class="sx-empty-t">Friends only</p><p class="sx-empty-d">${d.relation==='outgoing'?'You\u2019ll see this once your friend request is accepted.':'Become friends with @'+esc(d.username)+' to see this.'}</p></div>`;
  if(tab==='listening') return sxListeningHtml(D.listening||{});
  if(tab==='friendlist') return sxFriendListHtml(d.friend_list||[]);
  if(tab==='favorites') return sxSongRows(D.favorites,'fav'); if(tab==='disliked') return sxSongRows(D.disliked,'dis');
  if(tab==='lyrics'){ const L=D.lyrics||[]; if(!L.length) return `<p class="sx-none">No favorite lyrics yet.</p>`; return `<div class="sx-lyr">${L.map((g,i)=>`<div class="sx-lyr-card" data-testid="uprof-lyric-${i}"><button type="button" data-act="sx-play" data-id="${esc(g.id)}" data-ctx="one" class="sx-lyr-head press"><span class="sx-song-art">${g.c?`<img src="${esc(g.c)}" alt="">`:'<i data-lucide="quote"></i>'}</span><span class="min-w-0 flex-1"><b class="clamp-1">${esc(g.t)}</b><small class="clamp-1">${esc(g.a)}</small></span></button>${(g.lines||[]).map(l=>`<p class="sx-lyr-l">\u201c${esc(l)}\u201d</p>`).join('')}</div>`).join('')}</div>`; }
  if(tab==='playlists'){ const P=D.playlists||[]; if(!P.length) return `<p class="sx-none">No playlists yet.</p>`; return `<div class="sx-pls">${P.map((pl,i)=>{ const open=_sxV.pl===pl.id; const cov=(pl.songs||[]).map(s=>s&&(s.c||(SONG_BY_ID[s.id]&&SONG_BY_ID[s.id].coverArt))).filter(Boolean).slice(0,4); return `<div class="sx-pl${open?' is-open':''}" data-testid="uprof-playlist-${i}"><button type="button" data-act="sx-pl" data-id="${esc(pl.id)}" class="sx-pl-head press"><span class="sx-pl-art">${cov.length?cov.map(c=>`<img src="${esc(c)}" alt="">`).join(''):'<i data-lucide="list-music"></i>'}</span><span class="min-w-0 flex-1"><b class="clamp-1">${esc(pl.name)}</b><small>${(pl.songs||[]).length} track${(pl.songs||[]).length===1?'':'s'}</small></span><i data-lucide="chevron-down" class="sx-pl-chev"></i></button>${open?sxSongRows(pl.songs,'pl:'+pl.id):''}</div>`; }).join('')}</div>`; }
  if(tab==='badges'){ const on=new Set(D.badges||[]); const top=D.top||{}; return `${(top.song||top.artist)?`<div class="sx-top2">${top.artist?`<div class="sx-topc"><span class="sx-av">${top.artist.img?`<img src="${esc(top.artist.img)}" alt="">`:'<i data-lucide="mic-vocal"></i>'}</span><span class="min-w-0"><small>Top artist</small><b class="clamp-1">${esc(top.artist.n)}</b></span></div>`:''}${top.song?`<button type="button" data-act="sx-play" data-id="${esc(top.song.id)}" data-ctx="one" class="sx-topc press"><span class="sx-song-art">${top.song.c?`<img src="${esc(top.song.c)}" alt="">`:'<i data-lucide="music-4"></i>'}</span><span class="min-w-0"><small>Top song</small><b class="clamp-1">${esc(top.song.t)}</b></span></button>`:''}</div>`:''}<div class="grid grid-cols-3 gap-2 sm:grid-cols-4" data-testid="uprof-badges">${PF_BADGES.map(b=>{ const ok=on.has(b.id); return `<div class="pf-badge${ok?' is-on':''}" data-testid="uprof-badge-${b.id}" title="${esc(b.desc)}"><span class="pf-badge-ic"><i data-lucide="${b.ic}" style="width:18px;height:18px"></i></span><span class="pf-badge-name">${b.label}</span><span class="pf-badge-desc">${ok?'Earned':b.desc}</span></div>`; }).join('')}</div>`; }
  return ''; }
const SX_MAP={'settings-profile-name':'uprof-name','settings-profile-username':'uprof-username','settings-profile-bio':'uprof-bio','settings-profile-joined':'uprof-joined','settings-profile-zodiac':'uprof-zodiac','profile-banner':'uprof-banner','settings-profile':'uprof-hero'};
function sxApplyCustom(){ const d=_sxV&&_sxV.d, deep=d&&d.data&&d.data.custom&&d.data.custom.deep; const root=document.getElementById('sx-scroll'); if(!deep||!root) return;
  Object.keys(deep).forEach(k=>{ const m=/^T:(.+):0$/.exec(k); const tid=m&&SX_MAP[m[1]]; if(!tid) return; const el=root.querySelector('[data-testid="'+tid+'"]'); if(!el) return; const c=Object.assign({},deep[k]); delete c.x; delete c.y; delete c.w; delete c.h; if(c.txt!=null&&tid!=='uprof-bio') delete c.txt; try{ mkdApplyEl(el,c,false); }catch(e){} }); }
async function sxDo(fn,args,okMsg){ try{ const r=await sxRpc(fn,args); if(okMsg) toast(okMsg[0],okMsg[1]||''); return r; }catch(e){ toast('Couldn\u2019t do that',sxErr(e)); return null; } }
async function sxAct(a){ const d=_sxV&&_sxV.d; if(!d) return; const id=d.id, nm=d.display_name||d.username; let rel=null;
  if(a==='sx-add') rel=await sxDo('send_friend_request',{target:id},['Friend request sent','@'+d.username+' will see it next time they open Treesh']);
  else if(a==='sx-cancel') rel=await sxDo('remove_friend',{other:id},['Request cancelled']);
  else if(a==='sx-accept') rel=await sxDo('respond_friend_request',{other:id,accept:true},['You\u2019re friends now',nm]);
  else if(a==='sx-decline') rel=await sxDo('respond_friend_request',{other:id,accept:false},['Request declined']);
  else if(a==='sx-remove') rel=await sxDo('remove_friend',{other:id},['Friend removed']);
  else if(a==='sx-block') rel=await sxDo('block_user',{target:id},['Blocked @'+d.username,'They can\u2019t find you or send requests']);
  else if(a==='sx-unblock') rel=await sxDo('unblock_user',{target:id},['Unblocked @'+d.username]);
  if(rel!=null){ _sxQ.q=null; sxOpenProfile(d.username); if(_sxF) sxFriendsLoad(); } }
function sxMenu(){ const d=_sxV&&_sxV.d; if(!d) return; const link=SB_HOME+'?u='+encodeURIComponent(d.username); const it=(act,ic,l,cls,tid)=>`<button type="button" data-act="${act}" data-testid="${tid}" class="sx-mi press${cls?' '+cls:''}"><i data-lucide="${ic}"></i>${l}</button>`;
  $("#modal2").innerHTML=modal2Wrap(`<div class="sx-menu" data-testid="user-profile-menu-sheet"><div class="sx-menu-h">${sxAv(d)}<span class="min-w-0"><b class="clamp-1">${esc(d.display_name||d.username)}</b><small>@${esc(d.username)}</small></span></div>${it('sx-copy','link','Copy profile link','','uprof-copy-link').replace('data-act="sx-copy"','data-act="sx-copy" data-val="'+esc(link)+'"')}${d.relation==='friends'?it('sx-remove','user-minus','Remove friend','','uprof-remove-friend'):''}${d.relation==='blocked'?it('sx-unblock','undo-2','Unblock','','uprof-menu-unblock'):it('sx-block-ask','ban','Block @'+esc(d.username),'is-danger','uprof-block')}<button type="button" data-act="modal2-x" data-testid="uprof-menu-cancel" class="sba-btn lg press mt-2">Cancel</button></div>`,'user-profile-menu-modal'); icons(); syncScrollLock(); }

/* friends sheet */
async function sxFriendsLoad(){ if(!_sxF) return; _sxF.busy=true; sxFriendsPaint(); try{ _sxF.list=(await sxRpc('my_friends'))||[]; _sxF.err=null; }catch(e){ _sxF.err=e; } _sxF.busy=false; state._sxIncoming=(_sxF.list||[]).filter(x=>x.relation==='incoming').length; sxFriendsPaint(); try{ const b=document.querySelector('[data-testid="hero-friends"] .sx-badge'); if(b){ b.textContent=state._sxIncoming||''; b.hidden=!state._sxIncoming; } }catch(e){} }
function sxFriendsHtml(){ const F=_sxF||{}; if(F.busy&&!F.list) return `<div class="sx-load"><span class="sx-spin"></span><p>Loading your friends\u2026</p></div>`; if(F.err) return sxEmpty('triangle-alert','Couldn\u2019t load friends',esc(sxErr(F.err)));
  const L=F.list||[], g=r=>L.filter(x=>x.relation===r); const row=(x,acts)=>`<div class="sx-frow" data-testid="friend-row-${esc(x.username)}"><button type="button" data-act="sx-open" data-u="${esc(x.username)}" class="sx-frow-main press">${sxAv(x)}<span class="min-w-0 flex-1"><b class="sx-nm"><span class="clamp-1">${esc(x.display_name||x.username)}</span>${sxNameBadges(x,false,x.username)}</b><small class="clamp-1">@${esc(x.username)}</small></span></button>${acts}</div>`;
  const ib=(act,ic,l,cls,x)=>`<button type="button" data-act="${act}" data-id="${x.id}" data-u="${esc(x.username)}" aria-label="${l}" title="${l}" data-testid="${act}-${esc(x.username)}" class="sx-ib press${cls?' '+cls:''}"><i data-lucide="${ic}"></i></button>`;
  const sec=(t,list,fn,ic)=>list.length?`<section class="sx-fsec"><p class="sx-fk"><i data-lucide="${ic}"></i>${t}<span>${list.length}</span></p>${list.map(fn).join('')}</section>`:'';
  const body=sec('Friend requests',g('incoming'),x=>row(x,ib('sxf-accept','check','Accept','is-primary',x)+ib('sxf-decline','x','Decline','',x)),'user-plus')+sec('Friends',g('friends'),x=>row(x,ib('sxf-remove','user-minus','Remove friend','',x)),'users-round')+sec('Sent',g('outgoing'),x=>row(x,ib('sxf-cancel','x','Cancel request','',x)),'clock')+sec('Blocked',g('blocked'),x=>row(x,ib('sxf-unblock','undo-2','Unblock','',x)),'ban');
  return body||sxEmpty('users-round','No friends yet','Search Users to find people you know and add them.',`<button type="button" data-act="sx-find" data-testid="friends-find-people" class="sba-btn is-primary press mt-4"><i data-lucide="search"></i>Find people</button>`); }
function sxFriendsPaint(){ const b=document.getElementById('sx-fbody'); if(b){ b.innerHTML=sxFriendsHtml(); icons(); } }
function sxFriendsOpen(){ if(!sbUser()){ sbAuthOpen('signin'); return; } _sxF={busy:true,list:null};
  $("#modal2").innerHTML=modal2Wrap(`<div class="sx-fr" data-testid="friends-sheet"><div class="tsf-head"><span class="sba-orb"><i data-lucide="users-round"></i></span><div class="min-w-0 flex-1"><h3 class="tsf-t">Friends</h3><p class="tsf-d">Requests, friends and people you\u2019ve blocked.</p></div><button type="button" data-act="modal2-x" aria-label="Close" data-testid="friends-close" class="tsf-x press"><i data-lucide="x"></i></button></div><button type="button" data-act="sx-find" data-testid="friends-search" class="sx-find press"><i data-lucide="search"></i>Find people by @username</button><div id="sx-fbody" class="sx-fbody">${sxFriendsHtml()}</div></div>`,'friends-modal','lg'); icons(); syncScrollLock(); sxFriendsLoad(); }

/* privacy sheet */
function sxPrivacyRow(){ const c=sxCfg(); const n=SX_SECS.filter(([k])=>c.sections[k]!=='everyone').length; return `<button type="button" data-act="sx-privacy" data-testid="pf-acct-privacy" class="pfa-row press"><span class="pfa-row-ic"><i data-lucide="${c.private?'lock':'globe'}"></i></span><span class="min-w-0 flex-1"><b>Privacy</b><small class="clamp-1">${c.private?'Private profile \u00b7 friends only':'Public profile'}${n?' \u00b7 '+n+' hidden page'+(n>1?'s':''):''}</small></span><em>Manage<i data-lucide="chevron-right"></i></em></button>`; }
function sxPrivacyHtml(){ const c=sxCfg();
  return `<div class="sx-pv" data-testid="privacy-sheet"><div class="tsf-head"><span class="sba-orb"><i data-lucide="shield"></i></span><div class="min-w-0 flex-1"><h3 class="tsf-t">Profile privacy</h3><p class="tsf-d">Choose who can see your Treesh page when they search Users.</p></div><button type="button" data-act="modal2-x" aria-label="Close" data-testid="privacy-close" class="tsf-x press"><i data-lucide="x"></i></button></div>
   <div class="sx-pv-mode" role="radiogroup" data-testid="privacy-mode">${[[false,'globe','Public','Anyone on Treesh can see your page.'],[true,'lock','Private','People see that you exist. Only friends see your page.']].map(([v,ic,t,d])=>`<button type="button" role="radio" aria-checked="${c.private===v}" data-act="sx-pv-mode" data-val="${v?1:0}" data-testid="privacy-${v?'private':'public'}" class="sx-pv-opt press${c.private===v?' on':''}"><i data-lucide="${ic}"></i><span><b>${t}</b><small>${d}</small></span></button>`).join('')}</div>
   <p class="tsf-k mt-5">Who can see each page</p><div class="sx-pv-list">${SX_SECS.map(([k,l,ic])=>`<div class="sx-pv-row" data-testid="privacy-row-${k}"><span class="pfa-row-ic"><i data-lucide="${ic}"></i></span><b class="flex-1">${l}</b><div class="sx-pv-seg">${SX_VIS.map(([v,vl])=>`<button type="button" data-act="sx-pv-sec" data-k="${k}" data-val="${v}" data-testid="privacy-${k}-${v}" aria-pressed="${c.sections[k]===v}" class="${c.sections[k]===v?'on':''}">${vl}</button>`).join('')}</div></div>`).join('')}</div>
   <p class="sba-fine">Your nickname, @username and photo always show in search so friends can find you. ${sbUser()?'':'Sign in to publish your page.'}</p></div>`; }
function sxPrivacyOpen(){ $("#modal2").innerHTML=modal2Wrap(sxPrivacyHtml(),'privacy-modal','lg'); icons(); syncScrollLock(); }
function sxPrivacyPaint(){ const s=document.querySelector('#modal2 .sx-pv'); if(s){ const t=document.createElement('div'); t.innerHTML=sxPrivacyHtml(); s.replaceWith(t.firstElementChild); icons(); } const r=document.querySelector('[data-testid="pf-acct-privacy"]'); if(r){ const t=document.createElement('div'); t.innerHTML=sxPrivacyRow(); r.replaceWith(t.firstElementChild); icons(); } }

/* own profile: Friends button in the hero */
const _sph9mf=settingsProfileHtml; settingsProfileHtml=function(editing){ const h=_sph9mf.apply(this,arguments); if(editing||!sbUser()) return h; const k='<div class="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-5" data-testid="profile-stats-row">'; const i=h.indexOf(k); if(i<0) return h;
  const n=state._sxIncoming||0; return h.slice(0,i)+`<div class="mt-4 flex flex-wrap gap-2"><button type="button" data-act="sx-friends" data-testid="hero-friends" class="sx-hbtn press"><i data-lucide="users-round"></i>Friends<span class="sx-badge"${n?'':' hidden'}>${n||''}</span></button><button type="button" data-act="sx-find" data-testid="hero-find-people" class="sx-hbtn press"><i data-lucide="user-search"></i>Find people</button><button type="button" data-act="sx-privacy" data-testid="hero-privacy" class="sx-hbtn press"><i data-lucide="${sxCfg().private?'lock':'globe'}"></i>${sxCfg().private?'Private':'Public'}</button>${modHeroBtn()}</div>`+h.slice(i); };
function sxFindPeople(){ if(document.querySelector('#modal2 .sx-fr')) closeModal2(); state.searchTab='users'; if(state.searchOpen){ updateSearchTabs(); refreshSearchResults(); } else openSearch(); setTimeout(()=>{ const i=document.getElementById('search-input'); if(i){ i.placeholder=searchPlaceholder(); i.focus(); } },60); }

document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act]'); if(!t) return; const a=t.dataset.act; if(a.indexOf('sx')!==0&&a!=='modal2-x') return;
  switch(a){
    case 'modal2-x': if(t.closest('.sx-menu,.sx-fr,.sx-pv')) closeModal2(); break;
    case 'sx-open': if(document.querySelector('#modal2 .sx-fr')) closeModal2(); sxOpenProfile(t.dataset.u); break;
    case 'sx-close': sxClose(); break;
    case 'sx-retry': if(_sxV) sxOpenProfile(_sxV.u); break;
    case 'sx-tab': if(_sxV){ _sxV.tab=t.dataset.val; const s=document.getElementById('sx-scroll'), y=s?s.scrollTop:0; sxRender(); const n=document.getElementById('sx-scroll'); if(n) n.scrollTop=y; } break;
    case 'sx-pl': if(_sxV){ _sxV.pl=_sxV.pl===t.dataset.id?null:t.dataset.id; const s=document.getElementById('sx-scroll'), y=s?s.scrollTop:0; sxRender(); const n=document.getElementById('sx-scroll'); if(n) n.scrollTop=y; } break;
    case 'sx-play': { const s=SONG_BY_ID[t.dataset.id]; if(!s){ toast('Not on this device','That song lives on their phone'); break; } const D=(_sxV&&_sxV.d&&_sxV.d.data)||{}, c=t.dataset.ctx||''; const src=c==='top'?(D.listening||{}).songs:c==='fav'?D.favorites:c==='dis'?D.disliked:c.indexOf('pl:')===0?((D.playlists||[]).find(p=>p.id===c.slice(3))||{}).songs:null; const list=(src||[]).map(x=>x&&SONG_BY_ID[x.id]).filter(Boolean); playSong(s,list.length?list:[s]); break; }
    case 'sx-add': case 'sx-cancel': case 'sx-accept': case 'sx-decline': case 'sx-unblock': sxAct(a); break;
    case 'sx-remove': closeModal2(); sxAct(a); break;
    case 'sx-remove-ask': { const d=_sxV&&_sxV.d; if(d) openConfirm('Remove @'+d.username+' as a friend?','You\u2019ll stop seeing their friends-only pages.',()=>sxAct('sx-remove')); break; }
    case 'sx-block-ask': { const d=_sxV&&_sxV.d; if(!d) break; closeModal2(); setTimeout(()=>openConfirm('Block @'+d.username+'?','They won\u2019t be able to find you, see your page or send friend requests. Any friendship ends.',()=>sxAct('sx-block')),60); break; }
    case 'sx-menu': sxMenu(); break;
    case 'sx-copy': { const v=t.dataset.val; (navigator.clipboard?navigator.clipboard.writeText(v):Promise.reject()).then(()=>toast('Link copied',v)).catch(()=>toast('Profile link',v)); closeModal2(); break; }
    case 'sx-friends': sxFriendsOpen(); break;
    case 'sx-find': sxFindPeople(); break;
    case 'sx-privacy': sxPrivacyOpen(); break;
    case 'sx-pv-mode': { const c=sxCfg(); c.private=t.dataset.val==='1'; sxSaveCfg(c); sxPrivacyPaint(); toast(c.private?'Your profile is private':'Your profile is public',c.private?'Only friends can see your page':'Anyone on Treesh can see your page'); try{ if(state.profileOpen&&!state.settingsEditProfile){ const b=document.querySelector('[data-testid="hero-privacy"]'); if(b){ b.innerHTML=`<i data-lucide="${c.private?'lock':'globe'}"></i>${c.private?'Private':'Public'}`; icons(); } } }catch(_){} break; }
    case 'sx-pv-sec': { const c=sxCfg(); c.sections[t.dataset.k]=t.dataset.val; sxSaveCfg(c); sxPrivacyPaint(); break; }
    case 'sxf-accept': case 'sxf-decline': case 'sxf-remove': case 'sxf-cancel': case 'sxf-unblock': { const id=t.dataset.id; t.disabled=true; const M={'sxf-accept':['respond_friend_request',{other:id,accept:true},['You\u2019re friends now']],'sxf-decline':['respond_friend_request',{other:id,accept:false},['Request declined']],'sxf-remove':['remove_friend',{other:id},['Friend removed']],'sxf-cancel':['remove_friend',{other:id},['Request cancelled']],'sxf-unblock':['unblock_user',{target:id},['Unblocked']]}[a];
      const go=()=>sxDo(M[0],M[1],M[2]).then(()=>sxFriendsLoad()); if(a==='sxf-remove') openConfirm('Remove @'+t.dataset.u+'?','You can add them again any time.',()=>{ go(); setTimeout(sxFriendsOpen,80); }); else go(); break; }
  } });
document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act="artist-open"]'); if(!t||!t.closest('#sx-root,#modal2')) return; if(document.getElementById('sx-root')) sxClose(); if(document.querySelector('#modal2 > *')) closeModal2(); if(state.searchOpen) closeSearch(true); if(state.profileOpen) closeProfile(true); },true);
document.addEventListener('keydown',e=>{ if(e.key==='Escape'&&_sxV&&!(document.getElementById('modal2')||{}).childElementCount){ e.stopImmediatePropagation(); sxClose(); } },true);
const _ovo9m=overlaysOpen; overlaysOpen=function(){ return !!document.getElementById('sx-root')||_ovo9m.apply(this,arguments); };
const _p9Init9m=p9Init; p9Init=function(){ const r=_p9Init9m.apply(this,arguments); try{ const u=new URLSearchParams(location.search).get('u'); if(u&&/^[a-z0-9_.]{3,20}$/i.test(u)){ const k=new URLSearchParams(location.search); k.delete('u'); history.replaceState(null,'',location.pathname+(k.toString()?'?'+k:'')+location.hash); setTimeout(()=>sxOpenProfile(u),1400); } }catch(e){}
  setTimeout(()=>{ if(sbUser()) sxRpc('my_friends').then(l=>{ state._sxIncoming=(l||[]).filter(x=>x.relation==='incoming').length; if(state._sxIncoming) toast(state._sxIncoming+' friend request'+(state._sxIncoming>1?'s':''),'Open your profile, then Friends'); }).catch(()=>{}); },5000); return r; };
