/* ---------- P9n: Image Studio, free crop. Drag any corner or edge, or use the ratio slider ---------- */
const PS_RATIOS=[['orig','Original',0],['free','Free',-1],['1:1','Square',1],['4:5','4:5',.8],['3:4','3:4',.75],['16:9','16:9',16/9],['9:16','9:16',9/16],['3:1','Banner',3]];
function psLocked(){ const o=(_cv&&_cv.opts)||{}; return !!(o.round||o.lockAspect); }
function psImgA(){ const i=_cvImg; return i?((i.naturalWidth||1)/(i.naturalHeight||1)):1; }
function psRatioLabel(A){ const hit=PS_RATIOS.find(r=>r[2]>0&&Math.abs(r[2]-A)<.01); if(hit) return hit[0]; if(_cvImg&&Math.abs(psImgA()-A)<.01) return 'Original'; return A>=1?A.toFixed(2)+' : 1':'1 : '+(1/A).toFixed(2); }
function psSetA(A,snap){ if(!_cv) return; _cv.A=Math.max(.2,Math.min(5,A)); _psKey=''; psFit(); psCropUi(); if(snap) psSnap(); }
function psCropUi(){ const l=document.getElementById('ps-ratio-val'); if(l) l.textContent=psRatioLabel(_cv.A); const r=document.getElementById('ps-ratio'); if(r&&document.activeElement!==r){ r.value=Math.round(Math.log2(_cv.A)*50); try{ fillSlider(r); }catch(e){} }
  document.querySelectorAll('#ps-panel [data-ps-ratio]').forEach(b=>{ const k=b.dataset.psRatio, R=PS_RATIOS.find(x=>x[0]===k); const on=k==='free'?_cv.free:(!_cv.free&&(k==='orig'?Math.abs(psImgA()-_cv.A)<.01:Math.abs(R[2]-_cv.A)<.01)); b.classList.toggle('on',!!on); });
  const fr=document.getElementById('ps-frame'); if(fr){ fr.dataset.ratio=psRatioLabel(_cv.A); } }
function psCropHtml(){ if(psLocked()) return ''; return `<p class="ps-sub">Aspect ratio</p><div class="ps-row ps-ratios no-scrollbar" data-testid="ps-ratios">${PS_RATIOS.map(([k,l])=>`<button type="button" data-ps-ratio="${k}" data-testid="ps-ratio-${k.replace(':','x')}" class="ps-chip">${k==='free'?'<i data-lucide="scan"></i>':k==='orig'?'<i data-lucide="image"></i>':''}${l}</button>`).join('')}</div>
  <div class="ps-ratio-wrap"><div class="ps-dial-head"><span>Width : height</span><b id="ps-ratio-val" data-testid="ps-ratio-value">${psRatioLabel(_cv.A)}</b></div><div class="ps-ratio-in"><i data-lucide="rectangle-vertical"></i><input type="range" id="ps-ratio" class="tr" min="-116" max="116" step="1" value="${Math.round(Math.log2(_cv.A)*50)}" aria-label="Crop aspect ratio" data-testid="ps-ratio-range"><i data-lucide="rectangle-horizontal"></i></div></div>
  <p class="ps-hint"><i data-lucide="crop"></i>Drag any corner or edge of the photo to crop it to any shape.</p>`; }
const _psRT9n=psRenderTool; psRenderTool=function(){ const r=_psRT9n.apply(this,arguments); try{ if(_cv&&_cv.tool==='crop'&&!psLocked()){ const pane=document.querySelector('#ps-panel [data-testid="ps-pane-crop"]'); if(pane&&!pane.querySelector('[data-testid="ps-ratios"]')){ pane.insertAdjacentHTML('afterbegin',psCropHtml()); icons(); psCropUi(); } } }catch(e){ console.warn('crop ui',e); } return r; };
const _ocs9n=openCoverStudio; openCoverStudio=function(src,label,ownSrc,opts){ const r=_ocs9n.apply(this,arguments); try{ if(_cv){ _cv.A0=_cv.A; _cv.free=false; const fr=document.getElementById('ps-frame'); if(fr&&!psLocked()&&!fr.querySelector('.ps-hd')) fr.insertAdjacentHTML('beforeend',['nw','n','ne','e','se','s','sw','w'].map(h=>`<span class="ps-hd ps-hd-${h}" data-ps-hd="${h}" data-testid="ps-crop-handle-${h}" aria-hidden="true"></span>`).join('')+'<span class="ps-ratio-tag" aria-hidden="true"></span>'); } }catch(e){} return r; };
const _psSt9n=psState; psState=function(){ const o=JSON.parse(_psSt9n.apply(this,arguments)); o.A=_cv.A; return JSON.stringify(o); };
const _psRs9n=psRestore; psRestore=function(s){ const r=_psRs9n.apply(this,arguments); try{ _psKey=''; psFit(); psCropUi(); }catch(e){} return r; };
const _psAct9n=psAct; psAct=function(a){ if(a==='crop-reset'&&_cv&&!psLocked()){ _cv.A=_cv.A0||1; _cv.free=false; _psKey=''; } const r=_psAct9n.apply(this,arguments); if(a==='crop-reset'){ try{ psFit(); psCropUi(); }catch(e){} } return r; };
const _cvAp9n=cvApply; cvApply=function(){ if(_cv&&!psLocked()&&_cv.A0&&Math.abs(_cv.A-_cv.A0)>.001){ const o=_cv.opts=Object.assign({},_cv.opts||{}); const big=Math.max(...((o.out||[_cv.A>1.2?1500:1000]).slice(0,2)),1000), cap=Math.min(2400,big); o.out=_cv.A>=1?[cap,Math.round(cap/_cv.A)]:[Math.round(cap*_cv.A),cap]; } return _cvAp9n.apply(this,arguments); };
document.addEventListener('click',e=>{ const b=e.target&&e.target.closest&&e.target.closest('#modal2 [data-ps-ratio]'); if(!b||!_cv) return; const k=b.dataset.psRatio, R=PS_RATIOS.find(x=>x[0]===k);
  if(k==='free'){ _cv.free=true; psCropUi(); toast('Free crop','Drag any corner or edge'); return; } _cv.free=false; psSetA(k==='orig'?psImgA():R[2],true); });
document.addEventListener('input',e=>{ if(!e.target||e.target.id!=='ps-ratio'||!_cv) return; _cv.free=true; let A=Math.pow(2,(+e.target.value)/50); const snapTo=[1,psImgA(),.8,.75,16/9,9/16,3,4/3,3/4].find(x=>Math.abs(Math.log2(x)-Math.log2(A))<.025); if(snapTo) A=snapTo; try{ fillSlider(e.target); }catch(_){} psSetA(A,false); });
document.addEventListener('change',e=>{ if(e.target&&e.target.id==='ps-ratio'&&_cv) psSnap(); });
document.addEventListener('pointerdown',e=>{ const h=e.target&&e.target.closest&&e.target.closest('[data-ps-hd]'); if(!h||!_cv) return; e.preventDefault(); e.stopPropagation(); const fr=document.getElementById('ps-frame'), st=document.getElementById('ps-stage'), cv=document.getElementById('cv-canvas'); if(!fr||!st||!cv) return;
  const d=h.dataset.psHd, x0=e.clientX, y0=e.clientY, w0=fr.clientWidth, h0=fr.clientHeight, mw=st.clientWidth-24, mh=st.clientHeight-24; fr.classList.add('is-sizing'); try{ h.setPointerCapture(e.pointerId); }catch(_){}
  const mv=ev=>{ const dx=ev.clientX-x0, dy=ev.clientY-y0; let w=w0, hh=h0; if(/e/.test(d)) w=w0+dx*2; if(/w/.test(d)) w=w0-dx*2; if(/s/.test(d)) hh=h0+dy*2; if(/n/.test(d)) hh=h0-dy*2;
    w=Math.max(60,Math.min(mw,w)); hh=Math.max(60,Math.min(mh,hh)); _cv.A=Math.max(.2,Math.min(5,w/hh)); _cv.free=true; fr.style.width=Math.round(w)+'px'; fr.style.height=Math.round(hh)+'px';
    const dpr=Math.min(2,window.devicePixelRatio||1); let W=Math.round(Math.min(1100,w*dpr)), H=Math.round(W/_cv.A); const cap=900000; if(W*H>cap){ const k=Math.sqrt(cap/(W*H)); W=Math.round(W*k); H=Math.round(H*k); } cv.width=W; cv.height=H; _psKey=''; psQueue(); cvRenderLayers(); psCropUi(); };
  const up=()=>{ h.removeEventListener('pointermove',mv); h.removeEventListener('pointerup',up); h.removeEventListener('pointercancel',up); fr.classList.remove('is-sizing'); _psKey=''; psFit(); psCropUi(); psSnap(); };
  h.addEventListener('pointermove',mv); h.addEventListener('pointerup',up); h.addEventListener('pointercancel',up); },true);
