/* ---------- P9o: staff (admins + moderators), verified Treesh Icons, bans, mutes, talents ---------- */
const MOD_DUR=[['1h','1 hour',36e5],['1d','1 day',864e5],['3d','3 days',2592e5],['7d','1 week',6048e5],['30d','30 days',2592e6],['perm','Permanent',0],['custom','Pick a date',-1]];
const MOD_ACT={ban:['ban','banned'],unban:['undo-2','lifted the ban on'],mute:['volume-x','muted'],unmute:['volume-2','unmuted'],edit:['user-pen','edited'],verify:['badge-check','verified'],unverify:['badge-x','removed verification from'],make_mod:['shield-plus','made a moderator:'],remove_mod:['shield-minus','removed moderator from'],make_admin:['shield-check','made an admin:'],remove_admin:['shield-off','removed admin from'],delete:['trash-2','deleted']};
const MOD_ROLES=[['user','Member','user-round','Regular account'],['moderator','Moderator','shield','Mute & edit profiles'],['admin','Admin','shield-check','Full staff powers']];
let _mod=null, _modD=null, _stT=0;
function stMe(){ return (sbUser()&&state._sxMe)||null; }
function stRole(){ const m=stMe(); return (m&&m.role)||'user'; }
function stStaff(){ return stRole()==='moderator'||stRole()==='admin'; }
function stMuted(){ const m=stMe(); return !!(m&&m.muted_until&&Date.parse(m.muted_until)>Date.now()); }
function stFmt(t){ const d=new Date(t); if(!t||isNaN(d)) return ''; if(d.getFullYear()>2100) return 'forever'; return d.toLocaleString(undefined,{month:'short',day:'numeric',year:d.getFullYear()!==new Date().getFullYear()?'numeric':undefined,hour:'numeric',minute:'2-digit'}); }
function stUntil(t){ const s=stFmt(t); return s==='forever'?'permanently':'until '+s; }
function stIcon(id){ return (id&&ARTIST_BY_ID[id])||null; }
function pfRepaint(){ try{ if(state.profileOpen){ if(state.settingsEditProfile) pfStashDraft(); renderProfile(); } }catch(e){} }

/* badges next to names */
function sxNameBadges(u,big,key){ if(!u) return ''; const k=key?'-'+key:''; let h=''; const ic=u.verified?stIcon(u.verified_icon):null;
  if(u.verified) h+=(big&&ic)?`<button type="button" data-act="artist-open" data-id="${esc(ic.id)}" class="sx-vf press" title="Verified Treesh Icon: ${esc(ic.name)}" aria-label="Verified Treesh Icon, open ${esc(ic.name)}" data-testid="badge-verified${k}"><i data-lucide="badge-check"></i></button>`:`<span class="sx-vf" title="${ic?'Verified Treesh Icon: '+esc(ic.name):'Verified'}" aria-label="Verified" data-testid="badge-verified${k}"><i data-lucide="badge-check"></i></span>`;
  if(u.role==='admin') h+=`<span class="sx-role is-admin" title="Treesh admin" data-testid="badge-admin${k}"><i data-lucide="shield-check"></i>${big?'<b>Admin</b>':''}</span>`;
  else if(u.role==='moderator') h+=`<span class="sx-role is-mod" title="Treesh moderator" data-testid="badge-moderator${k}"><i data-lucide="shield"></i>${big?'<b>Moderator</b>':''}</span>`;
  return h?`<span class="sx-nb${big?' is-big':''}">${h}</span>`:''; }
function sxIconChip(d){ const ic=d&&d.verified?stIcon(d.verified_icon):null; return ic?`<button type="button" data-act="artist-open" data-id="${esc(ic.id)}" class="sx-chip is-icon press" data-testid="uprof-icon-link"><i data-lucide="badge-check"></i>Treesh Icon \u00b7 ${esc(ic.name)}</button>`:''; }

/* public: top listening + friend list */
function sxListening(){ const pc=state.playCounts||{}, art={};
  const songs=Object.keys(pc).map(id=>[id,+pc[id]||0]).filter(x=>x[1]>0&&SONG_BY_ID[x[0]]).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,n])=>Object.assign(sxSong(SONG_BY_ID[id]),{n}));
  Object.keys(pc).forEach(id=>{ const s=SONG_BY_ID[id], n=+pc[id]||0; if(!s||!n) return; ((s.artistIds&&s.artistIds.length)?s.artistIds:['n:'+(s.artist||'')]).forEach(a=>{ art[a]=(art[a]||0)+n; }); });
  const artists=Object.keys(art).sort((a,b)=>art[b]-art[a]).slice(0,8).map(k=>{ const A=k.indexOf('n:')===0?null:ARTIST_BY_ID[k]; return {id:A?A.id:'',n:A?A.name:k.slice(2),img:A&&/^https?:/.test(A.image||'')?A.image:'',p:art[k]}; }).filter(a=>a.n);
  return {songs,artists}; }
const _sxSnap9o=sxSnapshot; sxSnapshot=function(){ const o=_sxSnap9o.apply(this,arguments); o.listening=sxListening(); o.talents=tlGet(); o.favs=fvShown(o.talents,(state.profile||{}).favs); return o; };
function sxListeningHtml(L){ const S=L.songs||[], A=L.artists||[]; if(!S.length&&!A.length) return `<p class="sx-none" data-testid="uprof-listening-empty">Nothing played yet.</p>`;
  return `${A.length?`<p class="sx-sub">Top artists</p><div class="sx-arts no-scrollbar" data-testid="uprof-top-artists">${A.map((a,i)=>{ const go=a.id&&ARTIST_BY_ID[a.id]; return `<button type="button" ${go?`data-act="artist-open" data-id="${esc(a.id)}"`:'disabled'} class="sx-art press" data-testid="uprof-top-artist-${i}"><span class="sx-art-img">${a.img?`<img src="${esc(a.img)}" alt="" loading="lazy">`:'<i data-lucide="mic-vocal"></i>'}<em class="font-doto">${i+1}</em></span><b class="clamp-1">${esc(a.n)}</b><small>${fmtNum(a.p||0)} play${a.p===1?'':'s'}</small></button>`; }).join('')}</div>`:''}
   ${S.length?`<p class="sx-sub">Most played</p><div data-testid="uprof-top-songs">${sxSongRows(S,'top',true)}</div>`:''}`; }
function sxFriendListHtml(F){ if(!F.length) return `<p class="sx-none" data-testid="uprof-friend-list-empty">No friends to show yet.</p>`;
  return `<div class="sx-list" data-testid="uprof-friend-list">${F.map((u,i)=>`<button type="button" data-act="sx-open" data-u="${esc(u.username)}" data-testid="uprof-friend-${esc(u.username)}" class="sx-row press" style="--d:${Math.min(i,8)*40}ms">${sxAv(u)}<span class="min-w-0 flex-1"><b class="sx-nm"><span class="clamp-1">${esc(u.display_name||u.username)}</span>${sxNameBadges(u,false,'fl-'+u.username)}</b><small class="clamp-1">@${esc(u.username)}</small></span><i data-lucide="chevron-right" class="sx-chev"></i></button>`).join('')}</div>`; }

/* my status: role, badges, ban, mute, staff edits */
async function stLoad(force){ if(!sb||!sbUser()){ state._sxMe=null; return null; } if(!force&&Date.now()-_stT<60000) return state._sxMe; _stT=Date.now();
  let d=null; try{ d=await sxRpc('my_status'); }catch(e){ return null; } const prev=JSON.stringify(state._sxMe||null); state._sxMe=d||null; if(d) await stApply(d);
  if(JSON.stringify(state._sxMe||null)!==prev){ pfRepaint(); try{ sbPaint(); if(state.view==='settings'&&state.settingsTab==='account') renderView(); }catch(e){} } return d; }
async function stApply(d){ if(d.banned_until&&Date.parse(d.banned_until)>Date.now()){ stBanned(d); return; }
  const rev=+d.mod_rev||0, seen=+(localStorage.getItem('sbx_mod_rev')||0), E=d.mod_edits;
  if(rev>seen&&E&&typeof E==='object'){ const p=Object.assign({},state.profile||{}), ch=[];
    if(E.display_name){ p.nickname=E.display_name; ch.push('name'); }
    if(E.username){ p.username=E.username; p.usernameSynced=E.username; ch.push('username'); }
    if('bio' in E){ p.bio=E.bio||''; ch.push('bio'); }
    if(E.remove_avatar){ p.avatar=''; p.avatarUrl=null; p.avatarSig=''; ch.push('photo'); }
    if(E.remove_banner){ try{ assetDel('profile_banner').catch(()=>{}); }catch(e){} state.profileBanner=''; sbMeta({bannerUrl:null,bannerSig:''}); ch.push('banner'); }
    state.profile=p; LS.set('treesh_profile',p); localStorage.setItem('sbx_mod_rev',String(rev)); try{ await sxRpc('ack_mod_edits',{rev}); }catch(e){}
    if(ch.length){ toast('A moderator updated your profile','Changed: '+ch.join(', ')); try{ renderShell(); renderSidebarLibrary(); }catch(e){} pfRepaint(); sbQueuePush(true); } }
  else if(rev>seen) localStorage.setItem('sbx_mod_rev',String(rev));
  if(!stMuted()){ if(localStorage.getItem('sbx_av_held')){ localStorage.removeItem('sbx_av_held'); if(state.profile){ state.profile.avatarSig=''; sbQuietSet('treesh_profile',state.profile); } sbQueuePush(true); }
    if(localStorage.getItem('sbx_bn_held')){ localStorage.removeItem('sbx_bn_held'); sbMeta({bannerSig:''}); sxPublishSoon(true); } } }
function stBanned(d){ $("#modal2").innerHTML=modal2Wrap(`<div class="mod-ban" data-testid="account-suspended-sheet"><div class="sba-hero"><span class="sba-orb is-err"><i data-lucide="ban"></i></span></div><h3 class="sba-mt">Your account is suspended</h3><p class="sba-md">You can\u2019t sign in ${esc(stUntil(d.banned_until))}.${d.ban_reason?`<br><b>Reason:</b> ${esc(d.ban_reason)}`:''}</p><div class="sba-col"><button type="button" data-act="modal2-close-ban" data-testid="account-suspended-ok" class="sba-btn is-primary lg press">OK</button><button type="button" data-act="ts-open" data-val="support" data-testid="account-suspended-support" class="sba-btn lg press"><i data-lucide="life-buoy"></i>Contact support</button></div><p class="sba-fine">Everything on this device stays here. You\u2019ve been signed out.</p></div>`,'account-suspended-modal');
  icons(); syncScrollLock(); state._sxMe=null; try{ sb.auth.signOut(); }catch(e){} }
const _sbSI9o=sbSignedIn; sbSignedIn=async function(u){ const r=await _sbSI9o.apply(this,arguments); setTimeout(()=>stLoad(true),300); return r; };
const _sbSO9o=sbSignedOut; sbSignedOut=function(){ state._sxMe=null; return _sbSO9o.apply(this,arguments); };
const _sbET9o=sbErrText; sbErrText=function(e){ const m=(e&&(e.message||e.error_description))||String(e||''); if(/banned/i.test(m)) return 'This account is suspended. Email support@treesh.app if you think it\u2019s a mistake.'; return _sbET9o.apply(this,arguments); };
const _sbAU9o=sbAvatarUpload; sbAvatarUpload=async function(uid,d){ if(stMuted()){ localStorage.setItem('sbx_av_held','1'); const p=state.profile||{}; if(p.avatarUrl&&/^https?:/.test(p.avatarUrl)) return p.avatarUrl; throw new Error('Photo saved on this device. It goes public when your mute ends.'); } return _sbAU9o.apply(this,arguments); };
const _opf9o=openProfile; openProfile=function(){ const r=_opf9o.apply(this,arguments); stLoad(false); return r; };

/* own profile: badges, talents, muted notice, staff button */
function modHeroBtn(){ return stStaff()?`<button type="button" data-act="mod-dash" data-testid="hero-mod-tools" class="sx-hbtn is-staff press"><i data-lucide="gavel"></i>Moderation</button>`:''; }
function stMuteNote(){ const m=stMe(); return stMuted()?`<div class="mod-note" data-testid="profile-muted-note"><i data-lucide="volume-x"></i><span><b>You\u2019re muted ${esc(stUntil(m.muted_until))}.</b> You can keep editing. Changes stay private until the mute ends.${m.mute_reason?' Reason: '+esc(m.mute_reason):''}</span></div>`:''; }
const _sph9o=settingsProfileHtml; settingsProfileHtml=function(editing){ let h=_sph9o.apply(this,arguments);
  if(editing){ h=h.replace('<div class="mt-4 grid gap-4 sm:grid-cols-2">',stMuteNote()+'<div class="mt-4 grid gap-4 sm:grid-cols-2">'); const blk=tlEditHtml(); const a='<div class="mt-6"><section class="pfa-card"', b='<div class="mt-4 flex items-center gap-2"><button data-act="save-profile"'; const i=h.indexOf(a)>=0?h.indexOf(a):h.indexOf(b); return i<0?h:h.slice(0,i)+blk+h.slice(i); }
  const me=stMe(); if(me) h=h.replace(/(data-testid="settings-profile-name">)([^<]*)<\/h1>/,(m,a,n)=>a+n+sxNameBadges(me,true,'me')+'</h1>');
  const t=tlGet(), nf=fvCount(fvShown(t,(state.profile||{}).favs)), row=`<div class="tl-row">${t?tlBadge(t,'me','profile-talent-badge'):`<button type="button" data-act="tl-pick" data-testid="profile-add-talents" class="tl-add press"><i data-lucide="plus"></i>Add talents</button>`}${nf?`<button type="button" data-act="tl-view" data-val="me" data-testid="profile-favorites-badge" class="tl-fav press"><i data-lucide="heart"></i>${nf} favorite${nf===1?'':'s'}</button>`:''}${stMuted()?`<span class="sx-chip is-warn" data-testid="profile-muted-chip"><i data-lucide="volume-x"></i>Muted</span>`:''}</div>`;
  return h.replace(/(data-testid="settings-profile-name">[\s\S]*?<\/h1>(?:<p class="pf-uname"[^>]*>[^<]*<\/p>)?)/,(m,a)=>a+row); };
const _sac9o=sbAccountCardHtml; sbAccountCardHtml=function(tab){ const h=_sac9o.apply(this,arguments); if(!h||!stStaff()) return h;
  return h+`<section class="sba-card mod-card" data-testid="mod-settings-card"><div class="sba-head"><span class="sba-ic"><i data-lucide="gavel"></i></span><div class="min-w-0 flex-1"><h2 class="sba-t">Moderation</h2><p class="sba-s">You\u2019re a Treesh ${stRole()==='admin'?'admin':'moderator'}. See bans, mutes, staff and the action log.</p></div></div><div class="sba-acts"><button type="button" data-act="mod-dash" data-testid="mod-open-dashboard" class="sba-btn is-primary press"><i data-lucide="gavel"></i>Open moderation</button></div></section>`; };

/* moderation sheet for one person */
function modCan(a){ const d=_sxV&&_sxV.d, vr=d&&d.mod&&d.mod.viewer_role; if(!vr||vr==='user') return false; const adm=vr==='admin';
  if(d.role==='admin'&&!adm) return false; if(a==='ban'||a==='verify') return adm; if(a==='role') return adm; if(a==='delete') return adm&&d.role!=='admin'; return true; }
function modOpen(){ const d=_sxV&&_sxV.d; if(!d||!d.mod) return; _mod={tab:'status',banDur:'1d',muteDur:'1d',busy:false}; modPaint(true); }
function modPaint(fresh){ const html=`<div class="mod-sheet" data-testid="moderation-sheet">${modHtml()}</div>`; const s=document.querySelector('#modal2 .mod-sheet');
  if(s&&!fresh){ const y=(s.querySelector('.mod-body')||{}).scrollTop||0; s.outerHTML=html; const b=document.querySelector('#modal2 .mod-body'); if(b) b.scrollTop=y; } else $("#modal2").innerHTML=modal2Wrap(html,'moderation-modal','xl'); icons(); syncScrollLock(); }
function modDurHtml(k){ const cur=_mod[k+'Dur']; const now=new Date(Date.now()+36e5-new Date().getTimezoneOffset()*6e4).toISOString().slice(0,16);
  return `<div class="tsf-chips mod-durs" data-testid="mod-${k}-durations">${MOD_DUR.map(([id,l])=>`<button type="button" data-act="mod-dur" data-k="${k}" data-val="${id}" aria-pressed="${cur===id}" data-testid="mod-${k}-dur-${id}" class="tsf-chip press${cur===id?' on':''}">${l}</button>`).join('')}</div>
   ${cur==='custom'?`<label class="sba-f mt-3"><span>Until</span><input type="datetime-local" id="mod-${k}-until" min="${now}" value="${now}" class="tsf-sel" data-testid="mod-${k}-until"></label>`:''}
   <label class="sba-f mt-3"><span>Reason <i class="tsf-opt">${k==='ban'?'shown to them':'optional'}</i></span><input id="mod-${k}-reason" maxlength="300" placeholder="${k==='ban'?'e.g. Harassing other users':'e.g. Inappropriate bio'}" data-testid="mod-${k}-reason"></label>`; }
function modHtml(){ const d=_sxV.d, M=d.mod||{}, L=M.live||{}, t=_mod.tab, nm=d.display_name||d.username, adm=M.viewer_role==='admin';
  const tabs=[['status','Ban & mute','gavel'],['profile','Profile','user-pen'],['badges','Badges & role','badge-check']].concat(modCan('delete')?[['danger','Delete','trash-2']]:[]);
  const lock=txt=>`<p class="mod-lock"><i data-lucide="lock"></i>${txt}</p>`;
  const sec=(ic,title,sub,body,tid)=>`<section class="mod-sec" data-testid="${tid}"><div class="mod-sec-h"><span class="pfa-row-ic"><i data-lucide="${ic}"></i></span><span class="min-w-0"><b>${title}</b><small>${sub}</small></span></div>${body}</section>`;
  const busy=_mod.busy?' disabled':'';
  let body='';
  if(t==='status'){
    body=sec('ban','Ban','Signs them out and stops them signing in until the time you pick. Their profile shows \u201cSuspended\u201d.',
      !modCan('ban')?lock(d.role==='admin'?'Moderators can\u2019t act on admins.':'Only admins can ban people.'):(M.banned_until?`<div class="mod-cur is-err" data-testid="mod-ban-current"><i data-lucide="ban"></i><span>Banned ${esc(stUntil(M.banned_until))}${M.ban_reason?'<small>'+esc(M.ban_reason)+'</small>':''}</span><button type="button" data-act="mod-unban" data-testid="mod-unban" class="sba-btn press"${busy}>Lift ban</button></div>`:'')+modDurHtml('ban')+`<button type="button" data-act="mod-ban-go" data-testid="mod-ban-submit" class="sba-btn is-danger lg press mt-4"${busy}><i data-lucide="ban"></i>${M.banned_until?'Update ban':'Ban @'+esc(d.username)}</button>`,'mod-ban-section')
     +sec('volume-x','Mute','They can keep editing their profile, but nothing they change goes public until the mute ends.',
      !modCan('mute')?lock('Moderators can\u2019t act on admins.'):(M.muted_until?`<div class="mod-cur is-warn" data-testid="mod-mute-current"><i data-lucide="volume-x"></i><span>Muted ${esc(stUntil(M.muted_until))}${M.mute_reason?'<small>'+esc(M.mute_reason)+'</small>':''}</span><button type="button" data-act="mod-unmute" data-testid="mod-unmute" class="sba-btn press"${busy}>Unmute</button></div>`:'')+modDurHtml('mute')+`<button type="button" data-act="mod-mute-go" data-testid="mod-mute-submit" class="sba-btn is-primary lg press mt-4"${busy}><i data-lucide="volume-x"></i>${M.muted_until?'Update mute':'Mute @'+esc(d.username)}</button>`,'mod-mute-section'); }
  else if(t==='profile'){ const can=modCan('edit');
    body=(M.muted_until?`<div class="mod-note"><i data-lucide="info"></i><span>@${esc(d.username)} is muted, so people see their profile from before the mute. Your changes apply to both.</span></div>`:'')+(!can?lock('Moderators can\u2019t act on admins.'):
     sec('type','Display name','Rename it if it\u2019s inappropriate.',`<div class="umx-lrow"><input id="mod-name" maxlength="40" value="${esc(L.display_name||'')}" class="umx-in" data-testid="mod-name-input"><button type="button" data-act="mod-save" data-val="display_name" data-testid="mod-name-save" class="sba-btn is-primary press"${busy}>Save</button></div>`,'mod-name-section')
     +sec('at-sign','Username','3\u201320 letters, numbers, _ or .',`<div class="umx-lrow"><input id="mod-uname" maxlength="20" autocapitalize="none" spellcheck="false" value="${esc(L.username||'')}" class="umx-in" data-testid="mod-username-input"><button type="button" data-act="mod-save" data-val="username" data-testid="mod-username-save" class="sba-btn is-primary press"${busy}>Save</button></div>`,'mod-username-section')
     +sec('quote','Bio','Edit or clear their bio.',`<textarea id="mod-bio" rows="3" maxlength="160" class="tsf-ta" data-testid="mod-bio-input">${esc(L.bio||'')}</textarea><div class="mod-row"><button type="button" data-act="mod-save" data-val="bio" data-testid="mod-bio-save" class="sba-btn is-primary press"${busy}>Save bio</button><button type="button" data-act="mod-clear-bio" data-testid="mod-bio-clear" class="sba-btn press"${busy}>Clear bio</button></div>`,'mod-bio-section')
     +sec('image','Photos','Removes the picture for everyone.',`<div class="mod-pics"><div class="mod-pic"><span class="sx-av is-md">${L.avatar_url?`<img src="${esc(L.avatar_url)}" alt="">`:'<i data-lucide="user-round"></i>'}</span><button type="button" data-act="mod-rm" data-val="avatar" data-testid="mod-remove-avatar" class="sba-btn press"${L.avatar_url&&!_mod.busy?'':' disabled'}><i data-lucide="trash-2"></i>Remove photo</button></div><div class="mod-pic"><span class="mod-bn"${L.banner_url?` style="background-image:url('${esc(L.banner_url)}')"`:''}></span><button type="button" data-act="mod-rm" data-val="banner" data-testid="mod-remove-banner" class="sba-btn press"${L.banner_url&&!_mod.busy?'':' disabled'}><i data-lucide="trash-2"></i>Remove banner</button></div></div>`,'mod-photos-section')); }
  else if(t==='badges'){ const ic=d.verified_icon||'';
    body=sec('badge-check','Verified','For real members of the Treesh Icons. Link their Icon page so people can find their music.',!modCan('verify')?lock('Only admins can verify people.'):`<label class="tsf-chk"><input type="checkbox" id="mod-vf" ${d.verified?'checked':''} data-testid="mod-verified-toggle"><span><b>Verified</b><small>Shows a check next to their name everywhere.</small></span></label><label class="sba-f mt-3"><span>Treesh Icon page <i class="tsf-opt">optional</i></span><select id="mod-vf-icon" class="tsf-sel" data-testid="mod-verified-icon"><option value="">No Icon link</option>${(ARTISTS||[]).slice().sort((a,b)=>String(a.name).localeCompare(b.name)).map(a=>`<option value="${esc(a.id)}"${a.id===ic?' selected':''}>${esc(a.name)}</option>`).join('')}</select></label><button type="button" data-act="mod-vf-save" data-testid="mod-verified-save" class="sba-btn is-primary lg press mt-4"${busy}><i data-lucide="badge-check"></i>Save verification</button>`,'mod-verified-section')
     +sec('shield','Role','Admins can do everything. Moderators can mute and edit profiles, but can\u2019t ban, delete, verify or act on admins.',
       !adm?lock('Only admins can change roles.'):`<div class="mod-roles" role="radiogroup" aria-label="Role" data-testid="mod-role-options">${MOD_ROLES.map(([r,l,ic,s])=>{ const on=(d.role||'user')===r; return `<button type="button" role="radio" aria-checked="${on}" data-act="mod-role" data-val="${r}" data-testid="mod-role-${r}" class="mod-role press is-${r}${on?' on':''}"${busy||(on?' disabled':'')}><span class="mod-role-ic"><i data-lucide="${ic}"></i></span><b>${l}</b><small>${s}</small>${on?'<em data-testid="mod-role-current">Current</em>':''}</button>`; }).join('')}</div>`,'mod-role-section'); }
  else if(t==='danger'){ body=sec('trash-2','Delete account','Deletes their account, profile, friends and synced data for good. This can\u2019t be undone.',`<label class="sba-f"><span>Type <b>${esc(d.username)}</b> to confirm</span><input id="mod-del" autocapitalize="none" spellcheck="false" placeholder="${esc(d.username)}" data-testid="mod-delete-confirm-input"></label><button type="button" data-act="mod-del-go" data-testid="mod-delete-submit" class="sba-btn is-danger lg press mt-4"${busy}><i data-lucide="trash-2"></i>Delete @${esc(d.username)}</button>`,'mod-delete-section'); }
  if(_mod.ask){ const A=_mod.ask; body=`<div class="mod-ask" data-testid="moderation-confirm"><span class="pm-alert-ic"><i data-lucide="triangle-alert"></i></span><h3 class="pm-title" data-testid="moderation-confirm-title">${esc(A.title)}</h3><p class="pm-desc">${esc(A.desc)}</p><div class="mod-row"><button type="button" data-act="mod-ask-no" data-testid="moderation-confirm-cancel" class="sba-btn lg press">Cancel</button><button type="button" data-act="mod-ask-yes" data-testid="moderation-confirm-ok" class="sba-btn is-danger lg press">${esc(A.ok)}</button></div></div>`; }
  return `<div class="tsf-head"><span class="mod-av">${sxAv(d)}</span><div class="min-w-0 flex-1"><h3 class="tsf-t sx-nm"><span class="clamp-1">${esc(nm)}</span>${sxNameBadges(d,false,'mod')}</h3><p class="tsf-d">@${esc(d.username)}${d.suspended?' \u00b7 <span class="sx-susp">Suspended</span>':''}${M.muted_until?' \u00b7 <span class="sx-susp is-warn">Muted</span>':''}</p></div><button type="button" data-act="modal2-close" aria-label="Close" data-testid="moderation-close" class="tsf-x press"><i data-lucide="x"></i></button></div>
   <div class="sx-tabs no-scrollbar mod-tabs" role="tablist" data-testid="moderation-tabs">${tabs.map(([k,l,ic])=>`<button type="button" role="tab" aria-selected="${t===k}" data-act="mod-tab" data-val="${k}" data-testid="moderation-tab-${k}" class="sx-tab${t===k?' on':''}"><i data-lucide="${ic}"></i>${l}</button>`).join('')}</div>
   <div class="mod-body soft-scroll" data-testid="moderation-body">${body}</div>`; }
function modAsk(title,desc,ok,fn){ _mod.ask={title,desc,ok,fn}; modPaint(); }
function modUntil(k){ const v=_mod[k+'Dur'], D=MOD_DUR.find(x=>x[0]===v); if(!D) return null;
  if(v==='perm') return new Date(Date.now()+100*365.25*864e5).toISOString();
  if(v==='custom'){ const i=document.getElementById('mod-'+k+'-until'), t=i&&i.value?new Date(i.value):null; if(!t||isNaN(t)||t.getTime()<=Date.now()+30000){ toast('Pick a time in the future'); if(i) i.focus(); return null; } return t.toISOString(); }
  return new Date(Date.now()+D[2]).toISOString(); }
async function modRun(fn,args,ok){ const d=_sxV&&_sxV.d; if(!d||_mod.busy) return null; _mod.busy=true; modPaint();
  try{ const r=await sxRpc(fn,args); toast(ok[0],ok[1]||''); return r==null?true:r; }catch(e){ toast('Couldn\u2019t do that',sxErr(e)); return null; } finally{ if(_mod) _mod.busy=false; } }
async function modReload(u){ await sxOpenProfile(u||(_sxV&&_sxV.u)); if(_mod&&document.querySelector('#modal2 .mod-sheet')&&_sxV&&_sxV.d&&_sxV.d.mod) modPaint(); }
async function modClean(uid,bucket,re){ try{ const {data}=await sb.storage.from(bucket).list(uid); const f=(data||[]).filter(x=>!re||re.test(x.name)).map(x=>uid+'/'+x.name); if(f.length) await sb.storage.from(bucket).remove(f); }catch(e){ console.warn('cleanup',e); } }
async function modAct(a,t){ const d=_sxV&&_sxV.d; if(!d) return; const id=d.id, u='@'+d.username, val=id2=>((document.getElementById(id2)||{}).value||'').trim();
  if(a==='mod-ban-go'){ const until=modUntil('ban'); if(!until) return; modAsk('Ban '+u+'?','They\u2019ll be signed out and can\u2019t sign in '+stUntil(until)+'.','Ban',async()=>{ if(await modRun('staff_set_ban',{target:id,until,reason:val('mod-ban-reason')},['Banned '+u,stUntil(until)])) modReload(); }); return; }
  if(a==='mod-unban'){ if(await modRun('staff_set_ban',{target:id,until:null,reason:null},['Ban lifted',u+' can sign in again'])) modReload(); return; }
  if(a==='mod-mute-go'){ const until=modUntil('mute'); if(!until) return; if(await modRun('staff_set_mute',{target:id,until,reason:val('mod-mute-reason')},['Muted '+u,stUntil(until)])) modReload(); return; }
  if(a==='mod-unmute'){ if(await modRun('staff_set_mute',{target:id,until:null,reason:null},['Unmuted '+u,'Their latest changes are public now'])) modReload(); return; }
  if(a==='mod-save'||a==='mod-clear-bio'){ const k=a==='mod-clear-bio'?'bio':t.dataset.val; let v=a==='mod-clear-bio'?'':val({display_name:'mod-name',username:'mod-uname',bio:'mod-bio'}[k]);
    if(k==='display_name'&&!v){ toast('Enter a name'); return; } if(k==='username'){ v=v.replace(/^@+/,'').toLowerCase(); if(!SB_UNAME.test(v)){ toast('Check the username','3\u201320 letters, numbers, _ or .'); return; } }
    const r=await modRun('staff_edit_profile',{target:id,changes:{[k]:v}},[{display_name:'Name changed',username:'Username changed',bio:a==='mod-clear-bio'?'Bio cleared':'Bio updated'}[k]]); if(r) modReload(k==='username'?v:null); return; }
  if(a==='mod-rm'){ const w=t.dataset.val; modAsk(w==='avatar'?'Remove '+u+'\u2019s photo?':'Remove '+u+'\u2019s banner?','It\u2019s removed for everyone.','Remove',async()=>{ const r=await modRun('staff_edit_profile',{target:id,changes:w==='avatar'?{remove_avatar:true}:{remove_banner:true}},[w==='avatar'?'Photo removed':'Banner removed']); if(r){ modClean(id,'avatars',w==='avatar'?/^avatar\./:/^banner\./); modReload(); } }); return; }
  if(a==='mod-vf-save'){ const on=!!(document.getElementById('mod-vf')||{}).checked, icon=val('mod-vf-icon'); if(await modRun('staff_set_verified',{target:id,on_off:on,icon:icon||null},[on?'Verified '+u:'Verification removed',on&&stIcon(icon)?'Linked to '+stIcon(icon).name:''])) modReload(); return; }
  if(a==='mod-role'){ const nr=t.dataset.val, cur=d.role||'user'; if(nr===cur) return; const go=async()=>{ if(await modRun('staff_set_role',{target:id,new_role:nr},[u+' is '+{user:'a member',moderator:'a moderator',admin:'an admin'}[nr]+' now'])) modReload(); };
    if(nr==='admin'||cur==='admin') modAsk(nr==='admin'?'Make '+u+' an admin?':'Remove admin from '+u+'?',nr==='admin'?'Admins can ban, delete accounts, verify people and change anyone\u2019s role, including yours.':'They lose admin powers right away.',nr==='admin'?'Make admin':'Remove admin',go); else go(); return; }
  if(a==='mod-del-go'){ if(val('mod-del').replace(/^@+/,'').toLowerCase()!==d.username){ toast('Type the username to confirm',d.username); return; }
    modAsk('Delete '+u+' for good?','Their account, profile and synced data are erased. This can\u2019t be undone.','Delete forever',async()=>{ await modClean(id,'avatars'); await modClean(id,'treesh-data'); const r=await modRun('staff_delete_user',{target:id},['Account deleted',u+' is gone']); if(r){ _mod=null; closeModal2(); sxClose(); _sxQ.q=null; } }); return; } }

/* staff dashboard */
function modDashOpen(){ if(!stStaff()){ toast('Moderation is for Treesh staff'); return; } _modD={tab:'log',list:null,busy:true,err:null,q:'',res:null,seq:0};
  $("#modal2").innerHTML=modal2Wrap(`<div class="mod-sheet mod-dash" data-testid="moderation-dashboard"><div class="tsf-head"><span class="sba-orb"><i data-lucide="gavel"></i></span><div class="min-w-0 flex-1"><h3 class="tsf-t">Moderation</h3><p class="tsf-d">You\u2019re a Treesh ${stRole()==='admin'?'admin':'moderator'}. Open anyone\u2019s profile to take action.</p></div><button type="button" data-act="modal2-close" aria-label="Close" data-testid="moderation-dashboard-close" class="tsf-x press"><i data-lucide="x"></i></button></div>
   <label class="tl-search"><i data-lucide="search"></i><input id="mod-q" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="Find anyone by @username or name" data-testid="moderation-search"></label>
   <div class="sx-tabs no-scrollbar mod-tabs" role="tablist" data-testid="moderation-dashboard-tabs">${[['log','Activity','history'],['suspended','Banned','ban'],['muted','Muted','volume-x'],['staff','Staff','shield'],['verified','Verified','badge-check']].map(([k,l,ic])=>`<button type="button" role="tab" data-act="mod-dtab" data-val="${k}" data-testid="moderation-dashboard-tab-${k}" class="sx-tab${k==='log'?' on':''}"><i data-lucide="${ic}"></i>${l}</button>`).join('')}</div>
   <div class="mod-body soft-scroll" id="mod-dlist" data-testid="moderation-dashboard-list"></div></div>`,'moderation-dashboard-modal','xl'); icons(); syncScrollLock(); modDashLoad(); }
async function modDashLoad(){ if(!_modD) return; const T=_modD.tab, seq=++_modD.seq; _modD.busy=true; _modD.err=null; modDashPaint();
  try{ const r=T==='log'?await sxRpc('staff_log',{lim:80}):await sxRpc('staff_list',{kind:T}); if(!_modD||seq!==_modD.seq) return; _modD.list=r||[]; }catch(e){ if(_modD) _modD.err=e; } if(_modD&&seq===_modD.seq){ _modD.busy=false; modDashPaint(); } }
function modUserRow(u,sub,i){ return `<button type="button" data-act="mod-open-u" data-u="${esc(u.username||'')}" data-testid="moderation-row-${esc(u.username||i)}" class="sx-row press" style="--d:${Math.min(i,8)*30}ms"${u.username?'':' disabled'}>${sxAv(u)}<span class="min-w-0 flex-1"><b class="sx-nm"><span class="clamp-1">${esc(u.display_name||u.username||'Deleted account')}</span>${sxNameBadges(u,false,'d-'+(u.username||i))}</b><small class="clamp-1">${u.username?'@'+esc(u.username)+' \u00b7 ':''}${sub}</small></span><i data-lucide="chevron-right" class="sx-chev"></i></button>`; }
function modDashPaint(){ const el=document.getElementById('mod-dlist'); if(!el||!_modD) return; const D=_modD;
  document.querySelectorAll('#modal2 [data-act="mod-dtab"]').forEach(b=>b.classList.toggle('on',b.dataset.val===D.tab&&!D.q));
  if(D.q){ el.innerHTML=D.res==null?`<div class="sx-load"><span class="sx-spin"></span></div>`:D.res.length?`<div class="sx-list">${D.res.map((u,i)=>modUserRow(u,u.suspended?'<span class="sx-susp">Suspended</span>':(u.role!=='user'?esc(u.role):'Member'),i)).join('')}</div>`:sxEmpty('search-x','No one matches','Try their exact @username.'); icons(); return; }
  if(D.busy&&!D.list){ el.innerHTML=`<div class="sx-load"><span class="sx-spin"></span><p>Loading\u2026</p></div>`; return; }
  if(D.err){ el.innerHTML=sxEmpty('triangle-alert','Couldn\u2019t load this',esc(sxErr(D.err))); icons(); return; }
  const L=D.list||[]; if(!L.length){ el.innerHTML=sxEmpty({log:'history',suspended:'ban',muted:'volume-x',staff:'shield',verified:'badge-check'}[D.tab],{log:'No actions yet',suspended:'No one is banned',muted:'No one is muted',staff:'No staff yet',verified:'No one is verified yet'}[D.tab],''); icons(); return; }
  if(D.tab==='log') el.innerHTML=`<div class="mod-log" data-testid="moderation-log">${L.map((x,i)=>{ const A=MOD_ACT[x.action]||['circle-dot',x.action], who=x.target_username||x.target_name; const det=x.detail||{}; const extra=x.action==='ban'||x.action==='mute'?(det.until?' '+stUntil(det.until):'')+(det.reason?' \u00b7 '+esc(det.reason):''):x.action==='edit'?' \u00b7 '+Object.keys(det).map(k=>k.replace('_',' ')).join(', '):'';
    return `<button type="button" data-act="mod-open-u" data-u="${esc(x.target_username||'')}" class="mod-log-row press" data-testid="moderation-log-${i}"${x.target_username?'':' disabled'}><span class="mod-log-ic is-${esc(x.action)}"><i data-lucide="${A[0]}"></i></span><span class="min-w-0 flex-1"><span class="mod-log-t"><b>@${esc(x.actor_username||'staff')}</b> ${A[1]} <b>${who?'@'+esc(who):'an account'}</b></span><small>${esc(swAgo(Date.parse(x.created_at)))}${extra}</small></span></button>`; }).join('')}</div>`;
  else el.innerHTML=`<div class="sx-list">${L.map((u,i)=>modUserRow(u,D.tab==='suspended'?'Banned '+esc(stUntil(u.banned_until))+(u.ban_reason?' \u00b7 '+esc(u.ban_reason):''):D.tab==='muted'?'Muted '+esc(stUntil(u.muted_until)):D.tab==='staff'?(u.role==='admin'?'Admin':'Moderator'):(stIcon(u.verified_icon)?'Icon \u00b7 '+esc(stIcon(u.verified_icon).name):'Verified'),i)).join('')}</div>`;
  icons(); }
let _modQT=0;
document.addEventListener('input',e=>{ if(!e.target||e.target.id!=='mod-q'||!_modD) return; const q=e.target.value.trim().replace(/^@+/,'').toLowerCase(); _modD.q=q; _modD.res=null; clearTimeout(_modQT); if(!q){ modDashPaint(); return; } modDashPaint(); const seq=++_modD.seq;
  _modQT=setTimeout(async()=>{ let r=[]; try{ r=(await sxRpc('search_users',{q}))||[]; }catch(err){} if(_modD&&seq===_modD.seq&&_modD.q===q){ _modD.res=r; modDashPaint(); } },260); });

/* talents */
const TL_MAX=5;
const TL_CATS=[
 ['Music',[['music-artist','Music Artist','mic-vocal'],['singer','Singer','mic-2'],['rapper','Rapper','mic'],['songwriter','Songwriter','pen-line'],['producer','Music Producer','sliders-horizontal'],['beatmaker','Beatmaker','drum'],['dj','DJ','disc-3'],['composer','Composer','music-4'],['audio-engineer','Audio Engineer','audio-lines'],['mixing-engineer','Mixing Engineer','sliders-horizontal'],['guitarist','Guitarist','guitar'],['bassist','Bassist','guitar'],['drummer','Drummer','drum'],['pianist','Pianist','piano'],['keyboardist','Keyboardist','piano'],['violinist','Violinist','music-2'],['cellist','Cellist','music-2'],['saxophonist','Saxophonist','music'],['trumpeter','Trumpeter','music'],['vocal-coach','Vocal Coach','ear'],['choir-singer','Choir Singer','users-round'],['beatboxer','Beatboxer','mic-2'],['music-teacher','Music Teacher','graduation-cap'],['a-and-r','A&R','headphones']]],
 ['Performance',[['actor','Actor','drama'],['dancer','Dancer','footprints'],['choreographer','Choreographer','sparkles'],['comedian','Comedian','smile'],['voice-actor','Voice Actor','mic'],['model','Model','camera'],['runway-model','Runway Model','sparkles'],['host','Host / MC','megaphone'],['magician','Magician','wand-sparkles'],['circus-artist','Circus Artist','tent'],['stunt-performer','Stunt Performer','rocket'],['spoken-word','Spoken Word Artist','message-square']]],
 ['Visual Arts',[['painter','Painter','palette'],['illustrator','Illustrator','pen-tool'],['graphic-designer','Graphic Designer','shapes'],['photographer','Photographer','camera'],['videographer','Videographer','video'],['filmmaker','Filmmaker','clapperboard'],['director','Director','film'],['cinematographer','Cinematographer','aperture'],['animator','Animator','layers-3'],['3d-artist','3D Artist','box'],['tattoo-artist','Tattoo Artist','pen-tool'],['graffiti-artist','Graffiti Artist','spray-can'],['sculptor','Sculptor','hammer'],['cartoonist','Cartoonist','sticker'],['calligrapher','Calligrapher','feather'],['art-director','Art Director','frame']]],
 ['Fashion & Beauty',[['fashion-designer','Fashion Designer','shirt'],['stylist','Stylist','sparkles'],['makeup-artist','Makeup Artist','brush'],['hair-stylist','Hair Stylist','scissors'],['barber','Barber','scissors'],['nail-artist','Nail Artist','paintbrush'],['cosplayer','Cosplayer','ghost'],['jewelry-designer','Jewelry Designer','gem'],['tailor','Tailor','ruler'],['sneaker-designer','Sneaker Designer','footprints']]],
 ['Writing',[['writer','Writer','pen-line'],['poet','Poet','feather'],['author','Author','book-open'],['lyricist','Lyricist','quote'],['journalist','Journalist','newspaper'],['screenwriter','Screenwriter','clapperboard'],['blogger','Blogger','notebook-pen'],['editor','Editor','type'],['translator','Translator','languages']]],
 ['Digital & Tech',[['content-creator','Content Creator','smartphone'],['video-creator','Video Creator','video'],['streamer','Streamer','tv'],['podcaster','Podcaster','podcast'],['influencer','Influencer','star'],['gamer','Gamer','gamepad-2'],['esports-player','Esports Player','trophy'],['developer','Developer','code'],['game-developer','Game Developer','gamepad-2'],['app-developer','App Developer','app-window'],['web-designer','Web Designer','monitor'],['ui-ux-designer','UI/UX Designer','component'],['video-editor','Video Editor','film'],['vfx-artist','VFX Artist','wand-sparkles'],['ai-artist','AI Artist','bot'],['data-scientist','Data Scientist','database'],['engineer','Engineer','cpu']]],
 ['Food & Drink',[['chef','Chef','chef-hat'],['baker','Baker','croissant'],['pastry-chef','Pastry Chef','cake'],['home-cook','Home Cook','cooking-pot'],['bartender','Bartender','martini'],['mixologist','Mixologist','wine'],['barista','Barista','coffee'],['food-creator','Food Creator','utensils'],['pitmaster','Pitmaster','flame'],['caterer','Caterer','utensils-crossed']]],
 ['Sports & Fitness',[['athlete','Athlete','medal'],['basketball-player','Basketball Player','trophy'],['soccer-player','Soccer Player','volleyball'],['football-player','Football Player','trophy'],['skater','Skater','footprints'],['skateboarder','Skateboarder','rocket'],['boxer','Boxer','hand-metal'],['martial-artist','Martial Artist','swords'],['fitness-coach','Fitness Coach','dumbbell'],['yoga-teacher','Yoga Teacher','leaf'],['runner','Runner','footprints'],['swimmer','Swimmer','waves'],['cyclist','Cyclist','bike'],['cheerleader','Cheerleader','megaphone'],['gymnast','Gymnast','sparkles'],['surfer','Surfer','waves'],['climber','Climber','mountain']]],
 ['Business',[['entrepreneur','Entrepreneur','rocket'],['artist-manager','Artist Manager','briefcase'],['marketer','Marketer','chart-line'],['promoter','Promoter','megaphone'],['event-planner','Event Planner','calendar'],['publicist','Publicist','newspaper'],['label-owner','Label Owner','disc-3'],['brand-strategist','Brand Strategist','target'],['sales','Sales','handshake'],['investor','Investor','piggy-bank'],['booking-agent','Booking Agent','ticket']]],
 ['Crafts & Making',[['crafter','Crafter','scissors'],['woodworker','Woodworker','axe'],['potter','Potter','shapes'],['knitter','Knitter','heart'],['florist','Florist','flower-2'],['gardener','Gardener','sprout'],['diy-maker','DIY Maker','wrench'],['builder','Builder','hard-hat'],['candle-maker','Candle Maker','flame']]],
 ['Life & Community',[['teacher','Teacher','graduation-cap'],['student','Student','book-marked'],['life-coach','Life Coach','heart-handshake'],['mentor','Mentor','users-round'],['activist','Activist','megaphone'],['volunteer','Volunteer','hand-heart'],['pet-trainer','Pet Trainer','paw-print'],['traveler','Traveler','plane'],['scientist','Scientist','flask-conical'],['healthcare-worker','Healthcare Worker','stethoscope'],['parent','Parent','baby'],['collector','Collector','library']]]];
const FV_MAX=10;
const FV_LISTS={
 music:['Music genres','music',['Hip-Hop','Rap','Trap','Drill','R&B','Soul','Neo-Soul','Pop','K-Pop','J-Pop','Afrobeats','Amapiano','Dancehall','Reggae','Reggaeton','Latin','Rock','Alternative','Indie','Punk','Metal','Emo','Grunge','Jazz','Blues','Funk','Disco','Gospel','Country','Folk','Classical','Opera','EDM','House','Techno','Dubstep','Drum & Bass','Lo-fi','Ambient','Synthwave','Hyperpop','Phonk','Soundtracks','Musicals']],
 movies:['Film & show genres','clapperboard',['Action','Comedy','Drama','Horror','Thriller','Romance','Sci-Fi','Fantasy','Animation','Anime','Documentary','Musicals','Mystery','Crime','Superhero','Reality TV','Sitcoms','Stand-up','Theater','Indie film']],
 art:['Art styles','palette',['Realism','Abstract','Surrealism','Pop Art','Street Art','Graffiti','Anime & Manga','Comics','Digital Art','Pixel Art','3D Art','Watercolor','Oil Painting','Portraits','Landscapes','Minimalism','Photography','Fashion Photography','Film Photography','Concept Art','Cyberpunk','Vaporwave','Collage','Sculpture','Tattoo Art']],
 fashion:['Fashion & beauty styles','shirt',['Streetwear','Y2K','Vintage','Thrift','Luxury','Minimalist','Grunge','Goth','Preppy','Athleisure','Boho','Techwear','Old Money','Cottagecore','Avant-garde','Sneakers','Jewelry','Makeup','Nail Art','Hairstyles']],
 books:['Book genres','book-open',['Fiction','Poetry','Fantasy','Sci-Fi','Romance','Mystery','Thriller','Horror','Biography','Memoir','Self-help','History','Comics','Manga','Graphic Novels','Young Adult','Classics','Short Stories','Journalism','Philosophy']],
 games:['Game genres','gamepad-2',['Action','Adventure','RPG','JRPG','Shooter','Battle Royale','Fighting','Racing','Sports','Platformer','Puzzle','Horror','Survival','Sandbox','Open World','Strategy','MOBA','MMO','Simulation','Rhythm','Indie','Retro','Card Games','Party Games','Visual Novels','VR']],
 tech:['Tech interests','cpu',['AI','Web Development','App Development','Game Dev','Gadgets','Cybersecurity','Crypto & Web3','Robotics','Open Source','Design Tools','Video Editing','Streaming Setups','Social Media','Podcasting','Camera Gear','Smart Home']],
 food:['Foods & cuisines','utensils',['Pizza','Burgers','Tacos','Sushi','Ramen','Pasta','BBQ','Fried Chicken','Wings','Soul Food','Southern','Mexican','Italian','Japanese','Korean','Chinese','Thai','Indian','Caribbean','Jamaican','Nigerian','Ethiopian','Mediterranean','Greek','French','Vegan','Vegetarian','Seafood','Desserts','Baking','Coffee','Tea','Smoothies','Cocktails','Street Food','Brunch']],
 sports:['Sports','trophy',['Basketball','Football','Soccer','Baseball','Tennis','Boxing','MMA','Wrestling','Track & Field','Swimming','Skateboarding','Surfing','Snowboarding','Cycling','Gymnastics','Volleyball','Golf','Hockey','Cheer','Dance','Yoga','Running','Weightlifting','Climbing','Esports','F1 & Racing']],
 business:['Industries','briefcase',['Music Industry','Fashion','Film & TV','Tech','Gaming','Beauty','Food & Hospitality','Sports','Real Estate','Finance','Marketing','Media','Events','Nonprofit','E-commerce','Education']],
 crafts:['Crafts','scissors',['Knitting','Crochet','Sewing','Embroidery','Woodworking','Pottery','Candle Making','Jewelry Making','Resin Art','Paper Crafts','Scrapbooking','Gardening','Plants','Home Decor','DIY Repairs','Upcycling']],
 community:['Causes & interests','heart-handshake',['Mental Health','Education','Environment','Animal Rescue','Social Justice','LGBTQ+','Community Service','Faith','Parenting','Travel','Wellness','Science','Space','History','Languages','Volunteering']]};
const FV_BY_CAT={'Music':'music','Performance':'movies','Visual Arts':'art','Fashion & Beauty':'fashion','Writing':'books','Digital & Tech':'tech','Food & Drink':'food','Sports & Fitness':'sports','Business':'business','Crafts & Making':'crafts','Life & Community':'community'};
const FV_BY_TL={'gamer':'games','esports-player':'games','game-developer':'games','streamer':'games'};
const FV_GENERAL=['music','movies','games','food'];
function fvTlKeys(t){ t=tlNorm(t); if(!t) return []; const out=[]; [t.main].concat(t.more).forEach(id=>{ const k=FV_BY_TL[id]||FV_BY_CAT[TL_BY[id].c]; if(k&&!out.includes(k)) out.push(k); }); return out; }
function fvKeys(t){ const out=fvTlKeys(t); FV_GENERAL.forEach(k=>{ if(!out.includes(k)) out.push(k); }); return out; }
function fvClean(f){ const o={}; if(!f||typeof f!=='object') return o; Object.keys(FV_LISTS).forEach(k=>{ const L=FV_LISTS[k][2]; const v=(Array.isArray(f[k])?f[k]:[]).filter((x,i,a)=>L.includes(x)&&a.indexOf(x)===i).slice(0,FV_MAX); if(v.length) o[k]=v; }); return o; }
function fvShown(t,f){ const c=fvClean(f), o={}; fvKeys(t).forEach(k=>{ if(c[k]) o[k]=c[k]; }); return o; }
function fvCount(F){ return Object.values(F||{}).reduce((n,a)=>n+a.length,0); }
function fvHtml(F){ return Object.keys(F).map(k=>`<section class="fv-sec" data-testid="favorites-view-${k}"><p class="tsf-k"><i data-lucide="${FV_LISTS[k][1]}"></i>${esc(FV_LISTS[k][0])}</p><div class="tl-chips">${F[k].map(x=>`<span class="fv-chip">${esc(x)}</span>`).join('')}</div></section>`).join(''); }
const TL_BY={}; TL_CATS.forEach(([c,l])=>l.forEach(t=>{ TL_BY[t[0]]={id:t[0],l:t[1],ic:t[2],c}; }));
function tlNorm(t){ if(!t||typeof t!=='object') return null; const main=TL_BY[t.main]?t.main:''; const more=(Array.isArray(t.more)?t.more:[]).filter((x,i,a)=>TL_BY[x]&&x!==main&&a.indexOf(x)===i).slice(0,TL_MAX); if(!main&&!more.length) return null; return main?{main,more}:{main:more[0],more:more.slice(1)}; }
function tlGet(){ return tlNorm((state.profile||{}).talents); }
function tlBadge(t,who,tid){ t=tlNorm(t); if(!t) return ''; const m=TL_BY[t.main], n=t.more.length; return `<button type="button" data-act="tl-view" data-val="${who}" data-testid="${tid}" class="tl-badge press" aria-label="${esc(m.l)}${n?', plus '+n+' more talents':''}. See all talents"><i data-lucide="${m.ic}"></i><span>${esc(m.l)}</span>${n?`<em>+${n}</em>`:''}</button>`; }
function tlEditHtml(){ const t=tlGet(); return `<div class="mt-5 tl-edit" data-testid="profile-talents-edit"><label class="mb-1.5 block text-xs uppercase tracking-wide text-white/50">Talents</label><div class="tl-edit-row">${t?[t.main].concat(t.more).map((id,i)=>`<span class="tl-chip${i?'':' is-main'}"><i data-lucide="${TL_BY[id].ic}"></i>${esc(TL_BY[id].l)}${i?'':'<span class="tl-star"><i data-lucide="star"></i></span>'}</span>`).join(''):'<span class="tl-hint">Show people what you do. Pick a main talent, then add more.</span>'}<button type="button" data-act="tl-pick" data-testid="profile-talents-choose" class="tl-add press"><i data-lucide="${t?'pencil':'plus'}"></i>${t?'Edit talents':'Add talents'}</button></div>${(()=>{ const nf=fvCount(fvShown(t,(state.profile||{}).favs)); return `<p class="tl-sub">${nf?nf+' favorite'+(nf===1?'':'s')+' picked. ':''}<button type="button" data-act="tl-pick" data-val="favs" data-testid="profile-favorites-choose" class="tl-link press">${nf?'Edit favorites':'Add favorite '+esc(fvKeys(t).map(k=>FV_LISTS[k][0].toLowerCase()).slice(0,2).join(' & '))}</button></p>`; })()}</div>`; }
function tlViewOpen(who){ const them=who==='them'; const src=them?((_sxV&&_sxV.d&&_sxV.d.data)||{}):(state.profile||{}); const t=tlNorm(src.talents), F=fvShown(t,src.favs); if(!t&&!fvCount(F)) return;
  const nm=them?(_sxV.d.display_name||_sxV.d.username):'Your', m=t?TL_BY[t.main]:null, nf=fvCount(F);
  $("#modal2").innerHTML=modal2Wrap(`<div class="tl-view" data-testid="talents-view-sheet"><div class="tsf-head"><span class="sba-orb"><i data-lucide="${t?'sparkles':'heart'}"></i></span><div class="min-w-0 flex-1"><h3 class="tsf-t">${them?esc(nm)+'\u2019s '+(t?'talents':'favorites'):'Your '+(t?'talents':'favorites')}</h3><p class="tsf-d">${t?(1+t.more.length)+' talent'+(t.more.length?'s':''):''}${t&&nf?' \u00b7 ':''}${nf?nf+' favorite'+(nf===1?'':'s'):''}</p></div><button type="button" data-act="modal2-close" aria-label="Close" data-testid="talents-view-close" class="tsf-x press"><i data-lucide="x"></i></button></div>
   ${m?`<div class="tl-main" data-testid="talents-view-main"><span class="tl-main-ic"><i data-lucide="${m.ic}"></i></span><span class="min-w-0"><small><i data-lucide="star"></i>Main talent</small><b>${esc(m.l)}</b><em>${esc(m.c)}</em></span></div>`:''}
   ${t&&t.more.length?`<p class="tsf-k mt-5">Also</p><div class="tl-grid" data-testid="talents-view-list">${t.more.map((id,i)=>`<div class="tl-cell" style="--d:${i*35}ms" data-testid="talents-view-${id}"><span class="tl-cell-ic"><i data-lucide="${TL_BY[id].ic}"></i></span><span class="min-w-0"><b class="clamp-1">${esc(TL_BY[id].l)}</b><small>${esc(TL_BY[id].c)}</small></span></div>`).join('')}</div>`:''}
   ${fvCount(F)?`<div class="fv-view" data-testid="favorites-view"><p class="tl-h"><i data-lucide="heart"></i>Favorites</p>${fvHtml(F)}</div>`:''}
   ${them?'':`<div class="mod-row mt-6"><button type="button" data-act="tl-pick" data-testid="talents-view-edit" class="sba-btn lg press"><i data-lucide="pencil"></i>Edit talents</button><button type="button" data-act="tl-pick" data-val="favs" data-testid="favorites-view-edit" class="sba-btn lg press"><i data-lucide="heart"></i>Edit favorites</button></div>`}</div>`,'talents-view-modal','lg'); icons(); syncScrollLock(); }
let _tl=null;
function tlPickOpen(tab){ const t=tlGet(); _tl={main:t?t.main:'',more:t?t.more.slice():[],q:'',tab:tab==='favs'?'favs':'talents',favs:fvClean((state.profile||{}).favs)};
  $("#modal2").innerHTML=modal2Wrap(`<div class="tl-pick" data-testid="talents-picker"><div class="tsf-head"><span class="sba-orb"><i data-lucide="sparkles"></i></span><div class="min-w-0 flex-1"><h3 class="tsf-t">Talents &amp; favorites</h3><p class="tsf-d">Your first talent is your main one. Add up to ${TL_MAX} more.</p></div><button type="button" data-act="modal2-close" aria-label="Close" data-testid="talents-close" class="tsf-x press"><i data-lucide="x"></i></button></div>
   <div class="sx-tabs no-scrollbar tl-tabs" role="tablist" data-testid="talents-tabs"><button type="button" role="tab" data-act="tl-tab" data-val="talents" data-testid="talents-tab-talents" class="sx-tab${_tl.tab==='talents'?' on':''}"><i data-lucide="sparkles"></i>Talents</button><button type="button" role="tab" data-act="tl-tab" data-val="favs" data-testid="talents-tab-favorites" class="sx-tab${_tl.tab==='favs'?' on':''}"><i data-lucide="heart"></i>Favorites</button></div>
   <div class="tl-sel" id="tl-sel" data-testid="talents-selected">${tlSelHtml()}</div>
   <label class="tl-search"><i data-lucide="search"></i><input id="tl-q" autocomplete="off" placeholder="${_tl.tab==='favs'?'Search favorites':'Search '+Object.keys(TL_BY).length+' talents'}" data-testid="talents-search"></label>
   <div class="tl-list soft-scroll" id="tl-list" data-testid="talents-list">${tlListHtml()}</div>
   <div class="tl-foot"><button type="button" data-act="tl-save" data-testid="talents-save" class="sba-btn is-primary lg press"><i data-lucide="check"></i>Save</button></div></div>`,'talents-modal','xl'); icons(); syncScrollLock(); }
function tlSelHtml(){ if(_tl.tab==='favs'){ const n=fvCount(fvShown({main:_tl.main,more:_tl.more},_tl.favs)); return `<p class="tl-hint" data-testid="favorites-hint">Pick up to ${FV_MAX} in each list. ${_tl.main?'Your talents unlock extra lists.':'Add talents to unlock more lists.'}${n?` <b>${n} picked</b>`:''}</p>`; }
  if(!_tl.main) return `<p class="tl-hint" data-testid="talents-empty">Tap a talent below to make it your main one.</p>`;
  const chip=(id,main)=>`<span class="tl-chip${main?' is-main':''}" data-testid="talents-selected-${id}"><i data-lucide="${TL_BY[id].ic}"></i>${esc(TL_BY[id].l)}${main?'<span class="tl-star"><i data-lucide="star"></i>Main</span>':`<button type="button" data-act="tl-main" data-val="${id}" aria-label="Make ${esc(TL_BY[id].l)} your main talent" title="Make main" data-testid="talents-make-main-${id}"><i data-lucide="star"></i></button>`}<button type="button" data-act="tl-rm" data-val="${id}" aria-label="Remove ${esc(TL_BY[id].l)}" data-testid="talents-remove-${id}"><i data-lucide="x"></i></button></span>`;
  return chip(_tl.main,true)+_tl.more.map(id=>chip(id,false)).join('')+`<span class="tl-count" data-testid="talents-count">${_tl.more.length}/${TL_MAX} more</span>`; }
function tlListHtml(){ const q=_tl.q.trim().toLowerCase(); let h='';
  if(_tl.tab==='favs'){ const tt={main:_tl.main,more:_tl.more}, keys=fvKeys(tt), tk=fvTlKeys(tt);
    keys.forEach(k=>{ const [title,ic,L]=FV_LISTS[k], cur=_tl.favs[k]||[]; const items=L.filter(x=>!q||x.toLowerCase().includes(q)||title.toLowerCase().includes(q)); if(!items.length) return;
      h+=`<section class="tl-cat" data-testid="favorites-list-${k}"><p class="tsf-k"><i data-lucide="${ic}"></i>${esc(title)}${tk.includes(k)&&!FV_GENERAL.includes(k)?'<span class="fv-tag" data-testid="favorites-tag-'+k+'">From your talents</span>':''}<span class="tl-n">${cur.length}/${FV_MAX}</span></p><div class="tl-chips">${items.map((x,i)=>{ const on=cur.includes(x); return `<button type="button" data-act="fv-tog" data-k="${k}" data-val="${esc(x)}" aria-pressed="${on}" data-testid="favorite-opt-${k}-${L.indexOf(x)}" class="tl-opt press${on?' on':''}">${on?'<i data-lucide="check"></i>':''}${esc(x)}</button>`; }).join('')}</div></section>`; });
    return h||`<p class="sx-none">Nothing matches \u201c${esc(q)}\u201d.</p>`; }
  TL_CATS.forEach(([c,l])=>{ const items=l.filter(t=>!q||t[1].toLowerCase().includes(q)||c.toLowerCase().includes(q)); if(!items.length) return;
    h+=`<section class="tl-cat"><p class="tsf-k">${esc(c)}</p><div class="tl-chips">${items.map(t=>{ const on=_tl.main===t[0]||_tl.more.includes(t[0]); return `<button type="button" data-act="tl-tog" data-val="${t[0]}" aria-pressed="${on}" data-testid="talent-opt-${t[0]}" class="tl-opt press${on?' on':''}${_tl.main===t[0]?' is-main':''}"><i data-lucide="${t[2]}"></i>${esc(t[1])}</button>`; }).join('')}</div></section>`; });
  return h||`<p class="sx-none">No talents match \u201c${esc(q)}\u201d.</p>`; }
function tlPaint(list){ const s=document.getElementById('tl-sel'); if(s) s.innerHTML=tlSelHtml(); if(list!==false){ const l=document.getElementById('tl-list'); if(l){ const y=l.scrollTop; l.innerHTML=tlListHtml(); l.scrollTop=y; } } icons(); }
function tlSave(){ const p=Object.assign({},state.profile||{}); p.talents=_tl.main?{main:_tl.main,more:_tl.more.slice()}:null; p.favs=fvClean(_tl.favs); if(state.settingsEditProfile) pfStashDraft(); state.profile=p; LS.set('treesh_profile',p); closeModal2(); _tl=null; const nf=fvCount(fvShown(p.talents,p.favs)); toast(p.talents?'Talents saved':nf?'Favorites saved':'Talents cleared',p.talents?TL_BY[p.talents.main].l+(p.talents.more.length?' + '+p.talents.more.length+' more':''):nf?nf+' picked':''); pfRepaint(); try{ sxPublishSoon(); }catch(e){} }
document.addEventListener('input',e=>{ if(!e.target||e.target.id!=='tl-q'||!_tl) return; _tl.q=e.target.value; tlPaint(); });

document.addEventListener('click',e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act]'); if(!t) return; const a=t.dataset.act, v=t.dataset.val;
  if(a.indexOf('tl-')===0){ switch(a){
    case 'tl-view': tlViewOpen(v); break;
    case 'tl-pick': tlPickOpen(v); break;
    case 'tl-tab': if(!_tl) break; _tl.tab=v==='favs'?'favs':'talents'; _tl.q=''; document.querySelectorAll('#modal2 [data-act="tl-tab"]').forEach(b=>b.classList.toggle('on',b.dataset.val===_tl.tab)); { const i=document.getElementById('tl-q'); if(i){ i.value=''; i.placeholder=_tl.tab==='favs'?'Search favorites':'Search '+Object.keys(TL_BY).length+' talents'; } } tlPaint(); { const l=document.getElementById('tl-list'); if(l) l.scrollTop=0; } break;
    case 'tl-save': if(_tl) tlSave(); break;
    case 'tl-tog': if(!_tl) break; if(_tl.main===v){ _tl.main=_tl.more.shift()||''; } else if(_tl.more.includes(v)) _tl.more.splice(_tl.more.indexOf(v),1); else if(!_tl.main) _tl.main=v; else if(_tl.more.length>=TL_MAX){ toast('That\u2019s the max','Remove one to add another'); break; } else _tl.more.push(v); tlPaint(); break;
    case 'tl-rm': if(!_tl) break; if(_tl.main===v) _tl.main=_tl.more.shift()||''; else _tl.more=_tl.more.filter(x=>x!==v); tlPaint(); break;
    case 'tl-main': if(!_tl||!_tl.more.includes(v)) break; _tl.more=_tl.more.filter(x=>x!==v); if(_tl.main) _tl.more.unshift(_tl.main); _tl.main=v; tlPaint(); break; } return; }
  if(a==='fv-tog'){ if(!_tl) return; const k=t.dataset.k, cur=(_tl.favs[k]=_tl.favs[k]||[]); const i=cur.indexOf(v); if(i>=0) cur.splice(i,1); else if(cur.length>=FV_MAX){ toast('That\u2019s the max for this list','Remove one to add another'); return; } else cur.push(v); tlPaint(); return; }
  if(a==='modal2-close-ban'){ closeModal2(); return; }
  if(a==='mod-dash'){ modDashOpen(); return; }
  if(a==='mod-open-u'){ const u=t.dataset.u; if(!u) return; closeModal2(); _modD=null; sxOpenProfile(u); return; }
  if(a==='mod-dtab'){ if(!_modD) return; _modD.tab=v; _modD.list=null; _modD.q=''; const i=document.getElementById('mod-q'); if(i) i.value=''; modDashLoad(); return; }
  if(a==='modal2-close'&&t.closest('.mod-sheet,.tl-pick,.tl-view')){ closeModal2(); _mod=null; _modD=null; _tl=null; return; }
  if(a==='mod-open'){ modOpen(); return; }
  if(!_mod||!t.closest('.mod-sheet')) return;
  if(a==='mod-tab'){ _mod.tab=v; _mod.ask=null; modPaint(); return; }
  if(a==='mod-ask-no'){ _mod.ask=null; modPaint(); return; }
  if(a==='mod-ask-yes'){ const A=_mod.ask; _mod.ask=null; if(A) A.fn(); return; }
  if(a==='mod-dur'){ _mod[t.dataset.k+'Dur']=v; const r=document.getElementById('mod-'+t.dataset.k+'-reason'), rv=r?r.value:''; modPaint(); const r2=document.getElementById('mod-'+t.dataset.k+'-reason'); if(r2) r2.value=rv; return; }
  if(a.indexOf('mod-')===0) modAct(a,t); });
