/* ---------- P9r: Treesh Space, full-page profiles + MySpace-style customization (visitors see it as designed) ---------- */
const SP_FONTS={'Manrope':'','Bebas Neue':'Bebas+Neue','Caveat':'Caveat:wght@400;700','Doto':'','Syne':'Syne:wght@400;600;800','Space Grotesk':'Space+Grotesk:wght@400;600;700','Outfit':'Outfit:wght@300..800','VT323':'VT323','Cinzel':'Cinzel:wght@400;700','Press Start 2P':'Press+Start+2P','Pacifico':'Pacifico','JetBrains Mono':'JetBrains+Mono:wght@400;700','Permanent Marker':'Permanent+Marker','Playfair Display':'Playfair+Display:wght@400;700;900','Lobster':'Lobster'};
const SP_PATTERNS=[['stars','Stars'],['hearts','Hearts'],['glitter','Glitter'],['checks','Checks'],['stripes','Stripes'],['grid','Cyber grid'],['dots','Dots'],['zigzag','Zigzag']];
const SP_CARDS=[['glass','Glass','Frosted see-through'],['solid','Solid','Clean, no blur'],['outline','Outline','Accent borders'],['neon','Neon','Glowing edges'],['zine','Zine','Paper + tape']];
const SP_MOODS=[['','No mood','circle-off'],['happy','Happy','smile'],['chill','Chill','coffee'],['creative','Creative','palette'],['hyped','Hyped','zap'],['in-love','In love','heart'],['focused','Focused','target'],['sleepy','Sleepy','moon'],['grateful','Grateful','sparkles'],['vibing','Vibing','music'],['moody','Moody','cloud-rain'],['partying','Partying','party-popper']];
const SP_SECS=[['song','Profile song','disc-3'],['about','About me','user-round'],['meet','Who I\u2019d like to meet','handshake'],['blocks','Text blocks','text'],['top8','Top 8 friends','users-round'],['music','Music & stats','chart-no-axes-column']];
const SP_THEMES=[
 {id:'treesh',name:'Treesh',bg:{type:'theme'},card:{style:'glass',tint:'#14111d',op:55,blur:16,radius:26},font:{h:'Manrope',b:'Manrope'},col:{}},
 {id:'glitter',name:'2006 Glitter',bg:{type:'pattern',color:'#19002e',pattern:'glitter',pc:'#ff66cc'},card:{style:'glass',tint:'#2a0a45',op:58,blur:14,radius:22},font:{h:'Bebas Neue',b:'Manrope'},col:{text:'#ffffff',head:'#ffffff',link:'#ff66cc',accent:'#ff007f'}},
 {id:'neon',name:'Midnight Neon',bg:{type:'pattern',color:'#050515',pattern:'grid',pc:'#00f0ff'},card:{style:'neon',tint:'#070720',op:78,blur:10,radius:18},font:{h:'Space Grotesk',b:'Manrope'},col:{text:'#e2e8f0',head:'#ffffff',link:'#00f0ff',accent:'#00c8ff'}},
 {id:'zine',name:'Paper Zine',bg:{type:'pattern',color:'#1a1816',pattern:'stripes',pc:'#2e2924'},card:{style:'zine',tint:'#23201c',op:96,blur:0,radius:6},font:{h:'VT323',b:'JetBrains Mono'},col:{text:'#f5f5f4',head:'#ffd23f',link:'#fbbf24',accent:'#e0a800'}},
 {id:'chrome',name:'Y2K Chrome',bg:{type:'pattern',color:'#0a0a12',pattern:'stars',pc:'#c084fc'},card:{style:'outline',tint:'#0a0a12',op:45,blur:8,radius:30},font:{h:'Doto',b:'Outfit'},col:{text:'#ffffff',head:'#ffffff',link:'#c084fc',accent:'#9328ff'}},
 {id:'synth',name:'Sunset Synth',bg:{type:'gradient',g1:'#3b0764',g2:'#f97316',angle:170,dim:30},card:{style:'glass',tint:'#1a0b2e',op:52,blur:18,radius:24},font:{h:'Syne',b:'Manrope'},col:{text:'#fff1f2',head:'#ffffff',link:'#ffb38a',accent:'#ff5500'}},
 {id:'swiss',name:'Swiss Brutal',bg:{type:'pattern',color:'#0f0f10',pattern:'checks',pc:'#26262b'},card:{style:'solid',tint:'#18181b',op:100,blur:0,radius:0},font:{h:'Outfit',b:'Manrope'},col:{text:'#f1f5f9',head:'#ffffff',link:'#fb7185',accent:'#e11d48'}},
 {id:'love',name:'Love Letter',bg:{type:'pattern',color:'#2a0614',pattern:'hearts',pc:'#ff4d8d'},card:{style:'glass',tint:'#3a0a1f',op:52,blur:12,radius:30},font:{h:'Pacifico',b:'Manrope'},col:{text:'#ffffff',head:'#ffd1e1',link:'#ff8fb3',accent:'#ff4d8d'}}];

const spHex=(v,d)=>/^#[0-9a-f]{6}$/i.test(String(v||''))?String(v).toLowerCase():d;
const spNum=(v,a,b,d)=>{ v=+v; return (v===v&&v!=null&&isFinite(v))?Math.max(a,Math.min(b,Math.round(v))):d; };
const spUrl=v=>{ v=String(v||'').trim(); return v.length<1500&&/^https:\/\/[^\s'"()<>\\]+$/.test(v)?v:''; };
const spTxt=(v,n)=>String(v==null?'':v).slice(0,n);
function spNorm(s){ s=(s&&typeof s==='object')?s:{}; const bg=s.bg||{}, c=s.card||{}, f=s.font||{}, col=s.col||{}, sg=s.song||{}, md=s.mood||{}; const keys=SP_SECS.map(x=>x[0]);
  const ord=(Array.isArray(s.order)?s.order:[]).filter((k,i,a)=>keys.includes(k)&&a.indexOf(k)===i); keys.forEach(k=>{ if(!ord.includes(k)) ord.push(k); });
  const hide={}; keys.forEach(k=>{ if(s.hide&&s.hide[k]) hide[k]=true; }); const song=SONG_BY_ID[sg.id];
  return {theme:spTxt(s.theme,20),
   bg:{type:['theme','color','gradient','image','pattern'].includes(bg.type)?bg.type:'theme',color:spHex(bg.color,'#120f1c'),g1:spHex(bg.g1,'#9328ff'),g2:spHex(bg.g2,'#0d0b14'),angle:spNum(bg.angle,0,360,160),pattern:SP_PATTERNS.some(p=>p[0]===bg.pattern)?bg.pattern:'stars',pc:spHex(bg.pc,'#ffffff'),img:spUrl(bg.img),local:!!bg.local,tile:!!bg.tile,dim:spNum(bg.dim,0,85,25)},
   card:{style:SP_CARDS.some(x=>x[0]===c.style)?c.style:'glass',tint:spHex(c.tint,'#14111d'),op:spNum(c.op,0,100,55),blur:spNum(c.blur,0,30,16),radius:spNum(c.radius,0,40,26)},
   font:{h:SP_FONTS[f.h]!=null?f.h:'Manrope',b:SP_FONTS[f.b]!=null?f.b:'Manrope'},
   col:{text:spHex(col.text,''),head:spHex(col.head,''),link:spHex(col.link,''),accent:spHex(col.accent,'')},
   song:{id:song&&!song._user&&song.audioUrl?song.id:'',auto:sg.auto!==false},
   mood:{k:SP_MOODS.some(m=>m[0]===md.k)?md.k:'',t:spTxt(md.t,48)},
   about:spTxt(s.about,1200),meet:spTxt(s.meet,600),
   blocks:(Array.isArray(s.blocks)?s.blocks:[]).slice(0,6).map((b,i)=>({id:spTxt(b&&b.id,14)||('b'+i),t:spTxt(b&&b.t,60),x:spTxt(b&&b.x,1500)})),
   top8:(Array.isArray(s.top8)?s.top8:[]).filter(x=>x&&/^[a-z0-9_.]{3,20}$/.test(x.u||'')).slice(0,8).map(x=>({u:x.u,n:spTxt(x.n,40),a:spUrl(x.a)})),
   order:ord,hide,layout:['left','right','center'].includes(s.layout)?s.layout:'left'}; }
function spMine(){ return state._spDraft||spNorm((state.profile||{}).space); }
function spLocalImg(S){ return S.bg.local?(state._spBgDraft||state.spaceBg||''):''; }

/* look: css vars, background, fonts */
function spSvg(svg){ return 'url("data:image/svg+xml,'+encodeURIComponent(svg)+'")'; }
function spPattern(p,pc,base){ const P={
  stars:spSvg(`<svg xmlns='http://www.w3.org/2000/svg' width='120' height='120'><g fill='${pc}'><path d='M20 8l2.4 6.6L29 17l-6.6 2.4L20 26l-2.4-6.6L11 17l6.6-2.4z' opacity='.85'/><path d='M84 44l1.6 4.4L90 50l-4.4 1.6L84 56l-1.6-4.4L78 50l4.4-1.6z' opacity='.55'/><circle cx='60' cy='96' r='1.6' opacity='.7'/><circle cx='104' cy='14' r='1.2' opacity='.5'/><circle cx='36' cy='70' r='1' opacity='.6'/><path d='M100 92l1.2 3.3 3.3 1.2-3.3 1.2-1.2 3.3-1.2-3.3-3.3-1.2 3.3-1.2z' opacity='.7'/></g></svg>`)+' 0 0/120px 120px',
  hearts:spSvg(`<svg xmlns='http://www.w3.org/2000/svg' width='96' height='96'><g fill='${pc}'><path d='M24 34c-7-5.6-13-10-13-16.5a6.5 6.5 0 0 1 13-1.3 6.5 6.5 0 0 1 13 1.3C37 24 31 28.4 24 34z' opacity='.5'/><path d='M70 82c-4.4-3.6-8.4-6.4-8.4-10.6a4.2 4.2 0 0 1 8.4-.8 4.2 4.2 0 0 1 8.4.8c0 4.2-4 7-8.4 10.6z' opacity='.32'/></g></svg>`)+' 0 0/96px 96px',
  glitter:`radial-gradient(circle, ${pc} 1px, transparent 1.7px) 0 0/23px 29px, radial-gradient(circle, ${pc}bb 1.4px, transparent 2.1px) 11px 7px/41px 37px, radial-gradient(circle, #ffffffaa 1px, transparent 1.7px) 5px 17px/53px 47px`,
  checks:`conic-gradient(${pc} 25%, transparent 0 50%, ${pc} 0 75%, transparent 0) 0 0/52px 52px`,
  stripes:`repeating-linear-gradient(45deg, ${pc} 0 16px, transparent 16px 32px)`,
  grid:`linear-gradient(${pc}40 1px, transparent 1px) 0 0/44px 44px, linear-gradient(90deg, ${pc}40 1px, transparent 1px) 0 0/44px 44px`,
  dots:`radial-gradient(circle, ${pc}99 2px, transparent 2.7px) 0 0/26px 26px`,
  zigzag:`linear-gradient(135deg, ${pc}2e 25%, transparent 25%) -22px 0/44px 44px, linear-gradient(225deg, ${pc}2e 25%, transparent 25%) -22px 0/44px 44px, linear-gradient(315deg, ${pc}2e 25%, transparent 25%) 0 0/44px 44px, linear-gradient(45deg, ${pc}2e 25%, transparent 25%) 0 0/44px 44px`};
  return (P[p]?P[p]+', ':'')+base; }
function spBgCss(S,local){ const b=S.bg, d=b.dim/100, dim=`linear-gradient(rgba(0,0,0,${d}),rgba(0,0,0,${d}))`;
  if(b.type==='color') return 'background:'+b.color;
  if(b.type==='gradient') return `background:${dim}, linear-gradient(${b.angle}deg, ${b.g1}, ${b.g2})`;
  if(b.type==='image'){ const u=local||b.img; return u?`background:${dim}, url('${u}') ${b.tile?'top left / 320px auto repeat':'center / cover no-repeat'}, ${b.color}`:'background:'+b.color; }
  if(b.type==='pattern') return 'background:'+spPattern(b.pattern,b.pc,b.color);
  return ''; }
function spFonts(S){ [S.font.h,S.font.b].forEach(f=>{ if(SP_FONTS[f]) try{ loadGoogleFont(SP_FONTS[f]); }catch(e){} }); }
function spApplyRoot(el,S,local){ if(!el) return; spFonts(S); const c=S.col, k=S.card;
  const vars={'--sp-tint':k.tint,'--sp-opp':k.op+'%','--sp-blur':k.blur+'px','--sp-r':k.radius+'px','--sp-fh':`'${S.font.h}'`,'--sp-fb':`'${S.font.b}'`,'--sp-text':c.text||null,'--sp-head':c.head||null,'--sp-link':c.link||null,'--treesh-purple':c.accent||null};
  Object.keys(vars).forEach(n=>{ if(vars[n]) el.style.setProperty(n,vars[n]); else if(n!=='--treesh-purple'||el._spAcc) el.style.removeProperty(n); }); el._spAcc=!!c.accent;
  const bgOn=S.bg.type!=='theme'; [['sp-on',true],['sp-tx',!!c.text],['sp-hd',!!c.head],['sp-lk',!!c.link],['sp-has-bg',bgOn],['sp-fb',S.font.b!=='Manrope'],['sp-fh',S.font.h!=='Manrope']].forEach(([n,on])=>el.classList.toggle(n,on));
  SP_CARDS.forEach(([s])=>el.classList.toggle('sp-c-'+s,k.style===s)); ['left','right','center'].forEach(l=>el.classList.toggle('sp-lay-'+l,S.layout===l));
  let bg=el.querySelector(':scope > .sp-bg'); if(bgOn){ if(!bg){ bg=document.createElement('div'); bg.className='sp-bg'; bg.setAttribute('aria-hidden','true'); bg.setAttribute('data-testid','profile-space-bg'); el.insertBefore(bg,el.firstChild); } bg.setAttribute('style',spBgCss(S,local)); bg.classList.toggle('is-glitter',S.bg.type==='pattern'&&S.bg.pattern==='glitter'); } else if(bg) bg.remove(); }

/* sections shared by your profile and visitors */
function spLinkify(t){ return esc(t).replace(/(https:\/\/[^\s<]+)/g,'<a href="$1" target="_blank" rel="noopener nofollow ugc" class="sp-a">$1</a>'); }
function spMoodHtml(S){ const m=SP_MOODS.find(x=>x[0]===S.mood.k); if(!m||(!m[0]&&!S.mood.t)) return ''; return `<p class="sp-mood" data-testid="profile-status-badge"><span class="sp-mood-ic"><i data-lucide="${m[0]?m[2]:'message-circle'}"></i></span><span class="min-w-0"><b>${m[0]?'Mood: '+esc(m[1]):'Status'}</b>${S.mood.t?`<span class="clamp-1">${esc(S.mood.t)}</span>`:''}</span></p>`; }
function spSecHtml(k,S,who){ const me=who==='me', sec=(tid,ic,title,body)=>`<section class="sp-card sp-sec" data-testid="${tid}"><h3 class="sp-h"><i data-lucide="${ic}"></i>${title}</h3>${body}</section>`;
  const ph=(tid,ic,t,d)=>me?`<button type="button" data-act="sp-open" data-val="sections" data-testid="${tid}" class="sp-card sp-ph press"><i data-lucide="${ic}"></i><span><b>${t}</b><small>${d}</small></span><i data-lucide="plus"></i></button>`:'';
  if(k==='song'){ const s=SONG_BY_ID[S.song.id]; if(!s) return ph('profile-song-add','disc-3','Add a profile song','It plays when people visit your page.'); const on=_spSong&&_spSong.id===s.id&&!_spSong.a.paused, mu=_spSong&&_spSong.a.muted;
    return `<section class="sp-card sp-song${on?' is-on':''}" data-testid="profile-visitor-song-player"><span class="sp-vinyl" aria-hidden="true"><span class="sp-vinyl-art">${img(s.coverArt,'h-full w-full object-cover')}</span></span><span class="min-w-0 flex-1"><span class="sp-k"><i data-lucide="disc-3"></i>Profile song${on?'<span class="sp-eq"><i></i><i></i><i></i><i></i></span>':''}</span><b class="clamp-1" data-testid="profile-song-title">${esc(s.title)}</b><small class="clamp-1">${esc(s.artist||'')}</small></span><button type="button" data-act="sp-song" data-id="${esc(s.id)}" aria-label="${on?'Pause':'Play'} profile song" data-testid="profile-song-toggle" class="sp-play press"><i data-lucide="${on?'pause':'play'}" class="${on?'':'fill-current'}"></i></button><button type="button" data-act="sp-mute" aria-label="${mu?'Unmute':'Mute'}" data-testid="profile-song-mute" class="sp-mute press"><i data-lucide="${mu?'volume-x':'volume-2'}"></i></button></section>`; }
  if(k==='about') return S.about.trim()?sec('profile-section-about-me','user-round','About me',`<div class="sp-txt">${spLinkify(S.about)}</div>`):ph('profile-about-add','user-round','Write your About me','Tell people who you are.');
  if(k==='meet') return S.meet.trim()?sec('profile-section-who-like-to-meet','handshake','Who I\u2019d like to meet',`<div class="sp-txt">${spLinkify(S.meet)}</div>`):ph('profile-meet-add','handshake','Who would you like to meet?','Collabs, friends, fans\u2026');
  if(k==='blocks') return S.blocks.filter(b=>b.t.trim()||b.x.trim()).map((b,i)=>`<section class="sp-card sp-sec" data-testid="profile-block-${i}">${b.t.trim()?`<h3 class="sp-h"><i data-lucide="sparkle"></i>${esc(b.t)}</h3>`:''}<div class="sp-txt">${spLinkify(b.x)}</div></section>`).join('');
  if(k==='top8'){ if(!S.top8.length) return me&&sbUser()?ph('profile-top8-add','users-round','Pick your Top 8','Show off your favorite people.'):'';
    return sec('profile-top8-friends-grid','users-round','Top 8',`<div class="sp-top8">${S.top8.map((f,i)=>`<button type="button" data-act="sx-open" data-u="${esc(f.u)}" data-testid="profile-top8-${esc(f.u)}" class="sp-t8 press" style="--d:${i*40}ms"><span class="sp-t8-av">${f.a?`<img src="${esc(f.a)}" alt="" loading="lazy">`:`<b>${esc((f.n||f.u).charAt(0).toUpperCase())}</b>`}<em>${i+1}</em></span><span class="clamp-1">${esc(f.n||f.u)}</span></button>`).join('')}</div>`); }
  return ''; }
function spSecsSplit(S,who){ const i=S.order.indexOf('music'), pick=L=>L.filter(k=>!S.hide[k]).map(k=>spSecHtml(k,S,who)).join(''); return [pick(S.order.slice(0,i)),pick(S.order.slice(i+1))]; }

/* profile song: its own player, pauses Treesh while it plays */
let _spSong=null;
function spSongPlay(id,quiet){ const s=SONG_BY_ID[id]; if(!s||!s.audioUrl) return; if(_spSong&&_spSong.id===id){ if(_spSong.a.paused){ spPauseMain(); _spSong.a.play().catch(()=>{}); } spSongPaint(); return; } spSongStop(true);
  const a=new Audio(s.audioUrl); a.loop=true; a.volume=.85; _spSong={id,a,resume:false}; spPauseMain(); a.addEventListener('play',spSongPaint); a.addEventListener('pause',spSongPaint);
  a.play().then(spSongPaint).catch(()=>{ if(!quiet) toast('Tap play to hear their song'); spSongPaint(); }); }
function spPauseMain(){ try{ if(typeof audio!=='undefined'&&!audio.paused){ _spSong.resume=true; audio.pause(); } }catch(e){} }
function spSongStop(keep){ if(!_spSong) return; const r=_spSong.resume; try{ _spSong.a.pause(); _spSong.a.src=''; }catch(e){} _spSong=null; if(r&&!keep) try{ audio.play().catch(()=>{}); }catch(e){} spSongPaint(); }
function spSongPaint(){ document.querySelectorAll('[data-testid="profile-visitor-song-player"]').forEach(el=>{ const who=el.closest('#sx-root')?'them':'me'; const S=who==='them'?spNorm((_sxV&&_sxV.d&&_sxV.d.data||{}).space):spMine(); const t=document.createElement('div'); t.innerHTML=spSecHtml('song',S,who); if(t.firstElementChild) el.replaceWith(t.firstElementChild); }); icons(); }
try{ audio.addEventListener('play',()=>{ if(_spSong&&!_spSong.a.paused){ _spSong.resume=false; _spSong.a.pause(); } }); }catch(e){}

/* your profile: full page on desktop + your space */
const _rpf9r=renderProfile; renderProfile=function(){ const r=_rpf9r.apply(this,arguments); try{ spDecorateOwn(); }catch(e){ console.warn('space',e); } return r; };
function spDecorateOwn(){ const panel=document.getElementById('profile-panel'); if(!panel) return; const S=spMine(), edit=!!state.settingsEditProfile;
  spApplyRoot(panel,S,spLocalImg(S)); panel.classList.toggle('sp-page',!edit); panel.classList.toggle('sp-editing',!!_spEd); panel.classList.toggle('dark-surface',S.bg.type!=='theme'); if(edit) return;
  const sc=document.getElementById('profile-scroll'), hero=sc&&sc.querySelector('[data-testid="settings-profile"]'); if(!hero) return;
  const info=hero.querySelector(':scope > div.relative:not([data-testid="profile-banner"])'); if(info) info.classList.add('sp-info');
  const nm=hero.querySelector('[data-testid="settings-profile-name"]'), mood=spMoodHtml(S); if(nm&&mood) nm.insertAdjacentHTML('afterend',mood);
  const eb=hero.querySelector('[data-testid="hero-edit-profile"]'); if(eb&&!hero.querySelector('[data-testid="profile-edit-style-button"]')) eb.insertAdjacentHTML('beforebegin',`<button type="button" data-act="sp-open" data-testid="profile-edit-style-button" class="pf-bubble press inline-flex h-10 items-center gap-2 rounded-full px-4 text-sm font-semibold"><i data-lucide="palette" style="width:15px;height:15px"></i>Style</button>`);
  const main=sc.querySelector(':scope > .pf-main'); if(main){ const [pre,post]=spSecsSplit(S,'me'); if(pre) main.insertAdjacentHTML('afterbegin',`<div class="sp-secs" data-testid="profile-space-sections">${pre}</div>`); if(post) main.insertAdjacentHTML('beforeend',`<div class="sp-secs is-post" data-testid="profile-space-sections-after">${post}</div>`); }
  icons(); }
const _cpf9r=closeProfile; closeProfile=function(){ spEdClose(true); if(_spSong&&!document.getElementById('sx-root')) spSongStop(); return _cpf9r.apply(this,arguments); };

/* visitors: same look, same sections, song autoplay */
const _sxr9r=sxRender; sxRender=function(){ const r=_sxr9r.apply(this,arguments); try{ spDecorateThem(); }catch(e){ console.warn('space view',e); } return r; };
function spDecorateThem(){ const panel=document.querySelector('#sx-root .sx-panel'); if(!panel) return; panel.classList.add('sp-page'); const d=_sxV&&_sxV.d; if(!d||!d.data) return;
  const S=spNorm(d.data.space); spApplyRoot(panel,S,''); const sc=document.getElementById('sx-scroll'), hero=sc&&sc.querySelector('.sx-hero'); if(!hero) return;
  const info=hero.querySelector('.sx-hero-in'); if(info) info.classList.add('sp-info');
  const un=hero.querySelector('[data-testid="uprof-username"]'), mood=spMoodHtml(S); if(un&&mood) un.insertAdjacentHTML('afterend',mood);
  if(d.locked_all||d.relation==='blocked') return; const [pre,post]=spSecsSplit(S,'them');
  if(pre) hero.insertAdjacentHTML('afterend',`<div class="sp-secs" data-testid="uprof-space-sections">${pre}</div>`); if(post) sc.insertAdjacentHTML('beforeend',`<div class="sp-secs is-post" data-testid="uprof-space-sections-after">${post}</div>`);
  icons(); if(S.song.id&&S.song.auto&&!S.hide.song&&_sxV._spAuto!==d.username){ _sxV._spAuto=d.username; spSongPlay(S.song.id,true); } }
const _sxc9r=sxClose; sxClose=function(){ if(_spSong) spSongStop(); return _sxc9r.apply(this,arguments); };

/* publish: your space goes into your public profile */
const _sxSnap9r=sxSnapshot; sxSnapshot=function(){ const o=_sxSnap9r.apply(this,arguments); const S=spNorm((state.profile||{}).space); if(S.bg.local){ S.bg.img=sbMeta().spaceBgUrl||''; if(!S.bg.img) S.bg.type='color'; } delete S.bg.local; o.space=S; return o; };
const _sxPub9r=sxPublish; sxPublish=async function(){ try{ await spEnsureBgUrl(); }catch(e){ console.warn('space bg upload',e); } return _sxPub9r.apply(this,arguments); };
async function spEnsureBgUrl(){ const u=sbUser(), S=spNorm((state.profile||{}).space), d=state.spaceBg||''; if(!sb||!u||!S.bg.local||S.bg.type!=='image'||!/^data:image\//.test(d)||stMuted()) return; const m=sbMeta(), sig=sbSig(d); if(sig===m.spaceBgSig&&m.spaceBgUrl) return;
  const b=await (await fetch(d)).blob(), path=u.id+'/space.jpg'; const {error}=await sb.storage.from('avatars').upload(path,b,{upsert:true,contentType:b.type||'image/jpeg',cacheControl:'3600'}); if(error) throw error;
  sbMeta({spaceBgSig:sig,spaceBgUrl:sb.storage.from('avatars').getPublicUrl(path).data.publicUrl+'?v='+Date.now()}); }
try{ assetGet('space_bg').then(v=>{ if(v){ state.spaceBg=v; if(state.profileOpen) renderProfile(); } }).catch(()=>{}); }catch(e){}

/* ---- Style my space editor ---- */
let _spEd=null;
function spEdOpen(tab){ if(!state.profileOpen) openProfile(); if(state.settingsEditProfile){ state.settingsEditProfile=false; } state._spDraft=JSON.parse(JSON.stringify(spNorm((state.profile||{}).space))); _spEd={tab:tab||'themes',q:'',friends:null}; state._spBgDraft=null;
  let el=document.getElementById('sp-ed'); if(!el){ el=document.createElement('div'); el.id='sp-ed'; document.body.appendChild(el); }
  el.className='sp-ed dark-surface is-in'; el.setAttribute('role','dialog'); el.setAttribute('aria-label','Style my space'); el.setAttribute('data-testid','myspace-editor-drawer'); spEdPaint(true); renderProfile(); const p=document.getElementById('profile-panel'); if(p) p.classList.add('sp-editing'); }
function spEdClose(silent){ const el=document.getElementById('sp-ed'); if(!el) return; state._spDraft=null; state._spBgDraft=null; _spEd=null; el.classList.add('is-out'); setTimeout(()=>el.remove(),260); if(!silent&&state.profileOpen) renderProfile(); }
const SP_TABS=[['themes','Themes','swatch-book'],['bg','Background','image'],['cards','Cards','square-stack'],['text','Text','type'],['song','Song & mood','disc-3'],['sections','Sections','layout-list'],['layout','Layout','columns-3']];
function spEdPaint(fresh){ const el=document.getElementById('sp-ed'); if(!el||!_spEd) return; const body=el.querySelector('.sp-ed-body'), y=body?body.scrollTop:0;
  el.innerHTML=`<span class="sp-ed-grab" aria-hidden="true"></span><div class="sp-ed-head"><span class="sp-ed-orb"><i data-lucide="palette"></i></span><div class="min-w-0 flex-1"><p class="sp-ed-k">Treesh Space</p><h3 class="sp-ed-t">Style my space</h3></div><button type="button" data-act="sp-cancel" aria-label="Close" data-testid="editor-close" class="sp-ed-x press"><i data-lucide="x"></i></button></div>
   <div class="sp-ed-tabs no-scrollbar" role="tablist">${SP_TABS.map(([k,l,ic])=>`<button type="button" role="tab" aria-selected="${_spEd.tab===k}" data-act="sp-tab" data-val="${k}" data-testid="editor-tab-${k}" class="sp-ed-tab press${_spEd.tab===k?' on':''}"><i data-lucide="${ic}"></i>${l}</button>`).join('')}</div>
   <div class="sp-ed-body soft-scroll" data-testid="editor-body">${spEdBody()}</div>
   <div class="sp-ed-foot"><button type="button" data-act="sp-reset" data-testid="editor-reset" class="sp-ed-btn press"><i data-lucide="rotate-ccw"></i>Reset</button><button type="button" data-act="sp-save" data-testid="editor-save-profile-style-button" class="sp-ed-btn is-primary press"><i data-lucide="check"></i>Save my space</button></div>`;
  icons(); const nb=el.querySelector('.sp-ed-body'); if(nb&&!fresh) nb.scrollTop=y; }
const spCol=(path,val,label,tid,reset)=>`<label class="sp-f sp-col"><span>${label}</span><span class="sp-col-row"><input type="color" value="${val||'#ffffff'}" data-sp="${path}" data-testid="${tid}">${reset?`<button type="button" data-act="sp-set" data-k="${path}" data-val="" class="sp-mini press${val?'':' on'}" data-testid="${tid}-reset">${val?'Reset':'Default'}</button>`:''}</span></label>`;
const spRange=(path,val,min,max,label,unit,tid)=>`<label class="sp-f"><span>${label}<em data-sp-out="${path}">${val}${unit}</em></span><input type="range" min="${min}" max="${max}" value="${val}" data-sp="${path}" data-unit="${unit}" class="sp-range" data-testid="${tid}"></label>`;
const spChips=(path,cur,list,tid)=>`<div class="sp-chips">${list.map(([v,l,ic])=>`<button type="button" data-act="sp-set" data-k="${path}" data-val="${esc(v)}" aria-pressed="${cur===v}" data-testid="${tid}-${v||'none'}" class="sp-chip press${cur===v?' on':''}">${ic?`<i data-lucide="${ic}"></i>`:''}${esc(l)}</button>`).join('')}</div>`;
function spEdBody(){ const S=state._spDraft, t=_spEd.tab, b=S.bg, k=S.card;
  if(t==='themes') return `<p class="sp-hint">One tap to restyle everything. Your words and song stay.</p><div class="sp-themes">${SP_THEMES.map(th=>{ const T=spNorm(Object.assign({},S,th)); return `<button type="button" data-act="sp-theme" data-val="${th.id}" data-testid="editor-theme-${th.id}" class="sp-theme press${S.theme===th.id?' on':''}"><span class="sp-theme-pv" style="${th.bg.type==='theme'?'background:radial-gradient(120% 120% at 0 0,#9328ff,transparent 60%),#120f1c':spBgCss(T,'')}"><span class="sp-theme-card" style="--sp-tint:${T.card.tint};--sp-r:${Math.min(T.card.radius,16)}px;border-color:${T.col.accent||'#9328ff'};font-family:'${T.font.h}'"><b style="color:${T.col.head||'#fff'}">Aa</b><i style="background:${T.col.accent||'#9328ff'}"></i></span></span><span class="sp-theme-n">${esc(th.name)}</span></button>`; }).join('')}</div>`;
  if(t==='bg'){ let h=spChips('bg.type',b.type,[['theme','App theme','sparkles'],['color','Color','paint-bucket'],['gradient','Gradient','blend'],['image','Image','image'],['pattern','Pattern','grid-3x3']],'editor-bg-type');
    if(b.type==='color') h+=spCol('bg.color',b.color,'Background color','editor-bg-color');
    if(b.type==='gradient') h+=`<div class="sp-2">${spCol('bg.g1',b.g1,'From','editor-bg-g1')}${spCol('bg.g2',b.g2,'To','editor-bg-g2')}</div>${spRange('bg.angle',b.angle,0,360,'Angle','\u00b0','editor-bg-angle')}${spRange('bg.dim',b.dim,0,85,'Darken','%','editor-bg-dim')}`;
    if(b.type==='image') h+=`<label class="sp-f"><span>Image link</span><input type="url" value="${esc(b.local?'':b.img)}" placeholder="https://\u2026" data-sp="bg.img" class="sp-in" data-testid="editor-bg-url"></label><label class="sp-ed-btn press sp-up"><i data-lucide="upload"></i>${b.local?'Replace uploaded image':'Upload an image'}<input type="file" accept="image/*" id="sp-bg-file" class="hidden" data-testid="editor-bg-upload"></label>${b.local?`<p class="sp-hint">Uploaded from this device. It goes public when you\u2019re signed in.</p>`:''}<label class="sp-tog"><input type="checkbox" data-sp="bg.tile" ${b.tile?'checked':''} data-testid="editor-bg-tile"><span>Tile it, old-school</span></label>${spRange('bg.dim',b.dim,0,85,'Darken','%','editor-bg-dim')}${spCol('bg.color',b.color,'Behind the image','editor-bg-color')}`;
    if(b.type==='pattern') h+=`<div class="sp-pats">${SP_PATTERNS.map(([p,l])=>`<button type="button" data-act="sp-set" data-k="bg.pattern" data-val="${p}" data-testid="editor-pattern-${p}" class="sp-pat press${b.pattern===p?' on':''}"><span style="background:${spPattern(p,b.pc,b.color)}"></span>${l}</button>`).join('')}</div><div class="sp-2">${spCol('bg.pc',b.pc,'Pattern color','editor-pattern-color')}${spCol('bg.color',b.color,'Base color','editor-bg-color')}</div>`;
    if(b.type==='theme') h+=`<p class="sp-hint">Your page uses your normal Treesh look. Pick another type to make it yours.</p>`; return h; }
  if(t==='cards') return `<p class="sp-k2">Card style</p><div class="sp-cards">${SP_CARDS.map(([s,l,dsc])=>`<button type="button" data-act="sp-set" data-k="card.style" data-val="${s}" data-testid="editor-card-${s}" class="sp-cardopt press${k.style===s?' on':''}"><b>${l}</b><small>${dsc}</small></button>`).join('')}</div>${spCol('card.tint',k.tint,'Card color','editor-card-tint')}${spRange('card.op',k.op,0,100,'Opacity','%','editor-card-opacity')}${spRange('card.blur',k.blur,0,30,'Blur','px','editor-card-blur')}${spRange('card.radius',k.radius,0,40,'Corners','px','editor-card-radius')}`;
  if(t==='text'){ const fl=Object.keys(SP_FONTS), fc=(path,cur,tid)=>`<div class="sp-fonts">${fl.map(f=>`<button type="button" data-act="sp-set" data-k="${path}" data-val="${esc(f)}" data-testid="${tid}-${f.toLowerCase().replace(/\s+/g,'-')}" class="sp-font press${cur===f?' on':''}" style="font-family:'${f}'">${esc(f)}</button>`).join('')}</div>`; fl.forEach(f=>{ if(SP_FONTS[f]) try{ loadGoogleFont(SP_FONTS[f]); }catch(e){} });
    return `<p class="sp-k2">Headings font</p>${fc('font.h',S.font.h,'editor-font-h')}<p class="sp-k2">Body font</p>${fc('font.b',S.font.b,'editor-font-b')}<div class="sp-2">${spCol('col.text',S.col.text,'Text','editor-color-text',true)}${spCol('col.head',S.col.head,'Headings','editor-color-head',true)}${spCol('col.link',S.col.link,'Links','editor-color-link',true)}${spCol('col.accent',S.col.accent,'Accent','editor-color-accent',true)}</div>`; }
  if(t==='song'){ const s=SONG_BY_ID[S.song.id], q=(_spEd.q||'').trim().toLowerCase(); const L=(SONGS||[]).filter(x=>x&&!x._user&&x.audioUrl&&(!q||(x.title+' '+x.artist).toLowerCase().includes(q))).slice(0,24);
    return `<p class="sp-k2">Profile song</p>${s?`<div class="sp-cur" data-testid="editor-song-current">${img(s.coverArt,'sp-cur-img')}<span class="min-w-0 flex-1"><b class="clamp-1">${esc(s.title)}</b><small class="clamp-1">${esc(s.artist||'')}</small></span><button type="button" data-act="sp-set" data-k="song.id" data-val="" class="sp-mini press" data-testid="editor-song-remove">Remove</button></div><label class="sp-tog"><input type="checkbox" data-sp="song.auto" ${S.song.auto?'checked':''} data-testid="editor-song-autoplay"><span>Play automatically for visitors</span></label>`:'<p class="sp-hint">Pick a Treesh song. Visitors hear it on your page with a mute button. Your own uploads stay private, so they can\u2019t be used.</p>'}
     <label class="tl-search"><i data-lucide="search"></i><input id="sp-song-q" value="${esc(_spEd.q||'')}" autocomplete="off" placeholder="Search Treesh songs" data-testid="editor-song-search"></label><div class="sp-songs" id="sp-songs">${L.map(x=>`<button type="button" data-act="sp-set" data-k="song.id" data-val="${esc(x.id)}" data-testid="editor-song-opt-${esc(x.id)}" class="sp-sopt press${x.id===S.song.id?' on':''}">${img(x.coverArt,'sp-sopt-img')}<span class="min-w-0 flex-1"><b class="clamp-1">${esc(x.title)}</b><small class="clamp-1">${esc(x.artist||'')}</small></span>${x.id===S.song.id?'<i data-lucide="check"></i>':''}</button>`).join('')||'<p class="sp-hint">No songs match.</p>'}</div>
     <p class="sp-k2 mt-5">Mood</p>${spChips('mood.k',S.mood.k,SP_MOODS,'editor-mood')}<label class="sp-f"><span>Status</span><input value="${esc(S.mood.t)}" maxlength="48" placeholder="e.g. Cooking up a new beat" data-sp="mood.t" class="sp-in" data-testid="editor-mood-text"></label>`; }
  if(t==='sections') return `<p class="sp-hint">Reorder with the arrows. The eye shows or hides a section.</p>${S.order.map((key,i)=>{ const D=SP_SECS.find(x=>x[0]===key), hid=!!S.hide[key]; let ed='';
      if(key==='about') ed=`<textarea rows="4" maxlength="1200" data-sp="about" class="sp-ta" placeholder="Who are you? What do you make? Links work too." data-testid="editor-about">${esc(S.about)}</textarea>`;
      if(key==='meet') ed=`<textarea rows="3" maxlength="600" data-sp="meet" class="sp-ta" placeholder="Producers, singers, new friends\u2026" data-testid="editor-meet">${esc(S.meet)}</textarea>`;
      if(key==='blocks') ed=S.blocks.map((bk,j)=>`<div class="sp-blk" data-testid="editor-block-${j}"><div class="sp-blk-h"><input value="${esc(bk.t)}" maxlength="60" placeholder="Block title" data-sp="blocks.${j}.t" class="sp-in" data-testid="editor-block-${j}-title"><button type="button" data-act="sp-blk-del" data-val="${j}" aria-label="Delete block" class="sp-mini press" data-testid="editor-block-${j}-delete"><i data-lucide="trash-2"></i></button></div><textarea rows="3" maxlength="1500" data-sp="blocks.${j}.x" class="sp-ta" placeholder="Anything: shout-outs, lyrics, links\u2026" data-testid="editor-block-${j}-text">${esc(bk.x)}</textarea></div>`).join('')+(S.blocks.length<6?`<button type="button" data-act="sp-blk-add" data-testid="editor-block-add" class="sp-ed-btn press sp-up"><i data-lucide="plus"></i>Add a text block</button>`:'');
      if(key==='top8') ed=spTop8Ed(S);
      if(key==='song') ed=`<button type="button" data-act="sp-tab" data-val="song" class="sp-mini press">${SONG_BY_ID[S.song.id]?'Change song':'Pick a song'}</button>`;
      if(key==='music') ed=`<p class="sp-hint">Your favorites, lyrics, playlists and stats tabs.</p>`;
      return `<div class="sp-srow${hid?' is-hid':''}" data-testid="editor-section-${key}"><div class="sp-srow-h"><span class="sp-srow-ic"><i data-lucide="${D[2]}"></i></span><b class="flex-1">${esc(D[1])}</b><button type="button" data-act="sp-mv" data-val="${key}" data-dir="-1" aria-label="Move up" class="sp-mini press"${i?'':' disabled'} data-testid="editor-section-${key}-up"><i data-lucide="chevron-up"></i></button><button type="button" data-act="sp-mv" data-val="${key}" data-dir="1" aria-label="Move down" class="sp-mini press"${i<S.order.length-1?'':' disabled'} data-testid="editor-section-${key}-down"><i data-lucide="chevron-down"></i></button><button type="button" data-act="sp-hide" data-val="${key}" aria-label="${hid?'Show':'Hide'}" aria-pressed="${!hid}" class="sp-mini press${hid?'':' on'}" data-testid="editor-section-${key}-toggle"><i data-lucide="${hid?'eye-off':'eye'}"></i></button></div>${hid?'':ed}</div>`; }).join('')}`;
  if(t==='layout') return `<p class="sp-hint">Where your info card sits on big screens. Phones always stack.</p><div class="sp-lays">${[['left','Info left'],['right','Info right'],['center','Centered']].map(([l,n])=>`<button type="button" data-act="sp-set" data-k="layout" data-val="${l}" data-testid="editor-layout-${l}" class="sp-lay press${S.layout===l?' on':''}"><span class="sp-lay-pv is-${l}"><i></i><b></b><b></b></span>${n}</button>`).join('')}</div>`;
  return ''; }
function spTop8Ed(S){ if(!sbUser()) return `<p class="sp-hint">Sign in to add friends to your Top 8.</p>`; const F=_spEd.friends;
  if(!F) return `<button type="button" data-act="sp-t8-load" data-testid="editor-top8-load" class="sp-ed-btn press sp-up"><i data-lucide="users-round"></i>${S.top8.length?'Edit your Top 8':'Choose from your friends'}</button>${S.top8.length?`<p class="sp-hint">${S.top8.map(f=>'@'+esc(f.u)).join(', ')}</p>`:''}`;
  if(F==='busy') return `<div class="sx-load"><span class="sx-spin"></span></div>`; if(!F.length) return `<p class="sp-hint">No friends yet. Add people from Find people.</p>`;
  return `<p class="sp-hint">${S.top8.length}/8 picked, in the order you tap.</p><div class="sp-t8ed">${F.map(f=>{ const i=S.top8.findIndex(x=>x.u===f.username); return `<button type="button" data-act="sp-t8" data-val="${esc(f.username)}" data-testid="editor-top8-${esc(f.username)}" class="sp-t8opt press${i>=0?' on':''}">${sxAv(f)}<span class="clamp-1">${esc(f.display_name||f.username)}</span>${i>=0?`<em>${i+1}</em>`:''}</button>`; }).join('')}</div>`; }
function spSetPath(o,path,v){ const p=path.split('.'); let x=o; for(let i=0;i<p.length-1;i++){ x=x[/^\d+$/.test(p[i])?+p[i]:p[i]]; if(x==null) return; } x[p[p.length-1]]=v; }
let _spRT=0;
function spLive(kind){ const S=state._spDraft; if(!S) return; if(kind==='look'){ spApplyRoot(document.getElementById('profile-panel'),S,spLocalImg(S)); const p=document.getElementById('profile-panel'); if(p) p.classList.toggle('dark-surface',S.bg.type!=='theme'); return; } clearTimeout(_spRT); _spRT=setTimeout(()=>{ if(state.profileOpen){ renderProfile(); const p=document.getElementById('profile-panel'); if(p) p.classList.add('sp-editing'); } },kind==='now'?0:180); }
function spEdSet(path,v,repaint){ const S=state._spDraft; if(!S) return; spSetPath(S,path,v); if(path==='bg.img'&&v) S.bg.local=false; if(path.indexOf('bg.')===0||path.indexOf('card.')===0||path.indexOf('col.')===0||path.indexOf('font.')===0) S.theme=''; state._spDraft=Object.assign(spNorm(S),{theme:S.theme});
  const look=/^(bg|card|col|font)\./.test(path); spLive(look?'look':'now'); if(repaint) spEdPaint(); }
document.addEventListener('input',e=>{ const t=e.target; if(!t||!_spEd||!t.closest||!t.closest('#sp-ed')) return; if(t.id==='sp-song-q'){ _spEd.q=t.value; const l=document.getElementById('sp-songs'); if(l){ const tmp=document.createElement('div'); tmp.innerHTML=spEdBody(); const nl=tmp.querySelector('#sp-songs'); if(nl){ l.innerHTML=nl.innerHTML; icons(); } } return; }
  const k=t.dataset.sp; if(!k) return; let v=t.type==='checkbox'?t.checked:t.type==='range'?+t.value:t.value; if(t.type==='url'){ if(v&&!spUrl(v)) return; }
  const out=document.querySelector('#sp-ed [data-sp-out="'+k+'"]'); if(out) out.textContent=v+(t.dataset.unit||''); const S=state._spDraft; spSetPath(S,k,v); if(k==='bg.img'&&v) S.bg.local=false; if(/^(bg|card|col|font)\./.test(k)) S.theme='';
  if(t.tagName==='TEXTAREA'||t.type==='text'||(t.type!=='color'&&t.type!=='range'&&t.type!=='checkbox'&&t.type!=='url')){ spLive('text'); return; } state._spDraft=Object.assign(spNorm(S),{theme:S.theme}); spLive(/^(bg|card|col|font)\./.test(k)?'look':'now');
  if(t.type==='color'){ const r=t.parentElement&&t.parentElement.querySelector('.sp-mini'); if(r){ r.textContent='Reset'; r.classList.remove('on'); } } });
document.addEventListener('change',async e=>{ const t=e.target; if(!t||t.id!=='sp-bg-file'||!state._spDraft) return; const f=t.files&&t.files[0]; if(!f) return; if(!/^image\//.test(f.type||'')){ toast('Pick an image file'); return; }
  try{ state._spBgDraft=await spShrink(f,1920); const S=state._spDraft; S.bg.type='image'; S.bg.local=true; S.bg.img=''; S.theme=''; spLive('look'); spEdPaint(); toast('Background added','Save to keep it'); }catch(err){ toast('Couldn\u2019t use that image'); } });
function spShrink(f,max){ return new Promise((res,rej)=>{ const u=URL.createObjectURL(f), im=new Image(); im.onload=()=>{ const s=Math.min(1,max/Math.max(im.width,im.height)), c=document.createElement('canvas'); c.width=Math.round(im.width*s); c.height=Math.round(im.height*s); c.getContext('2d').drawImage(im,0,0,c.width,c.height); URL.revokeObjectURL(u); res(c.toDataURL('image/jpeg',.86)); }; im.onerror=()=>{ URL.revokeObjectURL(u); rej(new Error('img')); }; im.src=u; }); }
async function spSave(){ const S=state._spDraft; if(!S) return; const p=Object.assign({},state.profile||{}); p.space=spNorm(S); p.space.theme=S.theme||''; if(state._spBgDraft){ try{ await assetPut('space_bg',state._spBgDraft); }catch(e){} state.spaceBg=state._spBgDraft; sbMeta({spaceBgSig:''}); }
  state.profile=p; LS.set('treesh_profile',p); try{ sbQueuePush(); }catch(e){} try{ sxPublishSoon(true); }catch(e){} spEdClose(); toast('Your space is saved',sbUser()?'Visitors see it exactly like this':'Sign in so others can visit it'); }
document.addEventListener('click',async e=>{ const t=e.target&&e.target.closest&&e.target.closest('[data-act^="sp-"]'); if(!t) return; const a=t.dataset.act, v=t.dataset.val;
  if(a==='sp-open'){ spEdOpen(v); return; } if(a==='sp-song'){ if(_spSong&&_spSong.id===t.dataset.id&&!_spSong.a.paused){ _spSong.a.pause(); spSongPaint(); } else spSongPlay(t.dataset.id); return; }
  if(a==='sp-mute'){ if(_spSong){ _spSong.a.muted=!_spSong.a.muted; spSongPaint(); } return; }
  if(!_spEd||!state._spDraft) return; const S=state._spDraft;
  switch(a){
    case 'sp-tab': _spEd.tab=v; spEdPaint(true); break;
    case 'sp-cancel': spEdClose(); break;
    case 'sp-save': spSave(); break;
    case 'sp-reset': state._spDraft=Object.assign(spNorm({about:S.about,meet:S.meet,blocks:S.blocks,top8:S.top8,song:S.song,mood:S.mood,order:S.order,hide:S.hide}),{theme:'treesh'}); spLive('now'); spEdPaint(); break;
    case 'sp-theme': { const th=SP_THEMES.find(x=>x.id===v); if(!th) break; const n=spNorm(Object.assign({},S,{bg:th.bg,card:th.card,font:th.font,col:th.col})); n.theme=th.id; state._spDraft=n; spLive('now'); spEdPaint(); break; }
    case 'sp-set': spEdSet(t.dataset.k,t.dataset.k==='bg.tile'?v==='true':v,true); break;
    case 'sp-mv': { const i=S.order.indexOf(v), j=i+(+t.dataset.dir); if(i<0||j<0||j>=S.order.length) break; S.order.splice(i,1); S.order.splice(j,0,v); spLive('now'); spEdPaint(); break; }
    case 'sp-hide': S.hide[v]=!S.hide[v]; if(!S.hide[v]) delete S.hide[v]; spLive('now'); spEdPaint(); break;
    case 'sp-blk-add': if(S.blocks.length<6){ S.blocks.push({id:'b'+Date.now().toString(36),t:'',x:''}); spEdPaint(); } break;
    case 'sp-blk-del': S.blocks.splice(+v,1); spLive('now'); spEdPaint(); break;
    case 'sp-t8-load': _spEd.friends='busy'; spEdPaint(); try{ const L=(await sxRpc('my_friends'))||[]; if(_spEd) _spEd.friends=L.filter(x=>x.relation==='friends'&&x.username); }catch(err){ if(_spEd) _spEd.friends=[]; toast('Couldn\u2019t load friends',sxErr(err)); } spEdPaint(); break;
    case 'sp-t8': { const F=Array.isArray(_spEd.friends)?_spEd.friends:[], f=F.find(x=>x.username===v), i=S.top8.findIndex(x=>x.u===v); if(i>=0) S.top8.splice(i,1); else if(S.top8.length>=8){ toast('Top 8 is full','Tap someone to remove them'); break; } else if(f) S.top8.push({u:f.username,n:f.display_name||'',a:spUrl(f.avatar_url)}); spLive('now'); spEdPaint(); break; } } });
document.addEventListener('keydown',e=>{ if(e.key==='Escape'&&_spEd&&document.getElementById('sp-ed')){ e.stopPropagation(); spEdClose(); } },true);
