/* ---------- P9s: Vocotap + Hoop (Treesh Active) on profiles, public Arcade tab, coming-soon games, help center ---------- */
const HOOP_GAMES={'horse':'HORSE','pig':'PIG','around-the-world':'Around the World','twenty-one':'21','knockout':'Knockout','beat-the-pro':'Beat the Pro','hot-shot':'Hot Shot','three-point-contest':'Three-Point Contest','mikan-challenge':'Mikan Challenge','free-throw-streak':'Free Throw Streak','golf':'Golf','king-of-the-court':'King of the Court','thirty-three':'33','cutthroat':'Cutthroat','lightning-free-throws':'Lightning Free Throws','dribble-knockout':'Dribble Knockout','five-spot':'Five Spot','tic-tac-toe':'Tic-Tac-Toe','make-it-take-it':'Make It Take It','beat-the-clock':'Beat the Clock','hundred-shots':'100 Shots'};
const gdDayKey=d=>d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate();
const gdNum=v=>{ v=+v; return isFinite(v)?Math.max(0,Math.round(v)):0; };
function gdDaySet(days){ const S=new Set(); (Array.isArray(days)?days:[]).forEach(s=>{ const p=String(s).split('-').map(Number); if(p.length===3&&p.every(n=>n>0)) S.add(p.join('-')); }); return S; }
function gdStreak(days){ const S=gdDaySet(days), c=new Date(); if(!S.has(gdDayKey(c))) c.setDate(c.getDate()-1); let n=0; while(S.has(gdDayKey(c))&&n<4000){ n++; c.setDate(c.getDate()-1); } return n; }
function gdLast28(days){ const S=gdDaySet(days), c=new Date(); let o=''; c.setDate(c.getDate()-27); for(let i=0;i<28;i++){ o+=S.has(gdDayKey(c))?'1':'0'; c.setDate(c.getDate()+1); } return o; }
function gdAgo(t){ t=+t; if(!t) return ''; const s=Math.max(0,(Date.now()-t)/1000); if(s<3600) return Math.max(1,Math.round(s/60))+'m ago'; if(s<86400) return Math.round(s/3600)+'h ago'; const d=Math.round(s/86400); return d<30?d+'d ago':new Date(t).toLocaleDateString(undefined,{month:'short',day:'numeric'}); }

/* Vocotap: scores, XP level, daily streak (its own keys on treesh.app) */
function vtStats(){ const L=_gdJson('vocotap_scores',[]), R=Array.isArray(L)?L.filter(x=>x&&typeof x==='object'):[]; const xp=Math.max(0,+((_gdJson('vocotap_progress',{})||{}).xp)||0); let lv=1, t=xp; while(lv<500&&t>=400+150*(lv-1)){ t-=400+150*(lv-1); lv++; }
  const mx=k=>R.reduce((a,x)=>Math.max(a,+x[k]||0),0); return {plays:R.length,best:mx('score'),combo:mx('maxCombo'),acc:mx('accuracy'),stars:mx('stars'),lv,streak:gdStreak(_gdJson('vocotap_daily_history',[]))}; }
GAME_DATA_SOURCES.push({ key:'vocotap', name:'Vocotap', mono:'V', a:'#e0567a', b:'#7a2540',
  hasData:()=>_gdRaw('vocotap_scores')!=null||_gdRaw('vocotap_progress')!=null, starlites:()=>0, chip:()=>['trending-up','Level '+vtStats().lv],
  stats:()=>{ const v=vtStats(); return [['Best score',fmtNum(v.best)],['Max combo',fmtNum(v.combo)+'\u00d7'],['Plays',fmtNum(v.plays)],['Accuracy',(Math.round(v.acc*10)/10)+'%'],['Top stars',v.stars+'\u2605'],['Day streak',fmtNum(v.streak)]]; } });

/* one shape for your profile and the public copy */
function gdArcadeData(){ return GAME_DATA_SOURCES.filter(g=>{ try{ return g.hasData(); }catch(e){ return false; } }).map(g=>{ const o={k:g.key,n:g.name,m:g.mono,a:g.a,b:g.b,sl:0,chip:null,rows:[]};
  try{ o.sl=+g.starlites()||0; }catch(e){} try{ o.chip=g.chip?g.chip():null; }catch(e){} try{ o.rows=(g.stats()||[]).filter(Boolean).slice(0,6).map(r=>[String(r[0]),String(r[1])]); }catch(e){} return o; }); }
function hpData(){ const raw=_gdRaw('treesh_hoop_stats'), log=_gdJson('treesh_hoop_game_log',[]), fav=_gdJson('treesh_hoop_favorites',[]); const L=Array.isArray(log)?log.filter(x=>x&&x.gameId):[]; if(raw==null&&!L.length) return null;
  const s=_gdJson('treesh_hoop_stats',{})||{}, days=Array.isArray(s.activeDays)?s.activeDays:[];
  return {sessions:gdNum(s.sessions),minutes:gdNum(s.minutes),drills:Object.values(s.drillsDone||{}).reduce((a,b)=>a+gdNum(b),0),games:gdNum(s.games),shots:gdNum(s.shots),best:gdNum(s.bestShot),streak:gdStreak(days),d28:gdLast28(days),courts:Array.isArray(fav)?fav.length:0,
    recent:L.slice(0,3).map(g=>({g:HOOP_GAMES[g.gameId]||String(g.gameId).replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase()).slice(0,40),w:String(g.winner||'').slice(0,40),at:Date.parse(g.at)||0}))}; }

function gdHead(ic,cls,t,right){ return `<div class="mb-2.5 flex items-center gap-2"><h3 class="flex flex-1 items-center gap-2 text-sm font-bold uppercase tracking-wide text-white/70"><i data-lucide="${ic}" class="${cls}" style="width:15px;height:15px"></i>${t}</h3>${right||''}</div>`; }
function gdGameCard(g,who){ const a=spHex(g.a,'#9328ff'), b=spHex(g.b,'#4d128f'), k=String(g.k||'').replace(/[^a-z0-9-]/g,'').slice(0,24), ch=Array.isArray(g.chip)&&g.chip.length===2?g.chip:null, rows=(Array.isArray(g.rows)?g.rows:[]).filter(Array.isArray).slice(0,6);
  const chip=ch?`<span class="gd-chip is-acc" data-testid="arcade-game-${k}-chip"><i data-lucide="${/^[a-z0-9-]{2,30}$/.test(ch[0])?ch[0]:'sparkles'}"></i>${esc(String(ch[1]).slice(0,24))}</span>`:`<span class="gd-chip is-gold" data-testid="arcade-game-${k}-starlites"><i data-lucide="sparkles"></i>${fmtNum(gdNum(g.sl))}</span>`;
  return `<div class="rounded-2xl border border-white/10 bg-white/[0.04] p-3.5" data-testid="arcade-game-${k}"><div class="flex items-center gap-3"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-sm font-extrabold text-white" style="background:linear-gradient(135deg,${a},${b})">${esc(String(g.m||'?').slice(0,2))}</span><div class="min-w-0 flex-1"><p class="clamp-1 text-sm font-bold">${esc(String(g.n||'Game').slice(0,40))}</p><p class="text-[11px] text-white/45">${who==='me'?'Synced from '+esc(g.n):'Treesh Arcade'}</p></div>${chip}</div>
   ${rows.length?`<div class="mt-3 grid grid-cols-3 gap-2">${rows.map(r=>`<div class="rounded-xl border border-white/10 bg-white/[0.03] p-2 text-center"><p class="font-doto text-base font-bold leading-none">${esc(String(r[1]).slice(0,16))}</p><p class="mt-1 text-[10px] uppercase tracking-wide text-white/45">${esc(String(r[0]).slice(0,20))}</p></div>`).join('')}</div>`:''}</div>`; }
function gdActiveHtml(h,who){ const me=who==='me', pre=me?'':'uprof-';
  let x=`<section data-testid="${pre}stats-treesh-active">${gdHead('activity','text-[#f97316]','Treesh Active',h&&gdNum(h.streak)?`<span class="gd-chip is-hoop" data-testid="${pre}hoop-streak"><i data-lucide="flame"></i>${fmtNum(gdNum(h.streak))} day streak</span>`:'')}`;
  if(!h||typeof h!=='object') return x+(me?`<div class="rounded-2xl border border-dashed border-white/12 bg-white/[0.02] p-5 text-center" data-testid="treesh-active-empty"><span class="mx-auto mb-2 grid h-10 w-10 place-items-center rounded-full bg-[#f97316]/15 text-[#f97316]"><i data-lucide="activity" style="width:18px;height:18px"></i></span><p class="text-sm font-semibold">No Hoop activity yet</p><p class="mx-auto mt-1 max-w-xs text-xs text-white/50">Log drills, run court games and check your shot form in Hoop. Your stats show up here.</p><button type="button" data-act="game-open" data-key="hoop" data-testid="treesh-active-open-hoop" class="gd-btn press mt-3"><i data-lucide="external-link"></i>Open Hoop</button></div>`:`<p class="sx-none" data-testid="uprof-treesh-active-empty">No Hoop activity yet.</p>`)+'</section>';
  const st=[['Sessions',h.sessions,'sessions'],['Minutes',h.minutes,'minutes'],['Drills done',h.drills,'drills'],['Games',h.games,'games'],['Shots checked',h.shots,'shots'],['Best form',gdNum(h.best)||'\u2013','best']];
  const d28=String(h.d28||'').replace(/[^01]/g,'').padStart(28,'0').slice(-28), on=(d28.match(/1/g)||[]).length, R=(Array.isArray(h.recent)?h.recent:[]).slice(0,3);
  x+=`<div class="gd-hoop" data-testid="${pre}treesh-active-hoop"><div class="relative flex items-center gap-3"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-sm font-extrabold text-white" style="background:linear-gradient(135deg,#f97316,#9a3412)">H</span><div class="min-w-0 flex-1"><p class="clamp-1 text-sm font-bold">Hoop from Treesh</p><p class="text-[11px] text-white/45">Basketball \u00b7 ${me?'synced from Hoop':'Treesh Active'}</p></div>${me?`<button type="button" data-act="game-open" data-key="hoop" data-testid="treesh-active-hoop-open" class="gd-chip is-hoop press"><i data-lucide="external-link"></i>Open</button>`:''}</div>
   <div class="relative mt-3 grid grid-cols-3 gap-2">${st.map(([l,v,k])=>`<div class="rounded-xl border border-white/10 bg-black/20 p-2 text-center" data-testid="${pre}hoop-stat-${k}"><p class="font-doto text-base font-bold leading-none">${typeof v==='number'?fmtNum(gdNum(v)):esc(String(v))}</p><p class="mt-1 text-[10px] uppercase tracking-wide text-white/45">${l}</p></div>`).join('')}</div>
   <div class="gd-heat relative mt-3" data-testid="${pre}hoop-activity-strip" title="Days you trained in the last 4 weeks"><div class="gd-heat-row">${[...d28].map((c,i)=>`<i class="${c==='1'?'on':''}" style="--i:${i}"></i>`).join('')}</div><p class="gd-heat-l"><span>Last 4 weeks</span><b>${on} active day${on===1?'':'s'}</b></p></div>
   ${R.length?`<div class="relative mt-3 space-y-1.5" data-testid="${pre}hoop-recent-games"><p class="text-[10px] font-bold uppercase tracking-wide text-white/45">Recent court games</p>${R.map((r,i)=>`<div class="gd-rg" data-testid="${pre}hoop-recent-${i}"><i data-lucide="trophy"></i><span class="min-w-0 flex-1"><b class="clamp-1">${esc(String(r.g||'Game').slice(0,40))}</b>${me&&r.w?`<small class="clamp-1">Winner: ${esc(r.w)}</small>`:''}</span><em>${esc(gdAgo(r.at))}</em></div>`).join('')}</div>`:''}
   ${gdNum(h.courts)?`<p class="gd-courts relative" data-testid="${pre}hoop-courts"><i data-lucide="map-pin"></i>${fmtNum(gdNum(h.courts))} saved court${gdNum(h.courts)===1?'':'s'}</p>`:''}</div>`;
  return x+'</section>'; }
function gdArcadeHtml(list,h,who){ const me=who==='me', L=(Array.isArray(list)?list:[]).filter(g=>g&&typeof g==='object').slice(0,8), tot=L.reduce((a,g)=>a+gdNum(g.sl),0);
  let x=`<section data-testid="${me?'stats-arcade-games':'uprof-arcade-games'}">${gdHead('joystick','text-[color:var(--treesh-gold)]','Arcade games',L.length&&tot?`<span class="gd-chip is-gold"><i data-lucide="sparkles"></i>${fmtNum(tot)} Starlites</span>`:'')}`;
  if(!L.length) x+=me?`<div class="rounded-2xl border border-dashed border-white/12 bg-white/[0.02] p-5 text-center" data-testid="arcade-games-empty"><span class="mx-auto mb-2 grid h-10 w-10 place-items-center rounded-full bg-[color:var(--treesh-purple)]/15 text-[color:var(--treesh-purple)]"><i data-lucide="joystick" style="width:18px;height:18px"></i></span><p class="text-sm font-semibold">No arcade progress yet</p><p class="mx-auto mt-1 max-w-xs text-xs text-white/50">Play Chainz, FREA!, Vocotap and more from the Games tab. Your stats show up here.</p></div>`:`<p class="sx-none" data-testid="uprof-arcade-empty">No arcade games played yet.</p>`;
  else x+=`<div class="space-y-2.5">${L.map(g=>gdGameCard(g,who)).join('')}</div>`;
  return x+'</section>'+gdActiveHtml(h,who); }
gamesDataSectionHtml=function(){ return gdArcadeHtml(gdArcadeData(),hpData(),'me'); };

/* public profile: Arcade tab with its own privacy row */
SX_SECS.push(['arcade','Arcade & Treesh Active','joystick']);
const _sxSnap9s=sxSnapshot; sxSnapshot=function(){ const o=_sxSnap9s.apply(this,arguments); try{ if(sxCfg().sections.arcade!=='me'){ const g=gdArcadeData(), h=hpData(); if(g.length||h) o.arcade={games:g,hoop:h?Object.assign({},h,{recent:h.recent.map(r=>({g:r.g,at:r.at}))}):null}; } }catch(e){} return o; };
const _sxt9s=sxTabs; sxTabs=function(d){ const T=_sxt9s.apply(this,arguments), D=(d&&d.data)||{}, L=(d&&d.locked)||[]; if(D.arcade!=null||L.includes('arcade')){ const i=T.findIndex(t=>t[0]==='friendlist'); T.splice(i<0?T.length:i,0,['arcade','Arcade','joystick']); } return T; };
const _sxth9s=sxTabHtml; sxTabHtml=function(d,tab){ if(tab==='arcade'&&!(d.locked||[]).includes('arcade')){ const A=((d.data||{}).arcade)||{}; return `<div class="space-y-6" data-testid="uprof-arcade">${gdArcadeHtml(A.games,A.hoop,'them')}</div>`; } return _sxth9s.apply(this,arguments); };
window.addEventListener('storage',e=>{ const k=e.key||''; if(!/^(treesh_hoop_|vocotap_|frea_|chainz_)/.test(k)) return; try{ if(sbUser()) sxPublishSoon(); }catch(_){} if(state.profileOpen&&state.profileTab==='stats'&&!state.settingsEditProfile){ clearTimeout(window._gdRT); window._gdRT=setTimeout(()=>{ try{ renderProfileBody(); }catch(_){} },400); } });

/* arcade: the newest games (now live) */
[['bronze-blitz','Bronze Blitz','B','#d08a4a','#6b3a14'],['ebonics','Ebonics','E','#6b5a8e','#1c1530'],['sonoku','Sonoku','S','#27b5c9','#0b4a63']].forEach(([key,name,mono,a,b])=>{ const g={key,name,url:'https://treesh.app/games/'+key,logo:'',banner:'',mono,a,b,age:'All',updated:'',desc:name+' is now live in the Treesh Arcade. Tap Play to jump in.'}; GAMES.push(g); GAME_BY_KEY[key]=g; });
GAMES.forEach(g=>{ g.updated='October 8, 2026'; });
const _gt9s=gameTile; gameTile=function(g,thing){ if(!g||!g.soon) return _gt9s.apply(this,arguments);
  return `<button data-act="game-open" data-key="${g.key}" data-testid="game-open-${g.key}" aria-label="${esc(g.name)}, coming soon" class="press card-lift group gm-soon relative flex flex-col items-center gap-3 overflow-hidden rounded-3xl border border-white/10 bg-white/[0.04] p-4 text-center backdrop-blur-sm"><span class="gm-soon-tag" data-testid="game-soon-badge-${g.key}">Soon</span><span class="pointer-events-none absolute inset-x-0 -top-8 h-20 opacity-30 blur-2xl" style="background:linear-gradient(135deg,${g.a},${g.b})"></span><span class="gm-soon-art relative grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-2xl border border-white/12 text-3xl font-extrabold text-white" style="background:linear-gradient(135deg,${g.a},${g.b})"><span class="font-display">${g.mono}</span></span><span class="relative w-full min-w-0"><span class="block truncate text-sm font-bold">${esc(g.name)}</span><span class="mt-0.5 inline-flex items-center justify-center gap-1 text-[11px] font-semibold text-[color:var(--treesh-gold)]"><i data-lucide="hourglass" style="width:11px;height:11px"></i>Coming soon</span></span></button>`; };
const _ogi9s=openGameInfo; openGameInfo=function(key){ const r=_ogi9s.apply(this,arguments); const g=GAME_BY_KEY[key]; if(!g||!g.soon) return r; const m=document.getElementById('modal'); if(!m) return r;
  const b=m.querySelector('[data-testid="game-info-play-'+key+'"]'); if(b) b.outerHTML=`<button type="button" disabled aria-disabled="true" data-testid="game-info-soon-${key}" class="gm-soon-cta inline-flex flex-1 items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-bold"><i data-lucide="hourglass" style="width:16px;height:16px"></i>Coming soon</button>`;
  const c=m.querySelector('.mb-4.flex.flex-wrap'); if(c) c.innerHTML=`<span class="gm-soon-pill" data-testid="game-info-soon-pill-${key}"><i data-lucide="hourglass" style="width:13px;height:13px"></i>Not live yet</span><span class="inline-flex items-center gap-1.5 rounded-full border border-white/12 bg-white/5 px-3 py-1 text-xs font-semibold text-white/70"><i data-lucide="link" style="width:13px;height:13px"></i>treesh.app/games/${key}</span>`;
  icons(); return r; };
const _ogf9s=openGameFrame; openGameFrame=function(key){ const g=GAME_BY_KEY[key]; if(g&&g.soon){ toast(g.name+' is coming soon','It isn\u2019t live yet. Check back soon.'); return; } return _ogf9s.apply(this,arguments); };

/* Settings \u2192 Help: the help center opens in the window viewer */
GAME_BY_KEY['help-center']={key:'help-center',name:'Treesh Help Center',url:'support.html',mono:'?',a:'#9328ff',b:'#3b0d73',label:'Treesh Support'};
const _tsr9s=tsAboutRows; tsAboutRows=function(){ return _tsr9s.apply(this,arguments).replace('data-testid="settings-help">','data-testid="settings-help"><button type="button" data-act="legal-open" data-val="help-center" data-testid="about-help-center-open" class="press flex w-full items-center justify-between gap-3 px-4 py-3.5 text-left transition-colors hover:bg-white/5"><span class="flex min-w-0 items-center gap-3"><i data-lucide="book-open" class="shrink-0 text-white/60" style="width:17px;height:17px"></i><span class="min-w-0"><span class="block text-sm font-semibold">Help center</span><span class="block text-xs text-white/45">Every feature explained, FAQ and contact form</span></span></span><i data-lucide="chevron-right" class="shrink-0 text-white/40" style="width:16px;height:16px"></i></button>'); };
