/* TEST ONLY: in-browser fake of supabase-js v2 used by _sbtest.html (never shipped) */
(function(){
  const DBK='__mock_sb_db', SK='__mock_sb_session';
  const db=()=>JSON.parse(localStorage.getItem(DBK)||'{"users":{},"profiles":{},"files":{}}');
  const save=d=>localStorage.setItem(DBK,JSON.stringify(d));
  const off=()=>!!window.__mockOffline;
  const NET={message:'TypeError: Failed to fetch'};
  const subs=[]; const emit=(ev,s)=>subs.forEach(cb=>{ try{ cb(ev,s); }catch(e){ console.error(e); } });
  const sess=()=>JSON.parse(localStorage.getItem(SK)||'null');
  const mk=u=>({access_token:'tok_'+u.id,refresh_token:'ref_'+u.id,user:{id:u.id,email:u.email}});
  window.__mockLog=[];
  const auth={
    onAuthStateChange(cb){ subs.push(cb); setTimeout(()=>cb('INITIAL_SESSION',sess()),0); return {data:{subscription:{unsubscribe(){}}}}; },
    async signInWithPassword({email,password}){ window.__mockLog.push('signin:'+email); if(off()) return {data:{},error:NET}; const u=db().users[email]; if(!u||u.password!==password) return {data:{},error:{message:'Invalid login credentials',status:400}}; if(!u.confirmed) return {data:{},error:{message:'Email not confirmed'}}; const s=mk(u); localStorage.setItem(SK,JSON.stringify(s)); setTimeout(()=>emit('SIGNED_IN',s),0); return {data:{session:s,user:s.user},error:null}; },
    async signUp({email,password,options}){ window.__mockLog.push('signup:'+email+':'+((options||{}).emailRedirectTo||'')); if(off()) return {data:{},error:NET}; const d=db(); if(d.users[email]) return {data:{user:{id:'x'},session:null},error:null}; const u={id:'u'+Math.random().toString(36).slice(2,10),email,password,confirmed:!!d.autoConfirm}; d.users[email]=u; save(d); if(!u.confirmed) return {data:{user:{id:u.id,email},session:null},error:null}; const s=mk(u); localStorage.setItem(SK,JSON.stringify(s)); setTimeout(()=>emit('SIGNED_IN',s),0); return {data:{user:s.user,session:s},error:null}; },
    async signOut(){ localStorage.removeItem(SK); setTimeout(()=>emit('SIGNED_OUT',null),0); return {error:null}; },
    async resetPasswordForEmail(email,o){ window.__mockLog.push('reset:'+email+':'+((o||{}).redirectTo||'')); return {data:{},error:null}; },
    async updateUser({password,email}){ window.__mockLog.push('updateUser:'+(email?'email:'+email:'password')); const s=sess(); if(!s) return {error:{message:'Auth session missing!'}}; const d=db(); const u=Object.values(d.users).find(x=>x.id===s.user.id); if(email){ if(d.users[email]) return {data:{},error:{message:'A user with this email address has already been registered'}}; u.pendingEmail=email; save(d); return {data:{user:s.user},error:null}; } u.password=password; save(d); setTimeout(()=>emit('USER_UPDATED',s),0); return {data:{user:s.user},error:null}; },
    async setSession({access_token}){ const d=db(); const u=Object.values(d.users).find(x=>'tok_'+x.id===access_token); if(!u) return {error:{message:'Invalid token'}}; u.confirmed=true; save(d); const s=mk(u); localStorage.setItem(SK,JSON.stringify(s)); setTimeout(()=>emit('SIGNED_IN',s),0); return {data:{session:s},error:null}; },
    async getUser(){ const s=sess(); return {data:{user:s?s.user:null}}; },
    async getSession(){ return {data:{session:sess()},error:null}; },
    async resend({type,email,options}){ window.__mockLog.push('resend:'+type+':'+email+':'+((options||{}).emailRedirectTo||'')); if(off()) return {error:NET}; return {data:{},error:null}; },
    async verifyOtp({token_hash,type}){ window.__mockLog.push('verify:'+type+':'+token_hash); const d=db(); const u=Object.values(d.users).find(x=>'th_'+x.id===token_hash); if(!u) return {data:{},error:{message:'Email link is invalid or has expired',code:'otp_expired'}}; u.confirmed=true; save(d); const s=mk(u); localStorage.setItem(SK,JSON.stringify(s)); setTimeout(()=>emit('SIGNED_IN',s),0); return {data:{user:s.user,session:s},error:null}; }
  };
  const fr=d=>(d.friendships=d.friendships||[]), bl=d=>(d.blocks=d.blocks||[]);
  const pair=(d,a,b)=>fr(d).find(f=>(f.r===a&&f.a===b)||(f.r===b&&f.a===a));
  const rel=(d,me,o)=>{ if(!me) return 'guest'; if(me===o) return 'self'; if(bl(d).some(x=>x.b===me&&x.t===o)) return 'blocked'; if(bl(d).some(x=>x.b===o&&x.t===me)) return 'blocked_me'; const f=pair(d,me,o); if(!f) return 'none'; if(f.s==='accepted') return 'friends'; return f.r===me?'outgoing':'incoming'; };
  const unpair=(d,a,b)=>{ d.friendships=fr(d).filter(f=>!((f.r===a&&f.a===b)||(f.r===b&&f.a===a))); };
  const SOC={
    search_users(d,me,a){ const s=String(a.q||'').replace(/^@+/,'').trim().toLowerCase(); if(!s) return []; return Object.values(d.profiles).filter(p=>p&&p.username&&p.id!==me&&!bl(d).some(x=>x.b===p.id&&x.t===me)&&(p.username.indexOf(s)===0||(p.display_name||'').toLowerCase().indexOf(s)>=0)).slice(0,25).map(p=>({id:p.id,username:p.username,display_name:p.display_name||null,avatar_url:p.avatar_url||null,is_private:!!p.is_private,relation:rel(d,me,p.id)})); },
    get_user_profile(d,me,a){ const n=String(a.uname||'').replace(/^@+/,'').toLowerCase(); const p=Object.values(d.profiles).find(x=>x&&x.username===n); if(!p) return null; const r=rel(d,me,p.id); if(r==='blocked_me') return null;
      const see=r!=='blocked'&&(r==='self'||r==='friends'||!p.is_private); const src=p.public_data||{}, pv=p.privacy||{}; let data={nickname:src.nickname}; const locked=[];
      if(see){ ['joined','accent','theme','custom'].forEach(k=>{ if(src[k]!=null) data[k]=src[k]; }); ['zodiac','badges','favorites','lyrics','disliked','playlists'].forEach(k=>{ const v=pv[k]||'everyone', keys=k==='badges'?['badges','stats','top']:[k]; if(r==='self'||v==='everyone'||(v==='friends'&&r==='friends')) keys.forEach(x=>{ if(src[x]!=null) data[x]=src[x]; }); else if(v==='friends') locked.push(k); }); }
      return {id:p.id,username:p.username,display_name:p.display_name||null,avatar_url:p.avatar_url||null,bio:see?p.bio||null:null,banner_url:see?p.banner_url||null:null,created_at:p.created_at||null,is_private:!!p.is_private,relation:r,friends:fr(d).filter(f=>f.s==='accepted'&&(f.r===p.id||f.a===p.id)).length,locked_all:!see&&r!=='blocked',locked,data}; },
    send_friend_request(d,me,a){ const t=a.target, r=rel(d,me,t); if(r==='blocked'||r==='blocked_me') throw {message:'You can\u2019t add this person'}; if(r==='friends'||r==='outgoing') return r; if(r==='incoming'){ pair(d,me,t).s='accepted'; return 'friends'; } fr(d).push({r:me,a:t,s:'pending'}); return 'outgoing'; },
    respond_friend_request(d,me,a){ const f=fr(d).find(x=>x.r===a.other&&x.a===me&&x.s==='pending'); if(f){ if(a.accept) f.s='accepted'; else unpair(d,me,a.other); } return rel(d,me,a.other); },
    remove_friend(d,me,a){ unpair(d,me,a.other); return rel(d,me,a.other); },
    block_user(d,me,a){ if(!bl(d).some(x=>x.b===me&&x.t===a.target)) bl(d).push({b:me,t:a.target}); unpair(d,me,a.target); return 'blocked'; },
    unblock_user(d,me,a){ d.blocks=bl(d).filter(x=>!(x.b===me&&x.t===a.target)); return rel(d,me,a.target); },
    my_friends(d,me){ const P=id=>d.profiles[id]||{id}; const out=fr(d).filter(f=>f.r===me||f.a===me).map(f=>{ const p=P(f.r===me?f.a:f.r); return {id:p.id,username:p.username,display_name:p.display_name||null,avatar_url:p.avatar_url||null,relation:f.s==='accepted'?'friends':f.r===me?'outgoing':'incoming'}; }); bl(d).filter(x=>x.b===me).forEach(x=>{ const p=P(x.t); out.push({id:p.id,username:p.username,display_name:p.display_name||null,avatar_url:p.avatar_url||null,relation:'blocked'}); }); return out; } };
  const rpc=async (fn,args)=>{ window.__mockLog.push('rpc:'+fn+(args?':'+JSON.stringify(args):'')); if(off()) return {error:NET}; if(fn==='username_available'){ const d0=db(); const n=String((args||{}).name||'').toLowerCase(); return {data:!Object.values(d0.profiles||{}).some(p=>p&&p.username===n),error:null}; }
    if(SOC[fn]){ const s0=sess(), me=s0?s0.user.id:null; if(!me&&fn!=='search_users'&&fn!=='get_user_profile') return {data:null,error:{message:'not signed in'}}; if(window.__mockNoSocial) return {data:null,error:{code:'PGRST202',message:'Could not find the function public.'+fn}}; const d=db(); try{ const r=SOC[fn](d,me,args||{}); save(d); return {data:r,error:null}; }catch(e){ return {data:null,error:{message:e.message||String(e)}}; } }
    const s=sess(); if(!s) return {error:{message:'not signed in'}}; if(fn!=='delete_user') return {error:{code:'PGRST202',message:'Could not find the function'}}; const d=db(); const em=Object.keys(d.users).find(k=>d.users[k].id===s.user.id); if(em) delete d.users[em]; delete d.profiles[s.user.id]; if(d.user_data) delete d.user_data[s.user.id]; save(d); return {data:null,error:null}; };
  const from=table=>({
    select(cols){ const q={ _k:null,_id:null, eq(k,v){ q._k=k; q._id=v; return q; }, async maybeSingle(){ window.__mockLog.push('select:'+table+':'+(cols||'*')+':'+q._id); if(off()) return {data:null,error:NET}; const s=sess(); if(!s||s.user.id!==q._id) return {data:null,error:null}; const d=db(); const row=table==='user_data'?((d.user_data||{})[q._id]||null):(d.profiles[q._id]||null); if(row&&table==='user_data'&&cols==='updated_at') return {data:{updated_at:row.updated_at},error:null}; return {data:row,error:null}; } }; return q; },
    update(row){ return { async eq(k,v){ window.__mockLog.push('update:'+table+':'+Object.keys(row).join(',')); if(off()) return {error:NET}; const s=sess(); if(!s||s.user.id!==v) return {error:{code:'42501',message:'row-level security'}}; const d=db(); if(d.noSocialCols) return {error:{code:'PGRST204',message:'Could not find the column'}}; d.profiles[v]=Object.assign({},d.profiles[v]||{id:v},row); save(d); return {error:null}; } }; },
    async upsert(row){ if(table==='user_data'){ window.__mockLog.push('upsert:user_data:'+Object.keys((row.data&&row.data.localStorage)||{}).length+':'+((row.data&&row.data.media)?'media':'nomedia')); if(off()) return {error:NET}; const s=sess(); if(!s||s.user.id!==row.user_id) return {error:{code:'42501',message:'new row violates row-level security policy for table "user_data"'}}; const d=db(); d.user_data=d.user_data||{}; d.user_data[row.user_id]=row; save(d); return {error:null}; }
      window.__mockLog.push('upsert:'+JSON.stringify(Object.assign({},row,{avatar_url:row.avatar_url?String(row.avatar_url).slice(0,60):row.avatar_url}))); if(off()) return {error:NET}; const s=sess(); if(!s||s.user.id!==row.id) return {error:{code:'42501',message:'new row violates row-level security policy for table "profiles"'}}; const d=db();
      if(row.username&&Object.values(d.profiles).some(p=>p.id!==row.id&&p.username===row.username)) return {error:{code:'23505',message:'duplicate key value violates unique constraint "profiles_username_key"',details:'Key (username)=('+row.username+') already exists.'}};
      d.profiles[row.id]=Object.assign({created_at:(d.profiles[row.id]||{}).created_at||new Date().toISOString()},row); save(d); return {error:null}; }
  });
  const storage={ from:b=>({ async upload(path,blob,o){ window.__mockLog.push('upload:'+b+'/'+path+':'+((blob&&blob.type)||(o&&o.contentType))+':'+!!(o&&o.upsert)); if(off()) return {error:NET}; const d=db(); if(d.noBucket) return {error:{message:'Bucket not found'}}; d.files[path]=blob&&(blob.size||blob.byteLength); if(o&&o.contentType==='application/json'&&blob&&blob.byteLength!=null){ d.texts=d.texts||{}; d.texts[path]=new TextDecoder().decode(blob); } save(d); return {data:{path},error:null}; },
    async download(path){ window.__mockLog.push('download:'+b+'/'+path); if(off()) return {data:null,error:NET}; const d=db(); return {data:new Blob([(d.texts&&d.texts[path])||'[]'],{type:'application/json'}),error:null}; }, getPublicUrl(path){ return {data:{publicUrl:location.origin+'/treesh_logo.png#'+b+'/'+path}}; },
    async list(dir){ window.__mockLog.push('list:'+b+'/'+dir); const d=db(); return {data:Object.keys(d.files||{}).filter(p=>p.indexOf(dir+'/')===0).map(p=>({name:p.slice(dir.length+1),id:p})),error:null}; },
    async remove(paths){ window.__mockLog.push('remove:'+b+':'+paths.join(',')); const d=db(); paths.forEach(p=>{ delete d.files[p]; }); save(d); return {data:paths,error:null}; } }) };
  window.supabase={ createClient(url,key,opts){ window.__mockLog.push('create:'+url+':'+key+':'+JSON.stringify(opts||{})); return {auth,from,storage,rpc}; } };
})();
