import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { GlassCard, NeonButton, ScreenHeader } from "@/src/components/ui";
import { colors, laneColors } from "@/src/game/theme";

const faqs = [
  ["Where are my songs stored?", "Inside Vocotap’s private device storage. Audio, charts, scores, and Starlites are never uploaded."],
  ["Why won’t a file play on iPhone?", "iOS decoder support depends on the file’s internal codec, not only its extension. MP3, AAC/M4A, and WAV are most reliable. Try exporting unusual FLAC, OGG, or WebM variants to one of those formats."],
  ["Can Vocotap download Treesh songs?", "Vocotap only imports when Treesh provides a documented, permitted audio URL. Today you can browse the catalog, then import a copy already saved to your device."],
  ["How do wavy holds work?", "Press the head, keep your finger down, and move across lanes with the glowing wave path until the tail ends."],
  ["What is Vocopulse?", "Hit notes to charge it. At 50% or higher, activate Vocopulse for an eight-second 2× score multiplier and amplified visuals."],
  ["How do Starlites stay compatible?", "Vocotap uses the exact treesh_stars key, schema, and reward values from Treesh. Native app storage is sandboxed; a web build on the same origin can read the website key directly."],
];

export default function GuideScreen() {
  const [step, setStep] = useState(0); const [open, setOpen] = useState(0);
  const steps = [
    { icon: "download-outline" as const, title: "Pick your sound", copy: "Choose Treesh Music or import an audio file from Files. Vocotap immediately makes a private app copy." },
    { icon: "analytics-outline" as const, title: "Build the chart", copy: "Select Easy through Expert. The on-device engine maps tempo, beat spacing, density, and note shapes." },
    { icon: "hand-left-outline" as const, title: "Own the highway", copy: "Tap heads, hold tails, trace waves, charge Vocopulse, then refine anything in the chart editor." },
  ];
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><ScreenHeader title="How to Play" /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.hero}><Text style={styles.eyebrow}>60-SECOND TOUR</Text><Text style={styles.heading}>From audio to encore</Text><View style={styles.stepDots}>{steps.map((_, index) => <View key={index} style={[styles.stepDot, index === step && styles.stepDotActive]} />)}</View></View>
    <GlassCard testID="tutorial-step-card" style={styles.tutorial}><View style={styles.iconRing}><Ionicons name={steps[step].icon} size={38} color={laneColors[step]} /></View><Text style={styles.stepNumber}>STEP {step + 1} OF 3</Text><Text style={styles.stepTitle}>{steps[step].title}</Text><Text style={styles.stepCopy}>{steps[step].copy}</Text><View style={styles.tutorialButtons}><Pressable testID="tutorial-previous-button" disabled={step === 0} onPress={() => setStep(value => value - 1)} style={[styles.circleButton, step === 0 && { opacity: 0.25 }]}><Ionicons name="arrow-back" size={21} color={colors.text} /></Pressable><Pressable testID="tutorial-next-button" onPress={() => setStep(value => value === 2 ? 0 : value + 1)} style={[styles.next, { backgroundColor: laneColors[step] }]}><Text style={styles.nextText}>{step === 2 ? "REPLAY" : "NEXT"}</Text><Ionicons name={step === 2 ? "refresh" : "arrow-forward"} size={18} color={colors.bg} /></Pressable></View></GlassCard>
    <View><Text style={styles.sectionTitle}>NOTE LANGUAGE</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.noteRow} contentContainerStyle={styles.noteCards}>{[["Tap", "ellipse", colors.cyan], ["Hold", "remove", colors.lime], ["Wavy", "water", colors.orange], ["Slide", "arrow-forward", colors.pink], ["Special", "sparkles", colors.violet]].map(([label, icon, color]) => <View key={String(label)} style={styles.noteCard}><View style={[styles.noteIcon, { backgroundColor: `${color}22`, borderColor: String(color) }]}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={22} color={String(color)} /></View><Text style={styles.noteLabel}>{label}</Text></View>)}</ScrollView></View>
    <View><Text style={styles.sectionTitle}>FAQ</Text><View style={styles.faqs}>{faqs.map(([question, answer], index) => <Pressable key={question} testID={`faq-item-${index + 1}`} onPress={() => setOpen(open === index ? -1 : index)} style={styles.faq}><View style={styles.faqHead}><Text style={styles.question}>{question}</Text><Ionicons name={open === index ? "remove" : "add"} size={20} color={colors.cyan} /></View>{open === index && <Text style={styles.answer}>{answer}</Text>}</Pressable>)}</View></View>
    <NeonButton testID="guide-start-playing-button" label="Start playing" icon="play" onPress={() => router.replace("/library")} />
  </ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg }, content: { padding: 17, gap: 24, paddingBottom: 36 }, hero: { alignItems: "center", paddingTop: 8 }, eyebrow: { color: colors.cyan, fontSize: 9, fontWeight: "900", letterSpacing: 1.7 }, heading: { color: colors.text, fontSize: 29, fontWeight: "900", marginTop: 6 }, stepDots: { flexDirection: "row", gap: 6, marginTop: 12 }, stepDot: { width: 18, height: 4, borderRadius: 2, backgroundColor: colors.panelStrong }, stepDotActive: { width: 34, backgroundColor: colors.cyan }, tutorial: { alignItems: "center", paddingVertical: 24 }, iconRing: { width: 84, height: 84, borderRadius: 42, alignItems: "center", justifyContent: "center", backgroundColor: colors.bg, borderWidth: 1, borderColor: colors.border }, stepNumber: { color: colors.muted, fontSize: 9, fontWeight: "900", letterSpacing: 1.4, marginTop: 15 }, stepTitle: { color: colors.text, fontSize: 24, fontWeight: "900", marginTop: 6 }, stepCopy: { color: colors.muted, fontSize: 14, lineHeight: 21, textAlign: "center", marginTop: 7, minHeight: 64 }, tutorialButtons: { flexDirection: "row", gap: 10, marginTop: 16 }, circleButton: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center", backgroundColor: colors.panelStrong }, next: { height: 48, minWidth: 120, borderRadius: 24, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 }, nextText: { color: colors.bg, fontSize: 11, fontWeight: "900", letterSpacing: 1 }, sectionTitle: { color: colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1.5, marginBottom: 9 }, noteRow: { marginHorizontal: -17 }, noteCards: { gap: 9, paddingHorizontal: 17 }, noteCard: { flexShrink: 0, width: 84, height: 100, borderRadius: 17, alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border }, noteIcon: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center", borderWidth: 1 }, noteLabel: { color: colors.text, fontSize: 11, fontWeight: "800" }, faqs: { borderRadius: 20, overflow: "hidden", borderWidth: 1, borderColor: colors.border }, faq: { padding: 16, backgroundColor: colors.panel, borderBottomWidth: 1, borderBottomColor: colors.border }, faqHead: { minHeight: 26, flexDirection: "row", alignItems: "center", gap: 10 }, question: { color: colors.text, flex: 1, fontSize: 14, fontWeight: "800" }, answer: { color: colors.muted, fontSize: 13, lineHeight: 20, paddingTop: 10 },
});