import Slider from "@react-native-community/slider";
import { Ionicons } from "@expo/vector-icons";
import * as Haptics from "expo-haptics";
import React, { useRef, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { NeonButton, ScreenHeader } from "@/src/components/ui";
import { useAppState } from "@/src/game/AppState";
import { colors } from "@/src/game/theme";

function ToggleRow({ icon, title, copy, value, onChange, testID }: { icon: keyof typeof Ionicons.glyphMap; title: string; copy: string; value: boolean; onChange: (value: boolean) => void; testID: string }) {
  return <View style={styles.row}><View style={styles.rowIcon}><Ionicons name={icon} size={19} color={colors.cyan} /></View><View style={styles.rowText}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowCopy}>{copy}</Text></View><Switch testID={testID} value={value} onValueChange={onChange} trackColor={{ false: "#373740", true: colors.cyan }} thumbColor={value ? colors.bg : "#A3A3AA"} /></View>;
}

export default function SettingsScreen() {
  const { settings, updateSettings, clearLocalData, restoreWarmup, songs, scores } = useAppState();
  const [confirm, setConfirm] = useState(false); const [tapResult, setTapResult] = useState<number | null>(null); const lastBeat = useRef(Date.now());
  const tap = () => { const now = Date.now(); const elapsed = (now - lastBeat.current) % 600; const delta = elapsed > 300 ? elapsed - 600 : elapsed; setTapResult(Math.round(delta)); lastBeat.current = now; Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium); };
  const preset = (label: string, value: number, testID: string) => { const active = settings.audioOffset === value; return <Pressable testID={testID} onPress={() => updateSettings({ audioOffset: value })} style={[styles.preset, active && styles.presetActive]}><Text style={[styles.presetText, active && styles.presetTextActive]}>{label}</Text></Pressable>; };
  return <SafeAreaView style={styles.safe} edges={["top", "bottom"]}><ScreenHeader title="Settings" /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.calibration}><Text style={styles.eyebrow}>INTERACTIVE LATENCY TEST</Text><Text style={styles.heading}>Tap with the pulse</Text><Text style={styles.copy}>Use your normal grip. We’ll show how early or late your taps land.</Text><Pressable testID="calibration-tap-pad" onPress={tap} style={({ pressed }) => [styles.tapPad, pressed && styles.tapPressed]}><View style={styles.ring}><Ionicons name="finger-print" size={42} color={colors.cyan} /></View><Text style={styles.tapLabel}>TAP</Text></Pressable><Text style={[styles.result, { color: tapResult === null ? colors.muted : Math.abs(tapResult) < 45 ? colors.lime : colors.orange }]}>{tapResult === null ? "Waiting for a tap" : `${tapResult > 0 ? "+" : ""}${tapResult} ms · ${Math.abs(tapResult) < 45 ? "Synced" : tapResult < 0 ? "Early" : "Late"}`}</Text></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>TIMING</Text><View style={styles.panel}><View style={styles.sliderHead}><Text style={styles.rowTitle}>Audio offset</Text><Text style={styles.value}>{settings.audioOffset > 0 ? "+" : ""}{settings.audioOffset} ms</Text></View><Slider testID="audio-offset-slider" minimumValue={-200} maximumValue={200} step={5} value={settings.audioOffset} onSlidingComplete={value => updateSettings({ audioOffset: value })} minimumTrackTintColor={colors.cyan} maximumTrackTintColor="#383840" thumbTintColor={colors.cyan} /><View style={styles.presets}>{preset("Speaker", 0, "speaker-preset-button")}{preset("Wired", 25, "wired-preset-button")}{preset("Bluetooth", 120, "bluetooth-preset-button")}</View><View style={styles.sliderHead}><Text style={styles.rowTitle}>Note speed</Text><Text style={styles.value}>{settings.noteSpeed.toFixed(1)}×</Text></View><Slider testID="note-speed-slider" minimumValue={0.7} maximumValue={1.8} step={0.1} value={settings.noteSpeed} onSlidingComplete={value => updateSettings({ noteSpeed: value })} minimumTrackTintColor={colors.lime} maximumTrackTintColor="#383840" thumbTintColor={colors.lime} /></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>PLAY FEEL</Text><View style={styles.panel}><ToggleRow testID="haptics-toggle" icon="phone-portrait" title="Haptics" copy="Tactile feedback on judgments" value={settings.haptics} onChange={value => updateSettings({ haptics: value })} /><ToggleRow testID="hit-sfx-toggle" icon="volume-high" title="Hit SFX" copy="Extra attack on successful notes" value={settings.hitSfx} onChange={value => updateSettings({ hitSfx: value })} /><ToggleRow testID="no-fail-toggle" icon="shield-checkmark" title="No Fail" copy="Keep playing if the rock meter empties" value={settings.noFail} onChange={value => updateSettings({ noFail: value })} /></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>PERFORMANCE MODE</Text><View style={styles.panel}><ToggleRow testID="performance-mode-toggle" icon="speedometer" title="Performance mode" copy="Lower update rate for older devices" value={settings.performanceMode} onChange={value => updateSettings({ performanceMode: value })} /><ToggleRow testID="reduced-particles-toggle" icon="sparkles" title="Reduced particles" copy="Keep hit flashes, remove bursts" value={settings.reducedParticles} onChange={value => updateSettings({ reducedParticles: value })} /><ToggleRow testID="grayscale-covers-toggle" icon="contrast" title="Grayscale cover art" copy="Mute the backdrop so notes are easier to see" value={settings.grayscaleCovers} onChange={value => updateSettings({ grayscaleCovers: value })} /><ToggleRow testID="lane-pads-toggle" icon="grid" title="Show lane pads" copy="Fill the tap zones with a colour flash on hit" value={settings.showLanePads} onChange={value => updateSettings({ showLanePads: value })} /></View></View>
    <View style={styles.section}><Text style={styles.sectionTitle}>LOCAL STORAGE</Text><View style={styles.panel}><View style={styles.storage}><Text style={styles.rowTitle}>{songs.length} songs · {scores.length} scores</Text><Text style={styles.rowCopy}>Audio, charts, scores, and settings stay in this app sandbox.</Text></View>{settings.warmupHidden && <NeonButton testID="restore-warmup-button" label="Restore Voco Warmup" icon="refresh" variant="secondary" onPress={() => restoreWarmup()} />}<NeonButton testID="clear-local-data-button" label="Clear Vocotap data" icon="trash" variant="danger" onPress={() => setConfirm(true)} /></View></View>
  </ScrollView>
  <Modal visible={confirm} transparent animationType="fade"><View style={styles.modal}><View style={styles.confirm}><Ionicons name="warning" size={32} color={colors.pink} /><Text style={styles.confirmTitle}>Clear local data?</Text><Text style={styles.confirmCopy}>This removes imported song references, charts, settings, and scores from Vocotap. Your original files remain in Files.</Text><NeonButton testID="confirm-clear-data-button" label="Clear everything" icon="trash" variant="danger" onPress={async () => { await clearLocalData(); setConfirm(false); }} /><NeonButton testID="cancel-clear-data-button" label="Keep my data" icon="close" variant="secondary" onPress={() => setConfirm(false)} /></View></View></Modal>
  </SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg }, content: { padding: 17, gap: 22, paddingBottom: 38 }, calibration: { alignItems: "center", paddingTop: 8 }, eyebrow: { color: colors.cyan, fontSize: 9, fontWeight: "900", letterSpacing: 1.7 }, heading: { color: colors.text, fontSize: 28, fontWeight: "900", marginTop: 5 }, copy: { color: colors.muted, textAlign: "center", fontSize: 13, lineHeight: 19, maxWidth: 310, marginTop: 6 }, tapPad: { width: 138, height: 138, borderRadius: 69, marginTop: 20, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(147,40,255,0.08)", borderWidth: 2, borderColor: colors.cyan }, tapPressed: { transform: [{ scale: 0.92 }], backgroundColor: "rgba(147,40,255,0.24)" }, ring: { width: 82, height: 82, borderRadius: 41, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "rgba(147,40,255,0.4)" }, tapLabel: { color: colors.text, fontSize: 11, fontWeight: "900", letterSpacing: 2, marginTop: 4 }, result: { fontWeight: "800", marginTop: 12 },
  section: { gap: 8 }, sectionTitle: { color: colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1.5, paddingLeft: 4 }, panel: { borderRadius: 20, paddingHorizontal: 15, paddingVertical: 7, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border }, row: { minHeight: 72, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: colors.border }, rowIcon: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(147,40,255,0.09)" }, rowText: { flex: 1 }, rowTitle: { color: colors.text, fontSize: 14, fontWeight: "800" }, rowCopy: { color: colors.muted, fontSize: 11, lineHeight: 15, marginTop: 3 }, sliderHead: { flexDirection: "row", justifyContent: "space-between", marginTop: 12 }, value: { color: colors.cyan, fontSize: 13, fontWeight: "900" }, presets: { flexDirection: "row", gap: 8, marginVertical: 9 }, preset: { flex: 1, minHeight: 40, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.panelStrong, borderWidth: 1, borderColor: "transparent" }, presetActive: { backgroundColor: "#FFFFFF", borderColor: colors.cyan }, presetText: { color: colors.text, fontSize: 11, fontWeight: "800" }, presetTextActive: { color: colors.cyan, fontWeight: "900" },
  starlitePanel: { minHeight: 82, padding: 16, borderRadius: 20, flexDirection: "row", alignItems: "center", gap: 14, backgroundColor: "rgba(147,40,255,0.09)", borderWidth: 1, borderColor: "rgba(147,40,255,0.3)" }, starliteValue: { color: colors.gold, fontSize: 18, fontWeight: "900" }, starliteCopy: { color: colors.muted, fontSize: 11, marginTop: 3 }, storage: { paddingVertical: 12 }, modal: { flex: 1, backgroundColor: "rgba(0,0,0,0.78)", justifyContent: "center", padding: 24 }, confirm: { padding: 24, borderRadius: 26, gap: 13, alignItems: "center", backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.pink }, confirmTitle: { color: colors.text, fontSize: 25, fontWeight: "900" }, confirmCopy: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: "center", marginBottom: 5 },
});
